"""Asbab al-nuzul overflow events (orders 651-800).

These are verse-tied incidents from classical asbab literature (al-Wahidi,
al-Suyuti's Lubab al-Nuqul) that don't map neatly to a single narrative
sira event but have a well-attested verse linkage. Organized roughly by
surah order.
"""

from __future__ import annotations
from training.pipeline.sira_db.db import E

ASBAB_EVENTS: list[dict] = [
    # ═══════════════ SURAT AL-BAQARAH ASBAB ═══════════════
    E("ab_baqara_no_compulsion", 651, 3, "medinan_early",
      "لا إكراه في الدين — أبناء الأنصار اليهود", "No compulsion in religion — Ansari children raised Jewish",
      "Medina", ["2:256"],
      "كان بعض نساء الأنصار يُنذرن إن عاش لهن ولد أن يُهوّدنه، فلما أُجلي بنو النضير أراد آباؤهم إكراههم على الإسلام فنزلت لا إكراه في الدين.",
      "الدين لا يُفرض حتى على الأبناء؛ الإقناع لا الإكراه.",
      "family_pressure", "parent_vs_child", "religious_freedom",
      "legal_innovation", "no_coercion_in_conviction", "legislation"),

    E("ab_baqara_spend_good", 652, 2, "medinan_early",
      "أنفقوا من طيبات ما كسبتم", "Spend from the good of what you have earned",
      "Medina", ["2:267"],
      "كان بعض الصحابة يتصدقون بالرديء من التمر ويُبقون الجيد لأنفسهم، فنزلت يا أيها الذين آمنوا أنفقوا من طيبات ما كسبتم.",
      "الصدقة من أجود ما عندك لا من أردئه؛ العطاء الحقيقي يُؤلم قليلاً.",
      "moral_temptation", "community_vs_outsider", "spiritual_integrity",
      "moral_rebuke", "sincerity_over_performance", "command"),

    E("ab_baqara_moon_phases", 653, 2, "medinan_early",
      "يسألونك عن الأهلة", "They ask you about the crescent moons",
      "Medina", ["2:189"],
      "سأل معاذ بن جبل النبي ﷺ عن الأهلة: ما بال الهلال يبدو رقيقاً ثم يعظم؟ فنزل يسألونك عن الأهلة قل هي مواقيت للناس والحج.",
      "الإجابة القرآنية تربط الظاهرة بوظيفتها لا بعلتها الفيزيائية؛ المعرفة النافعة أولى.",
      "intellectual_challenge", "teacher_vs_student", "knowledge_access",
      "clarification", "knowledge_before_action", "clarification"),

    E("ab_baqara_baynahum", 654, 2, "medinan_early",
      "ولا تأكلوا أموالكم بينكم بالباطل", "Do not consume each other's wealth unjustly",
      "Medina", ["2:188"],
      "كان رجل من المسلمين يُخاصم آخر في أرض ويعرف أنه مبطل، فنزل تحريم أكل المال بالباطل عند الحكام.",
      "الرشوة والتحايل القضائي أكل للمال بالباطل؛ علم المدعي ببطلانه يُضاعف الإثم.",
      "moral_temptation", "claimant_vs_accused", "property_rights",
      "moral_rebuke", "procedural_justice_over_outcome", "prohibition"),

    E("ab_baqara_jihad_fitna", 655, 2, "medinan_early",
      "وقاتلوهم حتى لا تكون فتنة", "Fight them until there is no more fitna",
      "Medina", ["2:193"],
      "نزلت هذه الآية لبيان أن القتال ليس غاية بل وسيلة لإزالة الفتنة عن المؤمنين، والفتنة هنا الصدّ عن الدين.",
      "الهدف من القتال إزالة الفتنة لا الإبادة؛ حين تُرفع الفتنة يتوقف القتال.",
      "political_pressure", "believer_vs_unbeliever", "religious_freedom",
      "legal_innovation", "scaling_principle_to_context", "legislation"),

    E("ab_baqara_hajj_months", 656, 2, "medinan_early",
      "الحج أشهر معلومات", "Hajj is in well-known months",
      "Medina", ["2:197"],
      "نزلت لتحديد أشهر الحج (شوال وذو القعدة وعشر ذي الحجة) ومنع الرفث والفسوق والجدال فيهن.",
      "تحديد الزمان بدقة يمنع التلاعب؛ العبادة لها وقت لا يُؤخّر.",
      "none", "community_vs_outsider", "spiritual_integrity",
      "legal_innovation", "consistency_public_and_private", "legislation"),

    E("ab_baqara_wasiyyah_before_death", 657, 2, "medinan_early",
      "كتب عليكم إذا حضر أحدكم الموت الوصية", "Prescribed for you when death approaches is the bequest",
      "Medina", ["2:180"],
      "نزلت الوصية قبل آيات المواريث، فلما نزل الميراث نُسخ بعض حكم الوصية ولكن بقي الإيصاء لغير الوارث.",
      "النسخ التشريعي تطور لا تناقض؛ الحكم السابق قد يُعدَّل بحكم لاحق.",
      "none", "community_vs_outsider", "property_rights",
      "legal_innovation", "scaling_principle_to_context", "legislation"),

    E("ab_baqara_shahr_ramadan", 658, 2, "medinan_early",
      "شهر رمضان الذي أُنزل فيه القرآن", "The month of Ramadan in which the Quran was revealed",
      "Medina", ["2:185"],
      "نزلت تعظيماً لشهر رمضان وبياناً لفضله بأنه شهر نزول القرآن، وتأسيساً لفرضية الصيام الدائمة.",
      "ربط الصيام بالحدث الأعظم (نزول القرآن) يُعلي قيمة الشهر فوق مجرد الامتناع عن الطعام.",
      "none", "community_vs_outsider", "spiritual_integrity",
      "legal_innovation", "knowledge_before_action", "legislation"),

    E("ab_baqara_dua_close", 659, 2, "medinan_early",
      "وإذا سألك عبادي عني فإني قريب", "When My servants ask about Me, I am near",
      "Medina", ["2:186"],
      "سأل أعرابي النبي ﷺ: أقريب ربنا فنناجيه أم بعيد فنناديه؟ فنزلت وإذا سألك عبادي عني فإني قريب أُجيب دعوة الداعي.",
      "القرب الإلهي ثابت لا يحتاج وسيطاً؛ الدعاء مباشر بلا سلّم.",
      "intellectual_challenge", "self_vs_self", "spiritual_integrity",
      "consolation_and_thabaat", "refuge_with_god_against_despair", "promise"),

    E("ab_baqara_wife_field", 660, 2, "medinan_early",
      "نساؤكم حرث لكم", "Your wives are a tilth for you",
      "Medina", ["2:223"],
      "سأل بعض المهاجرين عن حكم معاشرة الزوجة من خلف (في الفرج)، لأن اليهود كانوا يُحرّمون ذلك ويدّعون أنه يسبب الحَول، فنزلت نساؤكم حرث لكم فأتوا حرثكم أنى شئتم.",
      "الشريعة تُحرّر من الأوهام الموروثة؛ العلاقة الزوجية لها حدود لكنها أوسع من ظنون الناس.",
      "intellectual_challenge", "spouse_vs_spouse", "family_integrity",
      "clarification", "boundaries_in_intimate_relations", "legislation"),

    E("ab_baqara_ila_four_months", 661, 2, "medinan_early",
      "للذين يؤلون من نسائهم تربّص أربعة أشهر", "Those who swear to abstain from wives wait four months",
      "Medina", ["2:226", "2:227"],
      "كان الرجل في الجاهلية يحلف ألا يقرب زوجته السنة والسنتين ضراراً بها، فنزل تحديد الإيلاء بأربعة أشهر، بعدها إما يفيء أو يُطلّق.",
      "حماية المرأة من الإضرار الصامت؛ الزمن المحدد يمنع تعليق الزوجة إلى ما لا نهاية.",
      "legal_coercion", "spouse_vs_spouse", "family_integrity",
      "legal_innovation", "protection_of_the_weak", "legislation"),

    E("ab_baqara_talaq_iddah", 662, 2, "medinan_early",
      "والمطلقات يتربصن بأنفسهن ثلاثة قروء", "Divorced women wait three periods",
      "Medina", ["2:228", "2:229", "2:230", "2:231", "2:232"],
      "نزلت أحكام الطلاق والعدّة تنظم حقوق المرأة المطلقة: العدة ثلاثة قروء، والرجعة في العدة، والطلاق مرتان، والثالثة لا تحل حتى تنكح زوجاً غيره.",
      "نظام العدة يحمي حقوق الأطراف الثلاثة (الزوج، الزوجة، الجنين)؛ التشريع المتدرج يمنع الظلم.",
      "legal_coercion", "spouse_vs_spouse", "family_integrity",
      "legal_innovation", "protection_of_the_weak", "legislation"),

    E("ab_baqara_ridaa_two_years", 663, 2, "medinan_early",
      "والوالدات يُرضعن أولادهن حولين كاملين", "Mothers nurse their children two full years",
      "Medina", ["2:233"],
      "نزلت تنظم حقوق الرضاعة وتحدد مدتها بحولين كاملين لمن أراد إتمامها، مع عدم تضار الوالدة بولدها ولا المولود له بولده.",
      "حقّ الطفل في الرضاعة مكفول شرعاً؛ لا يُضارّ أحد الطرفين بسببه.",
      "legal_coercion", "spouse_vs_spouse", "family_integrity",
      "legal_innovation", "protection_of_the_weak", "legislation"),

    E("ab_baqara_ayat_kursi", 664, 2, "medinan_early",
      "نزول آية الكرسي سيدة آيات القرآن", "Revelation of Ayat al-Kursi",
      "Medina", ["2:255"],
      "نزلت آية الكرسي أعظم آية في القرآن، تُلخّص صفات الألوهية الكاملة: الحياة والقيومية والعلم والسلطان.",
      "التوحيد يُكثّف في آية واحدة؛ أعظم الآيات أجمعها للمعاني.",
      "none", "community_vs_outsider", "spiritual_integrity",
      "public_declaration", "source_integrity_over_popularity", "argument"),

    E("ab_baqara_ibrahim_birds", 665, 2, "medinan_early",
      "إبراهيم يسأل ربه كيف يُحيي الموتى", "Ibrahim asks how God revives the dead",
      "Medina", ["2:260"],
      "نزلت قصة سؤال إبراهيم لربه: أرني كيف تُحيي الموتى، لا شكاً بل ليطمئن قلبه، فأمره بتقطيع أربعة طيور.",
      "طلب الطمأنينة مشروع حتى مع الإيمان الكامل؛ اليقين يتدرج مراتب.",
      "intellectual_challenge", "self_vs_self", "spiritual_integrity",
      "teaching_through_demonstration", "signs_require_reflection_not_proof", "story"),

    # ═══════════════ SURAT AL-IMRAN ASBAB ═══════════════
    E("ab_imran_family_chosen", 666, 3, "medinan_early",
      "إن الله اصطفى آدم ونوحاً وآل إبراهيم وآل عمران", "Allah chose Adam, Nuh, Ibrahim's family, Imran's family",
      "Medina", ["3:33", "3:34"],
      "نزلت في سياق الرد على وفد نجران حين ادّعوا ألوهية عيسى، فبيّن القرآن أن عيسى من سلسلة الاصطفاء الطويلة لا إلهاً مستقلاً.",
      "وضع عيسى في سياق تاريخي يُزيل الغلو؛ النبوة سلسلة لا نقطة معزولة.",
      "intellectual_challenge", "community_vs_outsider", "truth_vs_falsehood",
      "intellectual_rebuttal", "truth_is_independent_of_carrier", "argument"),

    E("ab_imran_tawakkul", 667, 3, "medinan_early",
      "حسبنا الله ونعم الوكيل — بعد أحد", "Sufficient for us is Allah — after Uhud",
      "Medina", ["3:173", "3:174"],
      "قالها الصحابة لما قيل لهم إن الناس قد جمعوا لكم فاخشوهم فزادهم إيماناً وقالوا حسبنا الله ونعم الوكيل.",
      "التوكل عند الخوف يزيد الإيمان لا ينقصه؛ العبارة الواحدة قد تُحيي الأمة.",
      "psychological_pressure", "principled_minority_vs_powerful_majority", "collective_survival",
      "refuge_with_god_against_despair", "refuge_with_god_against_despair", "consolation"),

    E("ab_imran_lan_tanalu", 668, 3, "medinan_early",
      "لن تنالوا البر حتى تنفقوا مما تحبون", "You will not attain righteousness until you spend from what you love",
      "Medina", ["3:92"],
      "لما نزلت هذه الآية جاء أبو طلحة الأنصاري فقال: يا رسول الله، أحبّ أموالي إليّ بيرحاء، وإنها صدقة لله.",
      "الإنفاق من المحبوب معيار البر الحقيقي؛ الصدقة الأسهل لا تبلغ الذروة.",
      "none", "community_vs_outsider", "livelihood",
      "teaching_through_demonstration", "wealth_as_trust_not_ownership", "command"),

    E("ab_imran_women_equal_reward", 669, 3, "medinan_early",
      "أم سلمة تسأل عن ذكر النساء في القرآن", "Umm Salama asks why women aren't mentioned in the Quran",
      "Medina", ["3:195", "33:35"],
      "قالت أم سلمة: يا رسول الله، ما لنا لا نُذكر في القرآن كما يُذكر الرجال؟ فنزل فاستجاب لهم ربهم أني لا أضيع عمل عامل منكم من ذكر أو أنثى.",
      "سؤال المرأة يستنزل آية؛ المساواة في الأجر لا تحتاج إلى تلميح بل إلى نص.",
      "verbal_attack", "spouse_vs_spouse", "personal_dignity",
      "clarification", "protection_of_the_weak", "promise"),

    # ═══════════════ SURAT AL-NISA ASBAB ═══════════════
    E("ab_nisa_obey_authority", 670, 4, "medinan_early",
      "أطيعوا الله وأطيعوا الرسول وأولي الأمر منكم", "Obey Allah, the Messenger, and those in authority",
      "Medina", ["4:59"],
      "نزلت في عبد الله بن حذافة السهمي حين بعثه النبي ﷺ في سرية فغضب من أصحابه وأمرهم بشيء فتردّدوا.",
      "الطاعة لأولي الأمر مشروطة بعدم معصية الله؛ السلسلة: الله أولاً ثم الرسول ثم الأمير.",
      "political_pressure", "leader_vs_follower", "trust_between_parties",
      "clarification", "accountability_proportional_to_power", "legislation"),

    E("ab_nisa_judge_fairly", 671, 4, "medinan_early",
      "إن الله يأمركم أن تؤدوا الأمانات إلى أهلها", "Allah commands you to render trusts to their owners",
      "Medina", ["4:58"],
      "نزلت في عثمان بن طلحة حين ردّ النبي ﷺ مفتاح الكعبة إليه يوم الفتح بعد أن طُلب منه أن يُعطيه للعباس.",
      "ردّ الأمانة لأهلها حتى لو كانوا خصوماً سابقاً؛ العدل فوق القرابة.",
      "moral_temptation", "claimant_vs_accused", "trust_between_parties",
      "refusal_to_compromise", "procedural_justice_over_outcome", "legislation"),

    E("ab_nisa_wasiyyah_women", 672, 4, "medinan_early",
      "يوصيكم الله في أولادكم — ميراث البنات", "Allah instructs you about your children — daughters' inheritance",
      "Medina", ["4:11"],
      "جاءت امرأة سعد بن الربيع تشكو أن عمّ ابنتيها أخذ مالهما، فنزلت آيات المواريث.",
      "حقّ المرأة في الميراث ليس منّة من الرجل بل فرض من الله.",
      "legal_coercion", "claimant_vs_accused", "property_rights",
      "legal_innovation", "protection_of_the_weak", "legislation"),

    E("ab_nisa_nushuz_discipline", 673, 4, "medinan_early",
      "واللاتي تخافون نشوزهن فعظوهن", "Those women from whom you fear rebellion, advise them",
      "Medina", ["4:34"],
      "نزلت في سياق تنظيم العلاقة الزوجية حين اشتكت امرأة من ضرب زوجها فأراد النبي ﷺ القصاص ثم نزل تدرج الوعظ فالهجر فالضرب غير المبرّح.",
      "التدرج في معالجة النشوز: وعظ ثم هجر ثم ضرب رمزي؛ القصد الإصلاح لا الانتقام.",
      "family_pressure", "spouse_vs_spouse", "family_integrity",
      "legal_innovation", "scaling_principle_to_context", "legislation"),

    E("ab_nisa_secret_talk_charity", 674, 4, "medinan_middle",
      "لا خير في كثير من نجواهم إلا من أمر بصدقة", "No good in most private talks except charity",
      "Medina", ["4:114"],
      "نزلت في رجل من المنافقين كان يتناجى مع أصحابه في السوء، فبيّن القرآن أن النجوى المحمودة ما كانت في صدقة أو إصلاح.",
      "المحادثات السرية تُقيَّم بمضمونها؛ الخير ما أثمر في صدقة أو معروف أو إصلاح.",
      "internal_betrayal", "insider_hypocrite_vs_sincere", "trust_between_parties",
      "moral_rebuke", "consistency_public_and_private", "rebuke"),

    E("ab_nisa_qadam_sidq", 675, 4, "medinan_early",
      "ومن يُهاجر في سبيل الله يجد في الأرض مراغماً", "Whoever emigrates for God will find refuge",
      "Medina", ["4:97", "4:98", "4:99", "4:100"],
      "نزلت في المستضعفين بمكة الذين لم يهاجروا مع القدرة، ثم استثنت العاجزين حقاً من الرجال والنساء والولدان.",
      "الهجرة واجبة على القادر؛ العاجز معذور، والمتقاعس مسؤول.",
      "political_pressure", "principled_minority_vs_powerful_majority", "religious_freedom",
      "legal_innovation", "scaling_principle_to_context", "legislation"),

    E("ab_nisa_qasr_salat", 676, 4, "medinan_early",
      "إذا ضربتم في الأرض فليس عليكم جناح أن تقصروا من الصلاة", "No blame to shorten prayer when traveling",
      "Medina", ["4:101"],
      "سأل بعض الصحابة عن قصر الصلاة في السفر وليس هناك عدو، فبيّن القرآن أن القصر جائز في السفر مطلقاً وفي الخوف خاصة.",
      "التيسير في السفر رخصة عامة لا مقيدة بالخوف فقط؛ الله يحب أن تُؤخذ رخصه.",
      "none", "community_vs_outsider", "spiritual_integrity",
      "scaling_principle_to_context", "scaling_principle_to_context", "legislation"),

    E("ab_nisa_killed_believer_mistake", 677, 4, "medinan_early",
      "ما كان لمؤمن أن يقتل مؤمناً إلا خطأ", "A believer should not kill another believer except by mistake",
      "Medina", ["4:92", "4:93"],
      "نزلت في عياش بن أبي ربيعة حين قتل الحارث بن يزيد وهو لا يعلم أنه أسلم، فنزل تشريع القتل الخطأ والعمد والدية والكفارة.",
      "التفريق بين الخطأ والعمد أساس العدالة الجنائية؛ الكفارة تُطهّر الخطأ.",
      "moral_failure_by_self", "claimant_vs_accused", "justice_vs_privilege",
      "legal_innovation", "procedural_justice_over_outcome", "legislation"),

    # ═══════════════ SURAT AL-MAIDAH ASBAB ═══════════════
    E("ab_maidah_contracts", 678, 6, "medinan_late",
      "يا أيها الذين آمنوا أوفوا بالعقود", "O you who believe, fulfill contracts",
      "Medina", ["5:1"],
      "نزلت في آخر ما نزل من القرآن تنظيماً، تأمر بالوفاء بالعقود كلها: عقود الله، وعقود الناس، وعقود الأمانة.",
      "الوفاء بالعقد أصل الحضارة؛ المسلم من أكرم الناس عهداً.",
      "none", "community_vs_outsider", "trust_between_parties",
      "legal_innovation", "trust_is_earned_by_consistency", "command"),

    E("ab_maidah_table_isa", 679, 3, "medinan_early",
      "قصة المائدة — حواريو عيسى", "Story of the Table — disciples of Jesus",
      "Medina", ["5:112", "5:113", "5:114", "5:115"],
      "نزلت قصة طلب حواريي عيسى منه أن يُنزّل عليهم مائدة من السماء، فأنزلها الله وحذّر من يكفر بعدها بعذاب.",
      "الآيات المادية لا تلزم الإيمان إذا سبقها التردد؛ الطالب يُمتحن بما طلب.",
      "intellectual_challenge", "teacher_vs_student", "truth_vs_falsehood",
      "teaching_through_demonstration", "signs_require_reflection_not_proof", "story"),

    E("ab_maidah_hukm_jahiliyyah", 680, 4, "medinan_middle",
      "أفحكم الجاهلية يبغون", "Do they seek the judgment of ignorance?",
      "Medina", ["5:50"],
      "نزلت في بعض يهود المدينة الذين رفضوا حكم النبي ﷺ وطلبوا التحاكم إلى أعراف جاهلية بدل الشريعة.",
      "التحاكم إلى غير الله حين يكون حكم الله متاحاً مرفوض؛ الشريعة ليست اختياراً.",
      "legal_coercion", "community_vs_outsider", "justice_vs_privilege",
      "moral_rebuke", "refusing_to_legitimize_falsehood", "rebuke"),

    E("ab_maidah_wudu_full", 681, 5, "medinan_middle",
      "آية الوضوء الكاملة في المائدة", "The complete ablution verse in al-Maidah",
      "Medina", ["5:6"],
      "نزلت آية الوضوء في سورة المائدة مفصّلة: غسل الوجه واليدين ومسح الرأس وغسل الرجلين، والتيمم بدل عند عدم الماء.",
      "تفصيل العبادة البدنية بدقة يمنع الاجتهاد الخاطئ؛ الشكل في العبادة توقيفي.",
      "none", "community_vs_outsider", "spiritual_integrity",
      "legal_innovation", "consistency_public_and_private", "legislation"),

    E("ab_maidah_jews_christians_allies", 682, 5, "medinan_middle",
      "يا أيها الذين آمنوا لا تتخذوا اليهود والنصارى أولياء", "Do not take Jews and Christians as protectors",
      "Medina", ["5:51"],
      "نزلت في عبادة بن الصامت حين تبرّأ من حلفه مع بني قينقاع، وعبد الله بن أبي الذي أصرّ على حلفه معهم.",
      "الولاء السياسي في الحرب لا يجتمع مع التحالف مع العدو؛ الآية في سياق الحرب لا في التعامل العام.",
      "internal_betrayal", "community_vs_outsider", "trust_between_parties",
      "moral_rebuke", "solidarity_around_principle", "warning"),

    E("ab_maidah_qabil_habil", 683, 2, "medinan_early",
      "قصة ابني آدم هابيل وقابيل", "Story of Adam's two sons, Habil and Qabil",
      "Medina", ["5:27", "5:28", "5:29", "5:30", "5:31", "5:32"],
      "نزلت قصة ابني آدم لبيان بشاعة القتل وأنه أول ذنب بشري على الأرض، فمن قتل نفساً فكأنما قتل الناس جميعاً.",
      "القتل الأول مصدر كل قتل بعده؛ حرمة الدم أصل من أصول الشريعة.",
      "physical_persecution", "kin_vs_kin", "physical_safety",
      "moral_rebuke", "accountability_proportional_to_power", "story"),

    E("ab_maidah_sariqah_hadd", 684, 5, "medinan_middle",
      "والسارق والسارقة فاقطعوا أيديهما", "Cut the hand of the male and female thief",
      "Medina", ["5:38", "5:39"],
      "نزل حدّ السرقة بشروطه: النصاب المحدد، الحرز، وعدم الشبهة، مع فتح باب التوبة.",
      "العقوبة الرادعة للسرقة تحمي المال العام؛ لكنها مشروطة بتوفر الحدّ الأدنى.",
      "moral_failure_by_self", "claimant_vs_accused", "property_rights",
      "legal_innovation", "procedural_justice_over_outcome", "legislation"),

    # ═══════════════ SURAT AL-ANAM / AL-ARAF ASBAB ═══════════════
    E("ab_anam_cattle_superstition", 685, -5, "meccan_middle",
      "ما جعل الله من بحيرة ولا سائبة", "Allah did not ordain bahira, sa'iba, etc.",
      "Mecca", ["5:103", "6:136", "6:137", "6:138", "6:139"],
      "كان المشركون يُحرّمون بعض الأنعام بزعم ديني (البحيرة والسائبة والوصيلة والحامي)، فأبطل القرآن كل ذلك.",
      "التحريم الذاتي بلا سند إلهي افتراء على الله؛ العادات ليست شريعة.",
      "intellectual_challenge", "believer_vs_unbeliever", "religious_freedom",
      "intellectual_rebuttal", "rejection_of_blind_imitation", "rebuke"),

    E("ab_anam_do_not_curse_idols", 686, -6, "meccan_middle",
      "ولا تسبوا الذين يدعون من دون الله", "Do not insult those they invoke besides Allah",
      "Mecca", ["6:108"],
      "كان بعض المسلمين يسبّون أصنام المشركين فيسبّ المشركون الله، فنزل النهي عن سب الآلهة الباطلة لئلا يسبّوا الله عدواً بغير علم.",
      "الحكمة في الدعوة تمنع ردّ الفعل الأسوأ؛ النتيجة أهم من الانفعال.",
      "verbal_attack", "believer_vs_unbeliever", "religious_freedom",
      "scaling_principle_to_context", "scaling_principle_to_context", "prohibition"),

    E("ab_araf_heights_people", 687, -5, "meccan_middle",
      "أصحاب الأعراف بين الجنة والنار", "People of the Heights between paradise and fire",
      "Mecca", ["7:46", "7:47", "7:48", "7:49"],
      "نزل ذكر أصحاب الأعراف الذين تساوت حسناتهم وسيئاتهم فلم يدخلوا الجنة ولا النار ابتداءً، يعرفون أهل الجنة وأهل النار بسيماهم.",
      "الميزان الأخروي دقيق؛ التساوي بين الحسنات والسيئات موقف معلّق.",
      "none", "self_vs_self", "divine_acceptance",
      "teaching_through_demonstration", "balance_between_fear_and_hope", "story"),

    E("ab_araf_clothes_decoration", 688, -5, "meccan_middle",
      "يا بني آدم خذوا زينتكم عند كل مسجد", "Take your adornment at every masjid",
      "Mecca", ["7:31", "7:32"],
      "كان بعض المشركين يطوفون بالبيت عُراة بحجّة التعبّد، فنزل الأمر بأخذ الزينة عند كل مسجد ولا تُسرفوا.",
      "الزينة في العبادة مشروعة بل مأمور بها؛ التعري ليس تقرّباً.",
      "none", "community_vs_outsider", "spiritual_integrity",
      "moral_rebuke", "rejection_of_blind_imitation", "command"),

    # ═══════════════ SURAT AL-ANFAL / AL-TAWBAH ═══════════════
    E("ab_anfal_spoils_question", 689, 2, "medinan_early",
      "يسألونك عن الأنفال", "They ask about the spoils of war",
      "Medina", ["8:1"],
      "اختلف المسلمون بعد بدر في الغنائم: من جمعها ومن قاتل ومن حرس، فنزلت يسألونك عن الأنفال لله والرسول.",
      "ملكية الغنائم لله ورسوله يمنع التنازع؛ القائد يقسم بالعدل.",
      "legal_coercion", "ally_vs_ally_dispute", "property_rights",
      "legal_innovation", "procedural_justice_over_outcome", "legislation"),

    E("ab_tawbah_sadaqat_types", 690, 9, "medinan_late",
      "إنما الصدقات للفقراء والمساكين", "Charity is only for the poor and the needy",
      "Medina", ["9:60"],
      "نزلت لتحديد ثمانية مصارف للزكاة بدقة: الفقراء والمساكين والعاملين عليها والمؤلفة قلوبهم وفي الرقاب والغارمين وفي سبيل الله وابن السبيل.",
      "تحديد المصارف يمنع الاجتهاد الخاطئ في صرف الزكاة؛ المال العام له قنوات محددة.",
      "none", "community_vs_outsider", "livelihood",
      "legal_innovation", "economic_justice_as_worship", "legislation"),

    E("ab_tawbah_bara_mushrikeen", 691, 9, "medinan_late",
      "براءة من الله ورسوله إلى الذين عاهدتم من المشركين", "Dissolution from Allah and His Messenger toward the polytheists",
      "Medina", ["9:1", "9:2", "9:3", "9:4", "9:5"],
      "نزلت بعد فتح مكة لنبذ عهود المشركين الذين نقضوها، مع أجل أربعة أشهر لمن لم ينقض، ولحرية من لم يُقاتل.",
      "نبذ العهود المنقوضة مشروع بعد إعلان مسبق؛ المهلة تحفظ حقّ المسالم.",
      "political_pressure", "community_vs_outsider", "trust_between_parties",
      "legal_innovation", "trust_is_earned_by_consistency", "legislation"),

    E("ab_tawbah_masjid_mushrikeen", 692, 9, "medinan_late",
      "ما كان للمشركين أن يعمروا مساجد الله", "It is not for polytheists to maintain Allah's mosques",
      "Medina", ["9:17", "9:18"],
      "نزلت حين افتخر المشركون بسقاية الحاج وعمارة المسجد الحرام، فبيّن القرآن أن العمارة الحقيقية بالإيمان لا بالبناء المادي.",
      "الخدمة المادية لا تُغني عن الإيمان؛ العمارة الروحية فوق العمارة الحجرية.",
      "verbal_attack", "believer_vs_unbeliever", "spiritual_integrity",
      "moral_rebuke", "sincerity_over_performance", "rebuke"),

    E("ab_tawbah_gold_silver_hoarded", 693, 9, "medinan_late",
      "والذين يكنزون الذهب والفضة", "Those who hoard gold and silver",
      "Medina", ["9:34", "9:35"],
      "نزلت في التحذير من كنز المال وعدم إخراج حقّ الله فيه، وفيها وعيد بالكي بالنار يوم القيامة.",
      "كنز المال دون إخراج الزكاة جريمة اقتصادية وأخلاقية؛ المال يتحرك أو يُعذّب صاحبه.",
      "moral_temptation", "self_vs_self", "livelihood",
      "moral_rebuke", "economic_justice_as_worship", "warning"),

    # ═══════════════ SURAT YUNUS TO AL-KAHF ═══════════════
    E("ab_yunus_wahi_confirm", 694, -5, "meccan_middle",
      "وما كان هذا القرآن أن يُفترى من دون الله", "This Quran could not have been produced other than by Allah",
      "Mecca", ["10:37", "10:38"],
      "ادّعى المشركون أن النبي ﷺ اختلق القرآن، فنزل التحدي بأن يأتوا بسورة واحدة من مثله واستعينوا بمن شئتم.",
      "التحدي بسورة واحدة أقل ما يُبرهن به الإعجاز؛ العجز عن الأقل دليل على العجز عن الكل.",
      "intellectual_challenge", "principled_minority_vs_powerful_majority", "truth_vs_falsehood",
      "intellectual_rebuttal", "legitimacy_follows_method", "argument"),

    E("ab_hud_istiqamah", 695, -5, "meccan_middle",
      "فاستقم كما أُمرت", "So remain steadfast as you have been commanded",
      "Mecca", ["11:112"],
      "قال النبي ﷺ: شيّبتني هود وأخواتها، لأن آية الاستقامة أشدّ ما نزل عليه.",
      "الاستقامة أثقل من كل عبادة مفردة؛ الثبات المستمر أشقّ من الانفجار اللحظي.",
      "psychological_pressure", "self_vs_self", "spiritual_integrity",
      "endurance_without_retaliation", "consistency_public_and_private", "command"),

    E("ab_ra_d_thunder_praise", 696, -5, "meccan_middle",
      "ويسبح الرعد بحمده والملائكة من خيفته", "Thunder glorifies Him with praise, and the angels from fear",
      "Mecca", ["13:13"],
      "سأل بعض الناس عن الرعد والبرق، فبيّن القرآن أن الرعد ملك يُسبّح والملائكة خائفة من ربها.",
      "الظواهر الطبيعية لها بُعد غيبي فوق الفيزيائي؛ الكون يُسبّح بطريقته.",
      "intellectual_challenge", "community_vs_outsider", "knowledge_access",
      "clarification", "signs_require_reflection_not_proof", "clarification"),

    E("ab_ibrahim_tree_word", 697, -5, "meccan_middle",
      "ألم تر كيف ضرب الله مثلاً كلمة طيبة كشجرة طيبة", "Have you not seen how Allah sets forth a parable — a good word like a good tree",
      "Mecca", ["14:24", "14:25", "14:26"],
      "نزل مثل الكلمة الطيبة بالشجرة الثابتة والكلمة الخبيثة بالشجرة المجتثّة، تعليماً بالصورة لا بالمجرد.",
      "الأمثال القرآنية أداة تعليم بصري؛ الفكرة المجرّدة تُرسّخها الصورة الحسية.",
      "none", "community_vs_outsider", "knowledge_access",
      "teaching_through_demonstration", "knowledge_before_action", "argument"),

    E("ab_nahl_bee_revelation", 698, -5, "meccan_middle",
      "وأوحى ربك إلى النحل", "And your Lord inspired the bee",
      "Mecca", ["16:68", "16:69"],
      "نزلت آيات النحل ضمن حجة كونية مكية: الله أوحى للنحل بأن تتخذ من الجبال بيوتاً ومن الشجر ومما يعرشون، وفي بطونها شفاء.",
      "النحلة نموذج للتنظيم الإلهي في أصغر المخلوقات؛ الطبيعة كتاب مفتوح.",
      "intellectual_challenge", "community_vs_outsider", "knowledge_access",
      "teaching_through_demonstration", "signs_require_reflection_not_proof", "argument"),

    E("ab_isra_17_commandments", 699, -2, "meccan_late",
      "وصايا سورة الإسراء السبعة عشر", "The seventeen commandments of Surat al-Isra",
      "Mecca", ["17:22", "17:23", "17:24", "17:25", "17:26", "17:27", "17:28", "17:29", "17:30", "17:31", "17:32", "17:33", "17:34", "17:35", "17:36", "17:37", "17:38", "17:39"],
      "نزلت في سورة الإسراء 17 وصية متتالية تبدأ من التوحيد وبر الوالدين مروراً بحفظ المال والعرض والنفس وانتهاءً بالتواضع.",
      "دستور أخلاقي مكي مختصر؛ كل وصية أصل لباب فقهي كامل.",
      "none", "community_vs_outsider", "spiritual_integrity",
      "legal_innovation", "knowledge_before_action", "command"),

    # ═══════════════ SURAT MARYAM TO AL-SAJDAH ═══════════════
    E("ab_maryam_zakariyya_dua", 700, -5, "meccan_middle",
      "دعاء زكريا لطلب الولد", "Zakariyya's supplication for a child",
      "Mecca", ["19:2", "19:3", "19:4", "19:5", "19:6", "19:7", "19:8", "19:9", "19:10", "19:11"],
      "نزلت قصة زكريا في سورة مريم تروي دعاءه لربه في الشيخوخة أن يهبه ولياً يرث من آل يعقوب، فبشّره الله بيحيى.",
      "الدعاء لا ييأس من العمر؛ الاستجابة تأتي حتى في اللحظة المستحيلة.",
      "psychological_pressure", "self_vs_self", "generational_legacy",
      "refuge_with_god_against_despair", "refuge_with_god_against_despair", "story"),

    E("ab_maryam_isa_miracles", 701, -5, "meccan_middle",
      "ميلاد عيسى عليه السلام بلا أب", "Birth of Jesus without a father",
      "Mecca", ["19:16", "19:17", "19:18", "19:19", "19:20", "19:21", "19:22", "19:23", "19:24", "19:25", "19:26", "19:27", "19:28", "19:29", "19:30", "19:31", "19:32", "19:33", "19:34"],
      "نزلت قصة ولادة عيسى عليه السلام من مريم العذراء في مكة، تثبيتاً للمؤمنين وردّاً على شبهة ألوهية عيسى.",
      "الولادة المعجزة آية على القدرة لا على الألوهية؛ القرآن يُنزل عيسى من مرتبة الإله إلى مرتبة النبي.",
      "intellectual_challenge", "community_vs_outsider", "truth_vs_falsehood",
      "intellectual_rebuttal", "truth_is_independent_of_carrier", "story"),

    E("ab_taha_musa_tuwa", 702, -7, "meccan_middle",
      "مناجاة موسى في الوادي المقدس طوى", "Musa's conversation in the sacred valley of Tuwa",
      "Mecca", ["20:9", "20:10", "20:11", "20:12", "20:13", "20:14"],
      "نزلت قصة نداء الله لموسى في الوادي المقدس وتكليفه بالرسالة إلى فرعون، وهي من أقوى مشاهد الوحي المباشر.",
      "الوحي المباشر يعكس أعلى مراتب الاتصال بالله؛ موسى كلّمه الله تكليماً.",
      "none", "self_vs_self", "spiritual_integrity",
      "confrontation_with_truth", "knowledge_before_action", "story"),

    E("ab_anbiyaa_idols_break", 703, -6, "meccan_middle",
      "إبراهيم يكسر الأصنام", "Ibrahim breaks the idols",
      "Mecca", ["21:57", "21:58", "21:59", "21:60", "21:61", "21:62", "21:63", "21:64", "21:65", "21:66", "21:67", "21:68", "21:69", "21:70"],
      "نزلت قصة تحطيم إبراهيم للأصنام وتعليق الفأس على كبيرها، ليُحاجّ قومه بأن الأصنام لا تنفع ولا تضر.",
      "الحجة العملية أبلغ من النظرية؛ إبراهيم أثبت بطلان الأصنام بفعله لا بكلامه.",
      "intellectual_challenge", "individual_vs_majority", "truth_vs_falsehood",
      "confrontation_with_truth", "rejection_of_blind_imitation", "argument"),

    E("ab_hajj_pilgrimage_call", 704, -5, "meccan_middle",
      "وأذّن في الناس بالحج", "And proclaim to the people the Hajj",
      "Mecca", ["22:27", "22:28"],
      "نزل الأمر لإبراهيم بأن يُنادي في الناس بالحج، فصعد أبا قبيس ونادى: أيها الناس، إن ربكم بنى بيتاً فحجوه.",
      "النداء العلني يبلغ من يسمعه ومن لم يُخلق بعد؛ الصوت يُسجَّل في الكون.",
      "none", "community_vs_outsider", "religious_freedom",
      "public_declaration", "collective_obligation_above_personal", "command"),

    E("ab_furqan_criterion_name", 705, -5, "meccan_middle",
      "تسمية القرآن بالفرقان", "Naming the Quran 'al-Furqan'",
      "Mecca", ["25:1"],
      "سُمّي القرآن بالفرقان لأنه يفرق بين الحق والباطل، نزل في سياق الرد على المشركين الذين طلبوا كتاباً مختلفاً.",
      "الفرقان تسمية وظيفية لا مجرد لقب؛ الغرض التمييز بين الحق والباطل.",
      "intellectual_challenge", "principled_minority_vs_powerful_majority", "truth_vs_falsehood",
      "intellectual_rebuttal", "source_integrity_over_popularity", "argument"),

    E("ab_shuara_poets_exception", 706, -5, "meccan_middle",
      "إلا الذين آمنوا وعملوا الصالحات من الشعراء", "Except the poets who believe and do good",
      "Mecca", ["26:224", "26:225", "26:226", "26:227"],
      "لمّا نزل ذم الشعراء حزن حسان بن ثابت وعبد الله بن رواحة وكعب بن مالك، فنزل استثناء الشعراء المؤمنين.",
      "الإسلام لا يرفض الشعر بل يرفض الشعر الضال؛ الأداة محايدة والمحتوى هو المحكّ.",
      "verbal_attack", "teacher_vs_student", "knowledge_access",
      "clarification", "truth_is_independent_of_carrier", "clarification"),

    E("ab_naml_sulayman_ants", 707, -5, "meccan_middle",
      "قصة سليمان والنمل", "Story of Sulayman and the ants",
      "Mecca", ["27:18", "27:19"],
      "نزلت قصة مرور سليمان بوادي النمل وسماعه لنملة تحذّر قومها، فتبسّم ضاحكاً من قولها ودعا ربه.",
      "العلم بلغات المخلوقات آية من آيات الله؛ حتى النمل له حكومته ونظامه.",
      "none", "ruler_vs_ruled", "knowledge_access",
      "teaching_through_demonstration", "signs_require_reflection_not_proof", "story"),

    E("ab_qasas_firaun_haman", 708, -5, "meccan_middle",
      "فرعون يأمر هامان ببناء صرح", "Pharaoh orders Haman to build a tower",
      "Mecca", ["28:38", "40:36", "40:37"],
      "أمر فرعون وزيره هامان ببناء صرح ليبلغ أسباب السماوات فيطّلع إلى إله موسى، في أغرب محاولة بشرية لإثبات عدم وجود الله.",
      "الطاغية يتكلّف ما لا يستطيع ليُثبت باطله؛ الحيلة لا تُلغي الحقيقة.",
      "intellectual_challenge", "ruler_vs_ruled", "truth_vs_falsehood",
      "intellectual_rebuttal", "warning_against_arrogance", "story"),

    E("ab_rum_prophecy_victory", 709, -6, "meccan_middle",
      "نبوءة انتصار الروم على الفرس", "Prophecy of Roman victory over Persia",
      "Mecca", ["30:1", "30:2", "30:3", "30:4", "30:5", "30:6"],
      "نزلت نبوءة غلبة الروم على الفرس في بضع سنين، وراهن أبو بكر قريشاً على تحقّقها فتحققت في سبع سنين.",
      "النبوءة القرآنية تتحقق بحذافيرها؛ الإخبار بالغيب دليل على المصدر.",
      "intellectual_challenge", "principled_minority_vs_powerful_majority", "truth_vs_falsehood",
      "intellectual_rebuttal", "source_integrity_over_popularity", "promise"),

    E("ab_luqman_wisdom", 710, -5, "meccan_middle",
      "وصايا لقمان لابنه", "Luqman's advice to his son",
      "Mecca", ["31:13", "31:14", "31:15", "31:16", "31:17", "31:18", "31:19"],
      "نزلت وصايا لقمان الحكيم لابنه: التوحيد، بر الوالدين، مراقبة الله، الصلاة، الأمر بالمعروف، الصبر، عدم الكبر.",
      "الحكمة تُلقّن من أب لابن؛ التربية الروحية أصلها المنزل.",
      "none", "parent_vs_child", "generational_legacy",
      "teaching_through_demonstration", "knowledge_before_action", "command"),

    E("ab_sajdah_creation_stages", 711, -5, "meccan_middle",
      "خلق الإنسان من سلالة من طين", "Creation of man from an extract of clay",
      "Mecca", ["32:7", "32:8", "32:9"],
      "نزلت آيات مراحل خلق الإنسان: من طين ثم نطفة ثم تسوية ثم نفخ الروح، حجة على البعث والقدرة.",
      "العلم بمراحل الخلق يُثبت القدرة على الإعادة؛ من بدأ يُعيد.",
      "intellectual_challenge", "community_vs_outsider", "truth_vs_falsehood",
      "intellectual_rebuttal", "signs_require_reflection_not_proof", "argument"),

    # ═══════════════ SURAT AL-NUR SUPPLEMENTARY ═══════════════
    E("ab_nur_light_verse", 712, 5, "medinan_middle",
      "الله نور السماوات والأرض", "Allah is the light of the heavens and earth",
      "Medina", ["24:35"],
      "نزلت آية النور مثلاً لنور الله في الكون: مشكاة فيها مصباح المصباح في زجاجة كأنها كوكب درّي.",
      "التمثيل القرآني للنور الإلهي أبلغ من التعريف المجرد؛ الصورة تُقرّب المعنى.",
      "none", "community_vs_outsider", "spiritual_integrity",
      "teaching_through_demonstration", "signs_require_reflection_not_proof", "argument"),

    E("ab_nur_walking_modestly", 713, 5, "medinan_middle",
      "وقل للمؤمنات يغضضن من أبصارهن ويحفظن فروجهن", "Tell the believing women to lower their gaze",
      "Medina", ["24:31"],
      "نزل تفصيل حجاب المرأة المسلمة: غض البصر وحفظ الفرج وعدم إبداء الزينة إلا ما ظهر منها وضرب الخمار على الجيوب.",
      "الحشمة تشريع متبادل (للرجال والنساء)؛ الحدود تبدأ بالنظر.",
      "none", "community_vs_outsider", "personal_dignity",
      "legal_innovation", "boundaries_in_intimate_relations", "command"),

    E("ab_nur_walk_in_homes", 714, 5, "medinan_middle",
      "ليستأذنكم الذين ملكت أيمانكم والذين لم يبلغوا الحلم", "Let those under your authority ask permission at three times",
      "Medina", ["24:58", "24:59"],
      "نزلت أحكام الاستئذان داخل البيت الواحد: العبيد والأطفال يستأذنون في ثلاث أوقات (الفجر والظهيرة والعشاء).",
      "الخصوصية حقّ حتى داخل البيت الواحد؛ الحدود الداخلية تحفظ الكرامة.",
      "none", "parent_vs_child", "personal_dignity",
      "legal_innovation", "boundaries_in_intimate_relations", "legislation"),

    # ═══════════════ SURAT AL-HUJURAT ═══════════════
    E("ab_hujurat_verify_news", 715, 9, "medinan_late",
      "إن جاءكم فاسق بنبأ فتبيّنوا", "If a wicked person brings you news, verify it",
      "Medina", ["49:6"],
      "نزلت في الوليد بن عقبة حين أخبر النبي ﷺ أن بني المصطلق ارتدّوا (وكان كاذباً)، فكاد النبي يغزوهم حتى تبيّن الكذب.",
      "التثبت من الخبر قبل الحكم أصل؛ الخبر الكاذب قد يُشعل حرباً.",
      "internal_betrayal", "claimant_vs_accused", "trust_between_parties",
      "deferral_of_judgement", "procedural_justice_over_outcome", "legislation"),

    E("ab_hujurat_rooms_call", 716, 9, "medinan_late",
      "إن الذين ينادونك من وراء الحجرات أكثرهم لا يعقلون", "Those who call you from behind the chambers lack understanding",
      "Medina", ["49:4", "49:5"],
      "جاء وفد من بني تميم فنادوا النبي ﷺ من وراء حجراته في وقت القيلولة بصوت عالٍ، فنزلت تُؤدّبهم.",
      "احترام وقت القائد أدب واجب؛ المُنادي بلا أدب يفقد الاحترام.",
      "verbal_attack", "community_vs_outsider", "personal_dignity",
      "moral_rebuke", "boundaries_in_intimate_relations", "rebuke"),

    E("ab_hujurat_peoples_tribes", 717, 9, "medinan_late",
      "وجعلناكم شعوباً وقبائل لتعارفوا", "We made you peoples and tribes that you may know one another",
      "Medina", ["49:13"],
      "نزلت يوم فتح مكة حين أمر النبي ﷺ بلالاً أن يؤذّن فوق الكعبة فقال بعض قريش: أهذا العبد الأسود؟ فنزلت المساواة الجذرية.",
      "التعدد العرقي للتعارف لا للتفاخر؛ التقوى المعيار الوحيد.",
      "social_exclusion", "community_vs_outsider", "personal_dignity",
      "moral_rebuke", "rejection_of_blind_imitation", "legislation"),

    # ═══════════════ SURAT AL-MUMTAHANAH / AL-SAFF ═══════════════
    E("ab_mumtahanah_women_migrate", 718, 6, "medinan_middle",
      "امتحان المهاجرات قبل القبول", "Testing emigrant women before acceptance",
      "Medina", ["60:10"],
      "بعد صلح الحديبية جاءت نساء مؤمنات من مكة مهاجرات، فأمر الله بامتحانهن قبل القبول، فإن عُلم إيمانهن لا يُرجعن إلى الكفار.",
      "المرأة المؤمنة لا تُعاد إلى الكفر بحكم معاهدة؛ الإيمان فوق السياسة.",
      "political_pressure", "spouse_vs_spouse", "religious_freedom",
      "legal_innovation", "protection_of_the_weak", "legislation"),

    E("ab_mumtahanah_kind_to_peaceful", 719, 6, "medinan_middle",
      "لا ينهاكم الله عن الذين لم يقاتلوكم", "Allah does not forbid you from those who did not fight you",
      "Medina", ["60:8", "60:9"],
      "نزلت في أسماء بنت أبي بكر حين جاءت أمها (وكانت مشركة) تزورها، فسألت النبي ﷺ: أأصل أمي؟ فقال: صلي أمك.",
      "البر بالأقارب غير المحاربين مشروع بل مأمور به؛ التمييز بين المسالم والمحارب.",
      "family_pressure", "kin_vs_kin", "family_integrity",
      "clarification", "distinguishing_enemy_from_outsider", "legislation"),

    E("ab_saff_who_helps_god", 720, 3, "medinan_early",
      "من أنصاري إلى الله", "Who are my helpers to Allah?",
      "Medina", ["61:14"],
      "نزلت قصة حواريي عيسى حين قال لهم من أنصاري إلى الله قالوا نحن أنصار الله، تشبيهاً بأنصار المدينة.",
      "الأنصار في كل عصر هم من يستجيب لدعوة الله؛ التسمية أقدم من المسمَّين.",
      "none", "community_vs_outsider", "community_cohesion",
      "seeking_allies", "solidarity_around_principle", "praise"),

    # ═══════════════ SURAT AL-JUMUA / AL-MUNAFIQUN / AL-TALAQ / AL-TAHRIM ═══════════════
    E("ab_jumua_caravan_interrupts", 721, 2, "medinan_early",
      "انصراف الناس عن الخطبة لقافلة تجارية", "People leave the sermon for a trade caravan",
      "Medina", ["62:11"],
      "بينما النبي ﷺ يخطب الجمعة جاءت قافلة فانفضّ أكثر المصلين إليها ولم يبقَ معه إلا اثنا عشر، فنزل وإذا رأوا تجارة أو لهواً انفضوا إليها.",
      "البيع يُترك للخطبة لا العكس؛ الدنيا لا تُقدَّم على ذكر الله.",
      "moral_temptation", "community_vs_outsider", "spiritual_integrity",
      "moral_rebuke", "sincerity_over_performance", "rebuke"),

    E("ab_munafiqun_ibn_ubayy_exposed", 722, 5, "medinan_middle",
      "كشف ابن أبي بأبلغ صيغة", "Exposing Ibn Ubayy in the strongest terms",
      "Medina", ["63:1", "63:2", "63:3", "63:4"],
      "نزلت سورة المنافقون تكشف نفاق عبد الله بن أبي بأقسى الأوصاف: إذا رأيتهم تعجبك أجسامهم وإن يقولوا تسمع لقولهم كأنهم خُشُب مُسنّدة.",
      "الظاهر الجميل لا يعني الباطن الصادق؛ القرآن يكشف ما تُخفي النفوس.",
      "internal_betrayal", "insider_hypocrite_vs_sincere", "trust_between_parties",
      "moral_rebuke", "consistency_public_and_private", "rebuke"),

    E("ab_talaq_rules_divorce", 723, 6, "medinan_middle",
      "يا أيها النبي إذا طلقتم النساء فطلقوهن لعدتهن", "O Prophet, when you divorce women, divorce them for their waiting period",
      "Medina", ["65:1", "65:2", "65:3", "65:4", "65:5"],
      "نزلت سورة الطلاق تُنظّم أحكام الطلاق بدقة: الطلاق للعدة، عدم إخراج المطلقة من بيتها، نفقة الحامل، وأجر الرضاع.",
      "الطلاق له آداب كالنكاح؛ إنهاء العلاقة لا يعني إنهاء الحقوق.",
      "legal_coercion", "spouse_vs_spouse", "family_integrity",
      "legal_innovation", "protection_of_the_weak", "legislation"),

    E("ab_tahrim_honey_incident", 724, 7, "medinan_middle",
      "يا أيها النبي لمَ تحرّم ما أحلّ الله لك", "O Prophet, why do you prohibit what Allah has made lawful?",
      "Medina", ["66:1", "66:2", "66:3", "66:4", "66:5"],
      "حرّم النبي ﷺ على نفسه العسل (أو جاريته مارية) إرضاءً لبعض أزواجه، فعاتبه الله بأنه لا يُحرّم الحلال لمجاملة.",
      "حتى النبي يُعاتَب في إبطال الحلال بلا نص؛ الشريعة فوق المجاملة.",
      "family_pressure", "spouse_vs_spouse", "family_integrity",
      "moral_rebuke", "limits_of_personal_discretion", "rebuke"),

    E("ab_tahrim_wives_choice", 725, 7, "medinan_middle",
      "يا أيها النبي قل لأزواجك إن كنتن تردن الحياة الدنيا", "O Prophet, tell your wives: if you desire worldly life...",
      "Medina", ["33:28", "33:29"],
      "طلبت بعض زوجات النبي ﷺ التوسعة في النفقة، فاعتزلهن شهراً ثم نزلت آية التخيير، فاخترن الله ورسوله جميعاً.",
      "الشريك في بيت القيادة يختار الرسالة أو الراحة؛ الجمع بينهما ليس حقاً.",
      "family_pressure", "spouse_vs_spouse", "family_integrity",
      "refusal_to_compromise", "chosen_hardship_over_compromise", "legislation"),

    # ═══════════════ SHORT SURAHS ═══════════════
    E("ab_mulk_protection_from_grave", 726, -5, "meccan_middle",
      "سورة الملك تمنع عذاب القبر", "Surah al-Mulk protects from the grave's torment",
      "Mecca", ["67:1", "67:2"],
      "حثّ النبي ﷺ على قراءة سورة الملك كل ليلة وأخبر أنها المانعة من عذاب القبر وأنها تُجادل عن صاحبها.",
      "المواظبة على سورة واحدة يومياً شفاعة مؤجلة؛ العبادة البسيطة قد تحمي من الأثقل.",
      "none", "self_vs_self", "divine_acceptance",
      "teaching_through_demonstration", "consistency_public_and_private", "promise"),

    E("ab_qalam_ashab_jannah", 727, -8, "meccan_middle",
      "قصة أصحاب الجنة في سورة القلم", "Story of the garden owners in Surah al-Qalam",
      "Mecca", ["68:17", "68:18", "68:19", "68:20", "68:21", "68:22", "68:23", "68:24", "68:25", "68:26", "68:27", "68:28", "68:29", "68:30", "68:31", "68:32", "68:33"],
      "نزلت قصة أصحاب البستان الذين أقسموا ألا يُطعموا المساكين فأهلك الله بستانهم، عبرة لقريش في البخل.",
      "البخل يُهلك مصدره؛ النعمة تزول بترك حق الفقير فيها.",
      "moral_temptation", "community_vs_outsider", "livelihood",
      "moral_rebuke", "economic_justice_as_worship", "story"),

    E("ab_jinn_listen_quran", 728, -3, "meccan_late",
      "سورة الجن: نفر من الجن يستمعون للقرآن", "Surah al-Jinn: a group of jinn listen to the Quran",
      "Nakhla", ["72:1", "72:2", "72:3", "72:4", "72:5", "72:6", "72:7", "72:8"],
      "مرّ نفر من الجن بالنبي ﷺ وهو يصلي بنخلة فسمعوا القرآن وعادوا إلى قومهم منذرين.",
      "القرآن يستقطب كل ذي فطرة صادقة حتى من غير البشر.",
      "none", "community_vs_outsider", "truth_vs_falsehood",
      "intellectual_rebuttal", "truth_is_independent_of_carrier", "story"),

    E("ab_muzzammil_night_prayer", 729, -12, "meccan_early",
      "قم الليل إلا قليلاً", "Stand at night except a little",
      "Mecca", ["73:1", "73:2", "73:3", "73:4", "73:5", "73:6", "73:7", "73:8"],
      "نزلت في أول الإسلام تأمر النبي ﷺ بقيام الليل إلا قليلاً، فقام مع أصحابه حتى انتفخت أقدامهم، ثم خُفّف الحكم.",
      "الإعداد الروحي يسبق كل تكليف كبير؛ الليل مدرسة القادة.",
      "none", "self_vs_self", "spiritual_integrity",
      "legal_innovation", "consistency_public_and_private", "command"),

    E("ab_insan_itaam", 730, -5, "meccan_middle",
      "ويُطعمون الطعام على حبه مسكيناً ويتيماً وأسيراً", "They feed food out of love to the needy, orphan, and captive",
      "Mecca", ["76:8", "76:9", "76:10", "76:11"],
      "نزلت في علي وفاطمة وخادمهما (أو في المؤمنين عامة) حين صاموا ثلاثة أيام وأفطروا كل مرة على صدقة.",
      "الإيثار في وقت الحاجة أعلى مراتب الإنفاق؛ من أطعم وهو جائع فقد بلغ الذروة.",
      "economic_siege", "community_vs_outsider", "livelihood",
      "teaching_through_demonstration", "wealth_as_trust_not_ownership", "praise"),

    E("ab_naba_amma_yatasaalun", 731, -6, "meccan_middle",
      "عم يتساءلون — عن النبأ العظيم", "About what are they asking? About the great news",
      "Mecca", ["78:1", "78:2", "78:3", "78:4", "78:5"],
      "تساءل المشركون عن يوم القيامة واختلفوا فيه بين مُنكر ومتشكك، فنزلت لتُقرّر أنهم سيعلمون.",
      "الإنكار لا يُغيّر الحقيقة؛ الجدل في الواضحات إشغال عن الاستعداد.",
      "intellectual_challenge", "principled_minority_vs_powerful_majority", "truth_vs_falsehood",
      "intellectual_rebuttal", "warning_against_arrogance", "warning"),

    E("ab_takwir_soul_questioned", 732, -6, "meccan_middle",
      "وإذا الموءودة سئلت بأي ذنب قتلت", "When the female infant buried alive is asked for what sin she was killed",
      "Mecca", ["81:8", "81:9"],
      "نزلت في وأد البنات الذي كان منتشراً في الجاهلية، فجعل القرآن السؤال يُوجَّه للضحية لا للجاني.",
      "العدالة الإلهية تُعيد الحق للضعيف؛ المُستضعف في الدنيا شاهد في الآخرة.",
      "physical_persecution", "parent_vs_child", "physical_safety",
      "moral_rebuke", "protection_of_the_weak", "rhetorical_question"),

    E("ab_infitar_angels_watching", 733, -6, "meccan_middle",
      "وإن عليكم لحافظين كراماً كاتبين", "Over you are appointed angels, noble and recording",
      "Mecca", ["82:10", "82:11", "82:12"],
      "نزلت تذكيراً بأن الملائكة تُسجّل كل فعل، فلا يظن الإنسان أنه بلا رقيب.",
      "الرقابة الذاتية مبنية على يقين الرقابة الإلهية؛ المؤمن يتصرف كمن يُراقَب.",
      "none", "self_vs_self", "spiritual_integrity",
      "moral_rebuke", "consistency_public_and_private", "warning"),

    E("ab_mutaffifin_cheaters", 734, -1, "meccan_late",
      "ويل للمطففين", "Woe to those who cheat in weights",
      "Medina/Mecca", ["83:1", "83:2", "83:3", "83:4", "83:5", "83:6"],
      "نزلت في أهل المدينة (أو مكة) الذين كانوا يُطفّفون في الميزان: يستوفون إذا اكتالوا على الناس ويُخسرون إذا كالوهم أو وزنوهم.",
      "الغش في الميزان ظلم اقتصادي يستوجب الويل؛ العدل يبدأ من الميزان.",
      "moral_temptation", "debtor_vs_creditor", "livelihood",
      "moral_rebuke", "economic_justice_as_worship", "warning"),

    E("ab_buruj_ashab_ukhdud", 735, -6, "meccan_middle",
      "أصحاب الأخدود — قصة المؤمنين المحرَقين", "People of the Ditch — story of believers burned alive",
      "Mecca", ["85:4", "85:5", "85:6", "85:7", "85:8", "85:9", "85:10"],
      "نزلت قصة أصحاب الأخدود الذين حفروا أخاديد وأشعلوا فيها النار وألقوا المؤمنين فيها، تسليةً للمستضعفين في مكة.",
      "النصر ليس شرطاً في الدنيا؛ الثبات على الحق قد يعني الموت ويبقى الخلود.",
      "physical_persecution", "principled_minority_vs_powerful_majority", "physical_safety",
      "consolation_and_thabaat", "chosen_hardship_over_compromise", "story"),

    E("ab_tariq_star_oath", 736, -6, "meccan_middle",
      "والسماء والطارق — وما أدراك ما الطارق", "By the sky and the night visitor",
      "Mecca", ["86:1", "86:2", "86:3", "86:4"],
      "أقسم القرآن بالنجم الثاقب على أن كل نفس عليها حافظ، فربط بين الكون المشاهد والرقابة الغيبية.",
      "القسم بالظاهرة الكونية يربط الفلك بالأخلاق؛ السماء تشهد على الأرض.",
      "none", "self_vs_self", "spiritual_integrity",
      "teaching_through_demonstration", "signs_require_reflection_not_proof", "oath"),

    E("ab_ala_sabbih", 737, -6, "meccan_middle",
      "سبّح اسم ربك الأعلى", "Glorify the name of your Lord the Most High",
      "Mecca", ["87:1", "87:2", "87:3", "87:4", "87:5", "87:6"],
      "نزلت تأمر بالتسبيح وتذكر أن الله خلق فسوّى وقدّر فهدى وأخرج المرعى، أي أن كل شيء بتقدير.",
      "التسبيح اعتراف بالكمال الإلهي؛ التسمية باسم الأعلى منطلق كل عمل.",
      "none", "self_vs_self", "spiritual_integrity",
      "teaching_through_demonstration", "source_integrity_over_popularity", "command"),

    E("ab_ghashiya_faces_types", 738, -6, "meccan_middle",
      "وجوه يومئذ خاشعة عاملة ناصبة", "Some faces that day will be humble, laboring, exhausted",
      "Mecca", ["88:1", "88:2", "88:3", "88:4", "88:5", "88:6", "88:7"],
      "نزلت تفرّق بين وجوه الآخرة: الخاشعة العاملة التي تعبت بلا فائدة (لأنها على ضلال)، والناعمة الراضية التي أتعبت في الحق.",
      "العمل بلا هدى تعب خاسر؛ النية والاتجاه يحددان قيمة الجهد.",
      "intellectual_challenge", "self_vs_self", "divine_acceptance",
      "moral_rebuke", "intention_determines_value", "warning"),

    E("ab_fajr_iram_columns", 739, -6, "meccan_middle",
      "إرم ذات العماد التي لم يُخلق مثلها في البلاد", "Iram of the pillars, the like of which was not created",
      "Mecca", ["89:6", "89:7", "89:8"],
      "نزل ذكر إرم ذات العماد (قوم عاد) وثمود وفرعون في سياق التحذير من عذاب الأمم السابقة التي طغت.",
      "الحضارات العملاقة تسقط بطغيانها؛ البنيان لا يحمي من العذاب.",
      "political_pressure", "ruler_vs_ruled", "collective_survival",
      "moral_rebuke", "warning_against_arrogance", "warning"),

    E("ab_balad_oath_makkah", 740, -7, "meccan_middle",
      "لا أقسم بهذا البلد وأنت حلّ بهذا البلد", "I swear by this city — and you are lawful in this city",
      "Mecca", ["90:1", "90:2", "90:3", "90:4"],
      "أقسم القرآن بمكة والنبي ﷺ حال فيها، وأن الإنسان خُلق في كبد (مشقة)، تمهيداً للحث على العقبة (الإنفاق والإيمان).",
      "الحياة مشقة بالتصميم لا بالصدفة؛ التسلق أصعب من الراحة لكنه أعلى.",
      "psychological_pressure", "self_vs_self", "spiritual_integrity",
      "consolation_and_thabaat", "chosen_hardship_over_compromise", "oath"),

    E("ab_shams_nafs_oath", 741, -7, "meccan_middle",
      "ونفس وما سوّاها فألهمها فجورها وتقواها", "And a soul and He who proportioned it, inspiring its wickedness and righteousness",
      "Mecca", ["91:7", "91:8", "91:9", "91:10"],
      "أقسم القرآن بأحد عشر قسماً على أن من زكّى نفسه أفلح ومن دسّاها خاب، تأسيساً لمبدأ المسؤولية الفردية.",
      "الإنسان مُلهم بالخير والشر معاً؛ الاختيار بينهما هو الاختبار.",
      "none", "self_vs_self", "spiritual_integrity",
      "teaching_through_demonstration", "correction_of_self_first", "oath"),

    E("ab_layl_generosity_miserliness", 742, -7, "meccan_middle",
      "فأما من أعطى واتقى وصدّق بالحسنى", "As for he who gives and fears God and believes in the best",
      "Mecca", ["92:5", "92:6", "92:7", "92:8", "92:9", "92:10", "92:11"],
      "نزلت تقابل بين صنفين: من أعطى واتقى فيُسّر لليُسرى، ومن بخل واستغنى فيُسّر للعُسرى.",
      "الاختيار بين اليُسرى والعُسرى يومي؛ كل فعل يدفع في اتجاه.",
      "moral_temptation", "self_vs_self", "spiritual_integrity",
      "moral_rebuke", "wealth_as_trust_not_ownership", "warning"),

    E("ab_duha_consolation_orphan", 743, -3, "meccan_late",
      "ما ودعك ربك وما قلى", "Your Lord has not forsaken you nor has He become displeased",
      "Mecca", ["93:1", "93:2", "93:3", "93:4", "93:5", "93:6", "93:7", "93:8"],
      "انقطع الوحي فترة فقال المشركون: إن إلهه قلاه، فنزلت والضحى لتُثبّته: ما ودعك ربك.",
      "الصمت الإلهي اختبار لا هجران؛ العناية مستمرة حتى حين ينقطع الصوت.",
      "psychological_pressure", "self_vs_self", "spiritual_integrity",
      "consolation_and_thabaat", "refuge_with_god_against_despair", "consolation"),

    E("ab_sharh_chest_opened", 744, -3, "meccan_late",
      "ألم نشرح لك صدرك", "Did We not expand for you your chest?",
      "Mecca", ["94:1", "94:2", "94:3", "94:4", "94:5", "94:6"],
      "نزلت تذكيراً بنعم الله على النبي ﷺ: شرح صدره ووضع وزره ورفع ذكره، وأن مع العسر يسراً.",
      "العسر لا يدوم؛ التكرار (مع العسر يسراً) يُضاعف الأمل.",
      "psychological_pressure", "self_vs_self", "spiritual_integrity",
      "consolation_and_thabaat", "refuge_with_god_against_despair", "consolation"),

    E("ab_teen_ahsan_taqweem", 745, -5, "meccan_middle",
      "لقد خلقنا الإنسان في أحسن تقويم", "We have certainly created man in the best of stature",
      "Mecca", ["95:4", "95:5", "95:6"],
      "نزلت تُقرّر كرامة الإنسان بالخِلقة ثم ردّه إلى أسفل سافلين إن لم يُحسن، إلا الذين آمنوا.",
      "الكرامة الأصلية لا تكفي بلا إيمان؛ الإنسان يبدأ من الأعلى ويسقط بالاختيار.",
      "none", "self_vs_self", "personal_dignity",
      "moral_rebuke", "correction_of_self_first", "argument"),

    E("ab_qadr_night_of_power", 746, -3, "meccan_late",
      "ليلة القدر خير من ألف شهر", "The Night of Power is better than a thousand months",
      "Mecca", ["97:1", "97:2", "97:3", "97:4", "97:5"],
      "نزلت سورة القدر تعظيماً لليلة نزول القرآن، وأنها خير من ألف شهر وفيها تنزل الملائكة والروح.",
      "ليلة واحدة قد تُساوي عمراً كاملاً؛ الكمّ لا يقاس بالزمن بل بالأثر.",
      "none", "community_vs_outsider", "spiritual_integrity",
      "teaching_through_demonstration", "divine_testing_mechanism", "promise"),

    E("ab_bayyinah_people_book", 747, 1, "medinan_early",
      "لم يكن الذين كفروا من أهل الكتاب منفكين", "Those who disbelieved among the People of the Book were not to be parted",
      "Medina", ["98:1", "98:2", "98:3", "98:4", "98:5"],
      "نزلت تبيّن أن أهل الكتاب لم يتفرّقوا إلا بعد أن جاءتهم البيّنة، فالحجة قائمة عليهم.",
      "الحجة قائمة بعد البيّنة؛ التفرّق بعد العلم أشدّ من الجهل.",
      "intellectual_challenge", "community_vs_outsider", "truth_vs_falsehood",
      "intellectual_rebuttal", "source_integrity_over_popularity", "argument"),

    E("ab_zilzal_atom_weight", 748, 1, "medinan_early",
      "فمن يعمل مثقال ذرة خيراً يره", "Whoever does an atom's weight of good will see it",
      "Medina", ["99:7", "99:8"],
      "نزلت خواتيم سورة الزلزلة تُقرّر أن كل ذرة من الأعمال محسوبة، خيراً أو شراً.",
      "الميزان الأخروي دقيق إلى حد الذرة؛ لا عمل يضيع ولا ذنب يُتجاهل.",
      "none", "self_vs_self", "divine_acceptance",
      "moral_rebuke", "intention_determines_value", "warning"),

    E("ab_adiyat_horse_oath", 749, -5, "meccan_middle",
      "والعاديات ضبحاً", "By the charging horses panting",
      "Mecca", ["100:1", "100:2", "100:3", "100:4", "100:5", "100:6"],
      "أقسم القرآن بالخيل المغيرة صبحاً على أن الإنسان لربه لكنود (جاحد)، ربطاً بين قوة الحيوان وضعف شكر الإنسان.",
      "الحيوان يخدم بصدق والإنسان يجحد؛ المقارنة تُوقظ الضمير.",
      "none", "self_vs_self", "spiritual_integrity",
      "moral_rebuke", "warning_against_arrogance", "oath"),

    E("ab_takathur_graveyard", 750, -5, "meccan_middle",
      "ألهاكم التكاثر حتى زرتم المقابر", "Competition in increase diverts you until you visit the graves",
      "Mecca", ["102:1", "102:2", "102:3", "102:4"],
      "نزلت في قبيلتين من قريش تفاخرتا بالأحياء والأموات حتى ذهبتا إلى المقابر تعدّان قبورهما.",
      "التفاخر بالكثرة عبث حتى الموت؛ الحياة أقصر من أن تُهدر في العدّ.",
      "verbal_attack", "ally_vs_ally_dispute", "reputation_honor",
      "moral_rebuke", "warning_against_arrogance", "warning"),

    E("ab_asr_time_oath", 751, -5, "meccan_middle",
      "والعصر إن الإنسان لفي خسر", "By time, indeed mankind is in loss",
      "Mecca", ["103:1", "103:2", "103:3"],
      "نزلت أقصر سور القرآن المعنوية تختصر الدين في أربعة أركان: الإيمان والعمل الصالح والتواصي بالحق والتواصي بالصبر.",
      "لو لم ينزل غيرها لكفت؛ الاختصار الإلهي أبلغ من التفصيل البشري.",
      "none", "self_vs_self", "spiritual_integrity",
      "teaching_through_demonstration", "knowledge_before_action", "oath"),

    E("ab_humazah_backbiter", 752, -7, "meccan_middle",
      "ويل لكل همزة لمزة", "Woe to every scorner and mocker",
      "Mecca", ["104:1", "104:2", "104:3", "104:4", "104:5", "104:6"],
      "نزلت في أحد المشركين (قيل الأخنس بن شريق أو أمية بن خلف) الذي كان يسخر من المسلمين ويعدّ ماله ظاناً أنه يخلّده.",
      "السخرية والعد الحريص للمال وجهان لعملة الغرور؛ المال لا يُخلّد.",
      "verbal_attack", "individual_vs_majority", "reputation_honor",
      "moral_rebuke", "warning_against_arrogance", "warning"),

    E("ab_fil_elephant", 753, -40, "meccan_early",
      "ألم تر كيف فعل ربك بأصحاب الفيل", "Have you not seen what your Lord did with the elephant people?",
      "Mecca", ["105:1", "105:2", "105:3", "105:4", "105:5"],
      "نزلت تذكّر قريشاً بأن الله حمى الكعبة من أبرهة وفيله بطير أبابيل ترميهم بحجارة من سجيل.",
      "حماية البيت الحرام رسالة لقريش: الله يحمي بيته بلا جيش بشري.",
      "existential_threat", "principled_minority_vs_powerful_majority", "collective_survival",
      "refuge_with_god_against_despair", "refuge_with_god_against_despair", "story"),

    E("ab_quraysh_winter_summer", 754, -40, "meccan_early",
      "لإيلاف قريش إيلافهم رحلة الشتاء والصيف", "For the accustomed security of Quraysh, their winter and summer journeys",
      "Mecca", ["106:1", "106:2", "106:3", "106:4"],
      "نزلت تُذكّر قريشاً بأن رحلتيهم التجاريتين (إلى اليمن شتاءً والشام صيفاً) نعمة من الله يجب أن يعبدوه شكراً عليها.",
      "النعم الاقتصادية تستوجب الشكر لمصدرها؛ الاستقرار التجاري لا يأتي بالصدفة.",
      "none", "community_vs_outsider", "livelihood",
      "moral_rebuke", "wealth_as_trust_not_ownership", "command"),

    E("ab_maun_charity_refusal", 755, -6, "meccan_middle",
      "أرأيت الذي يكذّب بالدين", "Have you seen the one who denies the religion?",
      "Mecca", ["107:1", "107:2", "107:3", "107:4", "107:5", "107:6", "107:7"],
      "نزلت في من يدفع اليتيم ولا يحضّ على طعام المسكين ثم يُصلّي رياءً ويمنع الماعون (الأدوات المنزلية البسيطة).",
      "الدين ليس شعائر بلا أخلاق؛ من منع الماعون فقد كذّب بالدين.",
      "moral_temptation", "community_vs_outsider", "livelihood",
      "moral_rebuke", "sincerity_over_performance", "rebuke"),

    E("ab_kawthar_abundance", 756, -6, "meccan_middle",
      "إنا أعطيناك الكوثر", "Indeed We have given you al-Kawthar",
      "Mecca", ["108:1", "108:2", "108:3"],
      "نزلت ردّاً على العاص بن وائل حين قال إن محمداً أبتر لا عقب له، فبشّره الله بالكوثر (الخير الكثير).",
      "العطاء الإلهي لا يُقاس بالذرية الجسدية؛ الأتباع والأمة أبقى من النسل.",
      "verbal_attack", "individual_vs_majority", "reputation_honor",
      "consolation_and_thabaat", "truth_is_independent_of_carrier", "promise"),

    E("ab_kafirun_no_worship_yours", 757, -6, "meccan_middle",
      "قل يا أيها الكافرون لا أعبد ما تعبدون", "Say: O disbelievers, I do not worship what you worship",
      "Mecca", ["109:1", "109:2", "109:3", "109:4", "109:5", "109:6"],
      "عرض المشركون على النبي ﷺ أن يعبد آلهتهم سنة ويعبدوا إلهه سنة، فنزلت سورة الكافرون قاطعة للمساومة.",
      "المساومة في التوحيد مرفوضة؛ الحق لا يُبادل بالباطل.",
      "moral_temptation", "believer_vs_unbeliever", "religious_freedom",
      "refusal_to_compromise", "principled_refusal_to_transgress", "command"),

    E("ab_nasr_fath_victory", 758, 10, "medinan_late",
      "إذا جاء نصر الله والفتح", "When the victory of Allah has come and the conquest",
      "Mina", ["110:1", "110:2", "110:3"],
      "نزلت سورة النصر بمنى في حجة الوداع، وفهم ابن عباس أنها نعي النبي ﷺ، لأنها أمرت بالتسبيح والاستغفار وهو علامة الاقتراب.",
      "البشرى بالنصر الشامل إيذان بنهاية المهمة؛ التسبيح والاستغفار خاتمة كل عمل.",
      "none", "leader_vs_follower", "spiritual_integrity",
      "teaching_through_demonstration", "consistency_public_and_private", "command"),

    E("ab_masad_abu_lahab", 759, -10, "meccan_early",
      "تبت يدا أبي لهب وتب", "May the hands of Abu Lahab be ruined",
      "Mecca", ["111:1", "111:2", "111:3", "111:4", "111:5"],
      "لما دعا النبي ﷺ قريشاً على الصفا وقال أبو لهب: تباً لك ألهذا جمعتنا؟ نزلت سورة المسد.",
      "التحدي القرآني: أبو لهب عاش سنوات بعدها ولم يُسلم، فكان بقاؤه على الكفر إثباتاً للنبوءة.",
      "verbal_attack", "kin_vs_kin", "reputation_honor",
      "moral_rebuke", "truth_before_kinship", "rebuke"),

    E("ab_ikhlas_tawhid_pure", 760, -6, "meccan_middle",
      "قل هو الله أحد — سورة الإخلاص", "Say: He is Allah, the One — Surat al-Ikhlas",
      "Mecca", ["112:1", "112:2", "112:3", "112:4"],
      "سأل المشركون (أو اليهود) النبي ﷺ: صف لنا ربك، فنزلت سورة الإخلاص تُعرّف الله بأربع صفات سلبية وإيجابية.",
      "تعريف الله بالنفي (لم يلد ولم يولد) أبلغ من الإثبات؛ التوحيد الخالص في أربع آيات.",
      "intellectual_challenge", "community_vs_outsider", "truth_vs_falsehood",
      "intellectual_rebuttal", "source_integrity_over_popularity", "argument"),

    E("ab_falaq_nas_protection", 761, -3, "meccan_late",
      "المعوذتان للاستعاذة من الشرور", "The two surahs of seeking refuge from evils",
      "Mecca", ["113:1", "113:2", "113:3", "113:4", "113:5", "114:1", "114:2", "114:3", "114:4", "114:5", "114:6"],
      "نزلت المعوذتان يستعيذ بهما المؤمن من شر المخلوقات والوسوسة، وكان النبي ﷺ يقرأهما كل ليلة قبل النوم.",
      "الاستعاذة بالله من كل شر اعتراف بالضعف البشري؛ القوة في الالتجاء لا في الاكتفاء.",
      "psychological_pressure", "self_vs_self", "spiritual_integrity",
      "refuge_with_god_against_despair", "refuge_with_god_against_despair", "command"),

    # ═══════════════ PERSONAL INCIDENTS ═══════════════
    E("ab_companion_lost_camel", 762, 3, "medinan_early",
      "رجل يفقد بعيره فيُحكّم النبي ﷺ", "A man loses his camel and asks the Prophet",
      "Medina", ["49:6"],
      "جاء رجل يشتكي أنه فقد بعيره فادّعاه آخر، فحكم النبي ﷺ بالبيّنة على المدّعي واليمين على من أنكر.",
      "البيّنة على المدّعي واليمين على المنكر قاعدة قضائية أساسية.",
      "legal_coercion", "claimant_vs_accused", "property_rights",
      "deferral_of_judgement", "procedural_justice_over_outcome", "legislation"),

    E("ab_woman_asks_about_ghusl", 763, 3, "medinan_early",
      "امرأة تسأل عن الغسل من المحيض", "A woman asks about ghusl after menstruation",
      "Medina", ["2:222"],
      "جاءت امرأة تسأل النبي ﷺ عن كيفية الغسل بعد الحيض، فأخذ قطعة مسك وعلّمها، ثم قالت عائشة: نعم النساء نساء الأنصار لم يمنعهن الحياء من التفقّه.",
      "الحياء لا يمنع السؤال عن الدين؛ العلم بالأحكام فرض على الرجال والنساء.",
      "psychological_pressure", "teacher_vs_student", "knowledge_access",
      "clarification", "knowledge_before_action", "legislation"),

    E("ab_man_too_poor_sadaqah", 764, 3, "medinan_early",
      "رجل لا يملك صدقة يسأل النبي ﷺ", "A man with nothing to give asks the Prophet",
      "Medina", ["2:271"],
      "جاء رجل يقول: ما عندي شيء أتصدق به، فقال النبي ﷺ: تبسّمك في وجه أخيك صدقة، وأمرك بالمعروف صدقة، ونهيك عن المنكر صدقة.",
      "الفقير يستطيع التصدّق بأشياء لا مادية؛ العطاء أوسع من المال.",
      "economic_siege", "community_vs_outsider", "spiritual_integrity",
      "consolation_and_thabaat", "protection_of_the_weak", "praise"),

    E("ab_sahabiyya_dream", 765, 3, "medinan_early",
      "امرأة ترى رؤيا مخيفة فيطمئنها النبي ﷺ", "A woman has a scary dream and the Prophet reassures her",
      "Medina", ["12:6"],
      "جاءت امرأة إلى النبي ﷺ تشكو رؤيا مخيفة، فقال لها: إذا رأيتِ ما تكرهين فاستعيذي بالله من شرها ومن شر الشيطان.",
      "القلق النفسي يُعالج بالأذكار لا بالتجاهل؛ الدعاء أداة نفسية.",
      "psychological_pressure", "self_vs_self", "spiritual_integrity",
      "consolation_and_thabaat", "refuge_with_god_against_despair", "consolation"),

    E("ab_man_asks_best_deed", 766, 2, "medinan_early",
      "أي العمل أحب إلى الله؟", "Which deed is most beloved to Allah?",
      "Medina", ["2:177"],
      "سأل رجل النبي ﷺ: أي العمل أحب إلى الله؟ فقال: الصلاة على وقتها، قال ثم أي؟ قال: بر الوالدين، قال ثم أي؟ قال: الجهاد في سبيل الله.",
      "ترتيب الأولويات أصل في الدين؛ الصلاة في وقتها فوق كل عبادة.",
      "none", "teacher_vs_student", "spiritual_integrity",
      "clarification", "knowledge_before_action", "command"),

    E("ab_awf_mahr_gold", 767, 1, "medinan_early",
      "عبد الرحمن بن عوف يتزوج بنواة من ذهب", "Abd al-Rahman ibn Awf marries with a gold date-stone",
      "Medina", ["4:4"],
      "رأى النبي ﷺ على عبد الرحمن بن عوف أثر صُفرة فسأله، فقال: تزوجت امرأة من الأنصار بمهر نواة من ذهب. فقال: أولم ولو بشاة.",
      "المهر الخفيف لا ينقص العقد؛ الوليمة ولو بأقل شيء واجب اجتماعي.",
      "none", "community_vs_outsider", "family_integrity",
      "teaching_through_demonstration", "scaling_principle_to_context", "legislation"),

    E("ab_jabir_debt_bless", 768, 3, "medinan_early",
      "جابر يستعين بالنبي ﷺ في دينه", "Jabir seeks the Prophet's help with his debt",
      "Medina", ["2:280"],
      "كان على أبي جابر دين كبير من يهود، فجاء جابر يطلب شفاعة النبي ﷺ عند الدائن، فبارك النبي في تمره حتى وفى الدين وبقي.",
      "الشفاعة في الدين مشروعة والبركة تُعين المدين؛ القائد يتوسط للمحتاج.",
      "economic_siege", "debtor_vs_creditor", "livelihood",
      "private_counsel", "protection_of_the_weak", "praise"),

    E("ab_child_dies_patience", 769, 3, "medinan_early",
      "وفاة إبراهيم ابن النبي ﷺ", "Death of Ibrahim the Prophet's son",
      "Medina", ["3:185"],
      "توفي إبراهيم بن النبي ﷺ رضيعاً، فبكى النبي وقال: إن العين تدمع والقلب يحزن ولا نقول إلا ما يرضي ربنا.",
      "البكاء على الفقد حقّ بشري لا ينقض الصبر؛ القلب يحزن واللسان يرضى.",
      "psychological_pressure", "parent_vs_child", "family_integrity",
      "endurance_without_retaliation", "balance_between_fear_and_hope", "consolation"),

    E("ab_solar_eclipse_ibrahim", 770, 3, "medinan_early",
      "كسوف الشمس يوم وفاة إبراهيم", "Solar eclipse on the day of Ibrahim's death",
      "Medina", ["41:37"],
      "كسفت الشمس يوم وفاة إبراهيم فقال الناس كسفت لموته، فقال النبي ﷺ: إن الشمس والقمر آيتان من آيات الله لا يُكسفان لموت أحد.",
      "الظواهر الطبيعية لا تُربط بأحداث بشرية؛ النبي يُصحّح التفكير الخرافي حتى لو كان لصالحه.",
      "intellectual_challenge", "community_vs_outsider", "knowledge_access",
      "clarification", "knowledge_before_action", "clarification"),

    # ═══════════════ ADDITIONAL LEGAL/ETHICAL ASBAB ═══════════════
    E("ab_lian_hilal_wife", 771, 9, "medinan_late",
      "حكم اللعان — هلال بن أمية", "Li'an ruling — Hilal ibn Umayyah",
      "Medina", ["24:6", "24:7", "24:8", "24:9"],
      "رمى هلال بن أمية زوجته بالزنا ولم يجد أربعة شهود، فنزل حكم اللعان: كل منهما يُقسم خمس مرات، والخامسة لعنة الله على الكاذب.",
      "حين تستحيل البيّنة العادية يُفتح باب آخر يحفظ الحق ويُرهب الكاذب.",
      "legal_coercion", "spouse_vs_spouse", "family_integrity",
      "legal_innovation", "procedural_justice_over_outcome", "legislation"),

    E("ab_stoning_revelation", 772, 5, "medinan_middle",
      "حدّ الرجم للمحصن", "Stoning hadd for the married adulterer",
      "Medina", ["24:2"],
      "ثبت حكم الرجم للمحصن بالسنة وتأكيد عمر أنه كان في القرآن ثم رُفع لفظاً وبقي حكماً.",
      "الحكم قد يبقى في السنة وإن رُفع من النص؛ النسخ لفظي لا حكمي.",
      "moral_failure_by_self", "claimant_vs_accused", "justice_vs_privilege",
      "legal_innovation", "procedural_justice_over_outcome", "legislation"),

    E("ab_qasamah_oath_blood", 773, 3, "medinan_early",
      "القسامة في القتل", "Qasama oath in murder cases",
      "Medina", ["2:178"],
      "وُجد أنصاري قتيلاً في خيبر فلم يُعرف قاتله، فطبّق النبي ﷺ القسامة: خمسون يميناً من أهل القتيل أو يُبرّأ المتهمون بخمسين.",
      "حين يغيب الشاهد يُلجأ إلى اليمين الجماعي؛ العدالة تجد طريقها ولو بأقل وسائل.",
      "legal_coercion", "claimant_vs_accused", "justice_vs_privilege",
      "deferral_of_judgement", "procedural_justice_over_outcome", "legislation"),

    E("ab_qat_alnafsi_haram", 774, 4, "medinan_early",
      "ولا تقتلوا أنفسكم", "And do not kill yourselves",
      "Medina", ["4:29"],
      "فهم عمرو بن العاص من هذه الآية تحريم الانتحار، فلما أصابته البرودة في غزوة ذات السلاسل تيمّم ولم يغتسل خوف الموت.",
      "حفظ النفس مقدّم على أداء الشعيرة بكمالها؛ التيمم رخصة حتى عن خوف الموت.",
      "existential_threat", "self_vs_self", "physical_safety",
      "scaling_principle_to_context", "scaling_principle_to_context", "legislation"),

    E("ab_nikah_mutah_ban", 775, 7, "medinan_late",
      "تحريم نكاح المتعة نهائياً في خيبر", "Final prohibition of mut'ah marriage at Khaybar",
      "Khaybar", ["5:87"],
      "حرّم النبي ﷺ نكاح المتعة نهائياً يوم خيبر بعد أن كان مباحاً سابقاً، وأكّد تحريمه في فتح مكة.",
      "التشريع قد يُنسخ لمصلحة مستجدة؛ الحرام ينسخ الحلال السابق.",
      "none", "community_vs_outsider", "family_integrity",
      "legal_innovation", "gradualism_in_hard_change", "prohibition"),

    E("ab_umm_haraam_sea_battle", 776, 5, "medinan_middle",
      "أم حرام ونبوءة الجهاد البحري", "Umm Haram and the prophecy of sea jihad",
      "Medina", ["8:60"],
      "نام النبي ﷺ عند أم حرام بنت ملحان فاستيقظ يضحك وأخبرها أنه رأى أناساً من أمته يركبون البحر غزاةً في سبيل الله، فقالت: ادع الله أن يجعلني منهم.",
      "البشارة بالمستقبل تُحفّز العمل؛ الرؤيا النبوية خارطة طريق.",
      "none", "community_vs_outsider", "collective_survival",
      "consolation_and_thabaat", "knowledge_before_action", "promise"),

    E("ab_animal_slaughter_rule", 777, 5, "medinan_middle",
      "أحكام الذبائح والصيد", "Rulings on slaughter and hunting",
      "Medina", ["5:3", "5:4", "5:5", "6:118", "6:119", "6:121"],
      "نزلت أحكام الذبح والصيد تُحدّد ما يُحلّ وما يُحرّم من الذبائح وما صاده الجارح المعلّم وذبائح أهل الكتاب.",
      "الطعام له أحكام شرعية دقيقة؛ ذبيحة الكتابي حلال وذبيحة المشرك حرام.",
      "none", "community_vs_outsider", "spiritual_integrity",
      "legal_innovation", "scaling_principle_to_context", "legislation"),

    E("ab_salam_alaikum_greeting", 778, 3, "medinan_early",
      "إفشاء السلام بين المسلمين", "Spreading the greeting of peace among Muslims",
      "Medina", ["4:86"],
      "أمر النبي ﷺ بإفشاء السلام وقال: لا تدخلوا الجنة حتى تؤمنوا ولا تؤمنوا حتى تحابّوا، أوَلا أدلّكم على شيء إذا فعلتموه تحاببتم؟ أفشوا السلام بينكم.",
      "التحية أول جسر بين النفوس؛ السلام كلمة تُذيب الجليد.",
      "none", "community_vs_outsider", "trust_between_parties",
      "teaching_through_demonstration", "solidarity_around_principle", "command"),

    E("ab_wahi_ilahi_najm", 779, -8, "meccan_middle",
      "وما ينطق عن الهوى إن هو إلا وحي يوحى", "He does not speak from desire, it is only revelation",
      "Mecca", ["53:3", "53:4"],
      "نزلت تُقرّر أن كلام النبي ﷺ في التشريع ليس من هوى نفسه بل هو وحي من الله.",
      "الفرق بين كلام النبي الشخصي وكلامه التشريعي؛ الثاني معصوم.",
      "intellectual_challenge", "community_vs_outsider", "truth_vs_falsehood",
      "intellectual_rebuttal", "source_integrity_over_popularity", "oath"),

    E("ab_mutah_expedition_poet", 780, 8, "medinan_late",
      "رثاء حسان بن ثابت لشهداء مؤتة", "Hassan ibn Thabit's elegy for Mu'tah martyrs",
      "Medina", ["3:169"],
      "رثى حسان بن ثابت شهداء مؤتة بقصيدة مؤثرة ذكر فيها زيد بن حارثة وجعفر بن أبي طالب وعبد الله بن رواحة.",
      "الشعر في خدمة الدعوة والحق يُوثّق التاريخ ويُخلّد الشهداء.",
      "psychological_pressure", "community_vs_outsider", "community_cohesion",
      "consolation_and_thabaat", "witnessing_and_documentation", "praise"),

    # ═══════════════ FINAL FILLER TO 800 ═══════════════
    E("ab_prophet_walking_market", 781, 2, "medinan_early",
      "النبي ﷺ يمشي في السوق بنفسه", "Prophet walks in the marketplace himself",
      "Medina", ["25:7"],
      "كان النبي ﷺ يمشي في الأسواق ويشتري حاجاته بنفسه، فاستنكر المشركون ذلك فنزل: وقالوا ما لهذا الرسول يأكل الطعام ويمشي في الأسواق.",
      "تواضع القائد في الحياة اليومية رسالة؛ الرسول بشر يأكل ويمشي كالناس.",
      "verbal_attack", "principled_minority_vs_powerful_majority", "personal_dignity",
      "teaching_through_demonstration", "leadership_accountability", "argument"),

    E("ab_masquerade_iman", 782, 9, "medinan_late",
      "قالت الأعراب آمنا قل لم تؤمنوا ولكن قولوا أسلمنا", "The bedouins say 'we believe,' say: you have not believed but say 'we submitted'",
      "Medina", ["49:14"],
      "جاء قوم من بني أسد وقالوا: آمنا ولم نُقاتلك كما قاتلتك القبائل، يُريدون المنّ بإسلامهم، فنزلت تُفرّق بين الإيمان الحقيقي والإسلام الشكلي.",
      "التمييز بين الإسلام الشكلي والإيمان القلبي أصل عقدي؛ الادعاء لا يكفي.",
      "verbal_attack", "community_vs_outsider", "spiritual_integrity",
      "moral_rebuke", "sincerity_over_performance", "rebuke"),

    E("ab_earth_witness", 783, 2, "medinan_early",
      "يومئذ تحدّث أخبارها", "That Day it will report its news",
      "Medina", ["99:4", "99:5"],
      "نزل وصف الأرض شاهدة على كل ما فُعل فوقها يوم القيامة: تُخرج أثقالها وتُحدّث بأخبارها.",
      "الأرض شاهد حيّ؛ المكان يُسجّل ما لا يُسجّله صاحبه.",
      "none", "self_vs_self", "divine_acceptance",
      "moral_rebuke", "consistency_public_and_private", "warning"),

    E("ab_neighbor_rights_repeated", 784, 3, "medinan_early",
      "ما زال جبريل يوصيني بالجار", "Jibril kept advising me about the neighbor",
      "Medina", ["4:36"],
      "قال النبي ﷺ: ما زال جبريل يوصيني بالجار حتى ظننت أنه سيورّثه، تأكيداً على حقّ الجار.",
      "حقّ الجار كاد يبلغ مرتبة الميراث؛ الجيرة عقد ضمني.",
      "none", "community_vs_outsider", "community_cohesion",
      "teaching_through_demonstration", "solidarity_around_principle", "legislation"),

    E("ab_modesty_iman_branch", 785, 3, "medinan_early",
      "الحياء شعبة من الإيمان", "Modesty is a branch of faith",
      "Medina", ["7:26"],
      "عرّف النبي ﷺ الإيمان بأنه بضع وستون أو بضع وسبعون شعبة، أعلاها لا إله إلا الله وأدناها إماطة الأذى عن الطريق والحياء شعبة من الإيمان.",
      "الإيمان مركّب لا بسيط؛ الحياء ليس ضعفاً بل إيمان.",
      "none", "self_vs_self", "spiritual_integrity",
      "teaching_through_demonstration", "consistency_public_and_private", "legislation"),

    E("ab_la_darar", 786, 5, "medinan_middle",
      "لا ضرر ولا ضرار", "No harm and no reciprocal harm",
      "Medina", ["2:231"],
      "قعّد النبي ﷺ قاعدة فقهية كبرى: لا ضرر ولا ضرار، ونزلت آيات تمنع الإضرار بالمطلقة والمرضعة والجار.",
      "القاعدة الذهبية في الشريعة: الضرر يُزال؛ كل حكم يُقاس بأثره.",
      "legal_coercion", "community_vs_outsider", "justice_vs_privilege",
      "legal_innovation", "procedural_justice_over_outcome", "legislation"),

    E("ab_heart_disease_verses", 787, 5, "medinan_middle",
      "في قلوبهم مرض فزادهم الله مرضاً", "In their hearts is disease, so Allah increased their disease",
      "Medina", ["2:10"],
      "نزلت في المنافقين الذين تزداد قلوبهم مرضاً بكل آية تنزل، لأنهم يسمعون ولا يمتثلون.",
      "مرض القلب يتفاقم بالتجاهل؛ الآية التي تشفي المؤمن تُمرض المنافق.",
      "internal_betrayal", "insider_hypocrite_vs_sincere", "spiritual_integrity",
      "moral_rebuke", "consistency_public_and_private", "warning"),

    E("ab_shahada_nisa", 788, 5, "medinan_middle",
      "شهادة المرأة في القرآن", "Women's testimony in the Quran",
      "Medina", ["2:282"],
      "نزل أن تكون شهادة امرأتين بدل رجل في الدين، بشرط أن تُذكّر إحداهما الأخرى إن ضلّت.",
      "التذكير المتبادل لا ينتقص بل يُثبّت؛ الآية تعالج ظاهرة اجتماعية وقتية لا قصوراً ذاتياً.",
      "legal_coercion", "community_vs_outsider", "justice_vs_privilege",
      "legal_innovation", "scaling_principle_to_context", "legislation"),

    E("ab_tawbah_najasa_mushrik", 789, 9, "medinan_late",
      "إنما المشركون نجس فلا يقربوا المسجد الحرام", "The polytheists are impure so let them not approach the Sacred Mosque",
      "Medina", ["9:28"],
      "بعد أن أُعلنت سورة التوبة في السنة التاسعة مُنع المشركون من دخول المسجد الحرام بعد ذلك العام، فكان آخر حجّ فيه مشركون.",
      "المكان المقدس يُطهَّر من الشرك الفعلي؛ القرار يُتّخذ حين يكون التمكين كافياً.",
      "political_pressure", "community_vs_outsider", "religious_freedom",
      "refusal_to_compromise", "refusing_to_legitimize_falsehood", "legislation"),

    E("ab_iman_six_pillars", 790, 2, "medinan_early",
      "حديث جبريل عن أركان الإيمان الستة", "Jibril hadith on the six pillars of faith",
      "Medina", ["2:177", "2:285"],
      "جاء جبريل في صورة رجل يسأل النبي ﷺ عن الإيمان والإسلام والإحسان، فبيّن النبي الأركان الستة: الله والملائكة والكتب والرسل واليوم الآخر والقدر.",
      "تعريف الإيمان بأركانه الستة أصل كل علم عقدي؛ الإيمان عقيدة لا مجرد شعور.",
      "none", "teacher_vs_student", "knowledge_access",
      "clarification", "knowledge_before_action", "legislation"),

    E("ab_quran_7_mathani", 791, -5, "meccan_middle",
      "ولقد آتيناك سبعاً من المثاني والقرآن العظيم", "We have given you the seven oft-repeated and the great Quran",
      "Mecca", ["15:87"],
      "فسّر النبي ﷺ السبع المثاني بالفاتحة، فسُمّيت أم القرآن وأُقرّرت في كل ركعة.",
      "الفاتحة أساس كل صلاة ومفتاح كل مخاطبة؛ لا صلاة بدون أم القرآن.",
      "none", "teacher_vs_student", "spiritual_integrity",
      "clarification", "knowledge_before_action", "legislation"),

    E("ab_three_daily_adhkar", 792, 3, "medinan_early",
      "أذكار الصباح والمساء والنوم", "Morning, evening, and sleep adhkar",
      "Medina", ["3:190", "3:191"],
      "علّم النبي ﷺ أصحابه أذكاراً محددة للصباح والمساء والنوم، ومنها آية الكرسي وخواتيم البقرة والمعوذتين.",
      "العبادة اليومية تُشكّل حصناً؛ الذكر المنتظم يبني الصلة الدائمة.",
      "none", "self_vs_self", "spiritual_integrity",
      "teaching_through_demonstration", "consistency_public_and_private", "legislation"),

    E("ab_traveler_ease_fasting", 793, 2, "medinan_early",
      "رخصة الفطر في السفر", "Exemption from fasting while traveling",
      "Medina", ["2:184", "2:185"],
      "أفطر النبي ﷺ في سفر فأفطر معه الصحابة، فعاب بعضهم على بعض، فقال النبي: ليس من البر الصيام في السفر.",
      "الرخصة ليست ضعفاً بل رحمة؛ التشدد في غير موضعه ليس براً.",
      "none", "leader_vs_follower", "spiritual_integrity",
      "scaling_principle_to_context", "scaling_principle_to_context", "legislation"),

    E("ab_wasiyyat_shahid", 794, 3, "medinan_early",
      "وصية الشهيد قبل المعركة", "The martyr's will before battle",
      "Medina", ["2:180", "4:11"],
      "كان المسلمون يكتبون وصاياهم قبل كل معركة خوفاً من الاستشهاد، فصارت الوصية سنة مؤكدة في كل سفر وخطر.",
      "الاستعداد للموت ليس تشاؤماً بل حكمة؛ الوصية تحمي الأحياء.",
      "existential_threat", "self_vs_self", "family_integrity",
      "witnessing_and_documentation", "knowledge_before_action", "legislation"),

    E("ab_shura_practice", 795, 3, "medinan_early",
      "تطبيق مبدأ الشورى في الحياة اليومية", "Practicing shura in daily life",
      "Medina", ["42:38"],
      "كان النبي ﷺ يستشير أصحابه حتى في الأمور الصغيرة كمكان المعسكر ونوع الطعام وطريقة الاستقبال، لا يقتصر على الحرب.",
      "الشورى ليست للحرب فقط بل لكل أمر؛ القائد الذي يستشير لا يخسر هيبته.",
      "none", "leader_vs_follower", "trust_between_parties",
      "consultation_before_decision", "consultation_before_decision", "legislation"),

    E("ab_kindness_even_in_anger", 796, 5, "medinan_middle",
      "النبي ﷺ لا يغضب لنفسه", "Prophet does not get angry for himself",
      "Medina", ["3:134"],
      "كان النبي ﷺ لا ينتقم لنفسه قط، وإنما يغضب إذا انتُهكت حرمات الله، كما شهدت عائشة.",
      "الغضب الشخصي ضعف والغضب للمبدأ قوة؛ القائد يفصل بين ذاته وقضيته.",
      "verbal_attack", "self_vs_self", "personal_dignity",
      "endurance_without_retaliation", "consistency_public_and_private", "praise"),

    E("ab_promise_fulfilled_always", 797, 5, "medinan_middle",
      "النبي ﷺ يفي بوعد طفل", "Prophet keeps a promise to a child",
      "Medina", ["17:34"],
      "وعد النبي ﷺ طفلاً بشيء فجاء في الموعد ينتظره حتى لو كان ذلك يشقّ عليه، لأن الوعد عهد.",
      "الوفاء بالوعد حتى للأطفال معيار الأخلاق؛ الكلمة المعطاة لا تُنقض.",
      "none", "parent_vs_child", "trust_between_parties",
      "teaching_through_demonstration", "trust_is_earned_by_consistency", "praise"),

    E("ab_feeding_hungry_priority", 798, 5, "medinan_middle",
      "أطعموا الجائع وعودوا المريض وفكوا العاني", "Feed the hungry, visit the sick, free the captive",
      "Medina", ["76:8"],
      "أمر النبي ﷺ بثلاث أولويات اجتماعية: إطعام الجائع أولاً ثم عيادة المريض ثم فكاك الأسير.",
      "ترتيب الأولويات الإنسانية: الجوع أولاً؛ البطن الفارغ لا يسمع.",
      "economic_siege", "community_vs_outsider", "livelihood",
      "teaching_through_demonstration", "protection_of_the_weak", "command"),

    E("ab_last_ayah_revealed", 799, 10, "medinan_late",
      "آخر آية نزلت من القرآن", "Last verse revealed from the Quran",
      "Medina", ["2:281"],
      "اختُلف في آخر آية نزلت، وأشهر الأقوال أنها: واتقوا يوماً ترجعون فيه إلى الله ثم توفى كل نفس ما كسبت.",
      "الختام بالتقوى ولقاء الله؛ آخر كلمة تُردّ الأمة إلى جوهر الرسالة.",
      "none", "community_vs_outsider", "divine_acceptance",
      "moral_rebuke", "consistency_public_and_private", "warning"),

    E("ab_quran_complete_revelation", 800, 10, "medinan_late",
      "اكتمال نزول القرآن الكريم", "Completion of the Quran's revelation",
      "Arafat", ["5:3"],
      "أكمل الله الدين وأتمّ النعمة في حجة الوداع بنزول آخر ما نزل من الأحكام، فلم ينزل بعدها تشريع جديد.",
      "كمال الدين يعني انتهاء التشريع التأسيسي؛ بعد الكمال لا يحتاج البناء إلى مصدر جديد.",
      "none", "community_vs_outsider", "generational_legacy",
      "public_declaration", "leadership_accountability", "promise"),
]
