"""Meccan period events (years -13 to -1 before Hijrah).

Distribution:
  - early  (-13 to -10)  order 1-60    foundational revelation, first converts, early persecution
  - middle (-9 to -6)    order 61-110  boycott, intensified opposition, public debates
  - late   (-5 to -1)    order 111-150 Isra-Miraj, Aqaba pledges, hijrah preparation

Total target: ~150 events.

Many Meccan events are thematic (opposition patterns) rather than singular
incidents — classical asbab literature links these to specific verses even
when the incident is a recurring type. Where that's the case, the event
represents the *pattern* and the verse linkage follows classical attribution.
"""

from __future__ import annotations

from training.pipeline.sira_db.db import E

MECCAN_EVENTS: list[dict] = [
    # ═══════════════ MECCAN EARLY (order 1-60) ═══════════════
    E("meccan_first_revelation", 1, -13, "meccan_early",
      "نزول أول الوحي في غار حراء", "First revelation in cave Hira",
      "Mecca", ["96:1", "96:2", "96:3", "96:4", "96:5"],
      "نزل جبريل عليه السلام على النبي ﷺ في غار حراء وهو يتحنث، فضمّه ثلاثاً وأمره بالقراءة باسم ربه الذي خلق.",
      "العلم الحقيقي ينطلق من الاعتراف بالمصدر المتعالٍ قبل الذات، والقراءة الأولى تُنسب للخالق لا للقارئ.",
      "existential_threat", "self_vs_self", "spiritual_integrity",
      "public_declaration", "knowledge_before_action", "command"),

    E("meccan_fatrat_alwahy", 2, -13, "meccan_early",
      "فترة انقطاع الوحي", "Pause in revelation",
      "Mecca", ["93:1", "93:2", "93:3", "93:4", "93:5"],
      "انقطع الوحي فترة بعد أول نزول حتى حزن النبي ﷺ وظنّ أن ربه ودّعه أو قلاه.",
      "الصمت الإلهي اختبار لا هجران، والعناية مستمرة حتى حين ينقطع الصوت.",
      "psychological_pressure", "self_vs_self", "spiritual_integrity",
      "consolation_and_thabaat", "refuge_with_god_against_despair", "consolation"),

    E("meccan_muddaththir_start", 3, -13, "meccan_early",
      "نزول المدثر وبدء الإنذار", "Revelation of al-Muddaththir and start of warning",
      "Mecca", ["74:1", "74:2", "74:3", "74:4", "74:5", "74:6", "74:7"],
      "رأى النبي ﷺ جبريل بين السماء والأرض فرجع إلى خديجة خائفاً يقول زمّلوني، فنزلت يا أيها المدثر قم فأنذر.",
      "الانتقال من تلقي الوحي إلى تبليغه: لا يُعذر من علم أن يكتم علمه.",
      "existential_threat", "self_vs_self", "spiritual_integrity",
      "public_declaration", "collective_obligation_above_personal", "command"),

    E("meccan_khadija_first_belief", 4, -13, "meccan_early",
      "تصديق خديجة للنبي ﷺ", "Khadijah's immediate belief",
      "Mecca", ["28:52", "28:53", "28:54"],
      "لما رجع النبي ﷺ من غار حراء مرعوباً ثبّتته خديجة رضي الله عنها وقالت: كلا والله لا يخزيك الله أبداً.",
      "الدعم الأول يأتي من الأقرب؛ المرأة الصالحة ركيزة للقائد في أحرج اللحظات.",
      "psychological_pressure", "spouse_vs_spouse", "trust_between_parties",
      "consolation_and_thabaat", "solidarity_around_principle", "praise"),

    E("meccan_waraqa_verification", 5, -13, "meccan_early",
      "ورقة بن نوفل يصدق نبوة محمد ﷺ", "Waraqa ibn Nawfal confirms the prophethood",
      "Mecca", ["5:83", "28:52", "28:53"],
      "أخذت خديجة النبي ﷺ إلى ابن عمها ورقة بن نوفل — وكان يقرأ الإنجيل — فعرف أنه الناموس الذي نزل على موسى وأقرّ بنبوته.",
      "أهل الكتاب الصادقون أقرب الناس إلى تصديق الحق الجديد، لأن عندهم علماً يرشدهم.",
      "intellectual_challenge", "believer_vs_unbeliever", "truth_vs_falsehood",
      "intellectual_rebuttal", "truth_is_independent_of_carrier", "clarification"),

    E("meccan_ali_islam", 6, -13, "meccan_early",
      "إسلام علي بن أبي طالب", "Islam of Ali ibn Abi Talib",
      "Mecca", ["28:56"],
      "أسلم علي بن أبي طالب وهو غلام في نحو العاشرة من عمره، وكان أول من أسلم من الصبيان.",
      "الفطرة السليمة لا تحتاج إلى عمر طويل لتعرف الحق.",
      "none", "self_vs_self", "spiritual_integrity",
      "public_declaration", "truth_is_independent_of_carrier", "praise"),

    E("meccan_abubakr_islam", 7, -13, "meccan_early",
      "إسلام أبي بكر الصديق", "Islam of Abu Bakr al-Siddiq",
      "Mecca", ["39:33"],
      "أسلم أبو بكر الصديق رضي الله عنه فور دعوة النبي ﷺ له، ولم يتلعثم أو يطلب دليلاً.",
      "من اكتمل علمه بصدق المخبر استغنى عن طلب البرهان على كل خبر.",
      "none", "believer_vs_unbeliever", "trust_between_parties",
      "confrontation_with_truth", "trust_is_earned_by_consistency", "praise"),

    E("meccan_zayd_islam", 8, -13, "meccan_early",
      "إسلام زيد بن حارثة", "Islam of Zayd ibn Haritha",
      "Mecca", ["33:37"],
      "أسلم زيد بن حارثة مولى النبي ﷺ وكان من أوائل المؤمنين، واختار البقاء معه على العودة إلى أهله.",
      "الاختيار الحر للمبدأ أقوى من روابط الدم والنسب.",
      "family_pressure", "kin_vs_kin", "family_integrity",
      "refusal_to_compromise", "truth_before_kinship", "praise"),

    E("meccan_abubakr_brings_converts", 9, -13, "meccan_early",
      "أبو بكر يأتي بالأوائل إلى الإسلام", "Abu Bakr brings the early converts",
      "Mecca", ["9:100"],
      "دعا أبو بكر إلى الإسلام فآمن على يديه عثمان والزبير وعبد الرحمن بن عوف وسعد بن أبي وقاص وطلحة.",
      "من صدّق ثم دعا انطلقت الدعوة من دائرته القريبة قبل البعيدة.",
      "none", "ally_vs_ally_dispute", "community_cohesion",
      "seeking_allies", "solidarity_around_principle", "praise"),

    E("meccan_secret_dawa_dar_arqam", 10, -12, "meccan_early",
      "الدعوة في دار الأرقم", "Secret teaching at Dar al-Arqam",
      "Mecca", ["26:214", "26:215"],
      "اتخذ النبي ﷺ دار الأرقم بن أبي الأرقم في أصل الصفا مكاناً سرياً لتعليم أصحابه بعيداً عن عيون قريش.",
      "المرحلة السرية تبني القاعدة قبل أن تواجه الصدمة؛ الإخفاء ليس جبناً بل تخطيطاً.",
      "physical_persecution", "principled_minority_vs_powerful_majority", "collective_survival",
      "strategic_withdrawal", "gradualism_in_hard_change", "command"),

    E("meccan_public_safa_proclamation", 11, -10, "meccan_early",
      "الصدع بالحق على الصفا", "Public proclamation at Mount Safa",
      "Mecca", ["26:214", "26:215", "15:94"],
      "صعد النبي ﷺ على جبل الصفا ونادى بطون قريش يُحذّرها من عذاب الله، فقال له أبو لهب: تباً لك ألهذا جمعتنا؟",
      "الانتقال من السر إلى العلن قرار قيادي يتحمّل القائد تبعاته أمام أقرب الناس إليه.",
      "verbal_attack", "individual_vs_majority", "reputation_honor",
      "public_declaration", "chosen_hardship_over_compromise", "command"),

    E("meccan_abu_lahab_tabbat", 12, -10, "meccan_early",
      "سورة المسد في أبي لهب", "Surah al-Masad on Abu Lahab",
      "Mecca", ["111:1", "111:2", "111:3", "111:4", "111:5"],
      "لمّا قال أبو لهب: تباً لك، على الصفا، نزلت سورة تبّت تدعو عليه وعلى امرأته حمّالة الحطب.",
      "القرآن يوثّق العداء الشخصي المعاند كنموذج عام؛ لا النسب ولا المال ينجيان من الحق.",
      "verbal_attack", "kin_vs_kin", "reputation_honor",
      "moral_rebuke", "truth_before_kinship", "rebuke"),

    E("meccan_walid_sahir_verdict", 13, -10, "meccan_early",
      "الوليد بن المغيرة يصف القرآن بالسحر", "Al-Walid labels the Quran as sorcery",
      "Mecca", ["74:11", "74:12", "74:13", "74:14", "74:15", "74:16", "74:17", "74:18", "74:19", "74:20", "74:21", "74:22", "74:23", "74:24", "74:25"],
      "اجتمعت قريش تطلب من الوليد بن المغيرة وصفاً يُنفّرون به الناس عن القرآن، ففكّر وقدّر ثم قال: إن هو إلا سحر يؤثر.",
      "التلفيق ضد الحق أعسر من الإنكار الصريح؛ القرآن يكشف بنية القرار الباطل خطوة خطوة.",
      "verbal_attack", "principled_minority_vs_powerful_majority", "truth_vs_falsehood",
      "moral_rebuke", "legitimacy_follows_method", "rebuke"),

    E("meccan_walid_al_akhnas_consultation", 14, -10, "meccan_early",
      "مشورة قريش في تسمية النبي ﷺ", "Quraysh deliberation on labeling the Prophet",
      "Mecca", ["52:29", "52:30", "68:51", "15:6", "21:5"],
      "اختلفت قريش في وصف يُلصقونه بالنبي ﷺ بين ساحر وكاهن وشاعر ومجنون، ولم يتفقوا على تهمة ثابتة.",
      "تناقض خصوم الحق في الوصف دليل على بطلان الوصف كله؛ من لا يملك حجة يُكثر الاتهام.",
      "verbal_attack", "individual_vs_majority", "reputation_honor",
      "intellectual_rebuttal", "legitimacy_follows_method", "rhetorical_question"),

    E("meccan_bilal_torture", 15, -10, "meccan_early",
      "تعذيب بلال بن رباح تحت حرّ الرمضاء", "Torture of Bilal under the burning sand",
      "Mecca", ["16:110", "85:4", "85:5", "85:6", "85:7", "85:8"],
      "عذّب أمية بن خلف مولاه بلالاً في حر الظهيرة، يضعه تحت الحجارة، وهو يقول أحدٌ أحد.",
      "ثبات المستضعف على كلمة واحدة أبلغ من بيان الفصحاء؛ القدم المعذّبة تَهزّ قصور الطغاة.",
      "physical_persecution", "principled_minority_vs_powerful_majority", "physical_safety",
      "endurance_without_retaliation", "patience_under_collective_punishment", "consolation"),

    E("meccan_abubakr_frees_bilal", 16, -10, "meccan_early",
      "أبو بكر يعتق بلالاً", "Abu Bakr frees Bilal",
      "Mecca", ["92:17", "92:18", "92:19", "92:20", "92:21"],
      "اشترى أبو بكر بلالاً من أمية بن خلف وأعتقه لله، وهكذا أعتق ستة من الموالي المعذّبين.",
      "القوة المالية توظَّف لفكّ رقاب المظلومين؛ المال أمانة لا تملك مطلق.",
      "economic_siege", "principled_minority_vs_powerful_majority", "livelihood",
      "forgiveness_from_power", "wealth_as_trust_not_ownership", "praise"),

    E("meccan_sumayya_first_martyr", 17, -10, "meccan_early",
      "استشهاد سمية أم عمار", "Martyrdom of Sumayya mother of Ammar",
      "Mecca", ["85:4", "85:5", "85:6", "85:7", "85:8"],
      "طعن أبو جهل سميةَ بنت خياط في قبلها برمح فقتلها، فكانت أول شهيدة في الإسلام.",
      "المرأة الضعيفة قد تكون أول من يدفع الثمن؛ والشهادة الأولى ميسم يُكرّم الله به أهلها إلى الأبد.",
      "physical_persecution", "principled_minority_vs_powerful_majority", "physical_safety",
      "endurance_without_retaliation", "patience_under_collective_punishment", "story"),

    E("meccan_yasir_martyr", 18, -10, "meccan_early",
      "استشهاد ياسر والد عمار", "Martyrdom of Yasir father of Ammar",
      "Mecca", ["85:4", "85:5", "85:6", "85:7", "85:8"],
      "مات ياسر تحت التعذيب مع زوجه سمية في أوائل من قدّم حياته ثمناً للإيمان.",
      "العائلة بأسرها قد تُقدَّم قرباناً للحق؛ التضحية قد تمسّ الجذر كله لا الفرع فقط.",
      "physical_persecution", "principled_minority_vs_powerful_majority", "physical_safety",
      "endurance_without_retaliation", "chosen_hardship_over_compromise", "story"),

    E("meccan_ammar_forced_to_curse", 19, -10, "meccan_early",
      "عمار يُكره على كلمة الكفر", "Ammar coerced into words of disbelief",
      "Mecca", ["16:106"],
      "اشتدّ التعذيب على عمار بن ياسر حتى أعطاهم بعض ما أرادوا بلسانه، فجاء إلى النبي ﷺ باكياً فعذره وأنزل الله رخصة الإكراه.",
      "الإكراه يرفع الإثم عن ظاهر اللسان ما اطمأن القلب بالإيمان؛ الشريعة ترحم المضطر ولا تُحمّله فوق طاقته.",
      "physical_persecution", "principled_minority_vs_powerful_majority", "spiritual_integrity",
      "legal_innovation", "scaling_principle_to_context", "legislation"),

    E("meccan_khabbab_iron_torture", 20, -10, "meccan_early",
      "تعذيب خباب بن الأرت بالحديد", "Torture of Khabbab ibn al-Aratt",
      "Mecca", ["3:186"],
      "كان خباب حدّاداً فعذّبه سيده بالحديد المحمى حتى ذابت شحمة ظهره، فشكا إلى النبي ﷺ استبطاء النصر.",
      "استبطاء النصر طبع بشري؛ والجواب النبوي: كان من قبلكم يُنشر بالمنشار ولا يصرفه ذلك عن دينه.",
      "physical_persecution", "principled_minority_vs_powerful_majority", "physical_safety",
      "endurance_without_retaliation", "divine_testing_mechanism", "consolation"),

    E("meccan_hamza_islam", 21, -9, "meccan_middle",
      "إسلام حمزة بن عبد المطلب", "Conversion of Hamza ibn Abd al-Muttalib",
      "Mecca", ["6:122"],
      "اعتدى أبو جهل على النبي ﷺ فبلغ ذلك عمَّه حمزة وهو عائد من الصيد، فضرب أبا جهل بقوسه وأعلن إسلامه حميةً لابن أخيه.",
      "النور قد يدخل القلب من باب الحمية قبل باب الاقتناع؛ كل دافع يُستثمر في خدمة الحق.",
      "verbal_attack", "kin_vs_kin", "reputation_honor",
      "confrontation_with_truth", "solidarity_around_principle", "praise"),

    E("meccan_umar_islam_taha", 22, -8, "meccan_middle",
      "إسلام عمر بن الخطاب بقراءة طه", "Umar's conversion via reading Ta-Ha",
      "Mecca", ["20:1", "20:2", "20:3", "20:4", "20:5", "20:6", "20:7", "20:8"],
      "خرج عمر متقلّداً سيفه يريد قتل النبي ﷺ، فدُلّ على إسلام أخته، فسمع صحيفة من طه في بيتها فأسلم وذهب إلى النبي معلناً.",
      "البيان القرآني حجة بنفسه على القلب الصادق، ولا يحتاج وسيطاً يعدّله ليكون مقنعاً.",
      "intellectual_challenge", "individual_vs_majority", "spiritual_integrity",
      "confrontation_with_truth", "truth_is_independent_of_carrier", "clarification"),

    E("meccan_umar_public_prayer", 23, -8, "meccan_middle",
      "أول صلاة جماعية علنية بإسلام عمر", "First public congregational prayer after Umar's islam",
      "Mecca", ["9:40"],
      "بعد إسلام عمر صلّى المسلمون أول مرة عند الكعبة جماعة علنية، فأطاقتهم قريش ولم تستطع منعهم.",
      "الشجاعة الفردية لشخص واحد قد تغيّر حسابات الجماعة كلها.",
      "physical_persecution", "principled_minority_vs_powerful_majority", "religious_freedom",
      "public_declaration", "solidarity_around_principle", "praise"),

    E("meccan_quraysh_offer_utba", 24, -9, "meccan_middle",
      "عرض عتبة بن ربيعة المغريات على النبي ﷺ", "Utba ibn Rabi'a's offer of wealth and kingship",
      "Mecca", ["41:1", "41:2", "41:3", "41:4", "41:5", "41:6", "41:7", "41:8"],
      "جاء عتبة بن ربيعة يعرض على النبي ﷺ المال والملك والطب إن كفّ عن الدعوة، فردّ عليه النبي بتلاوة أول سورة فصلت فقام مبهوتاً.",
      "القرآن حين يُتلى يقطع أطماع المساومين؛ الإغراء لا يُهزم بالرفض اللفظي بل بكشف ما لا يُقاس به.",
      "moral_temptation", "individual_vs_majority", "truth_vs_falsehood",
      "refusal_to_compromise", "principled_refusal_to_transgress", "rebuke"),

    E("meccan_abu_talib_delegation", 25, -9, "meccan_middle",
      "وفد قريش إلى أبي طالب", "Quraysh delegation to Abu Talib",
      "Mecca", ["38:5", "38:6", "38:7", "38:8"],
      "جاء أشراف قريش إلى أبي طالب يطلبون منه أن يكفّ ابن أخيه أو يُسلمه لهم، فدعاه وعرض الأمر فقال النبي ﷺ: والله لو وضعوا الشمس في يميني ما تركت هذا الأمر.",
      "العزيمة على الحق لا تساوم حتى مع الأقرباء؛ الحق أثمن من كل عوض يُعرض عليه.",
      "family_pressure", "kin_vs_kin", "truth_vs_falsehood",
      "refusal_to_compromise", "principled_refusal_to_transgress", "praise"),

    E("meccan_quraysh_offer_umara", 26, -9, "meccan_middle",
      "عرض عمارة بن الوليد مبادلاً بالنبي ﷺ", "Quraysh offer to swap Umara ibn al-Walid for the Prophet",
      "Mecca", ["43:31", "43:32"],
      "عرضت قريش على أبي طالب أن يأخذ عمارة بن الوليد فتى قريش ابناً بدل النبي ﷺ ليسلموه إليهم، فرفض أبو طالب رفضاً قاطعاً.",
      "لا يُستبدل الحق برجل جميل مهما بلغت صفاته؛ التبني لا يصنع قرابة الدم.",
      "moral_temptation", "kin_vs_kin", "family_integrity",
      "refusal_to_compromise", "truth_before_kinship", "rebuke"),

    E("meccan_demand_miracles", 27, -8, "meccan_middle",
      "مطالبة قريش بآيات خارقة", "Quraysh demanding spectacular miracles",
      "Mecca", ["17:90", "17:91", "17:92", "17:93"],
      "طلبت قريش من النبي ﷺ أن يُفجّر لهم ينبوعاً أو يُنزل كتاباً من السماء أو يرقى إلى السماء على مرأى منهم، فلم يُجبهم لأن النتيجة ليست إيماناً بل إعناتاً.",
      "الآيات الحسية لا تُنتج إيماناً عند من أعمى قلبه؛ البرهان يُقدَّم للطالب لا للمعاند.",
      "intellectual_challenge", "principled_minority_vs_powerful_majority", "truth_vs_falsehood",
      "intellectual_rebuttal", "signs_require_reflection_not_proof", "rhetorical_question"),

    E("meccan_demand_poor_removed", 28, -8, "meccan_middle",
      "طلب إبعاد فقراء المؤمنين", "Demand to remove the poor believers",
      "Mecca", ["6:52", "6:53", "18:28", "80:5", "80:6", "80:7"],
      "طلب سادة قريش من النبي ﷺ أن يُبعد بلالاً وصهيباً وخبّاباً وأمثالهم ليجلسوا معه، فرفض وثبت عنده المستضعفون.",
      "المبدأ لا يُفرّق بين الضعيف والقوي؛ من اشترط في الحق شرط الطبقة أفسده.",
      "social_exclusion", "principled_minority_vs_powerful_majority", "community_cohesion",
      "refusal_to_compromise", "protection_of_the_weak", "command"),

    E("meccan_demand_angelic_messenger", 29, -8, "meccan_middle",
      "طلب رسول من الملائكة", "Demand for an angelic messenger",
      "Mecca", ["6:8", "6:9", "25:7", "25:8", "17:94", "17:95"],
      "قالت قريش: لولا أنزل عليه ملك، أو هلاّ أُرسل ملك يُشاركه في الإنذار. فبيّن القرآن أن الرسول يجب أن يكون من جنس المُرسَل إليهم ليُمكن اتّباعه.",
      "الاقتداء لا يتحقق إلا بمشاكل بينَ القائد والأتباع؛ الحكمة الإلهية راعت إمكان التأسي.",
      "intellectual_challenge", "principled_minority_vs_powerful_majority", "truth_vs_falsehood",
      "intellectual_rebuttal", "scaling_principle_to_context", "argument"),

    E("meccan_foreign_teacher_charge", 30, -8, "meccan_middle",
      "تهمة أن غلاماً أعجمياً يُعلّم النبي ﷺ", "Charge that a foreign servant taught the Prophet",
      "Mecca", ["16:103"],
      "قال المشركون إن محمداً إنما يُعلّمه غلامٌ أعجمي (قيل اسمه جبر) يعمل بمكة، فردّ القرآن أن لسان الرجل أعجمي وهذا لسان عربي مبين.",
      "اتهام المصلح بالاقتباس من الأدنى منه علمياً حجة الضعيف؛ اللسان العربي المبين شاهد على نفسه.",
      "verbal_attack", "principled_minority_vs_powerful_majority", "reputation_honor",
      "intellectual_rebuttal", "legitimacy_follows_method", "argument"),

    E("meccan_poet_charge", 31, -8, "meccan_middle",
      "تهمة أن النبي ﷺ شاعر", "Charge that the Prophet is a poet",
      "Mecca", ["21:5", "36:69", "52:30", "69:41"],
      "رمى المشركون النبي ﷺ بأنه شاعر يفتعل الأبيات، فنفى القرآن ذلك بأن النبي لم يكن يقول الشعر ولا ينبغي له.",
      "محاولة وضع الحق في قالب معروف بهدف تحييده؛ لا يُصنّف القرآن في أي باب بشري مألوف.",
      "verbal_attack", "principled_minority_vs_powerful_majority", "reputation_honor",
      "intellectual_rebuttal", "legitimacy_follows_method", "argument"),

    E("meccan_sorcerer_charge", 32, -8, "meccan_middle",
      "تهمة الكهانة والسحر", "Charge of sorcery and soothsaying",
      "Mecca", ["51:52", "52:29", "69:42"],
      "رمى المشركون النبي ﷺ بالكهانة والسحر تارةً بعد الشعر، فأنكر القرآن ذلك بأنهم يتداولون التهم ولا يستقرّون على واحدة.",
      "تعدد التهم المتناقضة برهان على إفلاس المتهم؛ العاجز عن الحجة يتنقّل بين التسميات.",
      "verbal_attack", "principled_minority_vs_powerful_majority", "reputation_honor",
      "intellectual_rebuttal", "legitimacy_follows_method", "argument"),

    E("meccan_madman_charge", 33, -8, "meccan_middle",
      "تهمة الجنون", "Charge of madness",
      "Mecca", ["52:29", "68:2", "68:51", "81:22"],
      "قال أعداء النبي ﷺ إنه مجنون، فأقسم القرآن بالقلم وما يسطرون أن صاحبهم ليس بمجنون وأنه على خلق عظيم.",
      "حين تعجز البلاغة عن إسكات الحق يُلجأ إلى الاتهام بالعقل؛ الجواب الأبلغ هو ذكر الأخلاق العالية.",
      "verbal_attack", "individual_vs_majority", "reputation_honor",
      "intellectual_rebuttal", "consistency_public_and_private", "oath"),

    E("meccan_liar_charge", 34, -8, "meccan_middle",
      "تهمة الكذب مع معرفة صدقه", "Charge of lying despite knowing his honesty",
      "Mecca", ["6:33", "38:4"],
      "اعترف المشركون سراً بصدق النبي ﷺ (كما قال الأخنس لأبي جهل) لكنهم أعلنوا تكذيبه، فعزّى الله نبيه بقوله فإنهم لا يُكذّبونك ولكن الظالمين بآيات الله يجحدون.",
      "العناد السياسي قد يتعارض مع اليقين الشخصي؛ النفي العلني قد يُخفي التصديق السري.",
      "verbal_attack", "principled_minority_vs_powerful_majority", "truth_vs_falsehood",
      "consolation_and_thabaat", "consistency_public_and_private", "consolation"),

    E("meccan_asatir_alawwalin", 35, -8, "meccan_middle",
      "تهمة أساطير الأولين", "Charge of 'fables of the ancients'",
      "Mecca", ["25:5", "6:25", "8:31", "16:24"],
      "قال النضر بن الحارث وأمثاله: ما هذا القرآن إلا أساطير الأولين اكتتبها فهي تُملى عليه بكرة وأصيلاً، فبيّن القرآن أن ما يأتي به ليس مما يُعرف بشراً.",
      "تصنيف الجديد في خانة القديم وسيلة للتقليل منه؛ من لم يسمع مثله من قبل يحسبه نسخة مما سمع.",
      "verbal_attack", "principled_minority_vs_powerful_majority", "truth_vs_falsehood",
      "intellectual_rebuttal", "legitimacy_follows_method", "rebuke"),

    E("meccan_habasha_first_migration", 36, -8, "meccan_middle",
      "الهجرة الأولى إلى الحبشة", "First migration to Abyssinia",
      "Mecca", ["16:41", "16:42", "29:56", "39:10"],
      "أذن النبي ﷺ لعشرة رجال وخمس نسوة بالهجرة إلى أرض الحبشة فراراً بدينهم، فاستقبلهم النجاشي ملكها بالحفاوة.",
      "الهجرة في سبيل الله باب مفتوح حين يضيق الوطن؛ الأرض واسعة لمن صدق طلبه للحق.",
      "physical_persecution", "principled_minority_vs_powerful_majority", "religious_freedom",
      "strategic_withdrawal", "chosen_hardship_over_compromise", "command"),

    E("meccan_najashi_delegation", 37, -7, "meccan_middle",
      "وفد قريش إلى النجاشي", "Quraysh delegation to the Negus",
      "Mecca", ["3:113", "3:114", "3:115", "5:82", "5:83"],
      "أرسلت قريش عمرو بن العاص وعبد الله بن أبي ربيعة إلى النجاشي ليطلبا إخراج المسلمين، فتكلّم جعفر بن أبي طالب بحجة قرآنية فبكى النجاشي ومن حوله.",
      "الحجة الصادقة تتجاوز الحدود السياسية؛ القلب العادل ينحاز للحق حتى لو تضرّر من ذلك سياسياً.",
      "political_pressure", "principled_minority_vs_powerful_majority", "religious_freedom",
      "intellectual_rebuttal", "truth_is_independent_of_carrier", "argument"),

    E("meccan_najashi_judges", 38, -7, "meccan_middle",
      "حكم النجاشي لصالح المهاجرين", "Negus judges in favor of the migrants",
      "Mecca", ["3:199", "5:82"],
      "قرأ جعفر على النجاشي مطلع سورة مريم في عيسى وأمه، فاطمأن النجاشي أن ما عندهم مصدّق لما عنده فرفض تسليمهم.",
      "الصدق في عرض المعتقد لا يحتاج للتمويه؛ الحق حين يُكشف بصدق يجد أرضه.",
      "political_pressure", "principled_minority_vs_powerful_majority", "religious_freedom",
      "refusal_to_compromise", "truth_before_kinship", "praise"),

    E("meccan_shiab_boycott_written", 39, -7, "meccan_middle",
      "كتابة صحيفة مقاطعة بني هاشم", "Writing of the Bani Hashim boycott document",
      "Mecca", ["6:34", "29:2", "29:3"],
      "كتبت قريش صحيفة تقاطع فيها بني هاشم وبني المطلب حتى يسلموا محمداً ﷺ، وعلّقت الصحيفة في جوف الكعبة.",
      "التشريع القانوني قد يُوظَّف أداةً للظلم؛ العقود قد تُكتب ضد المظلوم وتُعلَّق في أقدس الأماكن.",
      "legal_coercion", "principled_minority_vs_powerful_majority", "collective_survival",
      "endurance_without_retaliation", "refusing_to_legitimize_falsehood", "warning"),

    E("meccan_shiab_hunger", 40, -6, "meccan_middle",
      "حصار شعب أبي طالب وجوع الأطفال", "Siege of Shi'b Abi Talib and children's hunger",
      "Mecca", ["29:2", "29:3", "85:4", "85:5"],
      "حوصر بنو هاشم في شعب أبي طالب نحو ثلاث سنين، وكانوا يأكلون أوراق الشجر، ويُسمع بكاء الأطفال من الجوع وراء الجبل.",
      "الصبر على العقوبة الجماعية يختبر التماسك حول المبدأ؛ من ثبت تحت الجوع ثبت على كل أذى.",
      ["economic_siege", "social_exclusion"], "principled_minority_vs_powerful_majority",
      "collective_survival", "endurance_without_retaliation",
      "patience_under_collective_punishment", "consolation"),

    E("meccan_shiab_smuggling", 41, -5, "meccan_middle",
      "تهريب الطعام إلى المحصورين", "Smuggling food to those in the siege",
      "Mecca", ["3:113", "3:114", "3:115"],
      "كان هشام بن عمرو وحكيم بن حزام وغيرهما من قريش يُرسلون الطعام خفيةً إلى بني هاشم في الشعب رحمةً بهم.",
      "حتى في الظلم الجماعي تبقى ضمائر حية؛ المنقذ قد يأتي من داخل صف الخصم.",
      "social_exclusion", "ally_vs_ally_dispute", "trust_between_parties",
      "private_counsel", "distinguishing_enemy_from_outsider", "praise"),

    E("meccan_shiab_document_eaten", 42, -5, "meccan_middle",
      "أكل الأرضة لصحيفة المقاطعة", "Termites eat the boycott document",
      "Mecca", ["27:18", "27:19"],
      "أخبر النبي ﷺ عمّه أبا طالب أن الله أرسل على صحيفة قريش الأرضة فأكلت كل ما فيها إلا اسم الله، فأخبرهم أبو طالب فلما كشفوها صدق النبي فنقضوا الصحيفة.",
      "بطلان الظلم قد يأتي من أصغر خلق الله؛ التأييد الإلهي لا يستبق التوقعات.",
      "legal_coercion", "principled_minority_vs_powerful_majority", "justice_vs_privilege",
      "refusing_to_legitimize_falsehood", "divine_testing_mechanism", "story"),

    E("meccan_death_khadija", 43, -4, "meccan_late",
      "وفاة خديجة رضي الله عنها", "Death of Khadijah",
      "Mecca", ["93:6", "93:7", "93:8"],
      "توفيت خديجة بعد نحو خمس وعشرين سنة من الزواج وكانت الوزير الأول للنبي ﷺ، فحزن عليها حزناً شديداً.",
      "فقد السند الأقرب اختبار خاص للقائد؛ الدعم لا يُعوَّض بسهولة لكن الطريق يمضي.",
      "psychological_pressure", "spouse_vs_spouse", "family_integrity",
      "endurance_without_retaliation", "patience_under_collective_punishment", "consolation"),

    E("meccan_death_abu_talib", 44, -4, "meccan_late",
      "وفاة أبي طالب", "Death of Abu Talib",
      "Mecca", ["28:56", "9:113", "9:114"],
      "توفي أبو طالب عم النبي ﷺ وقد ظلّ يحميه من قريش، ولم يُعلن إسلامه حتى آخر لحظة رغم حرص النبي ﷺ عليه.",
      "الحرص لا يوصل بالضرورة إلى الهداية؛ المؤمن يبذل ما في وسعه ثم يدع أمر القلوب لمقلّبها.",
      "psychological_pressure", "kin_vs_kin", "spiritual_integrity",
      "endurance_without_retaliation", "no_coercion_in_conviction", "consolation"),

    E("meccan_year_of_sorrow", 45, -4, "meccan_late",
      "عام الحزن", "Year of sorrow",
      "Mecca", ["93:1", "93:2", "93:3", "93:4", "93:5", "94:1", "94:2", "94:3", "94:4", "94:5", "94:6"],
      "سُمّي العام الذي فقد فيه النبي ﷺ خديجة وأبا طالب عام الحزن، واشتدّ فيه الأذى من قريش بعد غياب حاميه.",
      "تراكم المصائب في فترة واحدة يكشف موضع الاستناد الحقيقي؛ من فقد البشر وجد الله.",
      "psychological_pressure", "self_vs_self", "spiritual_integrity",
      "consolation_and_thabaat", "refuge_with_god_against_despair", "consolation"),

    E("meccan_taif_journey", 46, -3, "meccan_late",
      "رحلة الطائف", "Journey to Ta'if",
      "Taif", ["6:33", "6:34", "10:99", "12:110"],
      "ذهب النبي ﷺ إلى الطائف يدعو ثقيفاً بعد ضيق مكة، فردّوه ثلاثة من ساداتهم بأقبح ردّ وأغروا به سفهاءهم حتى أدموا قدميه الشريفتين.",
      "رفض المخاطَبين للدعوة لا يُعفي الداعي من إكمال طريقه؛ الألم الجسدي أخفّ من خيانة الأمانة.",
      "physical_persecution", "individual_vs_majority", "physical_safety",
      "endurance_without_retaliation", "principled_refusal_to_transgress", "consolation"),

    E("meccan_taif_dua", 47, -3, "meccan_late",
      "دعاء النبي ﷺ في الطائف", "The Prophet's supplication at Ta'if",
      "Taif", ["10:99", "16:125", "16:126", "16:127"],
      "لجأ النبي ﷺ إلى ظل شجرة في الطائف وقال دعاءه المشهور: اللهم إليك أشكو ضعف قوتي، وقلة حيلتي، وهواني على الناس.",
      "الشكوى لله لا من الله؛ اللجوء الحقيقي في أشد اللحظات يكون إلى من بيده كل شيء.",
      "psychological_pressure", "self_vs_self", "spiritual_integrity",
      "refuge_with_god_against_despair", "refuge_with_god_against_despair", "consolation"),

    E("meccan_taif_addas", 48, -3, "meccan_late",
      "عدّاس النصراني يسلم في الطائف", "Addas the Christian converts at Ta'if",
      "Taif", ["28:52", "28:53"],
      "أرسل عتبة وشيبة ابنا ربيعة غلامهما عدّاساً بعنقود عنب إلى النبي ﷺ، فلما سمّى الله عند الأكل وسأله النبي عن بلده أخبره أنه من نينوى فذكر يونس، فأسلم عدّاس.",
      "الهداية تُهيَّأ للقلب الصادق من حيث لا يحتسب؛ خير واحد يخرج من رحلة الألم.",
      "none", "believer_vs_unbeliever", "spiritual_integrity",
      "teaching_through_demonstration", "truth_is_independent_of_carrier", "story"),

    E("meccan_mutim_protection_return", 49, -3, "meccan_late",
      "رجوع النبي ﷺ بجوار المطعم بن عدي", "Return under the protection of Mut'im ibn Adi",
      "Mecca", ["2:257", "9:40"],
      "لما رجع النبي ﷺ من الطائف لم يستطع دخول مكة إلا بجوار المطعم بن عدي، فلبس المطعم سلاحه وأدخله معه.",
      "قبول الحماية من غير المؤمن جائز إذا كانت تُخدم الرسالة؛ الجميل يُحفظ لأهله حتى لو كانوا مخالفين في الدين.",
      "political_pressure", "community_vs_outsider", "physical_safety",
      "seeking_allies", "distinguishing_enemy_from_outsider", "praise"),

    E("meccan_jinn_listen_nakhla", 50, -3, "meccan_late",
      "استماع الجن للقرآن بنخلة", "Jinn listening to the Quran at Nakhla",
      "Nakhla", ["46:29", "46:30", "46:31", "46:32", "72:1", "72:2", "72:3"],
      "مرّ نفر من الجن بالنبي ﷺ وهو يصلي بنخلة راجعاً من الطائف، فسمعوا القرآن فآمنوا ورجعوا إلى قومهم منذرين.",
      "القرآن يستقطب السامع الصادق مهما اختلف جنسه؛ الحق يعبر الحدود المألوفة.",
      "none", "community_vs_outsider", "truth_vs_falsehood",
      "intellectual_rebuttal", "truth_is_independent_of_carrier", "story"),

    E("meccan_isra_journey", 51, -2, "meccan_late",
      "الإسراء إلى بيت المقدس", "The night journey to Jerusalem",
      "Mecca", ["17:1"],
      "أُسري بالنبي ﷺ ليلاً من المسجد الحرام إلى المسجد الأقصى على البُراق، وصلى إماماً بالأنبياء هناك.",
      "ربط القلب المسلم بالمسجد الأقصى تأسيس وعي جغرافي سابق للتمكين؛ المكان المقدس يُحاط قبل أن يُفتح.",
      "existential_threat", "self_vs_self", "generational_legacy",
      "confrontation_with_truth", "knowledge_before_action", "story"),

    E("meccan_miraj_ascension", 52, -2, "meccan_late",
      "المعراج إلى السماوات", "Ascension through the heavens",
      "Mecca", ["53:1", "53:2", "53:3", "53:4", "53:5", "53:6", "53:7", "53:8", "53:9", "53:10", "53:11", "53:12", "53:13", "53:14", "53:15", "53:16", "53:17", "53:18"],
      "عُرج بالنبي ﷺ من بيت المقدس إلى السماوات العُلى، فلقي الأنبياء في كل سماء، ورأى من آيات ربه الكبرى.",
      "معاينة الآيات الكبرى تُثبّت قلب القائد قبل أعباء المرحلة التالية؛ الاطلاع على الغيب قوة دفع للحاضر.",
      "none", "self_vs_self", "spiritual_integrity",
      "consolation_and_thabaat", "signs_require_reflection_not_proof", "story"),

    E("meccan_salat_fardiyya", 53, -2, "meccan_late",
      "فرض الصلوات الخمس", "Imposition of the five daily prayers",
      "Mecca", ["17:78", "17:79", "20:14", "50:39", "50:40"],
      "فُرضت الصلوات في الإسراء خمسين ثم خُفّفت إلى خمس بمراجعة موسى عليه السلام بمشورته للنبي ﷺ.",
      "التشريع قد يُنسخ قبل أن يستقر لمصلحة المكلّفين؛ المشورة قد تأتي من الأكبر تجربة.",
      "none", "leader_vs_follower", "spiritual_integrity",
      "legal_innovation", "scaling_principle_to_context", "legislation"),

    E("meccan_abubakr_siddiq_title", 54, -2, "meccan_late",
      "لقب الصديق لأبي بكر بعد الإسراء", "Abu Bakr earns the title 'al-Siddiq' after the Isra",
      "Mecca", ["39:33"],
      "لما أخبر النبي ﷺ قريشاً بالإسراء سخروا وذهبوا إلى أبي بكر مستبشرين بردّه، فقال: إن كان قال فقد صدق، فسمي الصديق.",
      "التصديق بلا تردد في الخبر الصادق لا يحتاج إلى دليل زائد؛ اليقين باستقرار صدق المخبر.",
      "intellectual_challenge", "individual_vs_majority", "trust_between_parties",
      "confrontation_with_truth", "trust_is_earned_by_consistency", "praise"),

    E("meccan_describe_caravan", 55, -2, "meccan_late",
      "وصف النبي ﷺ لقافلة قريش من علامات الإسراء", "Describing Quraysh's caravan as a sign of Isra",
      "Mecca", ["17:60"],
      "طلبت قريش من النبي ﷺ علامات على صدق الإسراء، فوصف لهم قافلتهم ومواقعها في الطريق، فتحقّقوا فوجدوه مطابقاً، لكنهم أنكروا.",
      "البرهان لا يُنتج إيماناً إذا سبقه إصرار على الإنكار؛ الأدلة تحتاج إلى أرض مستعدة.",
      "intellectual_challenge", "principled_minority_vs_powerful_majority", "truth_vs_falsehood",
      "intellectual_rebuttal", "signs_require_reflection_not_proof", "argument"),

    E("meccan_suwayd_ibn_samit", 56, -2, "meccan_late",
      "عرض الإسلام على سويد بن الصامت", "Offering Islam to Suwayd ibn al-Samit",
      "Mecca", ["16:125"],
      "عرض النبي ﷺ على سويد بن الصامت الأنصاري الذي جاء للحج الإسلام، فقال: إن هذا الكلام لحسن، فأسلم ثم قُتل قبل بدر.",
      "البذور الصغيرة في المواسم تُنبت لاحقاً شجراً عظيمة؛ كل لقاء دعوي قد يكون بداية تاريخ.",
      "none", "community_vs_outsider", "truth_vs_falsehood",
      "seeking_allies", "teaching_through_demonstration", "praise"),

    E("meccan_iyas_ibn_muadh", 57, -2, "meccan_late",
      "دعوة إياس بن معاذ", "Inviting Iyas ibn Mu'adh",
      "Mecca", ["16:125"],
      "عرض النبي ﷺ على وفد من الأوس جاء يطلب حلفاً من قريش الإسلام، فقبل إياس بن معاذ وأنكر عليه أبو الحيسر ورجع الوفد.",
      "مقاومة الصف لا تُلغي بذرة الحق في أفراده؛ الجماعة قد تُعاند والفرد قد يستجيب.",
      "social_exclusion", "ally_vs_ally_dispute", "truth_vs_falsehood",
      "seeking_allies", "distinguishing_enemy_from_outsider", "praise"),

    E("meccan_first_aqaba_pledge", 58, -2, "meccan_late",
      "بيعة العقبة الأولى", "First Pledge of Aqaba",
      "Mina", ["60:12"],
      "بايع ستة من الخزرج النبي ﷺ في العقبة الأولى عند الموسم، على ألا يشركوا بالله شيئاً ولا يسرقوا ولا يزنوا ولا يقتلوا أولادهم.",
      "البيعة عقد أخلاقي قبل أن تكون ولاءً سياسياً؛ البناء يبدأ من أصول السلوك.",
      "none", "ally_vs_ally_dispute", "collective_survival",
      "organizational_response", "solidarity_around_principle", "legislation"),

    E("meccan_musab_teacher_medina", 59, -1, "meccan_late",
      "إرسال مصعب بن عمير معلماً إلى يثرب", "Sending Mus'ab ibn Umayr as teacher to Yathrib",
      "Medina", ["2:129"],
      "أرسل النبي ﷺ مصعب بن عمير بعد بيعة العقبة الأولى إلى أهل يثرب ليعلّمهم القرآن ويُفقّههم في الدين.",
      "التمكين الثقافي يسبق التمكين السياسي؛ المعلم المُحسن أهم من الجيش.",
      "none", "teacher_vs_student", "knowledge_access",
      "organizational_response", "knowledge_before_action", "command"),

    E("meccan_musab_usayd_saad", 60, -1, "meccan_late",
      "إسلام أسيد بن حضير وسعد بن معاذ على يد مصعب", "Islam of Usayd and Sa'd through Mus'ab",
      "Medina", ["16:125"],
      "عرض مصعب الإسلام على زعيمَي الأوس أسيد بن حضير ثم سعد بن معاذ، فأسلما وقال سعد لقومه: كلامكم عليّ حرام حتى تُسلموا، فأسلمت بنو عبد الأشهل كلها.",
      "إسلام القائد يفتح باب قومه؛ العمل بالرؤوس أسرع من العمل بالأفراد.",
      "none", "leader_vs_follower", "community_cohesion",
      "organizational_response", "solidarity_around_principle", "praise"),

    # ═══════════════ MECCAN MIDDLE (order 61-110) ═══════════════

    E("meccan_abu_jahl_step_on_neck", 61, -9, "meccan_middle",
      "أبو جهل يحاول وطء النبي ﷺ وهو يصلي", "Abu Jahl attempts to step on the Prophet in prayer",
      "Mecca", ["96:6", "96:7", "96:8", "96:9", "96:10", "96:11", "96:12", "96:13", "96:14", "96:15", "96:16", "96:17", "96:18", "96:19"],
      "توعّد أبو جهل أن يطأ رقبة النبي ﷺ وهو ساجد، فلما همّ رجع ينتكص على عقبيه وقال: رأيت بيني وبينه خندقاً من نار.",
      "الطاغية يتهاوى حين يواجه الحقيقة وجهاً لوجه؛ الحماية الإلهية قد تكون غير مرئية.",
      "physical_persecution", "individual_vs_majority", "physical_safety",
      "endurance_without_retaliation", "refuge_with_god_against_despair", "warning"),

    E("meccan_uqba_camel_entrails", 62, -9, "meccan_middle",
      "عقبة بن أبي معيط يضع سلا الجزور على النبي ﷺ", "Uqba places camel entrails on the praying Prophet",
      "Mecca", ["22:19", "22:20"],
      "وضع عقبة بن أبي معيط سَلا جزور على ظهر النبي ﷺ وهو ساجد بأمر أبي جهل، حتى جاءت فاطمة الصغيرة فأزالته عنه.",
      "الإهانة العلنية سلاح ضعيف البشر؛ الذل الظاهري للحق يُصبح عزّاً لأهله لاحقاً.",
      "physical_persecution", "individual_vs_majority", "personal_dignity",
      "endurance_without_retaliation", "patience_under_collective_punishment", "warning"),

    E("meccan_ibn_masud_public_recitation", 63, -9, "meccan_middle",
      "ابن مسعود يجهر بالقرآن عند الكعبة", "Ibn Mas'ud publicly recites at the Kaaba",
      "Mecca", ["55:1", "55:2", "55:3"],
      "قال ابن مسعود: والله ما جهر أحد بالقرآن عند قريش قبلي، فقرأ الرحمن عند الكعبة فضربوه ولم يرجع حتى أتمّ ما شاء الله.",
      "الشجاعة الفردية تكسر حاجز الخوف الجماعي؛ أول من يكسر السكوت يفتح الطريق للآخرين.",
      "physical_persecution", "individual_vs_majority", "religious_freedom",
      "public_declaration", "chosen_hardship_over_compromise", "praise"),

    E("meccan_three_night_listeners", 64, -9, "meccan_middle",
      "استماع أبي جهل والأخنس وأبي سفيان للقرآن ليلاً", "Abu Jahl, al-Akhnas and Abu Sufyan secretly listen at night",
      "Mecca", ["6:25", "41:26"],
      "كان ثلاثة من قريش يستمعون للقرآن ليلاً متخفّين أمام بيت النبي ﷺ ثلاث ليال متتاليات، يلتقون في الصباح فيتعاهدون على الامتناع ثم يعودون.",
      "الجاذبية الخفية للحق تهزم الإعلان الظاهر بالعداء؛ القلب يعرف ما ينكره اللسان.",
      "intellectual_challenge", "insider_hypocrite_vs_sincere", "truth_vs_falsehood",
      "silence_as_answer", "consistency_public_and_private", "warning"),

    E("meccan_akhnas_abujahl_exchange", 65, -9, "meccan_middle",
      "حوار الأخنس وأبي جهل في صدق النبي ﷺ", "The Akhnas-Abu Jahl exchange on the Prophet's truthfulness",
      "Mecca", ["6:33"],
      "سأل الأخنس بن شريق أبا جهل: أصادق محمد أم كاذب فلا أحد يسمعنا؟ فقال أبو جهل: والله إنه لصادق، ولكن الشرف والعدد دفعنا إلى الإنكار.",
      "الحسد يُعطّل الاعتراف بالحق المعروف؛ الرفض قد يكون سياسياً خالصاً لا علمياً.",
      "verbal_attack", "insider_hypocrite_vs_sincere", "reputation_honor",
      "silence_as_answer", "warning_against_arrogance", "rebuke"),

    E("meccan_demand_write_books", 66, -8, "meccan_middle",
      "طلب كتاب مكتوب من السماء", "Demand for a written book from the sky",
      "Mecca", ["6:7", "17:93", "52:34"],
      "قالت قريش لن نؤمن حتى تُنزّل علينا كتاباً نقرؤه، فبيّن القرآن أن الآيات الحسية لا تلزم من كذّب الرسول.",
      "توسيع قائمة الطلبات مراوغة من الإيمان؛ من لم يقتنع بآية لا يقتنع بألف.",
      "intellectual_challenge", "principled_minority_vs_powerful_majority", "truth_vs_falsehood",
      "intellectual_rebuttal", "signs_require_reflection_not_proof", "rhetorical_question"),

    E("meccan_demand_treasure", 67, -8, "meccan_middle",
      "طلب كنز وجنة", "Demand for a treasure and garden",
      "Mecca", ["25:7", "25:8", "11:12"],
      "قال المشركون هلاّ أُلقي إليه كنز أو تكون له جنة يأكل منها، فردّ القرآن أن الرسل يأكلون الطعام ويمشون في الأسواق كسائر البشر.",
      "معايير الجماهير للنبوة مستقاة من ثقافة الملك لا من منطق الرسالة.",
      "verbal_attack", "principled_minority_vs_powerful_majority", "truth_vs_falsehood",
      "intellectual_rebuttal", "legitimacy_follows_method", "argument"),

    E("meccan_uyayna_mocks_poor", 68, -8, "meccan_middle",
      "عيينة بن حصن يطلب إبعاد الفقراء عن المجلس", "Uyayna demands removal of the poor from the gathering",
      "Mecca", ["18:28", "6:52"],
      "طلب بعض سادة قريش من النبي ﷺ أن يُخصّص لهم مجلساً دون المستضعفين، فأبى ونزل القرآن يأمره أن يصبر نفسه مع الذين يدعون ربهم.",
      "لا يُقبل اجتماع أي جزء من الحق على إقصاء المستضعفين؛ الصلة بالله سابقة على أي ترتيب طبقي.",
      "social_exclusion", "principled_minority_vs_powerful_majority", "justice_vs_privilege",
      "refusal_to_compromise", "protection_of_the_weak", "command"),

    E("meccan_nadr_persian_stories", 69, -8, "meccan_middle",
      "النضر بن الحارث يروي قصص الفرس مضاهاةً", "Al-Nadr tells Persian stories to rival the Quran",
      "Mecca", ["31:6", "6:25", "25:4", "25:5"],
      "كان النضر بن الحارث يشتري من فارس قصص رستم واسفنديار ويرويها لقريش زاعماً أنها أحسن من قصص القرآن، فأنزل الله لهوَ الحديث ذماً له.",
      "منافسة الحق بالترفيه أسلوب قديم للصد عن السبيل؛ البدائل السهلة تنال الجمهور لكنها لا تُغذّي القلب.",
      "intellectual_challenge", "principled_minority_vs_powerful_majority", "truth_vs_falsehood",
      "moral_rebuke", "refusing_to_legitimize_falsehood", "rebuke"),

    E("meccan_rabbis_send_questions", 70, -7, "meccan_middle",
      "أحبار اليهود يُرسلون ثلاث أسئلة لاختبار النبي ﷺ", "Rabbis send three test questions to the Prophet",
      "Mecca", ["18:9", "18:83", "17:85"],
      "أرسلت قريش النضر وعقبة إلى أحبار يهود بيثرب فسألوهم عن اختبار للنبي ﷺ، فأعطوهم ثلاث مسائل: أصحاب الكهف، وذو القرنين، والروح.",
      "تحويل السؤال إلى لجان خارجية أسلوب للتعطيل؛ الحق لا يخاف من تعدد الأسئلة.",
      "intellectual_challenge", "principled_minority_vs_powerful_majority", "truth_vs_falsehood",
      "intellectual_rebuttal", "knowledge_before_action", "rhetorical_question"),

    E("meccan_ashab_kahf_answer", 71, -7, "meccan_middle",
      "جواب القرآن عن أصحاب الكهف", "Quran answers about the People of the Cave",
      "Mecca", ["18:9", "18:10", "18:11", "18:12", "18:13", "18:14", "18:15", "18:16", "18:17", "18:18", "18:19", "18:20", "18:21", "18:22", "18:23", "18:24", "18:25", "18:26"],
      "أجاب القرآن عن قصة أصحاب الكهف تفصيلاً في سورة الكهف، وذكر عِدّتهم ومدة لبثهم والعبرة من خبرهم.",
      "القصة القرآنية أعمق من الخبر التاريخي؛ تُختار التفاصيل للدرس لا للإثارة.",
      "intellectual_challenge", "principled_minority_vs_powerful_majority", "truth_vs_falsehood",
      "intellectual_rebuttal", "knowledge_before_action", "story"),

    E("meccan_dhul_qarnayn_answer", 72, -7, "meccan_middle",
      "جواب القرآن عن ذي القرنين", "Quran answers about Dhul-Qarnayn",
      "Mecca", ["18:83", "18:84", "18:85", "18:86", "18:87", "18:88", "18:89", "18:90", "18:91", "18:92", "18:93", "18:94", "18:95", "18:96", "18:97", "18:98"],
      "ذكر القرآن رحلات ذي القرنين في المشرق والمغرب وبين السدَّين، ومعالجته العادلة لكل قوم.",
      "السلطان العادل يُمكّنه الله ثم يُسأل عن عدله؛ القوة تُستعمل لحماية المستضعفين.",
      "political_pressure", "ruler_vs_ruled", "justice_vs_privilege",
      "organizational_response", "accountability_proportional_to_power", "story"),

    E("meccan_ruh_question", 73, -7, "meccan_middle",
      "جواب القرآن عن الروح", "Quran's answer about the soul",
      "Mecca", ["17:85"],
      "سُئل النبي ﷺ عن الروح فنزل قل الروح من أمر ربي وما أوتيتم من العلم إلا قليلاً.",
      "الاعتراف بحدود العلم البشري أصل من أصول المنهج؛ ليس كل سؤال له جواب مباشر.",
      "intellectual_challenge", "principled_minority_vs_powerful_majority", "knowledge_access",
      "intellectual_rebuttal", "knowledge_before_action", "clarification"),

    E("meccan_surah_najm_sajda", 74, -7, "meccan_middle",
      "سجدة المشركين عند تلاوة سورة النجم", "Disbelievers prostrate at the end of Surah al-Najm",
      "Mecca", ["53:59", "53:60", "53:61", "53:62"],
      "قرأ النبي ﷺ سورة النجم علناً عند الكعبة ولما ختمها بآية السجدة سجد، وسجد معه الحاضرون من المسلمين والمشركين لا يملكون من أنفسهم.",
      "جمال الحق قد يخترق القلوب العنيدة في لحظة؛ الفطرة تستجيب قبل العقل المتحيّز.",
      "intellectual_challenge", "principled_minority_vs_powerful_majority", "truth_vs_falsehood",
      "confrontation_with_truth", "truth_is_independent_of_carrier", "story"),

    E("meccan_as_wail_abtar", 75, -6, "meccan_middle",
      "العاص بن وائل يطعن بانقطاع نسل النبي ﷺ", "Al-As ibn Wa'il mocks the Prophet's lack of male heirs",
      "Mecca", ["108:1", "108:2", "108:3"],
      "توفي القاسم وعبد الله أبناء النبي ﷺ وهما صغيران، فطعن العاص بن وائل بأن محمداً أبتر لا عقب له، فنزلت سورة الكوثر تردّ عليه.",
      "محاولة تحقير الخصم بنقطة شخصية تنعكس عليه؛ الكوثر الحقيقي خير وأبقى من النسب.",
      "verbal_attack", "individual_vs_majority", "reputation_honor",
      "moral_rebuke", "truth_is_independent_of_carrier", "rebuke"),

    E("meccan_abu_lahab_wife_thorns", 76, -6, "meccan_middle",
      "زوجة أبي لهب تضع الشوك في طريق النبي ﷺ", "Abu Lahab's wife places thorns in the Prophet's path",
      "Mecca", ["111:4", "111:5"],
      "كانت أم جميل زوج أبي لهب تضع الشوك في طريق النبي ﷺ وتتبعه بالسباب، فسُمّيت حمّالة الحطب.",
      "تشارك في العداء كل من ساند الظالم ولو بحركة صغيرة؛ المرأة مسؤولة عن فعلها كالرجل.",
      "verbal_attack", "kin_vs_kin", "personal_dignity",
      "moral_rebuke", "accountability_proportional_to_power", "rebuke"),

    E("meccan_abu_jahl_head_crush_vow", 77, -6, "meccan_middle",
      "قسم أبي جهل على وطء رأس النبي ﷺ", "Abu Jahl vows to crush the Prophet's head",
      "Mecca", ["96:15", "96:16"],
      "أقسم أبو جهل أمام قريش أنه إن رأى محمداً يسجد ليطأن رأسه بقدمه، فلما جاء وهمّ رجع خائفاً يقول رأيت هولاً.",
      "كبر الصوت لا يعني قوة الفعل؛ المتوعّدون بالشر غالباً يعجزون عن أول خطوة.",
      "physical_persecution", "individual_vs_majority", "physical_safety",
      "endurance_without_retaliation", "refuge_with_god_against_despair", "warning"),

    E("meccan_abu_sufyan_secret_listen", 78, -6, "meccan_middle",
      "أبو سفيان يستمع للقرآن خفية ليلاً", "Abu Sufyan secretly listens to the Quran at night",
      "Mecca", ["41:26"],
      "كان أبو سفيان يأتي في الليل يستمع للقرآن من وراء جدار النبي ﷺ ثم يتعاهد مع أصحابه على الامتناع ثم يعود.",
      "المقاومة العلنية لا تلغي الإعجاب الخفي؛ الإنسان قد ينقسم على نفسه تحت ثقل الحق.",
      "intellectual_challenge", "insider_hypocrite_vs_sincere", "spiritual_integrity",
      "silence_as_answer", "consistency_public_and_private", "warning"),

    E("meccan_abu_dharr_islam", 79, -6, "meccan_middle",
      "إسلام أبي ذر الغفاري", "Islam of Abu Dharr al-Ghifari",
      "Mecca", ["93:6", "93:7"],
      "قدم أبو ذر من غفار باحثاً عن الحقيقة، فوجد النبي ﷺ في مكة سراً، فأسلم وأسرّ إسلامه بأمر النبي ثم خرج وصاح بالشهادة عند الكعبة فضُرب.",
      "الباحث الصادق يصل حتى لو كان من أقاصي الجزيرة؛ الشجاعة الأولى قد تُمتحن بالضرب.",
      "physical_persecution", "community_vs_outsider", "physical_safety",
      "public_declaration", "chosen_hardship_over_compromise", "praise"),

    E("meccan_tufayl_dawsi", 80, -6, "meccan_middle",
      "إسلام الطفيل بن عمرو الدوسي", "Islam of al-Tufayl ibn Amr al-Dawsi",
      "Mecca", ["16:125"],
      "قدم الطفيل شاعر دوس مكة، وحذّرته قريش من كلام النبي ﷺ، فوضع في أذنيه قطناً ثم سمع القرآن مصادفة فأسلم ودعا قومه.",
      "محاولة حجب الحق بالإعلام المضاد تفشل أمام القلب الصادق؛ الصدفة قد تكون قدراً.",
      "verbal_attack", "community_vs_outsider", "truth_vs_falsehood",
      "confrontation_with_truth", "truth_is_independent_of_carrier", "praise"),

    E("meccan_utba_shayba_offer", 81, -6, "meccan_middle",
      "عتبة وشيبة يعرضان المساومة على النبي ﷺ", "Utba and Shayba offer a compromise",
      "Mecca", ["41:13"],
      "جاء عتبة وأخوه شيبة يعرضان على النبي ﷺ عدة مقايضات: المال، الملك، الزواج، الطب، شريطة أن يكفّ عن الدعوة، فردّ بسورة فصلت.",
      "المساومة على المبدأ مرفوضة مهما تنوّعت الإغراءات؛ الجواب بالقرآن أبلغ من أي حوار.",
      "moral_temptation", "principled_minority_vs_powerful_majority", "truth_vs_falsehood",
      "refusal_to_compromise", "principled_refusal_to_transgress", "argument"),

    E("meccan_hungry_child_bitter", 82, -5, "meccan_middle",
      "بكاء أطفال بني هاشم في الشعب من الجوع", "Hunger cries of Bani Hashim children in the siege",
      "Mecca", ["6:42", "2:155", "2:156", "2:157"],
      "بلغ الجوع ببني هاشم في الشعب حداً أن يُسمع بكاء الأطفال من وراء الجبال، وكانوا يأكلون أوراق الشجر.",
      "العقوبة الجماعية تصيب الأبرياء قبل المعنيين؛ الصبر على آلام الذرية أشد الابتلاء.",
      ["economic_siege", "social_exclusion"], "principled_minority_vs_powerful_majority",
      "livelihood", "endurance_without_retaliation",
      "patience_under_collective_punishment", "consolation"),

    E("meccan_abu_talib_couplet", 83, -5, "meccan_middle",
      "شعر أبي طالب في نصرة النبي ﷺ", "Abu Talib's poetry defending the Prophet",
      "Mecca", ["26:219"],
      "قال أبو طالب في لاميته الشهيرة دفاعاً عن النبي ﷺ: واللهِ لن يصلوا إليك بجمعهم، حتى أُوسَّد في التراب دفيناً.",
      "حماية الحق قد تكون من غير مؤمن به؛ الروابط الإنسانية تُدعم المشروع الأكبر.",
      "physical_persecution", "kin_vs_kin", "physical_safety",
      "refusal_to_compromise", "solidarity_around_principle", "praise"),

    E("meccan_ibn_masud_quran_recitation", 84, -7, "meccan_middle",
      "ثناء النبي ﷺ على تلاوة ابن مسعود", "Prophet's praise of Ibn Mas'ud's recitation",
      "Mecca", ["96:1"],
      "قال النبي ﷺ: من أحبّ أن يقرأ القرآن غضاً كما أُنزل فليقرأه على قراءة ابن أم عبد (ابن مسعود).",
      "إتقان الرواية يحفظ النص عبر الأجيال؛ القارئ المتقن مرجع لمن جاء بعده.",
      "none", "teacher_vs_student", "knowledge_access",
      "witnessing_and_documentation", "knowledge_before_action", "praise"),

    E("meccan_saad_mother_hunger_strike", 85, -7, "meccan_middle",
      "أم سعد بن أبي وقاص تمتنع عن الطعام", "Sa'd ibn Abi Waqqas' mother hunger strike",
      "Mecca", ["29:8", "31:14", "31:15"],
      "امتنعت أم سعد بن أبي وقاص عن الطعام والشراب لترجعه عن الإسلام حتى كادت تموت، فقال سعد: لو كان لكِ مئة نفس فخرجت واحدة واحدة ما تركت ديني.",
      "ضغط الأم لا يُبرّر ترك الحق؛ بِرّ الوالدين له حدود عند الشرك بالله.",
      "family_pressure", "parent_vs_child", "family_integrity",
      "refusal_to_compromise", "truth_before_kinship", "legislation"),

    E("meccan_khabbab_dua_complaint", 86, -6, "meccan_middle",
      "شكوى خباب للنبي ﷺ من تأخر النصر", "Khabbab complains about the delay of victory",
      "Mecca", ["3:186", "29:2", "29:3"],
      "جاء خباب يشكو إلى النبي ﷺ وهو متوسد برده في ظل الكعبة شدة الأذى وتأخر النصر، فغضب النبي وذكر أن الأمم قبلهم كانت تُنشر بالمناشير.",
      "الدعاء في شدة الابتلاء مشروع لكنه لا يُعجّل القدر؛ صبر الأولين مرجع لصبر المتأخرين.",
      "psychological_pressure", "leader_vs_follower", "collective_survival",
      "consolation_and_thabaat", "divine_testing_mechanism", "rebuke"),

    E("meccan_polytheist_debate_resurrection", 87, -7, "meccan_middle",
      "محاجة المشركين في البعث بعظم بال", "Disputing resurrection with a decayed bone",
      "Mecca", ["36:77", "36:78", "36:79", "36:80", "36:81", "36:82", "36:83"],
      "أتى أبيّ بن خلف النبي ﷺ بعظم بالٍ يفتّه بيده ويقول: أيُحيي الله هذا بعد ما رمّ؟ فنزلت خواتيم يس تُقيم الحجة على البعث.",
      "الحجة القرآنية تُعيد البعث إلى القدرة الأولى على الخلق من لا شيء.",
      "intellectual_challenge", "principled_minority_vs_powerful_majority", "truth_vs_falsehood",
      "intellectual_rebuttal", "signs_require_reflection_not_proof", "argument"),

    E("meccan_walid_great_man_demand", 88, -7, "meccan_middle",
      "اعتراض الوليد: لولا نُزّل على رجل عظيم", "Al-Walid's objection: why not a great man",
      "Mecca", ["43:31", "43:32"],
      "قال الوليد: هلاّ نُزّل هذا القرآن على رجل عظيم من إحدى القريتين (مكة أو الطائف)، فردّ القرآن أهم يقسمون رحمة ربك.",
      "معيار الجاه البشري ليس معيار الاصطفاء الإلهي؛ الرسالة توزَّع بعلم أعلى من نظرة الناس.",
      "verbal_attack", "principled_minority_vs_powerful_majority", "truth_vs_falsehood",
      "intellectual_rebuttal", "truth_is_independent_of_carrier", "argument"),

    E("meccan_surah_yusuf_consolation", 89, -5, "meccan_middle",
      "نزول سورة يوسف تسلية للنبي ﷺ", "Surah Yusuf revealed as consolation",
      "Mecca", ["12:3", "12:7", "12:111"],
      "نزلت سورة يوسف في فترة شدة على النبي ﷺ، تحكي قصة الصبر من البئر إلى العرش في خمسة عشر فصلاً متدرجاً.",
      "السرد القرآني علاج نفسي للضغوط؛ القصة الكاملة أبلغ من النصيحة المجردة.",
      "psychological_pressure", "self_vs_self", "spiritual_integrity",
      "consolation_and_thabaat", "patience_under_collective_punishment", "story"),

    E("meccan_surah_kahf_trials", 90, -5, "meccan_middle",
      "نزول سورة الكهف وقصص الفتن الأربع", "Revelation of Surah al-Kahf with the four trials",
      "Mecca", ["18:1", "18:2", "18:3"],
      "نزلت سورة الكهف تعرض أربع قصص: فتنة الدين (الفتية)، وفتنة المال (صاحب الجنتين)، وفتنة العلم (موسى والخضر)، وفتنة السلطة (ذو القرنين).",
      "الفتن الأربع تشمل كل موضع ابتلاء إنساني؛ القرآن يُرتّب العلاج بترتيب المرض.",
      "intellectual_challenge", "self_vs_self", "spiritual_integrity",
      "teaching_through_demonstration", "divine_testing_mechanism", "story"),

    E("meccan_abu_jahl_curse_kabah", 91, -7, "meccan_middle",
      "أبو جهل يسب الله عند الكعبة", "Abu Jahl curses God at the Kaaba",
      "Mecca", ["26:217", "26:218"],
      "سمع النبي ﷺ أبا جهل يسبّ ربه جهاراً عند الكعبة، فسكت ولم يردّ عليه صبراً وحلماً.",
      "الصبر على سب الله للدواعي الأعلى من شجاعة الفرد؛ الرد قد يكون بالصمت حتى يحين وقته.",
      "verbal_attack", "individual_vs_majority", "religious_freedom",
      "silence_as_answer", "patience_under_collective_punishment", "consolation"),

    E("meccan_prophet_bearing_insults", 92, -7, "meccan_middle",
      "تحمّل النبي ﷺ لسب قريش من الأسماء", "Prophet's endurance of Quraysh nicknames",
      "Mecca", ["6:33", "15:94", "15:95", "15:96", "15:97"],
      "كان المشركون ينادون النبي ﷺ بأسماء مغيّرة كمذمّم بدل محمد، فيقول: ألا تعجبون كيف يصرف الله عني شتم قريش، يسبون مذمّماً وأنا محمد.",
      "الانشغال بالاسم الظاهري لا يغيّر الحقيقة الداخلية؛ الاستهزاء لا يضر المشتوم ما دام على الحق.",
      "verbal_attack", "individual_vs_majority", "reputation_honor",
      "endurance_without_retaliation", "consistency_public_and_private", "consolation"),

    E("meccan_muslim_women_early", 93, -9, "meccan_middle",
      "أول المؤمنات من النساء", "First women to accept Islam",
      "Mecca", ["33:35"],
      "أسلمت في أول الإسلام خديجة وأم الفضل وأسماء بنت أبي بكر ولبابة بنت الحارث، فكان للمرأة حضور مبكر في الرسالة.",
      "المرأة المؤمنة شريكة في بناء الأمة من أول لحظة؛ الدعوة لا تستثني نصف المجتمع.",
      "none", "community_vs_outsider", "community_cohesion",
      "solidarity_around_principle", "collective_obligation_above_personal", "praise"),

    E("meccan_second_habasha_migration", 94, -7, "meccan_middle",
      "الهجرة الثانية الأوسع إلى الحبشة", "Second and larger migration to Abyssinia",
      "Mecca", ["16:41", "39:10"],
      "هاجرت إلى الحبشة الهجرة الثانية 83 رجلاً و18 امرأة بعد اشتداد الأذى في مكة، وبقوا هناك سنوات حتى بعد الهجرة إلى المدينة.",
      "الهجرة خيار طويل الأمد ليس نزوة آنية؛ الأرض واسعة لمن اضطره الواقع.",
      "physical_persecution", "principled_minority_vs_powerful_majority", "religious_freedom",
      "strategic_withdrawal", "chosen_hardship_over_compromise", "command"),

    E("meccan_umm_habiba_husband_apostasy", 95, -6, "meccan_middle",
      "ارتداد زوج أم حبيبة في الحبشة", "Apostasy of Umm Habiba's husband in Abyssinia",
      "Mecca", ["60:10"],
      "ارتدّ عبيد الله بن جحش زوج أم حبيبة رضي الله عنها إلى النصرانية في الحبشة، فثبتت أم حبيبة على الإسلام وانفصلت عنه.",
      "ثبات الفرد على المبدأ قد يستلزم قطع أعزّ العلاقات؛ الزواج لا يُشترى بالإيمان.",
      "internal_betrayal", "spouse_vs_spouse", "spiritual_integrity",
      "refusal_to_compromise", "truth_before_kinship", "praise"),

    E("meccan_ibn_umm_maktum_blind", 96, -6, "meccan_middle",
      "عبس وتولى لما جاءه الأعمى", "He frowned when the blind man came",
      "Mecca", ["80:1", "80:2", "80:3", "80:4", "80:5", "80:6", "80:7", "80:8", "80:9", "80:10", "80:11", "80:12"],
      "كان النبي ﷺ يعرض الإسلام على صناديد قريش، فجاء ابن أم مكتوم الأعمى يسأل يتعلم، فأعرض النبي عنه مشغولاً، فنزل عتاب شديد.",
      "الأولوية القرآنية للطالب الصادق لا للمستهدف الاستراتيجي؛ القيمة في القلب لا في المنصب.",
      "social_exclusion", "principled_minority_vs_powerful_majority", "knowledge_access",
      "moral_rebuke", "protection_of_the_weak", "rebuke"),

    E("meccan_ubayy_bone_debate", 97, -6, "meccan_middle",
      "أُبَيّ بن خلف يُماحك في البعث", "Ubayy ibn Khalaf disputes resurrection",
      "Mecca", ["36:78", "36:79"],
      "جاء أُبيّ بن خلف إلى النبي ﷺ بعظم رميم يفتّه ويقول: أيبعث الله هذا؟ فنزل قل يُحييها الذي أنشأها أول مرة.",
      "استبعاد القدرة استغراب يسير؛ الذي بدأ الخلق من لا شيء قادر على الإعادة من شيء.",
      "intellectual_challenge", "individual_vs_majority", "truth_vs_falsehood",
      "intellectual_rebuttal", "signs_require_reflection_not_proof", "argument"),

    E("meccan_abu_lahab_call_sons_divorce", 98, -7, "meccan_middle",
      "أبو لهب يأمر ابنيه بطلاق بنتَي النبي ﷺ", "Abu Lahab orders his sons to divorce the Prophet's daughters",
      "Mecca", ["33:37"],
      "كان عتبة وعتيبة ابنا أبي لهب متزوجين من رقية وأم كلثوم بنات النبي ﷺ قبل البعثة، فأمرهما أبوهما بتطليقهما كرهاً في دعوة النبي.",
      "اضطهاد خصوم الحق يصل إلى تفكيك البيوت؛ الضغط الاجتماعي سلاح لا يقل عن السياط.",
      "family_pressure", "parent_vs_child", "family_integrity",
      "endurance_without_retaliation", "truth_before_kinship", "rebuke"),

    E("meccan_dirty_uterus_thrown", 99, -6, "meccan_middle",
      "إلقاء القاذورات عند باب النبي ﷺ", "Filth thrown at the Prophet's door",
      "Mecca", ["6:34", "68:48"],
      "كان بعض المشركين يُلقون الأقذار والنتن عند باب النبي ﷺ، فكان يخرج ويُنحّيه بقطعة من عود قائلاً: يا بني عبد مناف، أيّ جوار هذا؟",
      "الإهانة اليومية الصغيرة أشق من الضربة الكبيرة؛ التحمل المستمر يحتاج إلى حلم طويل.",
      "verbal_attack", "individual_vs_majority", "personal_dignity",
      "endurance_without_retaliation", "patience_under_collective_punishment", "consolation"),

    E("meccan_quraysh_divide_gates_mecca", 100, -5, "meccan_middle",
      "اقتسام قريش أبواب مكة لصد العرب", "Quraysh divides Mecca's entrances to block outsiders from hearing",
      "Mecca", ["16:125"],
      "اقتسمت قريش أبواب مكة في موسم الحج يُحذّرون الوافدين من سماع النبي ﷺ زاعمين أنه ساحر مجنون.",
      "محاولة عزل الحق عن الجمهور سلاح قديم؛ التعتيم الإعلامي لا يصمد طويلاً.",
      "verbal_attack", "principled_minority_vs_powerful_majority", "knowledge_access",
      "public_declaration", "refusing_to_legitimize_falsehood", "warning"),

    # Fleshing out to order 150 with late Meccan events
    E("meccan_tufayl_concert_quran", 101, -5, "meccan_middle",
      "الطفيل الشاعر يسمع القرآن بصدفة", "Tufayl the poet overhears the Quran by chance",
      "Mecca", ["16:125"],
      "وضع الطفيل القطن في أذنيه حذراً من سحر القرآن، ثم قال في نفسه: إنما أنا شاعر أدرك الحسن من القبيح، فسمع فأسلم.",
      "الانفتاح العقلي على المجهول طريق للهدى؛ الصد المصطنع عن الحق يُنقضه أول مراجعة صادقة.",
      "verbal_attack", "community_vs_outsider", "truth_vs_falsehood",
      "confrontation_with_truth", "knowledge_before_action", "praise"),

    E("meccan_daws_tribe_prayer", 102, -5, "meccan_middle",
      "دعاء النبي ﷺ لدوس بعد الطفيل", "Prophet's supplication for Daws after Tufayl",
      "Mecca", ["7:128"],
      "طلب الطفيل من النبي ﷺ أن يدعو على قومه دوس لتصلّبهم، فرفع النبي يديه وقال: اللهم اهدِ دوساً وأتِ بهم.",
      "الدعاء للقوم بالهداية أحبّ من الدعاء عليهم؛ الرحمة خيار القائد حتى مع الخصم.",
      "social_exclusion", "community_vs_outsider", "religious_freedom",
      "forgiveness_from_power", "mercy_as_strategic_choice", "praise"),

    E("meccan_suraqa_chase_later", 103, -1, "meccan_late",
      "سراقة بن مالك يتعقّب النبي ﷺ في الهجرة", "Suraqa ibn Malik pursues the Prophet during Hijrah",
      "Between Mecca and Medina", ["9:40"],
      "أخبر سراقة عن مكان النبي ﷺ وأبي بكر طمعاً في جائزة قريش، فخرج يتعقبهما، فساخت قوائم فرسه ثلاث مرات حتى استأمن وطلب كتاب أمان.",
      "مطاردة الحق تنقلب على المطارد؛ الخصم اليوم قد يكون حليفاً غداً.",
      "physical_persecution", "individual_vs_majority", "physical_safety",
      "refuge_with_god_against_despair", "divine_testing_mechanism", "story"),

    E("meccan_ghar_thawr", 104, -1, "meccan_late",
      "المبيت في غار ثور", "Taking refuge in cave Thawr",
      "Mecca area", ["9:40"],
      "اختبأ النبي ﷺ وأبو بكر في غار ثور ثلاث ليال، وجاءت قريش حتى وصلت إلى فم الغار، فقال أبو بكر: لو نظر أحدهم إلى قدميه لأبصرنا، فقال النبي: ما ظنك باثنين الله ثالثهما.",
      "المعية الإلهية أعظم حصن؛ الأسباب الضعيفة تُنجز ما لا تُنجزه الجيوش حين يشاء الله.",
      "existential_threat", "principled_minority_vs_powerful_majority", "physical_safety",
      "refuge_with_god_against_despair", "refuge_with_god_against_despair", "consolation"),

    E("meccan_ali_prophet_bed", 105, -1, "meccan_late",
      "علي ينام في فراش النبي ﷺ ليلة الهجرة", "Ali sleeps in the Prophet's bed on the night of Hijrah",
      "Mecca", ["2:207"],
      "أمر النبي ﷺ علياً أن يبيت في فراشه ويتسجّى ببرده ليُخيّل للمحاصرين أنه النبي، فنام علي وفدى نفسه بأخيه.",
      "الفداء بالنفس معيار الولاء الحقيقي؛ من بذل ذاته للمبدأ لا يخاف شيئاً بعدها.",
      "existential_threat", "leader_vs_follower", "physical_safety",
      "refusal_to_compromise", "solidarity_around_principle", "praise"),

    E("meccan_dar_alnadwa_plot", 106, -1, "meccan_late",
      "اجتماع دار الندوة لقتل النبي ﷺ", "Dar al-Nadwa meeting plotting the Prophet's death",
      "Mecca", ["8:30"],
      "اجتمعت قريش في دار الندوة وحضرهم إبليس متشبّهاً بشيخ من نجد، واتفقوا على أن يأخذوا من كل قبيلة شاباً فيضربوه ضربة رجل واحد ليتفرّق دمه.",
      "تخطيط الباطل يستند إلى الحيلة لا إلى الحق؛ الله يُفشل المكر مهما اجتمع عليه الخصماء.",
      "existential_threat", "principled_minority_vs_powerful_majority", "physical_safety",
      "strategic_withdrawal", "refusing_to_legitimize_falsehood", "warning"),

    E("meccan_hijra_news_quran", 107, -1, "meccan_late",
      "نزول قوله تعالى وإذ يمكر بك الذين كفروا", "Revelation about the plot",
      "Mecca", ["8:30"],
      "نزل على النبي ﷺ قوله تعالى وإذ يمكر بك الذين كفروا ليُثبتوك أو يقتلوك أو يُخرجوك ويمكرون ويمكر الله والله خير الماكرين.",
      "الوحي يسبق الحركة؛ علم النبي بالخطة أعلى من خطة الخصوم.",
      "existential_threat", "principled_minority_vs_powerful_majority", "physical_safety",
      "refuge_with_god_against_despair", "refusing_to_legitimize_falsehood", "warning"),

    E("meccan_hijra_departure", 108, -1, "meccan_late",
      "خروج النبي ﷺ من بيته ليلة الهجرة", "Prophet leaves his house on the night of migration",
      "Mecca", ["36:9"],
      "خرج النبي ﷺ من بين المحاصرين وهو يقرأ أول سورة يس، ويذرّ التراب على رؤوسهم، وقد طُمست أبصارهم حتى لم يروه.",
      "العناية الإلهية تغيّب الحق عن أعين المتربّصين؛ المحاصِر قد يُحاصَر بغير شعوره.",
      "existential_threat", "principled_minority_vs_powerful_majority", "physical_safety",
      "refuge_with_god_against_despair", "refuge_with_god_against_despair", "story"),

    E("meccan_hijra_abu_bakr_companion", 109, -1, "meccan_late",
      "اختيار أبي بكر صاحباً في الهجرة", "Abu Bakr chosen as companion for Hijrah",
      "Mecca", ["9:40"],
      "اختار النبي ﷺ أبا بكر صاحباً في الهجرة دون غيره، وكان أبو بكر قد هيّأ راحلتين قبل ذلك، فبكى فرحاً لما أخبره النبي.",
      "اختيار الرفيق في الشدة من أدق القرارات؛ الصاحب في الخطر هو الصاحب الحقيقي.",
      "existential_threat", "ally_vs_ally_dispute", "trust_between_parties",
      "seeking_allies", "trust_is_earned_by_consistency", "praise"),

    E("meccan_arrival_quba", 110, 1, "meccan_late",
      "وصول النبي ﷺ إلى قباء", "Prophet arrives at Quba",
      "Medina", ["9:108"],
      "وصل النبي ﷺ إلى قباء فاستقبله الأنصار بالفرح والسرور، وأقام فيها بضع عشرة ليلة يبني مسجد قباء على التقوى من أول يوم.",
      "بداية التمكين تبدأ بمسجد؛ الرمز الأول للجماعة الجديدة مكان عبادتها.",
      "none", "community_vs_outsider", "community_cohesion",
      "organizational_response", "solidarity_around_principle", "praise"),

    # ═══════════════ MECCAN LATE (order 111-150) ═══════════════

    E("meccan_quba_masjid", 111, 1, "meccan_late",
      "بناء مسجد قباء", "Building of Quba mosque",
      "Quba", ["9:108"],
      "بنى النبي ﷺ مسجد قباء بيديه مع أصحابه، وهو أول مسجد أسس على التقوى في الإسلام.",
      "القائد يشارك في بناء البنية التحتية بيده؛ القدوة العملية أبلغ من الأمر.",
      "none", "ally_vs_ally_dispute", "community_cohesion",
      "teaching_through_demonstration", "leadership_accountability", "praise"),

    E("meccan_first_friday_prayer", 112, 1, "meccan_late",
      "أول صلاة جمعة في بني سالم", "First Friday prayer in Bani Salim",
      "Wadi Ranuna", ["62:9"],
      "صلى النبي ﷺ أول جمعة في بطن الوادي في بني سالم بن عوف وهو في طريقه إلى المدينة، وخطب خطبة الجمعة الأولى.",
      "التجمع الأسبوعي شعيرة تؤسس الهوية الجماعية؛ البداية في الطريق لا تنتظر الاستقرار.",
      "none", "community_vs_outsider", "community_cohesion",
      "legal_innovation", "solidarity_around_principle", "legislation"),

    E("meccan_entry_medina", 113, 1, "meccan_late",
      "دخول النبي ﷺ المدينة", "Prophet enters Medina",
      "Medina", ["9:100"],
      "دخل النبي ﷺ المدينة فاستقبله الأنصار ينشدون طلع البدر علينا من ثنيات الوداع، فجعل يسير على ناقته ويقول: دعوها فإنها مأمورة.",
      "دخول القائد بالوفاء مع ناقته يؤسس لمبدأ القرار بالحكمة لا بالميل؛ التنازع على الشرف يُحلّ بحكم خارج عنه.",
      "none", "community_vs_outsider", "community_cohesion",
      "consultation_before_decision", "dispute_resolution_by_neutral", "praise"),

    # ═══════════════ Additional Meccan filler to reach ~150 ═══════════════

    E("meccan_quraysh_taunt_prophet_family", 114, -7, "meccan_middle",
      "سخرية قريش من فقر أتباع النبي ﷺ", "Quraysh mocking the poverty of the Prophet's followers",
      "Mecca", ["46:11"],
      "قالت قريش: انظروا إلى هؤلاء الضعفاء الذين اتّبعوا محمداً، لو كان حقاً ما سبقنا إليه هؤلاء.",
      "الاستدلال على الحق بوضع الأتباع الاجتماعي خطأ منهجي؛ الحق لا يُقاس بطبقة من يقبله.",
      "verbal_attack", "principled_minority_vs_powerful_majority", "reputation_honor",
      "intellectual_rebuttal", "protection_of_the_weak", "rebuke"),

    E("meccan_bayt_ammar_muadhdhab", 115, -9, "meccan_middle",
      "تعذيب آل ياسر جماعة واحدة", "Torture of the Yasir family as a group",
      "Mecca", ["11:42", "85:4", "85:5", "85:6", "85:7"],
      "عذّب أبو جهل آل ياسر جميعاً في البطحاء، فقال النبي ﷺ مراراً وهو لا يستطيع نصرهم: صبراً آل ياسر، فإن موعدكم الجنة.",
      "تثبيت القادة للضعفاء في لحظة العجز دعم معنوي لا يقل عن المادي؛ الوعد بالآخرة يُهوّن الأذى.",
      "physical_persecution", "principled_minority_vs_powerful_majority", "physical_safety",
      "consolation_and_thabaat", "patience_under_collective_punishment", "consolation"),

    E("meccan_umayya_blackens_bilal", 116, -10, "meccan_early",
      "أمية بن خلف يستعين بصبيان مكة لضرب بلال", "Umayya uses Mecca's boys to beat Bilal",
      "Mecca", ["85:8"],
      "كان أمية بن خلف يُسلّم بلالاً لصبيان مكة يلعبون به ويجرونه في شعاب مكة وحبل في عنقه.",
      "إهانة الكبير بيد الصغار ذروة التحقير؛ المؤمن يتجاوز بالصبر ما يُعجز القوي.",
      "physical_persecution", "principled_minority_vs_powerful_majority", "personal_dignity",
      "endurance_without_retaliation", "patience_under_collective_punishment", "consolation"),

    E("meccan_ali_young_declaration", 117, -13, "meccan_early",
      "إعلان علي الصغير نصرة النبي ﷺ", "Young Ali declares support for the Prophet",
      "Mecca", ["26:214"],
      "جمع النبي ﷺ أقاربه بعد أمره بالإنذار فعرض عليهم الإسلام، فقام علي (وهو غلام) قائلاً: أنا يا رسول الله، فقال النبي: اجلس. ثم أعاد، حتى قال في الثالثة أنا.",
      "الصغر سنّاً لا يمنع كبر الهمة؛ الحماس المبكر قد يسبق النضج الاجتماعي.",
      "none", "kin_vs_kin", "community_cohesion",
      "confrontation_with_truth", "truth_is_independent_of_carrier", "praise"),

    E("meccan_quraysh_banu_manaf_scorn", 118, -10, "meccan_early",
      "استهزاء بني عبد مناف بالدعوة بعد الصفا", "Bani Abd Manaf mocking the call after Safa",
      "Mecca", ["15:6"],
      "لما دعا النبي ﷺ قريشاً على الصفا سخروا منه وقالوا: يا محمد إنك لمجنون، ثم تركوه يخطب.",
      "السخرية وسيلة إبطال رخيصة حين تعجز الحجة؛ الضحك لا يلغي الحق.",
      "verbal_attack", "individual_vs_majority", "truth_vs_falsehood",
      "intellectual_rebuttal", "warning_against_arrogance", "rebuke"),

    E("meccan_prophet_dua_two_umar", 119, -9, "meccan_middle",
      "دعاء النبي ﷺ لأحد العمرين", "Prophet prays for one of the two Umars",
      "Mecca", ["39:33"],
      "دعا النبي ﷺ فقال: اللهم أعزّ الإسلام بأحب الرجلين إليك: بعمر بن الخطاب أو بعمرو بن هشام (أبي جهل)، فكان عمر.",
      "الدعاء للهداية قد يشمل الخصم الأكبر؛ العودة إلى الحق ممكنة من أبعد النقاط.",
      "none", "individual_vs_majority", "community_cohesion",
      "seeking_allies", "repentance_as_open_door", "promise"),

    E("meccan_abu_bakr_beaten_kabah", 120, -9, "meccan_middle",
      "ضرب أبي بكر عند الكعبة", "Abu Bakr beaten at the Kaaba",
      "Mecca", ["39:33"],
      "قام أبو بكر يدعو عند الكعبة فضربه عتبة بن ربيعة ضرباً شديداً حتى أُغمي عليه ولم يستيقظ إلا في آخر النهار، فكان أول ما سأل عنه: ما فعل رسول الله؟",
      "همّ القائد قبل الذات حتى في أشد اللحظات؛ الألم الجسدي يُنسى عند السؤال عن المقصد الأعلى.",
      "physical_persecution", "principled_minority_vs_powerful_majority", "physical_safety",
      "endurance_without_retaliation", "solidarity_around_principle", "praise"),

    E("meccan_suhayb_pays_wealth", 121, -1, "meccan_late",
      "صهيب يدفع ماله ثمناً للحرية في الهجرة", "Suhayb pays his wealth to be allowed to migrate",
      "Mecca", ["2:207"],
      "لما أراد صهيب الرومي الهجرة اعترضته قريش قائلين: جئتنا فقيراً واكتسبت عندنا، لا نتركك حتى تتركه، فدلّهم على كل ماله ومضى، فقال النبي ﷺ: ربح البيع يا أبا يحيى.",
      "الخسارة الماديّة في سبيل الحق ربح حقيقي؛ المال وسيلة لا غاية.",
      "economic_siege", "principled_minority_vs_powerful_majority", "livelihood",
      "strategic_withdrawal", "wealth_as_trust_not_ownership", "praise"),

    E("meccan_umar_public_hijra", 122, -1, "meccan_late",
      "هجرة عمر علناً معلناً", "Umar migrates publicly and openly",
      "Mecca", ["9:40"],
      "خرج عمر بن الخطاب للهجرة متقلّداً سيفه معلناً، وطاف بالكعبة سبعاً وصلى ركعتين ثم قال: من أراد أن تثكله أمه ويُيتّم ولده فليلقني وراء هذا الوادي.",
      "الشجاعة السياسية في إعلان المواقف تُرهب الخصوم؛ الإعلان قوة والسر ضعف في وقته.",
      "physical_persecution", "individual_vs_majority", "physical_safety",
      "public_declaration", "chosen_hardship_over_compromise", "praise"),

    E("meccan_quraysh_jewelry_plot", 123, -1, "meccan_late",
      "حلية قريش على رأس من يأتي بالنبي ﷺ", "Quraysh's bounty on the Prophet's head",
      "Mecca", ["8:30"],
      "رصدت قريش مئة ناقة لمن يأتي بالنبي ﷺ أو بأبي بكر حياً أو ميتاً بعد اكتشافهم للهجرة.",
      "السعي لمال الحرام دافع قوي للناس؛ الإغراء المادي أفتك من الجيوش في صدّ بعض النفوس.",
      "moral_temptation", "principled_minority_vs_powerful_majority", "physical_safety",
      "strategic_withdrawal", "refusing_to_legitimize_falsehood", "warning"),

    E("meccan_asma_twin_belts", 124, -1, "meccan_late",
      "أسماء ذات النطاقين", "Asma of the Two Belts",
      "Mecca", ["93:4"],
      "شقّت أسماء بنت أبي بكر نطاقها إلى نصفين لتربط طعام النبي ﷺ وأبيها في الغار، فسُمّيت ذات النطاقين.",
      "المرأة المؤمنة تبذل عند الحاجة جزءاً من ثوبها للمهمة؛ الدعم اللوجستي للمبادئ دور جليل.",
      "existential_threat", "family_pressure", "community_cohesion",
      "solidarity_around_principle", "solidarity_around_principle", "praise"),

    E("meccan_abu_quhafa_fear", 125, -1, "meccan_late",
      "أبو قحافة الأعمى يقلق على أبي بكر", "Abu Quhafa the blind worries about Abu Bakr",
      "Mecca", ["2:207"],
      "جاء أبو قحافة (أبو أبي بكر) الأعمى يقول: والله لا أظن أبا بكر ترك لكم شيئاً، فأخذت أسماء حصى فوضعته في الكوّة وقالت: هذا ترك لنا.",
      "الكذب لتطييب خاطر كبير السن جائز حين لا يترتب عليه ضرر؛ الكفالة النفسية للمسن عبادة.",
      "family_pressure", "parent_vs_child", "family_integrity",
      "private_counsel", "protection_of_the_weak", "praise"),

    E("meccan_medina_waiting_crowd", 126, 1, "meccan_late",
      "استقبال أهل المدينة للنبي ﷺ في كل يوم", "Medina residents waiting daily for the Prophet",
      "Medina", ["9:108"],
      "كان أهل المدينة يخرجون كل يوم إلى الحرّة ينتظرون قدوم النبي ﷺ، حتى إذا اشتد الحر رجعوا، حتى جاء في يوم لم يخرجوا فيه.",
      "الشوق إلى الحق طبع المؤمن؛ الانتظار في ذاته عبادة قبل التحقق.",
      "none", "community_vs_outsider", "community_cohesion",
      "consolation_and_thabaat", "solidarity_around_principle", "praise"),

    E("meccan_prophet_names_medina", 127, 1, "meccan_late",
      "تسمية يثرب بالمدينة", "Renaming Yathrib to 'al-Madina'",
      "Medina", ["33:13"],
      "غيّر النبي ﷺ اسم يثرب إلى المدينة (أي مدينة الرسول)، وفي رواية إلى طيبة لتنفّر من الاسم الجاهلي السابق.",
      "تغيير الأسماء جزء من تغيير الثقافة؛ الرمز اللغوي يحمل حمولته التاريخية.",
      "none", "community_vs_outsider", "community_cohesion",
      "legal_innovation", "teaching_through_demonstration", "legislation"),

    E("meccan_camel_quswa_stops", 128, 1, "meccan_late",
      "توقف ناقة النبي ﷺ في موضع المسجد", "The camel stops at the site of the mosque",
      "Medina", ["9:108"],
      "أطلق النبي ﷺ ناقته القصواء فمشت حتى بركت في موضع مسجد المدينة، فاشترى الأرض من غلامين يتيمين وبنى المسجد.",
      "القرار في المواضع المتنازع عليها يُحسَم بطريقة محايدة؛ شراء الأرض من اليتيمين أدب مع حقوقهم.",
      "none", "community_vs_outsider", "property_rights",
      "dispute_resolution_by_neutral", "protection_of_the_weak", "legislation"),

    E("meccan_anas_house_host", 129, 1, "meccan_late",
      "نزول النبي ﷺ عند أبي أيوب الأنصاري", "Prophet stays at Abu Ayyub al-Ansari's home",
      "Medina", ["59:9"],
      "نزل النبي ﷺ عند أبي أيوب الأنصاري، وفضّل السكن في الطابق الأسفل ليسهل على زوّاره، ثم انتقل إلى العلو إكراماً لأبي أيوب.",
      "القائد يسكن بين الناس لا فوقهم؛ مراعاة صاحب البيت فن من فنون القيادة.",
      "none", "community_vs_outsider", "trust_between_parties",
      "private_counsel", "leadership_accountability", "praise"),

    E("meccan_first_adhan_vision", 130, 1, "meccan_late",
      "رؤية عبد الله بن زيد للأذان", "Abdullah ibn Zayd's vision of the call to prayer",
      "Medina", ["62:9"],
      "رأى عبد الله بن زيد في منامه رجلاً يعلّمه كلمات الأذان، فجاء إلى النبي ﷺ فصدّق رؤياه وأمر بلالاً أن يؤذّن بها.",
      "الرؤيا الصالحة مصدر إرشاد ثانوي؛ العمل بالرؤيا مشروط بموافقة الشريعة.",
      "none", "teacher_vs_student", "community_cohesion",
      "consultation_before_decision", "legitimacy_follows_method", "legislation"),

    E("meccan_bilal_first_muezzin", 131, 1, "meccan_late",
      "اختيار بلال أول مؤذن", "Bilal chosen as the first muezzin",
      "Medina", ["62:9"],
      "اختار النبي ﷺ بلالاً ليكون أول مؤذن في الإسلام لقوة صوته وسابقته في الإيمان، فكان العبد المعذب أمس صوت الأمة اليوم.",
      "الإسلام يرفع الضعيف بالمبدأ لا بالنسب؛ المنصب يذهب إلى من كان له سابقة في الصدق.",
      "none", "leader_vs_follower", "community_cohesion",
      "legal_innovation", "protection_of_the_weak", "praise"),

    E("meccan_prophet_home_build", 132, 1, "meccan_late",
      "بناء بيت النبي ﷺ بجوار المسجد", "Building the Prophet's house next to the mosque",
      "Medina", ["33:33"],
      "بنى النبي ﷺ بيوته الزوجية ملاصقة للمسجد النبوي بطين وسعف نخل، وكان البيت بسيطاً لا يزيد عن الحاجة.",
      "زهد القائد في المسكن قدوة للأمة؛ البناء الجليل لا يعني البناء الفاخر.",
      "none", "self_vs_self", "personal_dignity",
      "teaching_through_demonstration", "leadership_accountability", "praise"),

    E("meccan_first_medina_census", 133, 1, "meccan_late",
      "أول إحصاء للمسلمين في المدينة", "First census of Muslims in Medina",
      "Medina", ["4:75"],
      "أمر النبي ﷺ بإحصاء من يلفظ بالإسلام من المدينة بعد قدومه، فبلغوا ألفاً وخمسمئة تقريباً.",
      "المعرفة بأحوال الجماعة قبل تدبير أمرها؛ لا إدارة بلا بيانات.",
      "none", "leader_vs_follower", "community_cohesion",
      "witnessing_and_documentation", "knowledge_before_action", "command"),

    E("meccan_muakhat_brotherhood_initial", 134, 1, "meccan_late",
      "إرساء نظام المؤاخاة بين المهاجرين والأنصار", "Institutional brotherhood between Muhajirun and Ansar",
      "Medina", ["59:9", "8:72"],
      "آخى النبي ﷺ بين كل مهاجر وأنصاري في عقد أخوة كامل يشمل التوارث في أول الأمر، فحلّ مشكلة استيعاب المهاجرين دفعة واحدة.",
      "المؤسسات الاجتماعية تُنشأ بقرار قيادي إذا بُنيت على مبدأ مشترك؛ البدء يحتاج إلى هندسة اجتماعية.",
      "none", "community_vs_outsider", "community_cohesion",
      "organizational_response", "solidarity_around_principle", "legislation"),

    E("meccan_sahifa_medina", 135, 1, "meccan_late",
      "كتابة صحيفة المدينة", "Drafting the Medina charter",
      "Medina", ["3:64"],
      "كتب النبي ﷺ صحيفة المدينة دستوراً ينظّم العلاقة بين المسلمين واليهود والمشركين، ويُحدّد حقوق كل طرف وواجباته.",
      "الدستور المكتوب يسبق النزاعات؛ تعدد الأطراف في الوطن يحتاج إلى قاعدة مشتركة.",
      "political_pressure", "community_vs_outsider", "trust_between_parties",
      "legal_innovation", "dispute_resolution_by_neutral", "legislation"),

    E("meccan_qibla_bayt_maqdis", 136, 1, "meccan_late",
      "صلاة النبي ﷺ إلى بيت المقدس في المدينة", "Praying toward Jerusalem in Medina",
      "Medina", ["2:144"],
      "ظل النبي ﷺ يصلي إلى بيت المقدس بعد قدومه المدينة نحو ستة عشر أو سبعة عشر شهراً، وكان يحب أن يُوجَّه إلى الكعبة.",
      "الانتظار على حكم قائم حتى يأتي التغيير؛ الطاعة لا تتعجل الحكم الجديد.",
      "none", "self_vs_self", "religious_freedom",
      "endurance_without_retaliation", "limits_of_personal_discretion", "command"),

    E("meccan_fatima_zahra_married", 137, 1, "meccan_late",
      "زواج فاطمة من علي بمهر يسير", "Marriage of Fatima to Ali with a simple dowry",
      "Medina", ["25:54"],
      "زوّج النبي ﷺ ابنته فاطمة من علي بن أبي طالب بدرع كان لعلي ثمنها أربعمئة درهم، وكان زواجاً متواضعاً رغم المكانة.",
      "البساطة في الأعراس قدوة؛ المهر الخفيف يسبق الحياة السعيدة عادة.",
      "none", "kin_vs_kin", "family_integrity",
      "teaching_through_demonstration", "leadership_accountability", "praise"),

    E("meccan_early_legislation_prayer", 138, 1, "meccan_late",
      "تقرير خمس صلوات يومية في المدينة", "Implementation of five daily prayers in Medina",
      "Medina", ["20:14"],
      "استقرّت الصلوات الخمس اليومية في المدينة وأصبحت هي العلامة الأولى على انتماء الفرد إلى الجماعة الجديدة.",
      "الشعائر اليومية المتكررة تُشكّل الهوية؛ الانتظام ينتج الولاء.",
      "none", "community_vs_outsider", "spiritual_integrity",
      "organizational_response", "consistency_public_and_private", "legislation"),

    E("meccan_first_visitor_delegation", 139, 1, "meccan_late",
      "أول وفد زائر للمدينة", "First delegation visiting Medina",
      "Medina", ["16:125"],
      "جاء أول وفد من قبائل العرب يسأل عن الرسالة الجديدة في المدينة قبل أن تبدأ المواجهات العسكرية.",
      "الانفتاح المبكر على الأطراف يؤسس للعلاقات قبل الصراع؛ الدبلوماسية سابقة على الحرب.",
      "none", "community_vs_outsider", "trust_between_parties",
      "seeking_allies", "distinguishing_enemy_from_outsider", "command"),

    E("meccan_early_mosque_school", 140, 1, "meccan_late",
      "تخصيص الصفّة لطلاب العلم الفقراء", "Dedicating al-Suffa for poor students of knowledge",
      "Medina", ["18:28"],
      "خصّص النبي ﷺ مكاناً في مؤخرة المسجد النبوي يُسمى الصُفّة لطلاب العلم الفقراء الذين لا بيت لهم ولا عمل، يُطعمهم المسلمون ويُعلّمهم النبي.",
      "المأوى للطالب الفقير جزء من البناء التعليمي؛ العلم لا يُقصر على من يملك.",
      "none", "community_vs_outsider", "knowledge_access",
      "organizational_response", "protection_of_the_weak", "praise"),

    E("meccan_first_sariya_hamza", 141, 1, "meccan_late",
      "أول سرية بقيادة حمزة بن عبد المطلب", "First expedition led by Hamza",
      "Medina area", ["22:39"],
      "بعث النبي ﷺ أول سرية بقيادة حمزة بن عبد المطلب في ثلاثين من المهاجرين إلى ساحل البحر لاعتراض قافلة قريش.",
      "الإذن بالقتال بعد سنين من الصبر؛ الانتقال من الدفاع إلى الردع.",
      "political_pressure", "community_vs_outsider", "collective_survival",
      "active_resistance", "collective_obligation_above_personal", "command"),

    E("meccan_sariya_ubayda_rabigh", 142, 1, "meccan_late",
      "سرية عبيدة بن الحارث", "Expedition of Ubayda ibn al-Harith",
      "Medina area", ["22:39"],
      "بعث النبي ﷺ عبيدة بن الحارث في سرية إلى بطن رابغ، وكانت هذه أول مواجهة رمي فيها سعد بن أبي وقاص أول سهم في الإسلام.",
      "التاريخ يسجّل الأول في كل عمل؛ أول سهم شهادة على المرحلة الانتقالية.",
      "political_pressure", "community_vs_outsider", "collective_survival",
      "active_resistance", "witnessing_and_documentation", "command"),

    E("meccan_sariya_saad_kharar", 143, 1, "meccan_late",
      "سرية سعد بن أبي وقاص إلى الخرار", "Sa'd ibn Abi Waqqas expedition to al-Kharrar",
      "Medina area", ["22:39"],
      "بعث النبي ﷺ سعد بن أبي وقاص في ثمانية من المهاجرين إلى الخرار، فرجعوا دون قتال بعد أن فاتتهم القافلة.",
      "النتيجة ليست شرط التقدير؛ الخروج في المهمة أجر ولو لم تُحقّق الغاية.",
      "political_pressure", "community_vs_outsider", "collective_survival",
      "active_resistance", "intention_determines_value", "command"),

    E("meccan_ghazwa_abwa_waddan", 144, 2, "meccan_late",
      "غزوة الأبواء (ودّان)", "Ghazwa of al-Abwa' (Waddan)",
      "Al-Abwa", ["22:39"],
      "خرج النبي ﷺ في أول غزوة يقودها بنفسه إلى الأبواء لاعتراض قافلة قريش، ولم يلق قتالاً، لكنه وادع بني ضمرة.",
      "المعاهدات تسبق المواجهة عند الإمكان؛ القوة الدبلوماسية أكبر من السيف في لحظتها.",
      "political_pressure", "community_vs_outsider", "trust_between_parties",
      "compromise_for_larger_goal", "dispute_resolution_by_neutral", "legislation"),

    E("meccan_ghazwa_buwat", 145, 2, "meccan_late",
      "غزوة بُواط", "Ghazwa of Buwat",
      "Buwat", ["22:39"],
      "خرج النبي ﷺ في مئتين من أصحابه إلى بواط لاعتراض عير لقريش، فلم يلقَ كيداً ورجع.",
      "المهمات التي لا تحقق نصراً ظاهراً تبني الخبرة؛ كل خروج إعداد لما بعده.",
      "political_pressure", "community_vs_outsider", "collective_survival",
      "active_resistance", "knowledge_before_action", "command"),

    E("meccan_ghazwa_safwan", 146, 2, "meccan_late",
      "غزوة بدر الأولى (سفوان)", "Ghazwa of Safwan (First Badr)",
      "Safwan", ["22:39"],
      "خرج النبي ﷺ في طلب كرز بن جابر الفهري بعدما أغار على سرح المدينة، فبلغ سفوان ولم يُدركه.",
      "الرد الفوري على العدوان شرط الردع؛ حتى لو لم تدرك الخصم تعرف أنك تُراقبه.",
      "political_pressure", "community_vs_outsider", "collective_survival",
      "active_resistance", "accountability_proportional_to_power", "command"),

    E("meccan_ghazwa_ushayra", 147, 2, "meccan_late",
      "غزوة ذات العشيرة", "Ghazwa of Dhat al-Ushayra",
      "Dhat al-Ushayra", ["22:39"],
      "خرج النبي ﷺ إلى ذات العشيرة لاعتراض قافلة لقريش ذاهبة إلى الشام، ففاتته وعقد موادعة مع بني مدلج وحلفائهم.",
      "الحركة تفتح أبواباً غير متوقعة؛ الخروج لمهمة قد يُنتج علاقات لم تكن في الحسبان.",
      "political_pressure", "community_vs_outsider", "trust_between_parties",
      "compromise_for_larger_goal", "seeking_allies", "legislation"),

    E("meccan_sariya_abdullah_jahsh_nakhla", 148, 2, "meccan_late",
      "سرية عبد الله بن جحش إلى نخلة", "Expedition of Abdullah ibn Jahsh to Nakhla",
      "Nakhla", ["2:217"],
      "بعث النبي ﷺ عبد الله بن جحش في ثمانية من المهاجرين في سرية سرية، ففتح الكتاب بعد يومين فقرأ أن يتحسّسوا قافلة لقريش، فوقع قتال في آخر يوم من رجب الحرام.",
      "المهام السرية تحتاج إلى ضبط محكم؛ الاجتهاد الخاطئ في الشهر الحرام أثار جدلاً كبيراً.",
      "legal_coercion", "principled_minority_vs_powerful_majority", "trust_between_parties",
      "deferral_of_judgement", "limits_of_personal_discretion", "legislation"),

    E("meccan_ramadan_fasting_ordered", 149, 2, "meccan_late",
      "فرض صيام رمضان", "Obligation of Ramadan fasting",
      "Medina", ["2:183", "2:184", "2:185"],
      "نزل فرض صيام رمضان في السنة الثانية من الهجرة، بعد أن كان الصيام يوم عاشوراء اختيارياً.",
      "التدرج في التشريع من الاختياري إلى الفرضي؛ العبادات الكبيرة تُؤسَّس بعد تمكين الجماعة.",
      "none", "community_vs_outsider", "spiritual_integrity",
      "legal_innovation", "gradualism_in_hard_change", "legislation"),

    E("meccan_zakah_obligation", 150, 2, "meccan_late",
      "فرض الزكاة بمقاديرها المحددة", "Obligation of zakat with specified amounts",
      "Medina", ["2:43", "9:103"],
      "استقرّ فرض الزكاة في السنة الثانية من الهجرة بمقاديرها المفصّلة، فبنت الدولة الإسلامية الوليدة مؤسسة اقتصادية جديدة.",
      "الزكاة ليست صدقة فردية فقط بل نظام اقتصادي عام؛ المال الخاص له حق على العام.",
      "none", "community_vs_outsider", "livelihood",
      "legal_innovation", "economic_justice_as_worship", "legislation"),
]
