"""Medinan early events (years 1-3 AH). Order range 151-300.

Coverage:
  - Setup of Medina society (year 1 AH, ~30 events)
  - Early Medinan legislation (qibla change, fasting, zakat refinements)
  - Badr expedition and its sub-events (year 2 AH, ~40 events)
  - Aftermath of Badr including captives, ransoms, individual judgements
  - Banu Qaynuqa expulsion (year 2 AH)
  - Uhud expedition and sub-events (year 3 AH, ~40 events)
  - Aftermath of Uhud
  - Asbab al-nuzul tied to this period (from al-Baqara, Al-Imran)
"""

from __future__ import annotations

from training.pipeline.sira_db.db import E

MEDINAN_EARLY_EVENTS: list[dict] = [
    # ═══════════════ YEAR 1 AH — SETTING UP MEDINA ═══════════════
    E("me_qibla_before_change", 151, 1, "medinan_early",
      "الصلاة إلى بيت المقدس قبل التحويل", "Prayer toward Jerusalem before the change",
      "Medina", ["2:142", "2:143"],
      "ظل النبي ﷺ يصلي إلى بيت المقدس في المدينة نحو 16-17 شهراً، وكان يقلّب وجهه في السماء يتوقع أمر التحويل.",
      "انتظار الحكم الإلهي أدب مع الشرع؛ الرغبة لا تستبق النص.",
      "none", "leader_vs_follower", "spiritual_integrity",
      "endurance_without_retaliation", "limits_of_personal_discretion", "command"),

    E("me_qibla_change_mid_salat", 152, 2, "medinan_early",
      "تحويل القبلة أثناء الصلاة", "Qibla change mid-prayer",
      "Medina", ["2:144", "2:149", "2:150"],
      "نزل أمر تحويل القبلة إلى الكعبة والنبي ﷺ في صلاة الظهر، فاستدار واستدار معه أصحابه حتى صاروا على الكعبة.",
      "الاستجابة الفورية للنص علامة الإيمان؛ لا نقاش في الأمر المحكم.",
      "none", "community_vs_outsider", "religious_freedom",
      "legal_innovation", "principled_refusal_to_transgress", "legislation"),

    E("me_qibla_yahud_protest", 153, 2, "medinan_early",
      "اعتراض اليهود على تحويل القبلة", "Jewish objection to the qibla change",
      "Medina", ["2:142", "2:143", "2:145"],
      "اعترض اليهود على تحويل القبلة وقالوا: ما ولّاهم عن قبلتهم التي كانوا عليها؟ فأجاب القرآن: قل لله المشرق والمغرب يهدي من يشاء.",
      "الاعتراض على أمر الله لا يُقبل مهما كان المعترض؛ الوجهة الحقيقية هي الله لا المكان.",
      "intellectual_challenge", "community_vs_outsider", "religious_freedom",
      "intellectual_rebuttal", "source_integrity_over_popularity", "argument"),

    E("me_masjid_qiblatayn", 154, 2, "medinan_early",
      "مسجد القبلتين يشهد التحويل", "Masjid al-Qiblatayn witnesses the change",
      "Medina", ["2:144"],
      "كان النبي ﷺ يصلي الظهر في مسجد بني سلمة لمّا نزل أمر التحويل، فسُمّي المسجد مسجد القبلتين.",
      "الأماكن تحفظ ذكريات التحولات الكبرى؛ الرمز المكاني يُخلّد المبدأ.",
      "none", "community_vs_outsider", "community_cohesion",
      "witnessing_and_documentation", "teaching_through_demonstration", "story"),

    E("me_tahweel_women", 155, 2, "medinan_early",
      "رجل يخبر النساء بتحويل القبلة في قباء", "A man informs the women in Quba of the qibla change",
      "Quba", ["2:144"],
      "دخل رجل على أهل قباء وهم في صلاة الصبح فأخبرهم بتحويل القبلة، فاستداروا وهم ركوع إلى الكعبة.",
      "نقل الخبر الموثّق التزام جماعي؛ الرواية عن النبي حجة على المجتمع.",
      "none", "community_vs_outsider", "community_cohesion",
      "witnessing_and_documentation", "trust_is_earned_by_consistency", "command"),

    E("me_jews_annoying_questions", 156, 1, "medinan_early",
      "أسئلة اليهود للإحراج", "Jewish questions meant to corner the Prophet",
      "Medina", ["2:108", "4:153", "2:118"],
      "كان بعض أحبار اليهود يسألون النبي ﷺ أسئلة مُحرجة كطلب إنزال كتاب من السماء وإراءة الله جهرة، فأجابهم القرآن بأن أسلافهم سألوا مثلها من موسى.",
      "الأسئلة التعجيزية منهج قديم للتملّص؛ التاريخ يعيد نفسه في كل جيل.",
      "intellectual_challenge", "community_vs_outsider", "truth_vs_falsehood",
      "intellectual_rebuttal", "signs_require_reflection_not_proof", "argument"),

    E("me_muqhan_hypocrites_start", 157, 1, "medinan_early",
      "بداية ظاهرة النفاق في المدينة", "The beginning of hypocrisy in Medina",
      "Medina", ["2:8", "2:9", "2:10", "2:11", "2:12", "2:13", "2:14", "2:15", "2:16", "2:17", "2:18", "2:19", "2:20"],
      "ظهر النفاق في المدينة بعد تمكّن الإسلام، إذ أظهر جماعة من الأوس والخزرج الإيمان وأبطنوا الكفر، وعلى رأسهم عبد الله بن أبي بن سلول.",
      "النفاق ظاهرة ترتبط بتمكّن الحق لا بضعفه؛ من لم يستطع المواجهة العلنية لجأ للخفاء.",
      "internal_betrayal", "insider_hypocrite_vs_sincere", "trust_between_parties",
      "moral_rebuke", "consistency_public_and_private", "warning"),

    E("me_ibn_salul_leader", 158, 1, "medinan_early",
      "عبد الله بن أبي زعيم المنافقين", "Abdullah ibn Ubayy as hypocrite leader",
      "Medina", ["63:1", "63:2", "63:3"],
      "كاد عبد الله بن أبي بن سلول أن يُتوَّج ملكاً على المدينة قبل الهجرة فأفسد قدوم النبي ﷺ عليه مشروعه، فبقي رأس المنافقين.",
      "السلطة المسلوبة تُنتج عداءً دائماً؛ المنافق يحمل جرحاً شخصياً لا جرحاً فكرياً.",
      "internal_betrayal", "insider_hypocrite_vs_sincere", "community_cohesion",
      "moral_rebuke", "consistency_public_and_private", "warning"),

    E("me_first_masjid_expansion", 159, 1, "medinan_early",
      "توسعة المسجد النبوي الأولى", "First expansion of the Prophet's mosque",
      "Medina", ["9:18"],
      "لمّا كثر المسلمون في المدينة احتاج المسجد إلى توسعة، فشارك النبي ﷺ بنفسه في البناء رغم تحمّله أعباء القيادة.",
      "النمو يستوجب التوسعة؛ البنية التحتية تتبع النمو الاجتماعي لا العكس.",
      "none", "community_vs_outsider", "community_cohesion",
      "organizational_response", "leadership_accountability", "command"),

    E("me_saad_ibn_muadh_pledge_loyalty", 160, 1, "medinan_early",
      "بيعة سعد بن معاذ على السمع والطاعة", "Sa'd ibn Mu'adh's pledge of obedience",
      "Medina", ["4:59", "8:1"],
      "أعلن سعد بن معاذ كبير الأوس بيعته على السمع والطاعة للنبي ﷺ في المنشط والمكره، وصار نموذجاً للطاعة الأنصارية.",
      "بيعة القادة على السمع والطاعة تُيسّر قيادة الجماعة؛ النموذج الأعلى يعمّم السلوك.",
      "none", "leader_vs_follower", "community_cohesion",
      "confrontation_with_truth", "trust_is_earned_by_consistency", "praise"),

    E("me_early_marketplace", 161, 1, "medinan_early",
      "تأسيس سوق المسلمين في المدينة", "Establishing the Muslim marketplace",
      "Medina", ["62:10", "2:198"],
      "أسّس النبي ﷺ سوقاً للمسلمين في المدينة مستقلاً عن سوق بني قينقاع اليهودي، فكان بذرة الاقتصاد الإسلامي المستقل.",
      "الاستقلال الاقتصادي شرط من شروط السيادة؛ السوق يُبنى بالإرادة لا بالصدفة.",
      "economic_siege", "community_vs_outsider", "livelihood",
      "organizational_response", "economic_justice_as_worship", "legislation"),

    E("me_fasting_before_ramadan", 162, 2, "medinan_early",
      "صيام عاشوراء قبل فرض رمضان", "Fasting Ashura before Ramadan was made obligatory",
      "Medina", ["2:183", "2:184"],
      "صام النبي ﷺ يوم عاشوراء حين قدم المدينة لمّا رأى اليهود يصومونه، وقال: نحن أولى بموسى منكم، ثم فُرض رمضان فصار عاشوراء اختيارياً.",
      "الاحتفاظ بالمشترك الصالح بين الأديان، مع التقدّم في الخصوصية؛ الحق إرث مشترك.",
      "none", "community_vs_outsider", "spiritual_integrity",
      "compromise_for_larger_goal", "solidarity_around_principle", "legislation"),

    E("me_ramadan_first_fasting", 163, 2, "medinan_early",
      "أول رمضان في الإسلام", "First Ramadan in Islam",
      "Medina", ["2:183", "2:184", "2:185", "2:186", "2:187"],
      "صام المسلمون أول رمضان في السنة الثانية من الهجرة، ونزل فيه قوله تعالى كُتب عليكم الصيام.",
      "بدايات الفرائض الكبرى لحظات مفصلية في تكوين الأمة؛ الصيام مدرسة نفسية للجماعة.",
      "none", "community_vs_outsider", "spiritual_integrity",
      "legal_innovation", "gradualism_in_hard_change", "legislation"),

    E("me_fitr_first_eid", 164, 2, "medinan_early",
      "أول عيد فطر في الإسلام", "First Eid al-Fitr",
      "Medina", ["2:185"],
      "صلّى النبي ﷺ أول عيد فطر بعد رمضان الأول، وحوّل احتفالات الجاهلية (النيروز والمهرجان) إلى عيدي الفطر والأضحى.",
      "استبدال الرموز الثقافية بأفضل منها؛ التغيير يمنح بدائل لا يُنكر الحاجة فقط.",
      "none", "community_vs_outsider", "community_cohesion",
      "legal_innovation", "teaching_through_demonstration", "legislation"),

    E("me_zakat_fitr_ordained", 165, 2, "medinan_early",
      "فرض زكاة الفطر", "Imposition of Zakat al-Fitr",
      "Medina", ["2:184", "2:185"],
      "فرض النبي ﷺ زكاة الفطر على كل مسلم صغير وكبير تطهيراً للصائم وطعمة للمساكين قبل صلاة العيد.",
      "الفرحة بالعيد لا تكتمل إلا بمشاركة المحرومين؛ الزكاة تغسل أثر الصيام.",
      "none", "community_vs_outsider", "livelihood",
      "legal_innovation", "protection_of_the_weak", "legislation"),

    # ═══════════════ BADR PRELUDE — YEAR 2 AH ═══════════════
    E("me_badr_caravan_news", 166, 2, "medinan_early",
      "نبأ قافلة أبي سفيان القادمة من الشام", "News of Abu Sufyan's caravan returning from Syria",
      "Medina", ["8:7"],
      "بلغ النبي ﷺ خبر قافلة كبيرة لقريش يقودها أبو سفيان من الشام، فندب أصحابه للخروج لها عسى الله أن ينفلهم إياها.",
      "المعلومة الاستخباراتية أول خطوات القرار العسكري؛ الفرصة الاقتصادية قد تتحول إلى معركة وجودية.",
      "political_pressure", "community_vs_outsider", "collective_survival",
      "active_resistance", "knowledge_before_action", "command"),

    E("me_badr_leave_medina", 167, 2, "medinan_early",
      "خروج المسلمين من المدينة", "Muslim departure from Medina",
      "Medina", ["8:5", "8:6"],
      "خرج النبي ﷺ في 313 من أصحابه ما بين 83 مهاجراً و170 أنصارياً للقاء القافلة دون إعداد كامل للحرب.",
      "الخروج للفرصة الصغيرة قد يُنتج معركة كبيرة؛ النية تتطور مع الأحداث.",
      "political_pressure", "community_vs_outsider", "collective_survival",
      "active_resistance", "testing_loyalty_under_stress", "command"),

    E("me_abu_sufyan_escape", 168, 2, "medinan_early",
      "أبو سفيان يتجنب طريق بدر", "Abu Sufyan avoids the Badr route",
      "Badr area", ["8:7"],
      "تنبّه أبو سفيان لخطر المسلمين فحوّل مسار القافلة نحو الساحل وأرسل استغاثة إلى قريش في مكة.",
      "القائد المحنّك يستبق الخطر بتغيير المسار؛ الاستخبارات تعمل في الاتجاهين.",
      "political_pressure", "principled_minority_vs_powerful_majority", "property_rights",
      "strategic_withdrawal", "knowledge_before_action", "story"),

    E("me_quraysh_army_march", 169, 2, "medinan_early",
      "خروج جيش قريش للدفاع عن القافلة", "Quraysh army marches to defend the caravan",
      "Mecca", ["8:47"],
      "خرجت قريش بألف مقاتل بطراً ورئاءً الناس، يتبعهم القيان والدفوف والشعراء، تقصد المسلمين.",
      "الخيلاء تسبق السقوط؛ المظهر الاستعراضي ليس بديلاً عن الاستعداد الحقيقي.",
      "political_pressure", "believer_vs_unbeliever", "collective_survival",
      "confrontation_with_truth", "warning_against_arrogance", "warning"),

    E("me_utba_advice_return", 170, 2, "medinan_early",
      "عتبة بن ربيعة ينصح بعدم القتال", "Utba ibn Rabi'a counsels against fighting",
      "Badr area", ["8:5", "8:6"],
      "لمّا نجت القافلة نصح عتبة بن ربيعة قريشاً بالعودة دون قتال، فردّ عليه أبو جهل قائلاً: قد انتفخ سحرك، فطبع الكبر على الموقف.",
      "نصيحة الحكيم قد يُرفضها المتكبر؛ التكبر على النصح بداية الهزيمة.",
      "verbal_attack", "ally_vs_ally_dispute", "collective_survival",
      "private_counsel", "warning_against_arrogance", "argument"),

    E("me_badr_shura_consultation", 171, 2, "medinan_early",
      "استشارة النبي ﷺ أصحابه في الإقدام", "Prophet consults his companions on engagement",
      "Badr area", ["3:159", "42:38"],
      "استشار النبي ﷺ أصحابه حين علم بخروج قريش، فتكلّم المهاجرون ثم تكلّم المقداد ثم طلب كلام الأنصار، فقال سعد بن معاذ: امضِ يا رسول الله فوالله لو استعرضت بنا هذا البحر لخضناه معك.",
      "الشورى في القرارات الكبرى سنّة نبوية؛ كلام الأنصار كان مطلوباً لأن العهد كان معهم.",
      "political_pressure", "leader_vs_follower", "collective_survival",
      "consultation_before_decision", "consultation_before_decision", "command"),

    E("me_badr_position_wells", 172, 2, "medinan_early",
      "تغيير المنزل إلى أدنى بئر ببدر", "Changing position to the nearest well at Badr",
      "Badr", ["8:11"],
      "نصح الحُباب بن المنذر النبي ﷺ بأن ينزل عند أدنى بئر إلى القوم ويُغوّر ما وراءها ليجعل الماء لهم، فقبل النبي مشورته.",
      "قبول القائد للمشورة الفنية علامة حكمة لا ضعف؛ كل اجتهاد يُحاكم بمصلحته.",
      "political_pressure", "leader_vs_follower", "collective_survival",
      "consultation_before_decision", "knowledge_before_action", "command"),

    E("me_badr_arish_canopy", 173, 2, "medinan_early",
      "بناء العريش للنبي ﷺ ببدر", "Building the canopy for the Prophet at Badr",
      "Badr", ["8:9", "8:10"],
      "بنى الأنصار عريشاً للنبي ﷺ ليتمركز فيه للقيادة ومناجاة ربه، وطلب منه سعد بن معاذ أن يُقيم فيه ويحفظه من الخطر.",
      "حماية القائد أولوية في المعركة؛ القيادة لا ينبغي أن تُخسر في أول ضربة.",
      "political_pressure", "leader_vs_follower", "collective_survival",
      "organizational_response", "leadership_accountability", "command"),

    E("me_badr_prophets_dua", 174, 2, "medinan_early",
      "دعاء النبي ﷺ في عريشه ببدر", "The Prophet's supplication in the canopy",
      "Badr", ["8:9", "8:10"],
      "رفع النبي ﷺ يديه في عريشه يدعو: اللهم أنجز لي ما وعدتني، اللهم إن تهلك هذه العصابة من أهل الإسلام فلن تُعبد في الأرض. حتى سقط رداؤه، وقال أبو بكر: حسبك يا رسول الله.",
      "الدعاء هو السلاح المعنوي الأول في الأزمات؛ القائد المؤمن يتعلق بالأسباب والمسبّب.",
      "existential_threat", "self_vs_self", "collective_survival",
      "refuge_with_god_against_despair", "refuge_with_god_against_despair", "consolation"),

    E("me_badr_rain_night", 175, 2, "medinan_early",
      "المطر ليلة بدر يُثبّت المسلمين", "Rain the night of Badr stabilizes the Muslims",
      "Badr", ["8:11"],
      "أنزل الله مطراً ليلة بدر جعل أرض المسلمين صلبة وأرض المشركين وحلاً، وطهّرهم من حدثهم وربط على قلوبهم.",
      "عوامل الطبيعة قد تكون جندياً من جنود الحق؛ النصر يأتي بأسباب لا تخطر للعقل.",
      "existential_threat", "community_vs_outsider", "collective_survival",
      "refuge_with_god_against_despair", "divine_testing_mechanism", "story"),

    E("me_badr_angels_participation", 176, 2, "medinan_early",
      "نزول الملائكة يوم بدر", "Angels descend at Badr",
      "Badr", ["8:9", "8:12", "3:123", "3:124", "3:125"],
      "أنزل الله يوم بدر ألفاً من الملائكة مردفين يُثبّتون المؤمنين ويضربون فوق الأعناق ومن كل بنان.",
      "التأييد الإلهي يصل عند الحاجة الحقيقية؛ الجيش الحق يُعزَّز بجنود من الغيب.",
      "existential_threat", "believer_vs_unbeliever", "collective_survival",
      "refuge_with_god_against_despair", "refuge_with_god_against_despair", "story"),

    E("me_badr_prophet_hand_pebbles", 177, 2, "medinan_early",
      "رمي النبي ﷺ الحصى في وجوه المشركين", "The Prophet throws pebbles at the polytheists' faces",
      "Badr", ["8:17"],
      "أخذ النبي ﷺ حفنة من تراب ورماها في وجوه المشركين قائلاً: شاهت الوجوه، فما منهم أحد إلا ملأ عينيه، فانهزموا.",
      "الفعل الرمزي يحمل معنى أكبر من أثره الفيزيائي؛ الله يُلقي الرعب بأسباب صغيرة.",
      "existential_threat", "community_vs_outsider", "collective_survival",
      "confrontation_with_truth", "refuge_with_god_against_despair", "story"),

    E("me_badr_three_duels", 178, 2, "medinan_early",
      "المبارزة الثلاثية قبل بدر", "The triple duel before Badr",
      "Badr", ["22:19"],
      "برز عتبة وشيبة والوليد من قريش وطلبوا النزال، فبرز لهم حمزة وعلي وعبيدة بن الحارث فقتلوهم، وكان فأل النصر للمسلمين.",
      "المبارزة الأولى تُهدم معنويات الخصم؛ الانتصار في أول خطوة نصف المعركة.",
      "existential_threat", "believer_vs_unbeliever", "collective_survival",
      "confrontation_with_truth", "chosen_hardship_over_compromise", "story"),

    E("me_badr_ubayda_martyrdom", 179, 2, "medinan_early",
      "استشهاد عبيدة بن الحارث ببدر", "Martyrdom of Ubayda ibn al-Harith at Badr",
      "Badr", ["22:58"],
      "قُطعت رِجل عبيدة بن الحارث في المبارزة الثلاثية فحُمل جريحاً ثم مات على الطريق ودُفن بالصفراء.",
      "القائد يدفع الثمن الأول؛ الشهادة شرف يسبق فيه القادة عموم الجند.",
      "existential_threat", "believer_vs_unbeliever", "physical_safety",
      "endurance_without_retaliation", "leadership_accountability", "story"),

    E("me_badr_abu_jahl_killed", 180, 2, "medinan_early",
      "مقتل أبي جهل فرعون هذه الأمة", "Killing of Abu Jahl the pharaoh of this ummah",
      "Badr", ["8:17"],
      "ضربه غلامان من الأنصار (معاذ بن عفراء ومعاذ بن عمرو) حتى أُثخن، ثم وجده عبد الله بن مسعود مصروعاً فاحتزّ رأسه وجاء به إلى النبي ﷺ.",
      "أكبر الطغاة قد يسقط بيد أصغر المؤمنين؛ العدالة لا تنتظر الجيل التالي.",
      "existential_threat", "believer_vs_unbeliever", "collective_survival",
      "active_resistance", "accountability_proportional_to_power", "warning"),

    E("me_badr_umayya_killed", 181, 2, "medinan_early",
      "مقتل أمية بن خلف ببدر", "Killing of Umayya ibn Khalaf at Badr",
      "Badr", ["8:17"],
      "التقى بلال بن رباح بسيّده أمية بن خلف يوم بدر فصاح: يا معاشر الأنصار، هذا رأس الكفر أمية، فتكاتفوا عليه حتى قتلوه.",
      "القصاص الإلهي قد يأتي بيد المظلوم نفسه؛ التاريخ يُعيد ترتيب الأدوار.",
      "existential_threat", "believer_vs_unbeliever", "personal_dignity",
      "active_resistance", "accountability_proportional_to_power", "warning"),

    E("me_badr_quraysh_defeat", 182, 2, "medinan_early",
      "هزيمة قريش الكبرى ببدر", "The great defeat of Quraysh at Badr",
      "Badr", ["3:123", "8:7", "8:47"],
      "انهزمت قريش بعد مقتل 70 من أشرافها وأُسر 70 آخرون، وقُتل من المسلمين 14 شهيداً، فكان فوزاً لم يتوقعه أحد.",
      "النصر الحقيقي لا يُقاس بالعدة والعدد؛ الإيمان يُقلب الموازين.",
      "existential_threat", "community_vs_outsider", "collective_survival",
      "confrontation_with_truth", "divine_testing_mechanism", "promise"),

    E("me_badr_quraysh_in_well", 183, 2, "medinan_early",
      "إلقاء قتلى قريش في قليب بدر", "Casting Quraysh dead into the Badr well",
      "Badr", ["54:45", "8:50"],
      "أمر النبي ﷺ بإلقاء قتلى قريش في قليب بدر، ثم وقف عليهم ونادى: يا أهل القليب، هل وجدتم ما وعد ربكم حقاً؟",
      "المواجهة مع نتائج الكفر بعد موت أصحابه درس حي؛ الحق يلقي كلمته حتى مع الأموات.",
      "existential_threat", "believer_vs_unbeliever", "truth_vs_falsehood",
      "public_declaration", "confronting_falsehood_even_posthumously", "story",
      response_type="warning"),

    E("me_badr_captives_return", 184, 2, "medinan_early",
      "عودة الجيش بأسرى بدر", "Return of the army with Badr captives",
      "Between Badr and Medina", ["8:67", "8:70"],
      "عاد المسلمون إلى المدينة يسوقون 70 أسيراً من كبار قريش، ففرح أهل المدينة واختلطت بفرحتهم حُزنٌ على الشهداء.",
      "النصر له تكلفته المعنوية؛ الفرح لا يلغي الحزن على الفقد.",
      "none", "community_vs_outsider", "community_cohesion",
      "organizational_response", "solidarity_around_principle", "story"),

    E("me_badr_ransom_ruling", 185, 2, "medinan_early",
      "الاختلاف في فداء أسرى بدر", "Dispute over ransoming the Badr captives",
      "Medina", ["8:67", "8:68", "8:69"],
      "اختلف الصحابة في أسرى بدر: أشار أبو بكر بالفداء رحمةً وأشار عمر بالقتل ردعاً، فأخذ النبي ﷺ برأي أبي بكر ففاداهم.",
      "الاختلاف في الرأي طبيعي حتى في أكبر الصحابة؛ القائد يُرجّح ثم يتحمّل النتيجة.",
      "political_pressure", "ally_vs_ally_dispute", "justice_vs_privilege",
      "consultation_before_decision", "consultation_before_decision", "argument"),

    E("me_quran_rebuke_ransom", 186, 2, "medinan_early",
      "عتاب السماء على قبول الفدية", "Divine rebuke for accepting ransom",
      "Medina", ["8:67", "8:68", "8:69"],
      "نزل في شأن أسرى بدر عتاب: ما كان لنبي أن يكون له أسرى حتى يُثخن في الأرض، لولا كتاب من الله سبق لمسّكم فيما أخذتم عذاب عظيم.",
      "الاجتهاد الجماعي قد يُصحَّح من السماء؛ القرارات الكبرى لها ميزان أعلى من ميزان الناس.",
      "verbal_attack", "leader_vs_follower", "justice_vs_privilege",
      "moral_rebuke", "accountability_proportional_to_power", "rebuke"),

    E("me_badr_captive_teach_literacy", 187, 2, "medinan_early",
      "فداء بعض الأسرى بتعليم صبيان المدينة", "Ransom via teaching Medina's boys to read",
      "Medina", ["2:129"],
      "قبل النبي ﷺ من بعض أسرى بدر الذين لم يملكوا فدية أن يُعلّموا عشرة من صبيان المدينة القراءة والكتابة فداءً لأنفسهم.",
      "المعرفة أثمن من المال؛ الاستثمار في تعليم جيل أعظم من فدية فردية.",
      "economic_siege", "teacher_vs_student", "knowledge_access",
      "legal_innovation", "knowledge_before_action", "legislation"),

    E("me_suhayl_escape_attempt", 188, 2, "medinan_early",
      "محاولة سهيل بن عمرو الفرار من الأسر", "Suhayl ibn Amr tries to escape captivity",
      "Medina", ["8:70"],
      "حاول سهيل بن عمرو (الخطيب) الفرار من الأسر ثم فُديَ بعد ذلك، وطلب عمر قلع أسنانه الأمامية حتى لا يخطب، فرفض النبي ﷺ.",
      "القصاص لا يكون بتعطيل المواهب؛ الرحمة تحفظ الإنسانية حتى في الخصم.",
      "physical_persecution", "claimant_vs_accused", "personal_dignity",
      "forgiveness_from_power", "forgiveness_without_surrender", "rebuke"),

    E("me_nadr_ibn_harith_executed", 189, 2, "medinan_early",
      "إعدام النضر بن الحارث بعد بدر", "Execution of al-Nadr ibn al-Harith after Badr",
      "Al-Safra", ["8:31"],
      "أُعدم النضر بن الحارث وعقبة بن أبي معيط بعد بدر لشدة جرمهما السابق في إيذاء المسلمين ومحاربتهم بالكلمة والفعل.",
      "العقوبة النهائية على القادة المخرّبين رسالة ردع؛ المجرم الأكبر لا يُعامل كالعامة.",
      "legal_coercion", "claimant_vs_accused", "justice_vs_privilege",
      "accountability_proportional_to_power", "accountability_proportional_to_power", "warning"),

    E("me_abbas_ransomed", 190, 2, "medinan_early",
      "فداء العباس بن عبد المطلب", "Ransom of al-Abbas ibn Abd al-Muttalib",
      "Medina", ["8:70"],
      "أُسر العباس عم النبي ﷺ ببدر وفادى نفسه وابنَي أخويه، ثم نزل: إن يعلم الله في قلوبكم خيراً يؤتكم خيراً مما أُخذ منكم.",
      "القريب لا يُميَّز في الحكم؛ لكن القلب الصادق يُعوَّض بأفضل.",
      "economic_siege", "kin_vs_kin", "family_integrity",
      "legal_innovation", "justice_vs_privilege", "legislation"),

    E("me_qaynuqa_market_dispute", 191, 2, "medinan_early",
      "حادثة السوق في بني قينقاع", "The market incident in Banu Qaynuqa",
      "Medina", ["5:51", "5:52", "5:57", "5:58"],
      "جاءت امرأة مسلمة إلى سوق بني قينقاع فعبث بها صائغ يهودي فكشف ثوبها، فقتل المسلم الصائغ فقتل اليهود المسلم، فاشتعلت الفتنة.",
      "حادثة فردية قد تكشف توتراً كامناً؛ الاستهانة بكرامة المرأة تُهدم العقود.",
      "verbal_attack", "community_vs_outsider", "reputation_honor",
      "confrontation_with_truth", "protection_of_the_weak", "warning"),

    E("me_qaynuqa_expulsion", 192, 2, "medinan_early",
      "حصار بني قينقاع وإجلاؤهم", "Siege and expulsion of Banu Qaynuqa",
      "Medina", ["59:2", "5:51"],
      "حاصر النبي ﷺ بني قينقاع خمسة عشر يوماً حتى نزلوا على حكمه، فأراد قتلهم، فتوسّط فيهم عبد الله بن أبي فأجلاهم إلى أذرعات.",
      "خرق العهد ثمنه الإجلاء؛ الوساطة السياسية قد تُخفّف العقوبة لا تُلغيها.",
      "legal_coercion", "community_vs_outsider", "collective_survival",
      "strategic_withdrawal", "refusing_to_legitimize_falsehood", "legislation"),

    E("me_ibn_ubayy_intercession", 193, 2, "medinan_early",
      "شفاعة ابن أبي في قينقاع", "Ibn Ubayy's intercession for Qaynuqa",
      "Medina", ["5:51", "5:52", "5:53"],
      "أصرّ عبد الله بن أبي بن سلول على شفاعته في بني قينقاع حتى أخذ بثوب النبي ﷺ وقال: أحسن في مواليّ، فأجلاهم النبي ولم يقتلهم.",
      "الشفاعة لها حدود حتى من القادة؛ الشافع يُحاسب إذا شفع في ظلم.",
      "political_pressure", "insider_hypocrite_vs_sincere", "justice_vs_privilege",
      "compromise_for_larger_goal", "distinguishing_enemy_from_outsider", "rebuke"),

    E("me_sawiq_expedition", 194, 2, "medinan_early",
      "غزوة السويق ردّاً على أبي سفيان", "Ghazwat al-Sawiq in response to Abu Sufyan",
      "Qarqarat al-Kudr", ["8:57"],
      "خرج أبو سفيان في 200 من قريش لغارة على المدينة فحرقوا أُطماً وقتلوا رجلاً، فخرج النبي ﷺ في طلبهم فأسقطوا سويقهم (زادهم).",
      "الرد الفوري على التحرّش شرط الردع؛ العدو لا يفهم إلا لغة الملاحقة.",
      "political_pressure", "community_vs_outsider", "collective_survival",
      "active_resistance", "accountability_proportional_to_power", "command"),

    E("me_ghazwa_banu_sulaym", 195, 2, "medinan_early",
      "غزوة بني سليم بقرقرة الكدر", "Expedition against Banu Sulaym at Qarqarat al-Kudr",
      "Qarqarat al-Kudr", ["8:57"],
      "بلغ النبي ﷺ أن بني سليم وغطفان يجمعون لغزو المدينة فباغتهم بجيشه، ففرّوا وغنم المسلمون إبلاً كثيرة.",
      "الهجوم خير وسيلة للدفاع أحياناً؛ السرعة تُحبط تجمعات الخصوم.",
      "political_pressure", "community_vs_outsider", "collective_survival",
      "active_resistance", "knowledge_before_action", "command"),

    E("me_ghazwa_dhi_amr", 196, 3, "medinan_early",
      "غزوة ذي أمر", "Ghazwa of Dhi Amr",
      "Dhi Amr", ["5:11"],
      "بلغ النبي ﷺ تجمّع بني ثعلبة ومحارب لغزو المدينة فخرج إليهم في 450 فتفرقوا في الجبال، وأنزل المطر عليه وحده فأراد رجل قتله فأمسك الله يده.",
      "حماية القائد من الاغتيال آية من آيات الله؛ الله يحفظ أدوات الحق.",
      "existential_threat", "individual_vs_majority", "physical_safety",
      "refuge_with_god_against_despair", "refuge_with_god_against_despair", "story"),

    E("me_kaab_ashraf_killed", 197, 3, "medinan_early",
      "قتل كعب بن الأشرف المحرّض", "Killing of Ka'b ibn al-Ashraf the agitator",
      "Medina area", ["59:2"],
      "كان كعب بن الأشرف يُحرّض على المسلمين بشعره ورحلاته إلى قريش، فأمر النبي ﷺ بتصفيته فذهب إليه محمد بن مسلمة في جماعة فقتلوه ليلاً.",
      "المحرّض السياسي بالكلمة يُعادل المحارب بالسيف؛ عقوبته أحياناً مستهدفة.",
      "verbal_attack", "claimant_vs_accused", "trust_between_parties",
      "active_resistance", "refusing_to_legitimize_falsehood", "warning"),

    # ═══════════════ UHUD — YEAR 3 AH ═══════════════
    E("me_uhud_quraysh_vow_revenge", 198, 3, "medinan_early",
      "قسم قريش بعد بدر بالأخذ بثأر قتلاها", "Quraysh's oath to avenge Badr",
      "Mecca", ["3:118"],
      "اجتمعت قريش بعد بدر وأقسمت على الأخذ بثأرها، وحرّم أبو سفيان على نساء قريش البكاء حتى يُقاتلوا محمداً.",
      "الحقد يُعيد تشكيل المجتمع حول هدف واحد؛ العدو المجروح أخطر من العدو في قوته.",
      "political_pressure", "believer_vs_unbeliever", "collective_survival",
      "active_resistance", "testing_loyalty_under_stress", "warning"),

    E("me_quraysh_caravan_profit_for_war", 199, 3, "medinan_early",
      "استثمار أرباح القافلة في حرب أُحد", "Investing the caravan profits in the Uhud war",
      "Mecca", ["8:36"],
      "اجتمعت قريش على أن تخصص أرباح القافلة الناجية (نحو 50,000 دينار) لتمويل جيش الانتقام من المسلمين في أحد.",
      "المال قد يُجنَّد لإطفاء الحق؛ الاقتصاد والحرب وجهان لعملة واحدة.",
      "political_pressure", "community_vs_outsider", "livelihood",
      "active_resistance", "wealth_as_trust_not_ownership", "warning"),

    E("me_quraysh_march_uhud", 200, 3, "medinan_early",
      "خروج قريش بثلاثة آلاف إلى أُحد", "Quraysh marches with 3000 toward Uhud",
      "Mecca/Uhud", ["3:13"],
      "خرجت قريش بثلاثة آلاف مقاتل منهم 200 فارس و700 دارع، معهم 15 امرأة لتحريض الرجال، وعلى رأسهم أبو سفيان.",
      "الاستعداد المضاد يفوق الأول؛ المرأة في الحرب القديمة قوة نفسية مؤثرة.",
      "existential_threat", "community_vs_outsider", "collective_survival",
      "active_resistance", "collective_obligation_above_personal", "warning"),

    E("me_uhud_consultation_defense", 201, 3, "medinan_early",
      "استشارة النبي ﷺ في خطة دفاع أُحد", "Prophet consults on Uhud defense strategy",
      "Medina", ["3:159"],
      "رأى النبي ﷺ أن يبقوا في المدينة يتحصّنون بشوارعها، لكن شباب الصحابة أصرّوا على الخروج طلباً للشهادة، فوافقهم ولبس لأمته.",
      "الشورى تغلب الرأي الشخصي أحياناً؛ القائد ينزل على رأي الأغلبية حتى لو لم يكن رأيه.",
      "political_pressure", "leader_vs_follower", "collective_survival",
      "consultation_before_decision", "consultation_before_decision", "command"),

    E("me_uhud_prophet_regret_exit", 202, 3, "medinan_early",
      "ندم الشباب بعد أن لبس النبي ﷺ لأمته", "The young men regret after the Prophet dons his armor",
      "Medina", ["3:154"],
      "لمّا لبس النبي ﷺ لأمته ندم الشباب وقالوا: ما كان لنا أن نخالفه، فخيّرهم بين الاستقامة على قرارهم أو الرجوع، فقال: لا ينبغي لنبي إذا لبس لأمته أن يضعها.",
      "القرار بعد المشورة ملزم؛ التراجع بعد الخروج ضعف قيادي.",
      "political_pressure", "leader_vs_follower", "community_cohesion",
      "refusal_to_compromise", "limits_of_personal_discretion", "command"),

    E("me_uhud_hypocrites_withdraw", 203, 3, "medinan_early",
      "انسحاب ابن أبي بثلث الجيش", "Ibn Ubayy withdraws with a third of the army",
      "Between Medina and Uhud", ["3:167", "4:88"],
      "انسحب عبد الله بن أبي بثلث جيش المسلمين في منتصف الطريق إلى أُحد بحجّة أن النبي ﷺ لم يأخذ بنصيحته، فبقي النبي في 700 رجل.",
      "الخيانة تكشف عن نفسها في أصعب اللحظات؛ المنافق يفرّ حين يكثر البذل.",
      "internal_betrayal", "insider_hypocrite_vs_sincere", "trust_between_parties",
      "strategic_withdrawal", "consistency_public_and_private", "warning"),

    E("me_uhud_archers_position", 204, 3, "medinan_early",
      "وضع الرماة على جبل عينين", "Positioning the archers on Jabal Ainayn",
      "Uhud", ["3:152", "3:153"],
      "وضع النبي ﷺ خمسين رامياً بقيادة عبد الله بن جبير على الجبل وأمرهم بألا يبرحوا مكانهم سواء انتصر المسلمون أو انهزموا.",
      "القائد يُحدّد الأوامر القاطعة بلا لبس؛ الانضباط التكتيكي شرط النصر.",
      "political_pressure", "leader_vs_follower", "collective_survival",
      "organizational_response", "consistency_public_and_private", "command"),

    E("me_uhud_initial_victory", 205, 3, "medinan_early",
      "النصر الأول للمسلمين في أُحد", "Initial Muslim victory at Uhud",
      "Uhud", ["3:152"],
      "هاجم المسلمون جيش قريش فكسروه، وانشغلت قريش بالفرار، وبدأ الصحابة يجمعون الغنائم ظناً أن الحرب انتهت.",
      "اللحظة الأخيرة في المعركة أخطر من أولها؛ النصر المبكر قد يُخفي الهزيمة.",
      "existential_threat", "community_vs_outsider", "collective_survival",
      "active_resistance", "testing_loyalty_under_stress", "story"),

    E("me_uhud_archers_abandon", 206, 3, "medinan_early",
      "ترك الرماة مواقعهم لجمع الغنائم", "Archers abandon their positions for loot",
      "Uhud", ["3:152", "3:153"],
      "رأى الرماة هزيمة قريش وانشغال المسلمين بالغنائم فظنّوا أن المعركة انتهت، فنزل معظمهم من الجبل خلافاً لأمر النبي ﷺ.",
      "الاجتهاد الفردي في خلاف أمر القائد يُدمّر العمل الجماعي؛ اللوم لا يُعفى بحسن النية.",
      "moral_failure_by_self", "leader_vs_follower", "collective_survival",
      "moral_rebuke", "limits_of_personal_discretion", "warning"),

    E("me_uhud_khalid_ambush", 207, 3, "medinan_early",
      "خالد بن الوليد يلتف من خلف الجبل", "Khalid ibn al-Walid flanks from behind the mountain",
      "Uhud", ["3:152", "3:153"],
      "استغلّ خالد بن الوليد (وكان مشركاً) نزول الرماة فالتف بالخيل من خلف الجبل وانقضّ على المسلمين من خلفهم.",
      "القائد المحترف يستغل كل ثغرة تكتيكية؛ العبقرية العسكرية قد تكون عند الخصم أيضاً.",
      "existential_threat", "community_vs_outsider", "collective_survival",
      "confrontation_with_truth", "knowledge_before_action", "warning"),

    E("me_uhud_muslim_panic", 208, 3, "medinan_early",
      "ارتباك المسلمين وقتل الأخوة", "Muslim panic and fratricide",
      "Uhud", ["3:153"],
      "انقلب الوضع على المسلمين فجأة وقُتل حتى بعضهم بعضاً في الارتباك، وكانت الصيحة من كل جانب.",
      "الفوضى أخطر من الهجوم؛ انقطاع التواصل في المعركة يُفقد السيطرة.",
      "existential_threat", "ally_vs_ally_dispute", "physical_safety",
      "endurance_without_retaliation", "limits_of_personal_discretion", "warning"),

    E("me_uhud_prophet_wounded", 209, 3, "medinan_early",
      "جرح النبي ﷺ في أُحد", "Wounding of the Prophet at Uhud",
      "Uhud", ["3:144"],
      "كُسرت رباعية النبي ﷺ وشُجّ وجهه ودخلت حلقتان من المغفر في وجنته، حتى قال: كيف يفلح قوم شجّوا نبيهم؟ فنزل: ليس لك من الأمر شيء.",
      "حتى النبي ﷺ يُصاب؛ العصمة في البلاغ لا في الحماية المطلقة من الأذى.",
      "physical_persecution", "individual_vs_majority", "physical_safety",
      "endurance_without_retaliation", "chosen_hardship_over_compromise", "story"),

    E("me_uhud_hamza_martyrdom", 210, 3, "medinan_early",
      "استشهاد حمزة سيد الشهداء", "Martyrdom of Hamza lord of the martyrs",
      "Uhud", ["3:169", "3:170", "3:171"],
      "قتل وحشي بن حرب حمزةَ بن عبد المطلب برمية حربة في خاصرته نيابة عن هند بنت عتبة التي حرّضته طلباً لثأر أبيها.",
      "الشهادة الكبرى تُدفع في أحرج اللحظات؛ الثأر القبلي يستعمل أدوات المرتزقة.",
      "existential_threat", "kin_vs_kin", "physical_safety",
      "endurance_without_retaliation", "chosen_hardship_over_compromise", "story"),

    E("me_hind_mutilation_hamza", 211, 3, "medinan_early",
      "تمثيل هند بجسد حمزة", "Hind's mutilation of Hamza's body",
      "Uhud", ["16:126", "16:127", "16:128"],
      "وصلت هند بنت عتبة إلى جثة حمزة بعد موته فشقّت بطنه ومضغت كبده ثم لفظتها، في منظر بشع صدم المسلمين.",
      "الحقد الشخصي يتجاوز حدود الإنسانية؛ التمثيل بالجثث محرَّم في الإسلام.",
      "physical_persecution", "kin_vs_kin", "personal_dignity",
      "moral_rebuke", "refusing_to_legitimize_falsehood", "rebuke"),

    E("me_prophet_oath_revenge", 212, 3, "medinan_early",
      "قسم النبي ﷺ بالانتقام وتصحيحه من السماء", "Prophet's oath of revenge and divine correction",
      "Uhud", ["16:126", "16:127"],
      "أقسم النبي ﷺ غاضباً أن يمثّل بسبعين من قريش إن ظهر عليهم، فنزل: وإن عاقبتم فعاقبوا بمثل ما عُوقبتم به، ولئن صبرتم لهو خير للصابرين.",
      "حتى القسم في لحظة الغضب يُصحَّح بالوحي؛ القصاص بالمثل سقف لا أرضية.",
      "psychological_pressure", "leader_vs_follower", "justice_vs_privilege",
      "moral_rebuke", "procedural_justice_over_outcome", "legislation"),

    E("me_uhud_rumor_prophet_killed", 213, 3, "medinan_early",
      "إشاعة مقتل النبي ﷺ", "Rumor that the Prophet was killed",
      "Uhud", ["3:144", "3:154"],
      "انتشرت إشاعة أن محمداً ﷺ قتل، فانكسر قلب المسلمين، ولكن أنس بن النضر صاح: ما تصنعون بالحياة بعده؟ وانطلق يقاتل حتى استشهد.",
      "الرسالة أكبر من الرسول؛ من فهم المبدأ يواصل ولو سقط حامله الأول.",
      "psychological_pressure", "community_vs_outsider", "spiritual_integrity",
      "refusal_to_compromise", "chosen_hardship_over_compromise", "consolation"),

    E("me_mu_sab_martyrdom", 214, 3, "medinan_early",
      "استشهاد مصعب بن عمير معلم المدينة", "Martyrdom of Mus'ab ibn Umayr",
      "Uhud", ["33:23"],
      "استشهد مصعب بن عمير حامل الراية في أُحد، وكفّنه الصحابة في بردة إذا غطّوا بها رأسه ظهرت قدماه وإذا غطّوا قدميه ظهر رأسه.",
      "من ترك النعيم للحق يُكرَّم بأعلى المكانات؛ الكفن القصير شاهد على العظمة.",
      "existential_threat", "community_vs_outsider", "physical_safety",
      "endurance_without_retaliation", "chosen_hardship_over_compromise", "story"),

    E("me_abu_sufyan_higher_hubul", 215, 3, "medinan_early",
      "صيحة أبي سفيان «اعل هبل»", "Abu Sufyan shouts 'Exalted be Hubal'",
      "Uhud", ["3:139"],
      "صاح أبو سفيان بعد أحد: اعل هبل، فردّ عليه النبي ﷺ بأمر عمر: الله أعلى وأجل، فردّ أبو سفيان: يوم بيوم بدر والحرب سجال.",
      "المعركة الإعلامية توازي المعركة الميدانية؛ كل صيحة تُحتاج إلى ردّ مكافئ.",
      "verbal_attack", "believer_vs_unbeliever", "truth_vs_falsehood",
      "confrontation_with_truth", "public_declaration", "argument"),

    E("me_uhud_casualties_70", 216, 3, "medinan_early",
      "مقتل سبعين من المسلمين في أُحد", "Seventy Muslim casualties at Uhud",
      "Uhud", ["3:140", "3:141", "3:142"],
      "قُتل في أُحد سبعون من المسلمين، معظمهم من الأنصار، وكانت صدمة أعقبت نشوة بدر.",
      "الانتصار لا يعني الاستمرار في النصر؛ الابتلاء سنّة لتمحيص الصفوف.",
      "existential_threat", "community_vs_outsider", "collective_survival",
      "endurance_without_retaliation", "divine_testing_mechanism", "warning"),

    E("me_hamra_asad_pursuit", 217, 3, "medinan_early",
      "غزوة حمراء الأسد", "Ghazwa of Hamra al-Asad",
      "Hamra al-Asad", ["3:172", "3:173", "3:174"],
      "بعد أحد خرج النبي ﷺ في طلب قريش إلى حمراء الأسد بمن شهد المعركة فقط (الجرحى أولهم) ليُظهر القوة لقريش.",
      "الظهور بعد الصدمة أعلى من الضربة الأولى؛ القائد يحوّل الخسارة إلى فرصة معنوية.",
      "political_pressure", "community_vs_outsider", "collective_survival",
      "active_resistance", "chosen_hardship_over_compromise", "command"),

    E("me_raji_betrayal", 218, 4, "medinan_early",
      "غدرة الرجيع وقتل المبعوثين", "Betrayal at al-Raji' and killing of the missionaries",
      "Al-Raji", ["3:173"],
      "طلب قوم من عضل والقارة معلمين من النبي ﷺ فبعث معهم ستة (أو عشرة) من أصحابه، فغدر بهم المبعوثون وسلّموهم إلى قريش التي قتلتهم.",
      "الغدر باسم الطلب العلمي أبشع أنواع الغدر؛ الأمانة تُنقض بأبسط المنافع.",
      "internal_betrayal", "teacher_vs_student", "trust_between_parties",
      "endurance_without_retaliation", "refusing_to_legitimize_falsehood", "warning"),

    E("me_khubayb_execution", 219, 4, "medinan_early",
      "استشهاد خبيب بن عدي في مكة", "Martyrdom of Khubayb ibn Adi in Mecca",
      "Mecca", ["3:173"],
      "أُسر خبيب بن عدي بعد الرجيع وبيع في مكة، فصلبته قريش وهو يقرأ الشعر والقرآن، وصلى ركعتين قبل الصلب فكانت سنة لكل مصلوب.",
      "لحظة الموت يُختتم بها العمل؛ ركعتان قبل الاستشهاد تُصبحان سنّة.",
      "existential_threat", "claimant_vs_accused", "physical_safety",
      "endurance_without_retaliation", "chosen_hardship_over_compromise", "story"),

    E("me_bir_mauna_massacre", 220, 4, "medinan_early",
      "مذبحة بئر معونة", "Bir Ma'una massacre",
      "Bir Ma'una", ["3:169"],
      "أرسل النبي ﷺ سبعين من القراء بطلب أبي البراء إلى بئر معونة ليعلّموا نجداً، فغدر بهم عامر بن الطفيل وحلفاؤه من بني سُليم فقتلوا القراء كلهم.",
      "خسارة العلماء دفعة واحدة ضربة للأمة؛ الحزن على العلماء أبلغ من الحزن على الجنود.",
      "internal_betrayal", "teacher_vs_student", "community_cohesion",
      "endurance_without_retaliation", "knowledge_before_action", "consolation"),

    E("me_bir_mauna_dua_against", 221, 4, "medinan_early",
      "قنوت النبي ﷺ بعد بئر معونة شهراً", "Prophet's qunut for a month after Bir Ma'una",
      "Medina", ["3:128"],
      "قنت النبي ﷺ شهراً في صلاة الفجر يدعو على رعل وذكوان وعُصية بعد غدرة بئر معونة، ثم نزل: ليس لك من الأمر شيء.",
      "الدعاء على المعتدي مشروع لكنه قد يُسحب؛ مصير العقاب بيد الله لا بيد المظلوم.",
      "psychological_pressure", "leader_vs_follower", "justice_vs_privilege",
      "moral_rebuke", "limits_of_personal_discretion", "rebuke"),

    E("me_nadr_expulsion", 222, 4, "medinan_early",
      "إجلاء بني النضير", "Expulsion of Banu al-Nadir",
      "Medina", ["59:1", "59:2", "59:3", "59:4", "59:5", "59:6"],
      "تآمرت بنو النضير على قتل النبي ﷺ برمي حجر عليه من فوق جدار، فحاصرهم النبي حتى نزلوا على الإجلاء يحملون ما تحمله إبلهم إلا السلاح.",
      "محاولة اغتيال القائد تُغيّر قواعد التعامل؛ الإجلاء عقوبة جماعية مبررة بعد خيانة جماعية.",
      "existential_threat", "community_vs_outsider", "collective_survival",
      "strategic_withdrawal", "accountability_proportional_to_power", "legislation"),

    E("me_nadr_palm_cutting", 223, 4, "medinan_early",
      "قطع نخيل بني النضير تكتيكياً", "Cutting Banu al-Nadir's palms tactically",
      "Medina", ["59:5"],
      "أمر النبي ﷺ بقطع بعض نخيل بني النضير حصاراً لهم، فقالت اليهود إن محمداً ينهى عن الفساد ويفعل، فنزل: ما قطعتم من لينة أو تركتموها قائمة على أصولها فبإذن الله.",
      "الاستثناءات العسكرية للقاعدة البيئية مشروعة؛ الضرورات تُبيح المحظورات بقدرها.",
      "economic_siege", "community_vs_outsider", "property_rights",
      "legal_innovation", "scaling_principle_to_context", "legislation"),

    E("me_nadr_treasures", 224, 4, "medinan_early",
      "تقسيم أموال بني النضير على المهاجرين", "Distributing Banu al-Nadir's wealth to Muhajirun",
      "Medina", ["59:7", "59:8", "59:9", "59:10"],
      "قسّم النبي ﷺ أموال بني النضير (فيء بلا قتال) على المهاجرين خاصة دون الأنصار، إلا رجلين من فقراء الأنصار، تعويضاً للمهاجرين عن فقرهم.",
      "التمييز الإيجابي للمحتاجين عدالة لا محاباة؛ العدل ليس القسمة بالتساوي دائماً.",
      "economic_siege", "ally_vs_ally_dispute", "livelihood",
      "legal_innovation", "protection_of_the_weak", "legislation"),

    E("me_hamra_cares_muslims", 225, 4, "medinan_early",
      "اهتمام نساء المدينة بجرحى أُحد", "Medina women care for Uhud's wounded",
      "Medina", ["3:165"],
      "خرجت نساء المدينة بعد أحد يُضمّدن الجرحى ويُقدّمن الماء للصحابة، ومنهن أم عمارة نسيبة التي قاتلت دون النبي ﷺ.",
      "المرأة المؤمنة شريكة في الميدان بأدوار متنوعة؛ الجهاد بالتمريض جهاد.",
      "physical_persecution", "community_vs_outsider", "physical_safety",
      "organizational_response", "solidarity_around_principle", "praise"),

    E("me_umm_umara_fights", 226, 3, "medinan_early",
      "دفاع أم عُمارة عن النبي ﷺ في أُحد", "Umm Umara defends the Prophet at Uhud",
      "Uhud", ["33:35"],
      "قاتلت أم عمارة نسيبة بنت كعب في أُحد بالسيف والقوس دون النبي ﷺ، وجُرحت اثني عشر جرحاً، فقال النبي: مقامها اليوم خير من مقام فلان وفلان.",
      "الشجاعة تُقدَّر بنوعية الفعل لا بجنس فاعله؛ المرأة في لحظة الدفاع قد تفوق كثيراً من الرجال.",
      "existential_threat", "community_vs_outsider", "physical_safety",
      "active_resistance", "protection_of_the_weak", "praise"),

    E("me_widow_uhud_question", 227, 3, "medinan_early",
      "امرأة تسأل عن النبي ﷺ وسط الفجيعة", "A woman asks about the Prophet amid tragedy",
      "Medina", ["3:139"],
      "جاءت امرأة من الأنصار بعد أحد تسأل عن النبي ﷺ لمّا بلغها مقتل زوجها وأخيها وأبيها، فلم تُبالِ بعد أن علمت أن النبي حي، وقالت: كل مصيبة بعدك جلل.",
      "التعلّق بالقائد فوق الأهل معيار الولاء الأعلى؛ الخطب يهون بسلامة الأصل.",
      "psychological_pressure", "community_vs_outsider", "family_integrity",
      "consolation_and_thabaat", "truth_before_kinship", "praise"),

    E("me_uhud_recovery_prayer", 228, 3, "medinan_early",
      "صلاة النبي ﷺ الجنازة على شهداء أُحد", "Prophet's funeral prayer over Uhud martyrs",
      "Uhud", ["3:169", "3:170"],
      "صلى النبي ﷺ على شهداء أُحد عشرة عشرة، ودفنهم في ثيابهم دون غسل ولا كفن، وجعل حمزة في العاشرة.",
      "الشهيد له أحكام مخصوصة في التكفين والدفن؛ دمه شاهد عليه.",
      "none", "community_vs_outsider", "community_cohesion",
      "legal_innovation", "witnessing_and_documentation", "legislation"),

    # ═══════════════ Legislation & incidents in years 1-3 AH ═══════════════
    E("me_ayat_wudu_travelers", 229, 3, "medinan_early",
      "آية الوضوء للمسافر ومن كان جنباً", "Verse of ablution for travelers and those in janaba",
      "Medina", ["4:43"],
      "نزلت أحكام الوضوء والغسل والتيمم في سورة النساء تنظم عبادة المسلمين في حالات الصحة والمرض والسفر.",
      "العبادة تراعي القدرة؛ الشريعة ترحم في مواضع المشقة.",
      "none", "community_vs_outsider", "spiritual_integrity",
      "legal_innovation", "scaling_principle_to_context", "legislation"),

    E("me_sada_khalilullah_question", 230, 2, "medinan_early",
      "سؤال عن الإنفاق: ماذا ينفقون", "Question about spending: what to give",
      "Medina", ["2:215", "2:219"],
      "سأل بعض الصحابة النبي ﷺ: ماذا ننفق من أموالنا؟ فنزل قل ما أنفقتم من خير فللوالدين والأقربين واليتامى والمساكين وابن السبيل.",
      "الإنفاق له ترتيب أولوية؛ الأقربون أولى بالمعروف.",
      "none", "community_vs_outsider", "livelihood",
      "legal_innovation", "protection_of_the_weak", "legislation"),

    E("me_sada_orphans_mingle", 231, 2, "medinan_early",
      "سؤال عن خلط أموال اليتامى بأموال الأوصياء", "Question on mixing orphans' property with guardians'",
      "Medina", ["2:220"],
      "خاف المسلمون بعد نزول الوعيد في أكل مال اليتيم أن يخلطوا طعامهم بطعام اليتامى، فنزل قل إصلاح لهم خير وإن تخالطوهم فإخوانكم.",
      "التشريع يراعي الكلفة التطبيقية؛ تجنب المباح إفراط كتجاوز الحرام.",
      "legal_coercion", "community_vs_outsider", "property_rights",
      "clarification", "scaling_principle_to_context", "legislation"),

    E("me_sada_khamr_first", 232, 2, "medinan_early",
      "أول نزول في الخمر: يسألونك عن الخمر", "First revelation about wine",
      "Medina", ["2:219"],
      "نزل في أول مراحل تحريم الخمر قوله يسألونك عن الخمر والميسر قل فيهما إثم كبير ومنافع للناس، فتركها بعض الصحابة وأبقاها آخرون.",
      "التدرج في تحريم العادات المتأصلة؛ الوعي يسبق الإلزام.",
      "none", "community_vs_outsider", "spiritual_integrity",
      "gradualism_in_hard_change", "gradualism_in_hard_change", "clarification"),

    E("me_sada_qital_haram_month", 233, 2, "medinan_early",
      "سؤال عن القتال في الشهر الحرام", "Question on fighting in a sacred month",
      "Medina", ["2:217"],
      "بعد سرية عبد الله بن جحش في رجب عابت قريش على المسلمين القتال في الشهر الحرام، فنزل قل قتال فيه كبير وصد عن سبيل الله أكبر.",
      "الميزان بين المحرّمات يختار أهونها؛ الصد عن الدين أكبر من انتهاك الشهر.",
      "legal_coercion", "principled_minority_vs_powerful_majority", "religious_freedom",
      "clarification", "scaling_principle_to_context", "argument"),

    E("me_sada_hayd", 234, 3, "medinan_early",
      "سؤال عن المحيض", "Question on menstruation",
      "Medina", ["2:222"],
      "سأل الصحابة عن معاشرة النساء في الحيض بعد ملاحظة عادات اليهود الشديدة، فنزل يسألونك عن المحيض قل هو أذى فاعتزلوا النساء في المحيض.",
      "التوسط بين التشدد والتسيّب في أحكام العلاقة الزوجية؛ الأذى محلّه محدد.",
      "intellectual_challenge", "spouse_vs_spouse", "family_integrity",
      "clarification", "boundaries_in_intimate_relations", "legislation"),

    E("me_sada_yatama", 235, 3, "medinan_early",
      "الأمر بالإحسان إلى اليتامى", "Command to treat orphans kindly",
      "Medina", ["2:220", "4:2"],
      "نزلت آيات متعددة في اليتامى، منها التحذير من أكل أموالهم والحث على الإحسان إليهم وتزويج من يحلّ منهم.",
      "اليتيم معيار صحة المجتمع؛ معاملته تكشف إنسانية الجماعة.",
      "legal_coercion", "community_vs_outsider", "property_rights",
      "legal_innovation", "protection_of_the_weak", "legislation"),

    E("me_sada_anfal_distribution", 236, 2, "medinan_early",
      "سؤال عن الأنفال بعد بدر", "Question on the spoils after Badr",
      "Medina", ["8:1", "8:41"],
      "اختلف الصحابة في قسمة الغنائم بعد بدر بين من جمعها ومن طارد العدو، فنزل يسألونك عن الأنفال قل الأنفال لله والرسول.",
      "قسمة الغنائم بحكم الله لا بالاجتهاد الفردي؛ القائد ينفذ الحكم.",
      "legal_coercion", "ally_vs_ally_dispute", "property_rights",
      "clarification", "consultation_before_decision", "legislation"),

    E("me_sada_khamr_second", 237, 3, "medinan_early",
      "ثاني نزول في الخمر: لا تقربوا الصلاة سكارى", "Second revelation on wine: pray not while intoxicated",
      "Medina", ["4:43"],
      "تقدّم رجل إلى الصلاة ثملاً فخلط في القراءة خلطاً فاحشاً، فنزل يا أيها الذين آمنوا لا تقربوا الصلاة وأنتم سكارى.",
      "المرحلة الثانية من تحريم الخمر بربطها بأهم الشعائر؛ الصلاة معيار الإصلاح.",
      "moral_failure_by_self", "community_vs_outsider", "spiritual_integrity",
      "gradualism_in_hard_change", "gradualism_in_hard_change", "prohibition"),

    E("me_first_eid_adha", 238, 2, "medinan_early",
      "أول عيد أضحى وأول أضحية", "First Eid al-Adha and first sacrifice",
      "Medina", ["22:34", "108:2"],
      "ضحّى النبي ﷺ أول أضحى في المدينة بكبشين أملحين أقرنين، وسنّ الأضحية في المسلمين.",
      "الذبح شعيرة تعظيم؛ إبراهيم عليه السلام أصلها.",
      "none", "community_vs_outsider", "spiritual_integrity",
      "legal_innovation", "teaching_through_demonstration", "legislation"),

    E("me_first_jumua_adhan", 239, 1, "medinan_early",
      "تأسيس أذان الجمعة", "Establishing the Friday call to prayer",
      "Medina", ["62:9"],
      "شرع النبي ﷺ أذان الجمعة حين كثر المسلمون في المدينة، ليجتمعوا على توقيت موحد كل أسبوع.",
      "العبادة الجماعية تحتاج إلى نداء واضح؛ الشعائر المرئية تُوحّد الجماعة.",
      "none", "community_vs_outsider", "community_cohesion",
      "organizational_response", "solidarity_around_principle", "legislation"),

    E("me_first_khutba_jumua", 240, 1, "medinan_early",
      "أول خطبة جمعة كاملة في المدينة", "First full Friday sermon in Medina",
      "Medina", ["62:9", "62:11"],
      "ألقى النبي ﷺ أول خطبة جمعة كاملة في المدينة بعد الاستقرار، ثم صلّى ركعتين علانية.",
      "الخطبة أسبوعية تُحيي النفوس بالتذكير؛ الكلمة المنبرية قيادة معنوية.",
      "none", "leader_vs_follower", "community_cohesion",
      "public_declaration", "teaching_through_demonstration", "legislation"),

    E("me_zakat_zayd_collectors", 241, 2, "medinan_early",
      "إرسال جامعي الزكاة إلى القبائل", "Sending zakat collectors to tribes",
      "Medina", ["9:60", "9:103"],
      "أرسل النبي ﷺ عمّال الزكاة إلى القبائل المسلمة لجمعها وتوزيعها على مستحقيها في كل قبيلة.",
      "الإدارة اللامركزية للمال العام؛ كل منطقة تُصرف زكاتها في فقرائها أولاً.",
      "none", "community_vs_outsider", "livelihood",
      "organizational_response", "economic_justice_as_worship", "legislation"),

    E("me_sa_d_mother_question", 242, 2, "medinan_early",
      "بر سعد لأمه رغم شركها", "Sa'd's kindness to his mother despite her shirk",
      "Medina", ["31:14", "31:15"],
      "كانت أم سعد بن أبي وقاص على الشرك وتضغط عليه، فنزل وصيناه بوالديه حملته أمه وهناً على وهن، وبأن يصاحبهما بالمعروف.",
      "البر بالوالدين واجب حتى مع الشرك؛ الحدود لا تُلغى الحقوق الأساسية.",
      "family_pressure", "parent_vs_child", "family_integrity",
      "private_counsel", "scaling_principle_to_context", "legislation"),

    E("me_fatima_birth_hasan", 243, 3, "medinan_early",
      "ولادة الحسن بن علي", "Birth of al-Hasan ibn Ali",
      "Medina", ["3:159"],
      "وُلد الحسن بن علي بن أبي طالب في السنة الثالثة من الهجرة، فسمّاه النبي ﷺ الحسن وقال: ابني هذا سيّد.",
      "البشارة بمستقبل الجيل القادم؛ القائد يُؤسس لقيادات بعده.",
      "none", "family_pressure", "generational_legacy",
      "consolation_and_thabaat", "solidarity_around_principle", "praise"),

    E("me_first_adabi_feast", 244, 1, "medinan_early",
      "دعوة النبي ﷺ لأول وليمة في المدينة", "Prophet's invitation to first walima in Medina",
      "Medina", ["33:53"],
      "دعا النبي ﷺ أصحابه لأول وليمة كبرى في المدينة، واعتنى بآداب الطعام وعدم تطويل الجلسة بعده.",
      "آداب الولائم تحمي خصوصية المضيف؛ الضيف الحسن يعرف متى يقوم.",
      "none", "community_vs_outsider", "trust_between_parties",
      "teaching_through_demonstration", "boundaries_in_intimate_relations", "legislation"),

    E("me_dhat_alriqa_first", 245, 3, "medinan_early",
      "غزوة ذات الرقاع (إحدى الروايات)", "Ghazwa of Dhat al-Riqa' (one account)",
      "Dhat al-Riqa'", ["4:101", "4:102"],
      "خرج النبي ﷺ إلى ذات الرقاع لقتال بني محارب وبني ثعلبة، ونزلت في هذه الغزوة أحكام صلاة الخوف.",
      "الصلاة لا تسقط في الخوف؛ الشريعة تجد صيغة لكل حال.",
      "existential_threat", "community_vs_outsider", "spiritual_integrity",
      "legal_innovation", "scaling_principle_to_context", "legislation"),

    E("me_salat_khawf_revelation", 246, 3, "medinan_early",
      "نزول صلاة الخوف", "Revelation of fear prayer (salat al-khawf)",
      "Dhat al-Riqa'", ["4:101", "4:102", "4:103"],
      "نزلت أحكام صلاة الخوف في ذات الرقاع بصيغها المتعددة، تسمح للجيش أن يصلي والعدو بين أيديهم.",
      "حتى في لحظة الاشتباك تبقى الصلة بالله؛ العبادة تستوعب كل ظرف.",
      "existential_threat", "community_vs_outsider", "spiritual_integrity",
      "legal_innovation", "scaling_principle_to_context", "legislation"),

    E("me_tribe_of_ghatafan_spies", 247, 3, "medinan_early",
      "جاسوس من غطفان على النبي ﷺ نائماً", "Ghatafan spy while the Prophet slept",
      "Dhat al-Riqa'", ["5:11"],
      "جاء رجل من غطفان والنبي ﷺ نائم تحت شجرة فأخذ سيفه وأيقظه قائلاً: من يمنعك مني؟ فقال النبي: الله، فسقط السيف من يده.",
      "الله يحمي عبده في لحظة الضعف الكامل؛ قوة الكلمة الواحدة تسقط السلاح.",
      "existential_threat", "individual_vs_majority", "physical_safety",
      "refuge_with_god_against_despair", "refuge_with_god_against_despair", "story"),

    E("me_uyayna_raid_prophet_camels", 248, 3, "medinan_early",
      "إغارة عيينة بن حصن على إبل النبي ﷺ", "Uyayna ibn Hisn raids the Prophet's camels",
      "Medina area", ["8:57"],
      "أغار عيينة بن حصن الفزاري على لقاح النبي ﷺ فقتل الراعي واستولى على الإبل، فلحقه المسلمون بقيادة سلمة بن الأكوع.",
      "الإغارة على الموارد الاقتصادية حرب غير معلنة؛ الرد الفوري يحفظ الهيبة.",
      "economic_siege", "community_vs_outsider", "livelihood",
      "active_resistance", "accountability_proportional_to_power", "warning"),

    E("me_salama_akwa_chase", 249, 3, "medinan_early",
      "مطاردة سلمة بن الأكوع للمغيرين", "Salama ibn al-Akwa' chases the raiders",
      "Medina area", ["8:57"],
      "انطلق سلمة بن الأكوع راجلاً في مطاردة المغيرين وهو يرميهم بسهامه حتى استرد الإبل، وأثنى عليه النبي ﷺ.",
      "البطولة الفردية قد تُنجز ما لا ينجزه الجيش؛ الشجاعة في لحظتها لا تنتظر الإذن.",
      "existential_threat", "individual_vs_majority", "property_rights",
      "active_resistance", "chosen_hardship_over_compromise", "praise"),

    E("me_suhayb_second_hijra", 250, 1, "medinan_early",
      "وصول صهيب إلى المدينة", "Suhayb arrives in Medina",
      "Medina", ["2:207"],
      "وصل صهيب الرومي إلى المدينة بعد أن دفع كل ماله فداء لنفسه في مكة، فقال له النبي ﷺ: ربح البيع يا أبا يحيى.",
      "المبدأ أغلى من كل مال؛ الربح الحقيقي في الآخرة.",
      "economic_siege", "individual_vs_majority", "livelihood",
      "strategic_withdrawal", "wealth_as_trust_not_ownership", "praise"),

    # Additional entries 251-300 to fill to 150 events
    E("me_abu_dharr_islam_declaration", 251, 1, "medinan_early",
      "عودة أبي ذر ليُعلن إسلامه بقومه", "Abu Dharr returns to his people to proclaim Islam",
      "Ghifar", ["93:6", "93:7"],
      "عاد أبو ذر إلى قومه بني غفار بعد إسلامه في مكة فأسلم نصفهم على يديه، ثم قدم بهم إلى المدينة بعد الهجرة.",
      "الداعية الناجح يحمل قومه معه؛ الفرد قد يكون مفتاح قبيلة.",
      "none", "community_vs_outsider", "community_cohesion",
      "seeking_allies", "teaching_through_demonstration", "praise"),

    E("me_tibb_nabawi_hijama", 252, 3, "medinan_early",
      "الحجامة علاجاً للنبي ﷺ", "Cupping as treatment for the Prophet",
      "Medina", ["26:80"],
      "احتجم النبي ﷺ في عدة مواضع وأمر بها أصحابه، وقال: نعم الدواء الحجامة، مشيراً إلى أن الدواء جزء من الشرع.",
      "التداوي من السنة؛ الإيمان لا يمنع الأخذ بالأسباب الطبية.",
      "none", "self_vs_self", "physical_safety",
      "teaching_through_demonstration", "knowledge_before_action", "legislation"),

    E("me_prophet_simple_food", 253, 2, "medinan_early",
      "بساطة طعام النبي ﷺ في المدينة", "Simplicity of the Prophet's food in Medina",
      "Medina", ["7:31"],
      "مرّت أشهر والنبي ﷺ لا يُوقد في بيته نار، وكان يأكل التمر والماء، فإذا جاء الطعام قليلاً قبله.",
      "الزهد قدوة لا فرض؛ القائد في بيته نموذج للتوسّط.",
      "economic_siege", "self_vs_self", "personal_dignity",
      "teaching_through_demonstration", "leadership_accountability", "praise"),

    E("me_prophet_cloak_single", 254, 2, "medinan_early",
      "اكتفاء النبي ﷺ بلباس واحد", "Prophet's contentment with a single garment",
      "Medina", ["7:31", "7:32"],
      "لبس النبي ﷺ ثوباً واحداً غُسل ثم يُعاد لبسه حتى تحصل له ثياب أخرى، وكان ذلك في سنوات الشدة.",
      "الحاجة تُسدّ بلا إسراف؛ التواضع أفضل زينة.",
      "economic_siege", "self_vs_self", "personal_dignity",
      "teaching_through_demonstration", "leadership_accountability", "praise"),

    E("me_new_converts_welcomed", 255, 2, "medinan_early",
      "استقبال النبي ﷺ للوافدين الجدد", "Prophet welcomes new arrivals",
      "Medina", ["9:108"],
      "كان النبي ﷺ يستقبل كل وافد جديد بلطف ويسأله عن قومه ويُعلّمه أصول الدين، فصارت المدينة بيت الهجرة لكل مسلم.",
      "الحفاوة بالقادم جزء من التعليم؛ الاستقبال الحسن أول درس.",
      "none", "community_vs_outsider", "community_cohesion",
      "teaching_through_demonstration", "solidarity_around_principle", "praise"),

    E("me_quran_teaching_morning", 256, 2, "medinan_early",
      "حلقات القرآن في المسجد صباحاً", "Quran study circles at the mosque in the morning",
      "Medina", ["2:121"],
      "عقد النبي ﷺ حلقات تعليم القرآن في المسجد النبوي، فكان بعض الصحابة يخرجون كل صباح يتعلمون الآيات الجديدة.",
      "التعليم المستمر رسالة الأمة الأولى؛ العلم يُغذّى صباحاً قبل أي عمل.",
      "none", "teacher_vs_student", "knowledge_access",
      "organizational_response", "knowledge_before_action", "praise"),

    E("me_sahaba_write_quran", 257, 2, "medinan_early",
      "كتابة الصحابة للقرآن في صحف متفرقة", "Companions writing the Quran on various surfaces",
      "Medina", ["56:78", "80:13", "80:14", "80:15", "80:16"],
      "كتب الصحابة القرآن على الرقاع والعظام والألواح والسعف، فلم تُترك آية نزلت إلا وكتبها كتبة الوحي.",
      "التوثيق شرط الحفظ؛ الذاكرة البشرية تحتاج إلى حارس مادي.",
      "none", "community_vs_outsider", "knowledge_access",
      "witnessing_and_documentation", "witnessing_and_documentation", "legislation"),

    E("me_kutbat_alwahi_select", 258, 1, "medinan_early",
      "اختيار كتبة الوحي الرسميين", "Selection of official Quran scribes",
      "Medina", ["96:4"],
      "اختار النبي ﷺ عدداً من أصحابه ككتبة رسميين للوحي، منهم زيد بن ثابت وأُبيّ بن كعب وعلي وعثمان ومعاوية.",
      "المؤسسة التعليمية تحتاج كادراً مختصاً؛ الكتابة فن يُعهد به إلى من يُحسنه.",
      "none", "teacher_vs_student", "knowledge_access",
      "organizational_response", "knowledge_before_action", "command"),

    E("me_morning_routine_prophet", 259, 1, "medinan_early",
      "أذكار الصباح اليومية في المسجد", "Daily morning remembrance at the mosque",
      "Medina", ["30:17", "30:18"],
      "سنّ النبي ﷺ لأصحابه الجلوس في مصلاه بعد الفجر حتى تطلع الشمس ذاكراً الله قارئاً، وأثنى على من فعل ذلك.",
      "الانضباط اليومي يبني الشخصية؛ صلة الصباح تُبارك اليوم كله.",
      "none", "community_vs_outsider", "spiritual_integrity",
      "teaching_through_demonstration", "consistency_public_and_private", "praise"),

    E("me_hadith_school_suffa", 260, 1, "medinan_early",
      "دروس أهل الصُفّة الخاصة", "Special lessons for the people of al-Suffa",
      "Medina", ["18:28"],
      "كان أهل الصُفّة يجلسون للنبي ﷺ في تفرّغ تام يتعلمون منه ويحفظون حديثه، فكان أبو هريرة منهم من أكثر رواة الحديث.",
      "التفرغ للعلم يُخرج حُفّاظ الأمة؛ الرواية تُحفظ بالوقت لا بالذكاء فقط.",
      "none", "teacher_vs_student", "knowledge_access",
      "organizational_response", "knowledge_before_action", "praise"),

    E("me_sadaqat_al_fitr_institution", 261, 2, "medinan_early",
      "تأسيس صدقة الفطر كنظام", "Establishing Zakat al-Fitr as a system",
      "Medina", ["2:184"],
      "فرض النبي ﷺ زكاة الفطر صاعاً من تمر أو شعير على كل صغير وكبير حر وعبد من المسلمين قبل صلاة العيد.",
      "توحيد الإجراء يُسهّل التنفيذ؛ الصاع معيار عادل لا يتحمل جدلاً.",
      "economic_siege", "community_vs_outsider", "livelihood",
      "legal_innovation", "economic_justice_as_worship", "legislation"),

    E("me_jabir_thirst_miracle", 262, 3, "medinan_early",
      "تكثير النبي ﷺ الماء في غزوة", "Prophet multiplies water in an expedition",
      "Expedition area", ["5:11"],
      "عطش الجيش في إحدى الغزوات فوضع النبي ﷺ يده في إناء ماء قليل فجعل الماء ينبع من بين أصابعه حتى روي الجيش.",
      "الآيات الكبرى تأتي في موضع الحاجة الجماعية؛ الله لا يترك أولياءه في عطش الأزمة.",
      "existential_threat", "community_vs_outsider", "livelihood",
      "refuge_with_god_against_despair", "refuge_with_god_against_despair", "story"),

    E("me_food_multiplication_miracle", 263, 3, "medinan_early",
      "بركة النبي ﷺ في الطعام القليل", "Barakah in little food by the Prophet",
      "Medina", ["7:96"],
      "أخرج جابر بن عبد الله طعاماً قليلاً في حفر الخندق فدعا النبي ﷺ أهل الخندق كلهم (ألفاً) وأكلوا جميعاً من طعام واحد وبقي.",
      "البركة في القليل مع الإيمان تُغني عن الكثير بلا إيمان؛ الدعاء يُضاعف الأثر.",
      "economic_siege", "community_vs_outsider", "livelihood",
      "refuge_with_god_against_despair", "wealth_as_trust_not_ownership", "story"),

    E("me_early_quran_compilation", 264, 3, "medinan_early",
      "حفّاظ القرآن في أُحد", "Quran memorizers at Uhud",
      "Uhud", ["3:169"],
      "استشهد في أُحد عدد من حفظة القرآن الذين كانوا يقرؤون على الناس، فكان استشهادهم خسارة علمية كبرى.",
      "حفظ القرآن ميراث الجيل؛ الشهادة في الميدان لا تُلغي قيمة العلم.",
      "existential_threat", "community_vs_outsider", "knowledge_access",
      "endurance_without_retaliation", "knowledge_before_action", "consolation"),

    E("me_bilal_dua_for_medina", 265, 1, "medinan_early",
      "دعاء النبي ﷺ للمدينة بالحب", "Prophet's supplication for love of Medina",
      "Medina", ["3:164"],
      "مرض بلال وأبو بكر من حمى المدينة، فدعا النبي ﷺ قائلاً: اللهم حبّب إلينا المدينة كحبنا مكة أو أشد، وبارك لنا في صاعها ومُدّها.",
      "الدعاء بتحويل المشاعر جائز؛ الوطن الجديد يحتاج إلى محبة مزروعة.",
      "psychological_pressure", "community_vs_outsider", "community_cohesion",
      "refuge_with_god_against_despair", "solidarity_around_principle", "praise"),

    E("me_abdallah_masud_reciter", 266, 1, "medinan_early",
      "ثناء النبي ﷺ على قراءة ابن مسعود", "Prophet's praise of Ibn Mas'ud's recitation in Medina",
      "Medina", ["7:204"],
      "طلب النبي ﷺ من ابن مسعود أن يقرأ عليه القرآن، فقال ابن مسعود: أأقرأ وعليك أُنزل؟ فقال النبي: إني أحب أن أسمعه من غيري، فلما بلغ الشاهد بكى النبي.",
      "القائد يتلقى من أصحابه ما أعطاهم؛ الدمعة على القرآن شاهدة على الأثر.",
      "none", "teacher_vs_student", "knowledge_access",
      "private_counsel", "teaching_through_demonstration", "praise"),

    E("me_first_call_prayer_formula", 267, 1, "medinan_early",
      "تأسيس صيغة الأذان الحالية", "Establishing the current adhan formula",
      "Medina", ["5:58"],
      "استقرّت صيغة الأذان: الله أكبر، أشهد أن لا إله إلا الله، أشهد أن محمداً رسول الله، حي على الصلاة، حي على الفلاح.",
      "النصوص الشعائرية تُحدَّد بدقّة؛ التوحيد في الصيغة يُسهّل الحفظ.",
      "none", "community_vs_outsider", "community_cohesion",
      "legal_innovation", "consistency_public_and_private", "legislation"),

    E("me_fasting_three_days", 268, 2, "medinan_early",
      "صيام ثلاثة أيام من كل شهر", "Fasting three days of each month",
      "Medina", ["2:184"],
      "أمر النبي ﷺ أصحابه بصيام ثلاثة أيام من كل شهر إضافة إلى رمضان، مفضّلاً الأيام البيض (13، 14، 15).",
      "العبادة المستدامة أحب إلى الله من العارض؛ القليل الدائم أثبت من الكثير المنقطع.",
      "none", "self_vs_self", "spiritual_integrity",
      "legal_innovation", "consistency_public_and_private", "legislation"),

    E("me_qiyam_al_layl_community", 269, 2, "medinan_early",
      "صلاة الليل في المسجد جماعة", "Night prayer in congregation at the mosque",
      "Medina", ["73:20"],
      "صلّى النبي ﷺ قيام الليل في المسجد جماعة في رمضان ثلاث ليال، ثم ترك ذلك خوفاً من أن تُفرض، فصلى الناس فرادى.",
      "ترك الأفضل لحكمة أعلى من الأفضل؛ القائد يتجنب فرض ما لا يطاق.",
      "none", "leader_vs_follower", "spiritual_integrity",
      "scaling_principle_to_context", "scaling_principle_to_context", "legislation"),

    E("me_meat_distribution_sacrifice", 270, 2, "medinan_early",
      "تقسيم لحم الأضحية", "Distribution of sacrifice meat",
      "Medina", ["22:28", "22:36"],
      "قسّم النبي ﷺ لحم أضحيته أثلاثاً: ثلث للبيت، وثلث للأقارب، وثلث للفقراء، وسنّ ذلك للأمة.",
      "الأضحية ليست للبيت فقط؛ الشعيرة يُشاركها المحتاج بالضرورة.",
      "none", "community_vs_outsider", "livelihood",
      "legal_innovation", "protection_of_the_weak", "legislation"),

    E("me_prayer_before_battle", 271, 2, "medinan_early",
      "الصلاة قبل المواجهات الكبرى", "Prayer before major confrontations",
      "Medina", ["2:153", "2:45"],
      "كان النبي ﷺ يُكثر من الصلاة قبل كل مواجهة كبرى، ويشجّع أصحابه على التضرّع والدعاء.",
      "القوة المعنوية تسبق القوة العسكرية؛ الصلة بالخالق أثبت الجنود.",
      "existential_threat", "leader_vs_follower", "spiritual_integrity",
      "refuge_with_god_against_despair", "refuge_with_god_against_despair", "command"),

    E("me_sadaqa_to_bashir", 272, 2, "medinan_early",
      "النعمان بن بشير وعطية أبيه", "Nu'man ibn Bashir and his father's gift",
      "Medina", ["2:177"],
      "وهب بشير ابنه النعمان عطية فجاء بالنبي ﷺ ليشهد، فسأل النبي: أفعلت بأولادك الآخرين مثل ذلك؟ قال: لا، فرفض النبي الشهادة وقال: اعدلوا بين أولادكم.",
      "العدل بين الأولاد واجب لا استحباب؛ المحاباة تُولّد العقوق.",
      "legal_coercion", "parent_vs_child", "family_integrity",
      "moral_rebuke", "procedural_justice_over_outcome", "legislation"),

    E("me_safwan_dream_interpretation", 273, 2, "medinan_early",
      "تفسير الرؤيا في الصباح", "Dream interpretation in the morning",
      "Medina", ["12:6"],
      "كان النبي ﷺ يسأل أصحابه بعد الفجر عن رؤاهم ويُفسّرها لهم، فكان ذلك تدريباً روحياً جماعياً.",
      "الحوار حول ما تحت الوعي نوع من التربية؛ القائد يهتم بعالم أصحابه الداخلي.",
      "none", "teacher_vs_student", "spiritual_integrity",
      "teaching_through_demonstration", "consultation_before_decision", "praise"),

    E("me_abu_burda_sheep", 274, 2, "medinan_early",
      "أبو بردة يضحّي قبل الصلاة", "Abu Burda sacrifices before the prayer",
      "Medina", ["22:36"],
      "ذبح أبو بردة بن نيار أضحيته قبل صلاة العيد، فقال له النبي ﷺ: شاتك شاة لحم لا أضحية، واجعلها لك من غيرها.",
      "توقيت العبادة شرط صحتها؛ الشعيرة لها بداية لا تُقدَّم عليها.",
      "legal_coercion", "teacher_vs_student", "spiritual_integrity",
      "clarification", "limits_of_personal_discretion", "legislation"),

    E("me_tahneek_newborn", 275, 1, "medinan_early",
      "تحنيك أبناء الصحابة عند الولادة", "Prophet blesses newborns with dates",
      "Medina", ["19:13"],
      "كان الصحابة يأتون بأبنائهم عند الولادة إلى النبي ﷺ ليُحنّكهم بتمرة يمضغها ويضعها في أفواههم ويُدعو لهم بالبركة.",
      "استقبال الجيل الجديد بالدعاء والبركة؛ التقاليد العائلية ذات صلة بالشريعة.",
      "none", "community_vs_outsider", "generational_legacy",
      "teaching_through_demonstration", "protection_of_the_weak", "praise"),

    E("me_abdullah_zubayr_first_muslim_born_medina", 276, 1, "medinan_early",
      "عبد الله بن الزبير أول مولود مسلم في المدينة", "Abdullah ibn al-Zubayr first Muslim born in Medina",
      "Medina", ["2:128"],
      "وُلد عبد الله بن الزبير بن العوام فكان أول مولود للمهاجرين في المدينة بعد الهجرة، فكبّر المسلمون فرحاً بكسر شائعة سحر اليهود.",
      "المواليد الجدد رسالة استمرار؛ الحياة تتغلب على كل محاولة إفنائها.",
      "none", "community_vs_outsider", "generational_legacy",
      "consolation_and_thabaat", "solidarity_around_principle", "praise"),

    E("me_abu_qatada_water", 277, 2, "medinan_early",
      "أبو قتادة يحفظ ماء النبي ﷺ في السفر", "Abu Qatada guards the Prophet's water in travel",
      "Expedition route", ["5:6"],
      "في سفر عطش فيه الجيش كلّف النبي ﷺ أبا قتادة بحفظ ماء قليل، فلما احتاج الجيش سقاهم النبي منه حتى رووا جميعاً.",
      "الأمانة على المورد الصغير اختبار قبل الكبير؛ البركة تزيد القليل.",
      "existential_threat", "community_vs_outsider", "livelihood",
      "witnessing_and_documentation", "trust_is_earned_by_consistency", "story"),

    E("me_prophet_sleep_short", 278, 2, "medinan_early",
      "قصر نوم النبي ﷺ لكثرة الأعمال", "Short sleep of the Prophet due to many duties",
      "Medina", ["73:1", "73:2", "73:3", "73:4"],
      "كان النبي ﷺ ينام نصف الليل أو أقل ويقوم باقيه، لكثرة ما يتحمّله من أعباء القيادة والعبادة.",
      "القائد يتحمّل ما لا يتحمّله غيره؛ النوم القليل ثمن المسؤولية.",
      "psychological_pressure", "self_vs_self", "spiritual_integrity",
      "teaching_through_demonstration", "leadership_accountability", "praise"),

    E("me_nakhila_first_dates", 279, 1, "medinan_early",
      "أول حصاد تمر للمسلمين في المدينة", "First date harvest for Muslims in Medina",
      "Medina", ["6:141"],
      "جاء أول حصاد تمر للمسلمين في المدينة فنزلت أحكام العُشر ونصف العُشر، وقسّمها المسلمون بين الأسر.",
      "الثمار لها حق اجتماعي عند الحصاد؛ لا يُقبل فرد يأكل وجاره جائع.",
      "none", "community_vs_outsider", "livelihood",
      "legal_innovation", "economic_justice_as_worship", "legislation"),

    E("me_khums_institution", 280, 2, "medinan_early",
      "تأسيس الخمس من الغنائم", "Establishing the khums of booty",
      "Medina", ["8:41"],
      "نزل تشريع الخمس: أن ما يغنمه الجيش من شيء فلله خمسه وللرسول ولذي القربى واليتامى والمساكين وابن السبيل.",
      "حقوق الفئات الاجتماعية مضمونة من أرباح الجيش؛ الحرب ليست لأفرادها فقط.",
      "none", "community_vs_outsider", "property_rights",
      "legal_innovation", "economic_justice_as_worship", "legislation"),

    E("me_poet_hassan_defense", 281, 3, "medinan_early",
      "حسان بن ثابت شاعر النبي ﷺ", "Hassan ibn Thabit the Prophet's poet",
      "Medina", ["26:227"],
      "دعا النبي ﷺ حسان بن ثابت إلى الدفاع عنه شعراً في وجه شعراء قريش، ووضع له منبراً في المسجد يُلقي منه قصائده.",
      "الكلمة سلاح كالسيف؛ المعركة الثقافية توازي المعركة الميدانية.",
      "verbal_attack", "community_vs_outsider", "reputation_honor",
      "intellectual_rebuttal", "public_declaration", "command"),

    E("me_kab_zuhayr_islam", 282, 3, "medinan_early",
      "إسلام كعب بن زهير وقصيدة البردة", "Islam of Ka'b ibn Zuhayr and Qasidat al-Burda",
      "Medina", ["7:199"],
      "كان كعب بن زهير يهجو النبي ﷺ فأهدر دمه، ثم جاء تائباً فأنشد قصيدة بانت سعاد فأعطاه النبي بردته.",
      "التوبة مفتوحة لأعتى الهاجين؛ القلم الجارح يتحوّل إلى مادح بحسن الاستقبال.",
      "verbal_attack", "claimant_vs_accused", "reputation_honor",
      "forgiveness_from_power", "repentance_as_open_door", "praise"),

    E("me_burda_robe_gift", 283, 3, "medinan_early",
      "بردة النبي ﷺ لكعب بن زهير", "The Prophet's mantle given to Ka'b",
      "Medina", ["7:199"],
      "خلع النبي ﷺ بردته وألقاها على كعب بن زهير بعد إسلامه، فاحتفظ بها كعب وتداولها الخلفاء بعده.",
      "الرموز المادية تحمل قصصاً أعمق من ثمنها؛ هدية القائد تتحوّل إلى إرث.",
      "none", "teacher_vs_student", "reputation_honor",
      "forgiveness_from_power", "teaching_through_demonstration", "praise"),

    E("me_prayer_times_fixed", 284, 1, "medinan_early",
      "تثبيت مواقيت الصلوات الخمس", "Fixing the times of the five prayers",
      "Medina", ["17:78", "20:130"],
      "استقرّت مواقيت الصلوات الخمس في المدينة بتعليم جبريل للنبي ﷺ بداياتها ونهاياتها، فعرف المسلمون متى يؤذّن ومتى يُقام.",
      "الانضباط في التوقيت شرط صحة العبادة؛ الوقت ليس اختيارياً.",
      "none", "community_vs_outsider", "spiritual_integrity",
      "legal_innovation", "consistency_public_and_private", "legislation"),

    E("me_fatima_household_chores", 285, 2, "medinan_early",
      "فاطمة تعمل في بيتها دون خادم", "Fatima works in her home without servant",
      "Medina", ["2:233"],
      "شكت فاطمة إلى أبيها تعب يديها من الرحى، فعلّمها النبي ﷺ أذكاراً بدل أن يعطيها خادمة.",
      "العبادة تُغني عن الراحة المادية أحياناً؛ القائد يُربّي أهله قبل غيرهم.",
      "economic_siege", "parent_vs_child", "family_integrity",
      "teaching_through_demonstration", "leadership_accountability", "legislation"),

    E("me_family_kindness_principle", 286, 2, "medinan_early",
      "الإحسان إلى الخدم والموالي", "Kindness to servants and freedmen",
      "Medina", ["4:36"],
      "أمر النبي ﷺ الصحابة بالإحسان إلى الخدم والموالي وإطعامهم مما يأكلون وإلباسهم مما يلبسون، وقال: هم إخوانكم جعلهم الله تحت أيديكم.",
      "الكرامة الإنسانية لا تتأثر بالوضع الاجتماعي؛ الخادم أخ قبل أن يكون موظفاً.",
      "none", "ruler_vs_ruled", "personal_dignity",
      "legal_innovation", "protection_of_the_weak", "command"),

    E("me_slave_freeing_encouraged", 287, 2, "medinan_early",
      "الحث على عتق الرقاب", "Encouraging the freeing of slaves",
      "Medina", ["90:11", "90:12", "90:13"],
      "شجّع القرآن والنبي ﷺ على عتق الرقاب وجعل ذلك كفارة لكثير من الذنوب (القتل الخطأ، الظهار، اليمين)، ترسيخاً لمسار إنهاء الرق.",
      "التدرج في تفكيك الرق من خلال العتق الواسع؛ التغيير بالحوافز لا بالصدمة.",
      "economic_siege", "ruler_vs_ruled", "personal_dignity",
      "gradualism_in_hard_change", "protection_of_the_weak", "legislation"),

    E("me_umm_ayman_anecdote", 288, 1, "medinan_early",
      "أم أيمن حاضنة النبي ﷺ في المدينة", "Umm Ayman the Prophet's nanny in Medina",
      "Medina", ["93:6"],
      "هاجرت أم أيمن حاضنة النبي ﷺ إلى المدينة، فكان النبي يزورها ويرعى حاجاتها ويقول عنها: بقية أهلي.",
      "الحاضن الأول له مكانة لا تُنسى؛ الوفاء لأصحاب الفضل القديم من أخلاق القادة.",
      "none", "parent_vs_child", "family_integrity",
      "forgiveness_from_power", "trust_is_earned_by_consistency", "praise"),

    E("me_fatima_marriage_ali", 289, 2, "medinan_early",
      "مهر فاطمة درع عليّ", "Ali's armor as Fatima's dowry",
      "Medina", ["4:4"],
      "زوّج النبي ﷺ فاطمة من علي فطلب علي شيئاً يدفعه مهراً، فقال النبي: أين درعك الحطمية؟ فدفعها مهراً.",
      "المهر يُقدَّر بما يملك الخاطب؛ اليسر في الزواج من علامات الصدق.",
      "economic_siege", "kin_vs_kin", "family_integrity",
      "teaching_through_demonstration", "wealth_as_trust_not_ownership", "legislation"),

    E("me_wedding_simple_event", 290, 2, "medinan_early",
      "بساطة وليمة فاطمة", "Simplicity of Fatima's wedding feast",
      "Medina", ["7:31"],
      "كانت وليمة زواج فاطمة بنت النبي ﷺ من تمر وسمن وسويق، ولم يزد فيها عن ذلك رغم المكانة.",
      "الزواج الأول في بيت النبوة قدوة؛ البساطة في الفرح تُعمّم الفرح.",
      "none", "kin_vs_kin", "community_cohesion",
      "teaching_through_demonstration", "leadership_accountability", "praise"),

    E("me_house_of_fatima_built", 291, 2, "medinan_early",
      "بناء بيت فاطمة ملاصقاً للنبي ﷺ", "Building Fatima's house next to the Prophet's",
      "Medina", ["33:33"],
      "بُني بيت فاطمة بسيطاً ملاصقاً لبيت النبي ﷺ، فكان النبي يزورها كل يوم ويسألها عن حالها.",
      "الارتباط العائلي حتى مع البناء المستقل؛ الزيارة اليومية تحفظ الصلة.",
      "none", "kin_vs_kin", "family_integrity",
      "teaching_through_demonstration", "boundaries_in_intimate_relations", "praise"),

    E("me_umar_wife_advice", 292, 2, "medinan_early",
      "امرأة عمر تراجعه في رأيه", "Umar's wife counters his view",
      "Medina", ["4:19"],
      "راجعت امرأةٌ عمرَ بن الخطاب في شيء فغضب، فقالت: إن نساء النبي ﷺ يراجعنه، فسكت عمر تعجباً من نصيحة بيت النبي.",
      "الحوار الزوجي حقّ مكفول؛ المرأة شريكة الرأي لا تابعة صامتة.",
      "family_pressure", "spouse_vs_spouse", "trust_between_parties",
      "private_counsel", "consultation_before_decision", "legislation"),

    E("me_zainab_charity_spender", 293, 3, "medinan_early",
      "زينب بنت جحش أطولكن يداً", "Zaynab bint Jahsh 'longest in hand' in charity",
      "Medina", ["2:267"],
      "قال النبي ﷺ لأزواجه: أسرعكن لحوقاً بي أطولكن يداً، فظننه طول يد، فإذا هي زينب بنت جحش أطولهن يداً في الصدقة.",
      "الإنفاق اليد الحقيقية الطويلة؛ الأعمال تُصحّح فهم الرمز.",
      "none", "community_vs_outsider", "livelihood",
      "teaching_through_demonstration", "economic_justice_as_worship", "praise"),

    E("me_uhud_women_water", 294, 3, "medinan_early",
      "عائشة وأم سليم يسقيان في أحد", "Aisha and Umm Sulaym serve water at Uhud",
      "Uhud", ["33:35"],
      "رأى أنس بن مالك عائشة وأم سليم يوم أحد تُقلّبان القرب على متونهما تسقيان الجرحى وتغسلان الدم.",
      "الخدمة في ميدان المعركة عبادة؛ المرأة ركن من أركان الجيش.",
      "existential_threat", "community_vs_outsider", "community_cohesion",
      "active_resistance", "solidarity_around_principle", "praise"),

    E("me_muhajirun_first_income", 295, 1, "medinan_early",
      "أول أعمال المهاجرين في المدينة", "First jobs of Muhajirun in Medina",
      "Medina", ["59:9"],
      "عمل المهاجرون في المدينة في الحمل والبيع البسيط كعبد الرحمن بن عوف الذي تاجر في السمن والأقط حتى صار غنياً.",
      "العمل من أول يوم صون للكرامة؛ العطاء لا يُلغي السعي.",
      "economic_siege", "community_vs_outsider", "livelihood",
      "organizational_response", "wealth_as_trust_not_ownership", "praise"),

    E("me_abdulrahman_auction", 296, 1, "medinan_early",
      "عبد الرحمن بن عوف يرفض المنح", "Abdul Rahman ibn Awf refuses gifts",
      "Medina", ["92:17", "92:18"],
      "لما آخى النبي ﷺ بين عبد الرحمن بن عوف وسعد بن الربيع عرض سعد عليه نصف ماله وإحدى زوجتيه، فرفض عبد الرحمن قائلاً: دلني على السوق.",
      "الكرامة في العمل أغلى من الصدقة؛ الكد الخاص أفضل من العطاء العام.",
      "economic_siege", "ally_vs_ally_dispute", "livelihood",
      "refusal_to_compromise", "wealth_as_trust_not_ownership", "praise"),

    E("me_abu_bakr_sadaqah_all", 297, 2, "medinan_early",
      "أبو بكر يتصدق بكل ماله", "Abu Bakr gives all his wealth in charity",
      "Medina", ["92:17", "92:18"],
      "جاء أبو بكر بكل ماله في غزوة تبوك، فسأله النبي ﷺ: ما أبقيت لأهلك؟ فقال: الله ورسوله.",
      "الإيثار المطلق ثقة مطلقة؛ المال يُبذل بلا حساب مع يقين حقيقي.",
      "economic_siege", "family_pressure", "livelihood",
      "refusal_to_compromise", "wealth_as_trust_not_ownership", "praise"),

    E("me_umar_half_wealth", 298, 2, "medinan_early",
      "عمر يتصدق بنصف ماله", "Umar gives half his wealth",
      "Medina", ["92:5"],
      "جاء عمر بنصف ماله في تبوك قائلاً: اليوم أسبق أبا بكر، فلما جاء أبو بكر بكل ماله قال عمر: لا أسبقك إلى شيء أبداً.",
      "المنافسة في الخير تُسرّع تقدم الجماعة؛ القدوة الأعلى تُغيّر مقاييس المنافسة.",
      "none", "ally_vs_ally_dispute", "livelihood",
      "seeking_allies", "solidarity_around_principle", "praise"),

    E("me_uthman_army_funding", 299, 3, "medinan_early",
      "عثمان يموّل جيش العسرة", "Uthman funds the Army of Hardship",
      "Medina", ["9:100"],
      "جهّز عثمان بن عفان ثلث جيش العسرة (تبوك لاحقاً) بمئة بعير وألف دينار، فقال النبي ﷺ: ما ضرّ عثمان ما عمل بعد اليوم.",
      "المال يُنقذ المشروع في وقت الضيق؛ الثري المؤمن ركيزة للجماعة.",
      "economic_siege", "community_vs_outsider", "collective_survival",
      "organizational_response", "wealth_as_trust_not_ownership", "praise"),

    E("me_first_hajj_not_done", 300, 3, "medinan_early",
      "عدم حج النبي ﷺ في السنة الثالثة بسبب الحرب", "Prophet does not perform Hajj in year 3 due to war",
      "Medina", ["2:196", "2:197"],
      "لم يتمكن النبي ﷺ من الحج في السنة الثالثة بسبب الحروب المتتالية، فأجّله حتى الفتح وعمرة القضاء.",
      "تأجيل العبادة لعذر مشروع؛ الشريعة تقدّر الظروف ولا تُكلّف فوق الطاقة.",
      "political_pressure", "community_vs_outsider", "spiritual_integrity",
      "deferral_of_judgement", "scaling_principle_to_context", "legislation"),
]
