"""Medinan late events (years 7-11 AH). Order range 501-650.

Coverage: Khaybar, Umrat al-qada, Mu'tah, Fath Makkah, Hunayn, Ta'if,
Tabuk, year of delegations, hajjat al-wada, final illness and death.
"""

from __future__ import annotations
from training.pipeline.sira_db.db import E

MEDINAN_LATE_EVENTS: list[dict] = [
    # ═══════════════ YEAR 7 AH — KHAYBAR ═══════════════
    E("ml_khaybar_march", 501, 7, "medinan_late",
      "زحف النبي ﷺ إلى خيبر", "Prophet marches to Khaybar",
      "Khaybar", ["48:15", "48:18", "48:19", "48:20"],
      "بعد عودته من الحديبية بأشهر سار النبي ﷺ إلى خيبر معقل اليهود الكبير في 1400 من أصحاب الحديبية فقط، تنفيذاً لوعد الفتح القريب.",
      "النصر يُكافأ بنصر؛ الصدق في موعد سابق يفتح موعداً جديداً.",
      "political_pressure", "community_vs_outsider", "collective_survival",
      "active_resistance", "trust_is_earned_by_consistency", "promise"),

    E("ml_khaybar_dua_wadi", 502, 7, "medinan_late",
      "دعاء النبي ﷺ عند دخول وادي خيبر", "Prophet's supplication entering Khaybar valley",
      "Khaybar", ["48:18"],
      "لمّا أشرف النبي ﷺ على وادي خيبر قال لأصحابه: قفوا، ثم دعا: اللهم رب السماوات وما أظللن، ورب الأرضين وما أقللن، نسألك خير هذه القرية.",
      "الدعاء قبل الإقدام أصل في الفتح؛ القائد يُذكّر أن النصر بيد الله.",
      "existential_threat", "leader_vs_follower", "spiritual_integrity",
      "refuge_with_god_against_despair", "refuge_with_god_against_despair", "command"),

    E("ml_khaybar_ali_banner", 503, 7, "medinan_late",
      "إعطاء الراية لعلي بن أبي طالب", "Giving the banner to Ali ibn Abi Talib",
      "Khaybar", ["48:19"],
      "قال النبي ﷺ في خيبر: لأعطين الراية غداً رجلاً يحبّ الله ورسوله ويحبه الله ورسوله، يفتح الله على يديه. فأعطاها علياً.",
      "الفتح يأتي بيد من اجتمعت فيه المحبة المتبادلة؛ القرب من الله شرط النصر.",
      "existential_threat", "leader_vs_follower", "collective_survival",
      "confrontation_with_truth", "trust_is_earned_by_consistency", "promise"),

    E("ml_ali_eyes_healed", 504, 7, "medinan_late",
      "شفاء عين علي قبل المعركة", "Healing of Ali's eye before the battle",
      "Khaybar", ["3:103"],
      "كان علي رمداً لا يكاد يُبصر، فدعا النبي ﷺ بأن يأتي به فبصق في عينيه فبرئ من ساعته كأن لم يكن به وجع.",
      "البركة بيد القائد لا تنفصل عن المهمة؛ التأهيل للقائد قبل القيادة.",
      "physical_persecution", "leader_vs_follower", "physical_safety",
      "refuge_with_god_against_despair", "refuge_with_god_against_despair", "story"),

    E("ml_khaybar_natat_fortresses", 505, 7, "medinan_late",
      "فتح حصون النطاة الواحد تلو الآخر", "Conquest of al-Natat fortresses one by one",
      "Khaybar", ["48:18"],
      "افتتح النبي ﷺ حصون النطاة في خيبر حصناً حصناً، وكان لكل حصن قتاله وحصاره، فصبر الجيش على المدة.",
      "التحرير يأتي بالصبر على المراحل؛ كل حصن يحتاج صبره.",
      "existential_threat", "community_vs_outsider", "collective_survival",
      "active_resistance", "patience_under_collective_punishment", "command"),

    E("ml_marhab_killed", 506, 7, "medinan_late",
      "قتل مرحب بطل خيبر", "Killing of Marhab the champion of Khaybar",
      "Khaybar", ["8:17"],
      "برز مرحب اليهودي يطلب النزال، فبرز له علي بن أبي طالب فقتله بضربة شقّت رأسه إلى أسفل، وكان من أبطال خيبر.",
      "البطل الفرد يتهاوى أمام الإيمان الفرد؛ الكفاءة مع النية أبلغ من العضل.",
      "existential_threat", "individual_vs_majority", "physical_safety",
      "active_resistance", "chosen_hardship_over_compromise", "story"),

    E("ml_safiyya_marriage", 507, 7, "medinan_late",
      "زواج النبي ﷺ من صفية بنت حيي", "Marriage of the Prophet to Safiyya bint Huyayy",
      "Khaybar", ["33:50"],
      "سُبيت صفية بنت حيي بن أخطب (سيدة بني النضير) في خيبر، فأعتقها النبي ﷺ وتزوجها فجعل عتقها صداقها.",
      "الكرامة بالعتق أعلى من الأسر؛ الزواج تحرير وعزة.",
      "physical_persecution", "kin_vs_kin", "personal_dignity",
      "forgiveness_from_power", "mercy_as_strategic_choice", "praise"),

    E("ml_khaybar_jews_keep_lands", 508, 7, "medinan_late",
      "إبقاء يهود خيبر على أرضهم بنصف الثمر", "Keeping Khaybar Jews on their land for half the produce",
      "Khaybar", ["8:41"],
      "صالح النبي ﷺ يهود خيبر على أن يبقوا في أرضهم يعملون فيها بشطر ما يخرج منها، وذلك بعد أن طلبوا ذلك لخبرتهم.",
      "الكفاءة الزراعية تُحفظ ولو من الخصم؛ المصلحة العامة تُقدَّم.",
      "economic_siege", "community_vs_outsider", "livelihood",
      "compromise_for_larger_goal", "knowledge_before_action", "legislation"),

    E("ml_zaynab_poisoned_meat", 509, 7, "medinan_late",
      "محاولة تسميم النبي ﷺ بشاة خيبر", "Attempted poisoning at Khaybar",
      "Khaybar", ["5:67"],
      "دسّت زينب بنت الحارث اليهودية سمّاً في شاة قدّمتها للنبي ﷺ، فأكل منها لقمة فأخبرته الذراع بأنها مسمومة، فلفظها وعاش الأثر معه إلى الموت.",
      "محاولة الاغتيال تستمر حتى بعد الهزيمة؛ الحقد لا يموت بسهولة.",
      "existential_threat", "individual_vs_majority", "physical_safety",
      "endurance_without_retaliation", "consistency_public_and_private", "warning"),

    E("ml_jafar_returns_habash", 510, 7, "medinan_late",
      "عودة جعفر بن أبي طالب من الحبشة", "Return of Ja'far from Abyssinia",
      "Medina", ["28:53", "28:54"],
      "عاد جعفر بن أبي طالب ومن معه من مهاجري الحبشة إلى المدينة في السنة السابعة بعد فتح خيبر، فلقيهم النبي ﷺ وقبّله بين عينيه.",
      "اللقاء بعد الفراق الطويل تفجير للمشاعر؛ القائد يكرم العائد بمحبة ظاهرة.",
      "none", "community_vs_outsider", "community_cohesion",
      "consolation_and_thabaat", "solidarity_around_principle", "praise"),

    E("ml_umrat_alqada", 511, 7, "medinan_late",
      "عمرة القضاء", "Umrat al-Qada (the makeup umrah)",
      "Mecca", ["48:27"],
      "خرج النبي ﷺ في ذي القعدة 7 هـ لأداء العمرة التي قضاها بالحديبية، فدخل مكة بعد أن أخلتها قريش ثلاثة أيام.",
      "الوفاء بالعهد يجلب الإذن الذي كان مرفوضاً؛ الصبر يفتح ما لا يفتحه الإلحاح.",
      "none", "community_vs_outsider", "religious_freedom",
      "compromise_for_larger_goal", "trust_is_earned_by_consistency", "promise"),

    E("ml_marriage_maymuna", 512, 7, "medinan_late",
      "زواج النبي ﷺ من ميمونة بنت الحارث", "Marriage of the Prophet to Maymuna bint al-Harith",
      "Sarif", ["33:50"],
      "تزوج النبي ﷺ ميمونة بنت الحارث في عمرة القضاء بسرف بعد تحلله، فكانت آخر امرأة تزوجها وآخر من توفي من زوجاته.",
      "العلاقات الاجتماعية تُبنى عبر المصاهرة؛ الزواج جسر بين القبائل.",
      "none", "kin_vs_kin", "trust_between_parties",
      "compromise_for_larger_goal", "solidarity_around_principle", "praise"),

    E("ml_mutah_battle", 513, 8, "medinan_late",
      "غزوة مؤتة", "Battle of Mu'tah",
      "Mu'tah", ["3:140", "9:25"],
      "بعث النبي ﷺ ثلاثة آلاف إلى مؤتة (شرق الأردن) لقتال جيش الروم وحلفائهم البالغ مئتي ألف، بقيادة زيد بن حارثة ثم جعفر ثم ابن رواحة.",
      "الجيش الصغير لا يخاف الجيش الكبير إذا صدقت النية؛ الشهادة قبل النصر.",
      "existential_threat", "community_vs_outsider", "collective_survival",
      "active_resistance", "chosen_hardship_over_compromise", "story"),

    E("ml_three_commanders_martyrdom", 514, 8, "medinan_late",
      "استشهاد قادة مؤتة الثلاثة", "Martyrdom of the three commanders of Mu'tah",
      "Mu'tah", ["3:169"],
      "استشهد في مؤتة زيد بن حارثة ثم جعفر بن أبي طالب الذي قُطعت يداه فاستشهد، ثم عبد الله بن رواحة، ثم تولى خالد القيادة.",
      "تتابع القيادات شرط بقاء الجيش؛ الاستشهاد لا يعني توقف المسيرة.",
      "existential_threat", "leader_vs_follower", "physical_safety",
      "endurance_without_retaliation", "leadership_accountability", "consolation"),

    E("ml_jafar_two_wings", 515, 8, "medinan_late",
      "جعفر الطيار جناحاه في الجنة", "Ja'far al-Tayyar with two wings in paradise",
      "Mu'tah", ["3:169", "3:170"],
      "قال النبي ﷺ لمّا نُعي إليه جعفر بن أبي طالب: رأيت جعفراً يطير في الجنة بجناحين، فلُقب بالطيار.",
      "البشرى للشهيد قبل أن يبلغ خبره أهله؛ الكشف الإلهي يُسلي القلوب.",
      "psychological_pressure", "kin_vs_kin", "spiritual_integrity",
      "consolation_and_thabaat", "refuge_with_god_against_despair", "promise"),

    E("ml_khalid_saves_army", 516, 8, "medinan_late",
      "خالد بن الوليد ينقذ جيش مؤتة", "Khalid ibn al-Walid saves the Mu'tah army",
      "Mu'tah", ["8:65"],
      "أخذ خالد بن الوليد الراية بعد استشهاد القادة الثلاثة، وغيّر التشكيل وأرعب الروم بحركاته حتى تمكن من سحب الجيش بسلامة.",
      "العبقرية القيادية تنقذ المستحيل؛ القائد المحنّك يحوّل الكارثة إلى انسحاب منظم.",
      "existential_threat", "leader_vs_follower", "collective_survival",
      "strategic_withdrawal", "knowledge_before_action", "praise"),

    E("ml_quraysh_breaks_treaty", 517, 8, "medinan_late",
      "نقض قريش لصلح الحديبية", "Quraysh breaks the Hudaybiyyah treaty",
      "Mecca area", ["8:56"],
      "أعانت قريش خزاعة (حلفاء النبي ﷺ) بنو بكر بأنفسها وسلاحها ضد خزاعة، فنقضوا بذلك صلح الحديبية.",
      "نقض العهد يفتح أبواب الحرب؛ الخائن يدفع الثمن آجلاً.",
      "internal_betrayal", "community_vs_outsider", "trust_between_parties",
      "active_resistance", "refusing_to_legitimize_falsehood", "warning"),

    E("ml_amr_khuzai_pleads", 518, 8, "medinan_late",
      "عمرو بن سالم الخزاعي يستنجد بالنبي ﷺ", "Amr ibn Salim al-Khuza'i appeals to the Prophet",
      "Medina", ["8:72"],
      "جاء عمرو بن سالم الخزاعي إلى المدينة يستنجد بالنبي ﷺ بسبب اعتداء بكر وقريش، فأنشد قصيدة بليغة، فقال النبي: نُصرت يا عمرو.",
      "الالتجاء إلى الحليف القوي حقّ المظلوم؛ القائد يستجيب للنداء فوراً.",
      "physical_persecution", "ally_vs_ally_dispute", "trust_between_parties",
      "seeking_allies", "solidarity_around_principle", "command"),

    E("ml_abu_sufyan_repair_attempt", 519, 8, "medinan_late",
      "أبو سفيان يحاول إصلاح الصلح", "Abu Sufyan tries to repair the treaty",
      "Medina", ["48:24"],
      "أحسّت قريش بالخطأ فأرسلت أبا سفيان إلى المدينة ليجدد الصلح، فلم يكلمه أحد من النبي ﷺ ولا أصحابه، فعاد بخفي حنين.",
      "الندم بعد الخيانة لا يُلغي النتائج؛ القوة الدبلوماسية تذهب بنقض العقد.",
      "political_pressure", "community_vs_outsider", "trust_between_parties",
      "silence_as_answer", "trust_is_earned_by_consistency", "rebuke"),

    E("ml_secret_preparation_makkah", 520, 8, "medinan_late",
      "الإعداد السري لفتح مكة", "Secret preparation for the Conquest of Mecca",
      "Medina", ["48:25"],
      "بدأ النبي ﷺ بالإعداد السري لغزو مكة دون أن يكشف الوجهة لأحد، حتى لأهله، حفاظاً على عنصر المفاجأة.",
      "السرية شرط نجاح العمليات الكبرى؛ كتمان السر فن قيادي.",
      "political_pressure", "leader_vs_follower", "collective_survival",
      "strategic_withdrawal", "knowledge_before_action", "command"),

    E("ml_hatib_letter", 521, 8, "medinan_late",
      "حاطب بن أبي بلتعة يُرسل رسالة لقريش", "Hatib sends a letter to Quraysh",
      "Medina", ["60:1", "60:2", "60:3", "60:4"],
      "كتب حاطب بن أبي بلتعة رسالة إلى قريش يُخبرهم بنية النبي ﷺ غزوهم، فأرسلها مع امرأة، فعلم النبي بالوحي وأرسل علياً والزبير لاسترداد الكتاب.",
      "حتى البدريون قد يخطئون؛ الخطيئة لا تُلغي السابقة.",
      "internal_betrayal", "ally_vs_ally_dispute", "trust_between_parties",
      "deferral_of_judgement", "forgiveness_without_surrender", "rebuke"),

    E("ml_hatib_excused", 522, 8, "medinan_late",
      "اعتذار حاطب وقبول النبي ﷺ", "Hatib's apology and Prophet's acceptance",
      "Medina", ["60:1", "60:2"],
      "اعتذر حاطب بأنه لم يرتد ولكن أراد يداً عند قريش يحفظون بها أهله بمكة، فعفا عنه النبي ﷺ وقال: إنه شهد بدراً، فمنع عمر من ضرب عنقه.",
      "السابقة في الإيمان تشفع في الزلة؛ الشفاعة بحسن السابقة.",
      "verbal_attack", "ally_vs_ally_dispute", "trust_between_parties",
      "forgiveness_from_power", "preserving_channels_of_return", "praise"),

    E("ml_march_to_mecca", 523, 8, "medinan_late",
      "خروج النبي ﷺ بعشرة آلاف إلى مكة", "Prophet marches with 10,000 to Mecca",
      "Mecca route", ["48:1", "48:18"],
      "خرج النبي ﷺ بعشرة آلاف من المسلمين في رمضان السنة الثامنة لفتح مكة، أكبر جيش لم تره الجزيرة من قبل.",
      "الانتقال من الدفاع إلى الفتح ثمرة سنوات الصبر؛ الكثرة معنى متقدم.",
      "political_pressure", "community_vs_outsider", "collective_survival",
      "active_resistance", "trust_is_earned_by_consistency", "promise"),

    E("ml_abu_sufyan_meets_abbas", 524, 8, "medinan_late",
      "العباس يأخذ أبا سفيان إلى النبي ﷺ", "Al-Abbas brings Abu Sufyan to the Prophet",
      "Marr al-Zahran", ["6:122"],
      "خرج أبو سفيان وحكيم بن حزام يتجسّسون فلقيهم العباس عمّ النبي ﷺ فأخذ أبا سفيان على بغلته وأدخله على النبي تحت أمانه.",
      "الشفاعة من القريب باب للهداية؛ القائد العادل يقبل الأمان.",
      "existential_threat", "kin_vs_kin", "physical_safety",
      "forgiveness_from_power", "preserving_channels_of_return", "praise"),

    E("ml_abu_sufyan_islam", 525, 8, "medinan_late",
      "إسلام أبي سفيان قبل دخول مكة", "Abu Sufyan's conversion before entering Mecca",
      "Marr al-Zahran", ["6:122"],
      "عرض النبي ﷺ على أبي سفيان الإسلام مرتين، فأسلم في الثالثة مرتعشاً، ثم قال له النبي: من دخل دار أبي سفيان فهو آمن.",
      "إكرام القائد المنهزم بإعطائه دوراً في الأمان؛ السياسة تُحوّل الخصم إلى حليف.",
      "existential_threat", "leader_vs_follower", "spiritual_integrity",
      "compromise_for_larger_goal", "preserving_channels_of_return", "praise"),

    E("ml_show_strength_columns", 526, 8, "medinan_late",
      "استعراض الجيش أمام أبي سفيان", "Display of the army before Abu Sufyan",
      "Marr al-Zahran", ["48:18"],
      "أمر النبي ﷺ العباس بأن يُوقف أبا سفيان في مضيق وأن يمر الجيش أمامه قبيلة قبيلة، فرأى من القوة ما لم يكن يحتسبه.",
      "إظهار القوة قد يُغني عن استعمالها؛ الهيبة تُسقط المعركة.",
      "political_pressure", "community_vs_outsider", "trust_between_parties",
      "public_declaration", "knowledge_before_action", "warning"),

    E("ml_four_columns_enter", 527, 8, "medinan_late",
      "دخول الجيش مكة من أربع جهات", "Army enters Mecca from four directions",
      "Mecca", ["110:1"],
      "قسّم النبي ﷺ الجيش إلى أربع كتائب يدخلون مكة من أربع جهات: الزبير وخالد وسعد وأبو عبيدة، حتى يمنع مقاومة منظمة.",
      "التخطيط العسكري الذكي يقطع المقاومة؛ الإحاطة تكسر إرادة الخصم.",
      "political_pressure", "community_vs_outsider", "collective_survival",
      "organizational_response", "knowledge_before_action", "command"),

    E("ml_safe_houses_declared", 528, 8, "medinan_late",
      "تحديد دور الأمان في مكة", "Designating houses of safety in Mecca",
      "Mecca", ["48:24"],
      "أعلن النبي ﷺ أن من دخل دار أبي سفيان فهو آمن، ومن دخل المسجد فهو آمن، ومن أغلق بابه فهو آمن، فلم يُقاتل إلا من قاتل.",
      "العفو يُعمّم بحسب المراتب؛ الأمان متاح لمن يطلبه.",
      "political_pressure", "community_vs_outsider", "physical_safety",
      "forgiveness_from_power", "mercy_as_strategic_choice", "command"),

    E("ml_khalid_resistance", 529, 8, "medinan_late",
      "مقاومة قليلة في الخندمة لكتيبة خالد", "Brief resistance in al-Khandama against Khalid's column",
      "Mecca", ["8:39"],
      "قاوم نفر من قريش بقيادة عكرمة بن أبي جهل وصفوان بن أمية كتيبة خالد بالخندمة، فقتل خالد منهم نحو 12-28 ثم انهزموا.",
      "المقاومة الفردية لا تُغيّر النتيجة؛ المعركة الكبرى محسومة.",
      "physical_persecution", "community_vs_outsider", "physical_safety",
      "active_resistance", "accountability_proportional_to_power", "warning"),

    E("ml_prophet_humble_entry", 530, 8, "medinan_late",
      "دخول النبي ﷺ مكة متواضعاً", "Prophet's humble entry into Mecca",
      "Mecca", ["110:3"],
      "دخل النبي ﷺ مكة منتصراً مطأطئ الرأس على راحلته حتى كادت لحيته تمسّ ظهرها، تواضعاً لله ولا فخر.",
      "النصر الحقيقي يُقابَل بالتواضع لا بالخيلاء؛ القائد العظيم يصغر أمام الله في أكبر يوم.",
      "none", "leader_vs_follower", "personal_dignity",
      "teaching_through_demonstration", "warning_against_arrogance", "praise"),

    E("ml_idols_around_kabah", 531, 8, "medinan_late",
      "تحطيم أصنام الكعبة", "Smashing the idols around the Ka'ba",
      "Mecca", ["17:81"],
      "كان حول الكعبة 360 صنماً، فأخذ النبي ﷺ يطعنها بقضيب في يده وهو يقول: جاء الحق وزهق الباطل إن الباطل كان زهوقاً.",
      "تطهير المكان المقدس من شوائبه؛ الحق يجتث الباطل بأبسط أداة.",
      "none", "community_vs_outsider", "religious_freedom",
      "refusal_to_compromise", "refusing_to_legitimize_falsehood", "command"),

    E("ml_khutba_conquest", 532, 8, "medinan_late",
      "خطبة النبي ﷺ يوم الفتح", "Prophet's sermon on the day of conquest",
      "Mecca", ["49:13"],
      "خطب النبي ﷺ في أهل مكة قائلاً: يا معشر قريش، ما تظنون أني فاعل بكم؟ قالوا: خيراً، أخ كريم وابن أخ كريم. قال: اذهبوا فأنتم الطلقاء.",
      "العفو الشامل يحوّل الأعداء إلى أتباع؛ الكلمة من القائد العفو رسالة لقرون.",
      "none", "leader_vs_follower", "trust_between_parties",
      "forgiveness_from_power", "mercy_as_strategic_choice", "praise"),

    E("ml_blood_revenge_abolished", 533, 8, "medinan_late",
      "إلغاء ثارات الجاهلية", "Abolishing pre-Islamic blood feuds",
      "Mecca", ["2:178"],
      "أعلن النبي ﷺ يوم الفتح: ألا كل دم في الجاهلية تحت قدميّ هاتين موضوع، وأول دم أضعه دم ابن ربيعة.",
      "كسر السلسلة الانتقامية بقرار قيادي؛ القائد يُسقط حقه أولاً ليُسقطه الآخرون.",
      "psychological_pressure", "leader_vs_follower", "community_cohesion",
      "forgiveness_from_power", "scaling_principle_to_context", "legislation"),

    E("ml_uthman_talha_keys", 534, 8, "medinan_late",
      "إعادة مفاتيح الكعبة لعثمان بن طلحة", "Returning the Ka'ba keys to Uthman ibn Talha",
      "Mecca", ["4:58"],
      "طلب علي والعباس مفاتيح الكعبة فأبى النبي ﷺ وردّها إلى عثمان بن طلحة سادنها قائلاً: خذوها يا بني طلحة خالدة تالدة، لا ينزعها منكم إلا ظالم.",
      "الأمانة تُرد إلى أهلها بصرف النظر عن القرابة؛ المنصب لا يُنتزع بالميل.",
      "moral_temptation", "kin_vs_kin", "trust_between_parties",
      "refusal_to_compromise", "procedural_justice_over_outcome", "legislation"),

    E("ml_only_few_executed", 535, 8, "medinan_late",
      "إهدار دم نفر معين فقط", "Death sentence for only a few",
      "Mecca", ["8:57"],
      "أهدر النبي ﷺ دم عشرة من أهل مكة على جرائم سابقة (عبد الله بن سعد، عكرمة، عبد الله بن خطل، مقيس، صفوان، حويرث، ومن النساء سارة وقرينتان)، وعفا عن معظمهم لاحقاً.",
      "العقوبة على المجرمين الأفراد لا الشعب؛ الفصل بين المسؤول والمتفرج.",
      "legal_coercion", "claimant_vs_accused", "justice_vs_privilege",
      "accountability_proportional_to_power", "accountability_proportional_to_power", "legislation"),

    E("ml_ikrima_pardoned", 536, 8, "medinan_late",
      "العفو عن عكرمة بن أبي جهل", "Pardon of Ikrima ibn Abi Jahl",
      "Mecca", ["6:122"],
      "هرب عكرمة بن أبي جهل خوفاً من النبي ﷺ، فلحقت به امرأته أم حكيم بأمان من النبي، فعاد وأسلم.",
      "العفو عن أبناء الخصوم الكبار رسالة عميقة؛ الماضي لا يُحاسب الجيل الجديد.",
      "psychological_pressure", "kin_vs_kin", "physical_safety",
      "forgiveness_from_power", "preserving_channels_of_return", "praise"),

    E("ml_safwan_pardoned", 537, 8, "medinan_late",
      "العفو عن صفوان بن أمية", "Pardon of Safwan ibn Umayya",
      "Mecca", ["6:122"],
      "هرب صفوان بن أمية يريد البحر، فلحقه عمير بن وهب بعمامة النبي ﷺ أمناً له، فعاد إلى النبي وأسلم بعد أن أمهله النبي شهرين للتفكير.",
      "إعطاء الوقت للتفكير قبل الإيمان حكمة؛ لا إكراه في الدين.",
      "psychological_pressure", "individual_vs_majority", "spiritual_integrity",
      "deferral_of_judgement", "no_coercion_in_conviction", "praise"),

    E("ml_hind_islam", 538, 8, "medinan_late",
      "إسلام هند بنت عتبة", "Conversion of Hind bint Utba",
      "Mecca", ["60:12"],
      "جاءت هند بنت عتبة (التي مثلت بحمزة) إلى النبي ﷺ بعد فتح مكة فبايعته على شروط وأسلمت، وقال لها: من تكونين؟ قالت: أنا هند، اعفُ عما سلف.",
      "أعتى الخصوم قد يصبحون مسلمين؛ التوبة باب لا يُغلق.",
      "none", "kin_vs_kin", "spiritual_integrity",
      "forgiveness_from_power", "repentance_as_open_door", "praise"),

    E("ml_wahshi_islam_later", 539, 8, "medinan_late",
      "إسلام وحشي قاتل حمزة", "Islam of Wahshi the killer of Hamza",
      "Mecca/Ta'if", ["6:122"],
      "أسلم وحشي بن حرب قاتل حمزة بعد فتح مكة، فعفا عنه النبي ﷺ ولكنه قال: لا تُرني وجهك، إذ كان يُذكّره بحمزة.",
      "العفو لا يُلغي الأسى الشخصي؛ المؤمن يحسن الاعتذار من الجرح.",
      "psychological_pressure", "claimant_vs_accused", "personal_dignity",
      "forgiveness_from_power", "forgiveness_without_surrender", "rebuke"),

    E("ml_first_friday_in_makkah", 540, 8, "medinan_late",
      "أول جمعة في مكة بعد الفتح", "First Friday prayer in Mecca after the conquest",
      "Mecca", ["62:9"],
      "صلى النبي ﷺ بأهل مكة المسلمين الجدد أول جمعة بعد فتح مكة في المسجد الحرام، تأسيساً للحياة الجديدة.",
      "العبادة الجماعية ترسم حدود المرحلة الجديدة؛ المسجد الحرام يعود مكاناً لذكر الله فقط.",
      "none", "community_vs_outsider", "spiritual_integrity",
      "organizational_response", "solidarity_around_principle", "legislation"),

    E("ml_uthman_house_taqeer", 541, 8, "medinan_late",
      "النبي ﷺ يأمر بإخراج صور الكعبة", "Prophet orders removing pictures from the Ka'ba",
      "Mecca", ["29:17"],
      "أمر النبي ﷺ يوم الفتح بإخراج كل الصور من داخل الكعبة، حتى صورة إبراهيم وإسماعيل بأيديهما الأزلام، وقال: قاتلهم الله، ما كانا يستقسمان بها قط.",
      "تطهير المكان المقدس من الزخارف الوثنية؛ الرموز الباطلة لا تُترك ولو في أقدس الأماكن.",
      "none", "community_vs_outsider", "religious_freedom",
      "refusal_to_compromise", "refusing_to_legitimize_falsehood", "command"),

    E("ml_bilal_adhan_kabah", 542, 8, "medinan_late",
      "بلال يؤذن من فوق الكعبة", "Bilal's adhan from atop the Ka'ba",
      "Mecca", ["62:9"],
      "أمر النبي ﷺ بلالاً أن يصعد فوق الكعبة فيؤذن، فصعد وأذّن أول أذان في المسجد الحرام بعد الفتح، فاستنكر بعض المشركين.",
      "العبد الأسود فوق رمز قريش رسالة للأبد؛ الإسلام يُعيد ترتيب المراتب.",
      "none", "community_vs_outsider", "personal_dignity",
      "teaching_through_demonstration", "rejection_of_blind_imitation", "praise"),

    E("ml_makkans_pledge", 543, 8, "medinan_late",
      "بيعة أهل مكة على الإسلام", "Pledge of the Meccans to Islam",
      "Mecca", ["48:18"],
      "بايع أهل مكة النبي ﷺ على الإسلام والسمع والطاعة بعد الفتح، رجالاً ونساءً، على الصفا.",
      "البيعة العامة بعد الفتح أنجح من فرضها بالسيف؛ الإيمان الطوعي أقوى.",
      "none", "community_vs_outsider", "community_cohesion",
      "public_declaration", "solidarity_around_principle", "legislation"),

    # ═══════════════ HUNAYN ═══════════════
    E("ml_hunayn_march", 544, 8, "medinan_late",
      "خروج النبي ﷺ إلى حنين", "Prophet marches to Hunayn",
      "Hunayn", ["9:25", "9:26"],
      "بعد فتح مكة بأيام بلغ النبي ﷺ تجمّع هوازن وثقيف لقتاله، فخرج إليهم في 12,000 (10,000 من المسلمين و2,000 من مسلمي الفتح).",
      "النصر الكبير لا يعني الراحة؛ التحديات تتجدد.",
      "political_pressure", "community_vs_outsider", "collective_survival",
      "active_resistance", "knowledge_before_action", "command"),

    E("ml_hunayn_pride_in_numbers", 545, 8, "medinan_late",
      "إعجاب المسلمين بكثرتهم في حنين", "Muslim pride in numbers at Hunayn",
      "Hunayn", ["9:25"],
      "أعجبت المسلمين كثرتهم يوم حنين فقال بعضهم: لن نُغلَب اليوم من قلة، فكان ذلك سبب الهزيمة الأولى.",
      "العجب بالأسباب يُذهب البركة؛ النصر بالله لا بالعدد.",
      "moral_failure_by_self", "community_vs_outsider", "collective_survival",
      "moral_rebuke", "warning_against_arrogance", "warning"),

    E("ml_hunayn_initial_panic", 546, 8, "medinan_late",
      "هزيمة المسلمين الأولى في حنين", "Initial Muslim defeat at Hunayn",
      "Hunayn", ["9:25"],
      "نصب هوازن كمائناً في وادي حنين وانقضّوا على المسلمين فجأة، فولّى المسلمون مدبرين لا يلوي بعضهم على بعض.",
      "الكمين يكسر الجيش الكبير؛ المفاجأة سلاح ضد الكثرة.",
      "existential_threat", "community_vs_outsider", "collective_survival",
      "endurance_without_retaliation", "testing_loyalty_under_stress", "warning"),

    E("ml_prophet_stays_firm_hunayn", 547, 8, "medinan_late",
      "ثبات النبي ﷺ في حنين", "Prophet's steadfastness at Hunayn",
      "Hunayn", ["9:26"],
      "ثبت النبي ﷺ في مكانه على بغلته وحوله الأقربون: العباس وأبو سفيان بن الحارث، يصيح: أنا النبي لا كذب، أنا ابن عبد المطلب.",
      "ثبات القائد يُعيد الجيش؛ الكلمة الواحدة من القائد تُحيي الجيش.",
      "existential_threat", "leader_vs_follower", "physical_safety",
      "refusal_to_compromise", "leadership_accountability", "praise"),

    E("ml_abbas_calls_back", 548, 8, "medinan_late",
      "العباس ينادي المسلمين بأعلى صوت", "Al-Abbas shouts to call back the Muslims",
      "Hunayn", ["9:26"],
      "أمر النبي ﷺ العباس عمَّه (وكان جهير الصوت) أن يُنادي: يا أصحاب البيعة، يا أصحاب سورة البقرة، فرجعوا حتى انقلب الحال.",
      "النداء بالرموز الوجدانية يُحرّك النفوس؛ الذكرى تُعيد الالتزام.",
      "psychological_pressure", "leader_vs_follower", "collective_survival",
      "consolation_and_thabaat", "solidarity_around_principle", "command"),

    E("ml_hunayn_victory", 549, 8, "medinan_late",
      "نصر المسلمين في حنين", "Muslim victory at Hunayn",
      "Hunayn", ["9:25", "9:26", "9:27"],
      "بعد عودة المسلمين انتصروا على هوازن انتصاراً كاملاً، وأنزل الله سكينته عليهم وأنزل جنوداً لم يروها.",
      "النصر بعد الهزيمة الأولى أعظم لأنه درس مقصود؛ الفشل المؤقت تربية.",
      "existential_threat", "community_vs_outsider", "collective_survival",
      "active_resistance", "divine_testing_mechanism", "promise"),

    E("ml_hawazin_captives", 550, 8, "medinan_late",
      "أسر هوازن وغنائمها الكبيرة", "Hawazin captives and great spoils",
      "Hunayn", ["9:25"],
      "أسر المسلمون 6000 من هوازن وغنموا 24000 بعير و40,000 شاة و4000 أوقية فضة، فكانت من أكبر غنائم المسلمين.",
      "الغنيمة الكبيرة قد تكون اختباراً أكبر من المعركة؛ الكنوز تختبر النفوس.",
      "none", "community_vs_outsider", "property_rights",
      "active_resistance", "wealth_as_trust_not_ownership", "story"),

    E("ml_hawazin_freed", 551, 8, "medinan_late",
      "إعتاق سبي هوازن بعد إسلامهم", "Freeing the Hawazin captives after their Islam",
      "Ji'rana", ["9:25"],
      "جاء وفد هوازن إلى النبي ﷺ مسلمين يطلبون أن يُردّ سبيهم، فأعاد النبي السبي بعد أن استطاب أنفس الصحابة الذين وقعوا في حصصهم.",
      "استرضاء النفوس قبل أخذ الحقوق؛ القائد لا يُجبر أتباعه.",
      "economic_siege", "community_vs_outsider", "personal_dignity",
      "forgiveness_from_power", "consultation_before_decision", "praise"),

    E("ml_taif_siege", 552, 8, "medinan_late",
      "حصار الطائف", "Siege of Ta'if",
      "Ta'if", ["9:25"],
      "حاصر النبي ﷺ الطائف بعد حنين أكثر من عشرين ليلة، فلم يفتحها لأن أهلها تحصّنوا في حصونهم، فرفع الحصار وعاد.",
      "ليس كل حصار ينتهي بفتح؛ القائد يقرأ متى يتراجع.",
      "political_pressure", "community_vs_outsider", "collective_survival",
      "strategic_withdrawal", "scaling_principle_to_context", "command"),

    E("ml_thaqif_delegation_later", 553, 9, "medinan_late",
      "إسلام ثقيف بالوفد لاحقاً", "Thaqif Islam through delegation later",
      "Medina", ["7:158"],
      "بعد حصار الطائف بسنة جاء وفد ثقيف إلى المدينة معلنين إسلامهم وطلبوا إبقاء صنم اللات فترة فرفض النبي ﷺ.",
      "ما يعجز السيف عن فتحه يفتحه الزمن؛ الصبر يأتي بالفتح بلا قتال.",
      "none", "community_vs_outsider", "religious_freedom",
      "refusal_to_compromise", "refusing_to_legitimize_falsehood", "praise"),

    E("ml_distribution_hunayn_meccans", 554, 8, "medinan_late",
      "إعطاء النبي ﷺ المؤلفة قلوبهم من قريش", "Giving the new Meccans from the spoils",
      "Ji'rana", ["9:60"],
      "أعطى النبي ﷺ من غنائم حنين قادة قريش الذين أسلموا حديثاً (المؤلفة قلوبهم) كأبي سفيان ومعاوية وصفوان عطايا كبيرة، تأليفاً لقلوبهم.",
      "تأليف القلوب بالعطاء سياسة مشروعة؛ الإيمان يُغذّى أحياناً بالمال.",
      "none", "community_vs_outsider", "trust_between_parties",
      "compromise_for_larger_goal", "scaling_principle_to_context", "legislation"),

    E("ml_ansar_complain_distribution", 555, 8, "medinan_late",
      "تذمّر بعض الأنصار من القسمة", "Some Ansar complain about the distribution",
      "Ji'rana", ["9:60"],
      "تذمّر بعض شباب الأنصار قائلين: يُعطَى قريش ونحن أصحاب السيوف، فبلغ النبي ﷺ، فجمعهم وخطبهم.",
      "الشكوى تستدعي حواراً صريحاً؛ القائد يستمع إلى الجراح المعنوية.",
      "psychological_pressure", "ally_vs_ally_dispute", "community_cohesion",
      "private_counsel", "consultation_before_decision", "argument"),

    E("ml_ansar_speech_consolation", 556, 8, "medinan_late",
      "خطبة النبي ﷺ للأنصار", "Prophet's speech to the Ansar",
      "Ji'rana", ["59:9"],
      "قال النبي ﷺ للأنصار: أما ترضون أن يذهب الناس بالشاة والبعير، وترجعون برسول الله إلى رحالكم؟ فبكوا حتى أخضلوا لحاهم وقالوا: رضينا.",
      "العاطفة الصادقة من القائد تُذيب كل غضب؛ القرب الشخصي أغلى من المال.",
      "psychological_pressure", "leader_vs_follower", "trust_between_parties",
      "consolation_and_thabaat", "solidarity_around_principle", "praise"),

    # ═══════════════ TABUK ═══════════════
    E("ml_tabuk_news_romans", 557, 9, "medinan_late",
      "نبأ تجمع الروم لغزو المدينة", "News of Roman gathering to invade Medina",
      "Medina", ["9:38", "9:39"],
      "بلغ النبي ﷺ أن الروم تجمع جيشاً كبيراً في الشام لغزو المدينة، فقرر الخروج إليهم في حر الصيف ووقت قطف الثمار وضيق الحال.",
      "أصعب القرارات في أصعب الظروف؛ القائد يخرج للأخطر لا للأسهل.",
      "existential_threat", "community_vs_outsider", "collective_survival",
      "active_resistance", "chosen_hardship_over_compromise", "command"),

    E("ml_tabuk_called_general", 558, 9, "medinan_late",
      "النفير العام لتبوك", "General call-up for Tabuk",
      "Medina", ["9:38", "9:39", "9:40", "9:41"],
      "أمر النبي ﷺ بالنفير العام، وكان النفير في تبوك إجبارياً للجميع لخطورة الموقف، خلافاً لعادته في إخفاء الوجهة.",
      "بعض المعارك تستحق التصريح؛ الشفافية عند الأزمة الكبرى.",
      "existential_threat", "community_vs_outsider", "collective_survival",
      "public_declaration", "knowledge_before_action", "command"),

    E("ml_uthman_funds_jaysh_alusra", 559, 9, "medinan_late",
      "عثمان يموّل جيش العسرة", "Uthman funds the Army of Hardship",
      "Medina", ["9:100"],
      "جهّز عثمان بن عفان ثلث جيش العسرة بـ 300 بعير و1000 دينار، فقال النبي ﷺ: ما ضرّ عثمان ما عمل بعد اليوم.",
      "العطاء في وقت العسرة يُعدل ما بعده من الذنوب؛ المال يفدي صاحبه.",
      "economic_siege", "community_vs_outsider", "collective_survival",
      "organizational_response", "wealth_as_trust_not_ownership", "praise"),

    E("ml_abu_bakr_all_wealth_again", 560, 9, "medinan_late",
      "أبو بكر يأتي بكل ماله مرة أخرى", "Abu Bakr brings all his wealth again",
      "Medina", ["92:5", "92:6", "92:7"],
      "جاء أبو بكر بكل ماله إلى تبوك، فسأله النبي ﷺ: ما أبقيت لأهلك؟ فقال: أبقيت لهم الله ورسوله. فقال عمر: لا أسبقك إلى شيء أبداً.",
      "الإيثار المطلق ثقة مطلقة بالله؛ المنافسة في الخير خطّت تاريخاً.",
      "economic_siege", "community_vs_outsider", "livelihood",
      "refusal_to_compromise", "wealth_as_trust_not_ownership", "praise"),

    E("ml_bakaeen", 561, 9, "medinan_late",
      "البكّاؤون الذين لم يجدوا مركباً", "The weeping ones who found no mount",
      "Medina", ["9:92"],
      "جاء سبعة من فقراء الصحابة إلى النبي ﷺ يطلبون مركباً للخروج إلى تبوك، فلم يجد فبكوا حزناً، فأنزل الله عذرهم.",
      "العجز عن الخدمة بالأسباب لا يُلغي النية؛ الدمعة الصادقة عذر مقبول.",
      "psychological_pressure", "community_vs_outsider", "spiritual_integrity",
      "endurance_without_retaliation", "intention_determines_value", "consolation"),

    E("ml_munafiqeen_excuses", 562, 9, "medinan_late",
      "أعذار المنافقين عن الخروج", "Hypocrites' excuses to avoid going",
      "Medina", ["9:42", "9:43", "9:44", "9:45", "9:46", "9:47", "9:48", "9:49"],
      "تخلّف ثلاثة أصناف عن تبوك: المنافقون، والثلاثة الذين خُلّفوا (كعب وصاحبيه)، والمعذورون. وفضح القرآن كل صنف.",
      "الخروج للجهاد يفرز الصفوف؛ الأعذار الكاذبة تُكشف.",
      "internal_betrayal", "insider_hypocrite_vs_sincere", "trust_between_parties",
      "moral_rebuke", "consistency_public_and_private", "rebuke"),

    E("ml_tabuk_journey_hardship", 563, 9, "medinan_late",
      "مشقة الطريق إلى تبوك", "Hardship of the journey to Tabuk",
      "Tabuk route", ["9:117"],
      "كانت الرحلة إلى تبوك في حر شديد ونقص ماء وطعام، حتى كان الرجلان والثلاثة يقتسمون التمرة الواحدة، ونحرت الإبل لعصر مياه أحشائها.",
      "المشقة الفعلية تختبر الإيمان؛ الكلمة سهلة والميدان صعب.",
      "existential_threat", "community_vs_outsider", "physical_safety",
      "endurance_without_retaliation", "chosen_hardship_over_compromise", "consolation"),

    E("ml_tabuk_no_battle", 564, 9, "medinan_late",
      "وصول النبي ﷺ تبوك دون قتال", "Reaching Tabuk without fighting",
      "Tabuk", ["9:38", "9:39"],
      "وصل النبي ﷺ إلى تبوك ولم يجد جيش الروم، فأقام عشرين ليلة ثم رجع، وكان مجرد الخروج كافياً لردع التحالف.",
      "الردع قد يكفي عن الحرب؛ الظهور بقوة يُلغي حاجة الاشتباك.",
      "political_pressure", "community_vs_outsider", "collective_survival",
      "public_declaration", "knowledge_before_action", "promise"),

    E("ml_ayla_treaty", 565, 9, "medinan_late",
      "صلح أيلة وأذرح", "Treaty with Ayla and Adhruh",
      "Tabuk", ["9:29"],
      "في تبوك جاء يوحنا بن رؤبة صاحب أيلة فصالح النبي ﷺ على الجزية، وكذلك أهل أذرح والجرباء، فدخلوا تحت حماية الإسلام دون قتال.",
      "الجزية بدل القتال نظام مشروع؛ السلام بالتعايش.",
      "political_pressure", "community_vs_outsider", "trust_between_parties",
      "compromise_for_larger_goal", "distinguishing_enemy_from_outsider", "legislation"),

    E("ml_kab_malik_truth", 566, 9, "medinan_late",
      "كعب بن مالك يصدق في الاعتذار", "Ka'b ibn Malik is truthful in his apology",
      "Medina", ["9:117", "9:118", "9:119"],
      "تخلّف كعب بن مالك ومرارة بن الربيع وهلال بن أمية عن تبوك بلا عذر حقيقي، فأمرهم النبي ﷺ أن يعتذروا بصدق، فاعترفوا، فهجرهم 50 ليلة حتى تيب عليهم.",
      "الصدق في الاعتراف بالذنب أنجى من اعتذار المنافقين؛ القرآن يكافئ الصدق حتى لو كان ضد صاحبه.",
      "moral_failure_by_self", "self_vs_self", "trust_between_parties",
      "self_correction", "honesty_over_expedience", "praise"),

    E("ml_hijra_boycott_three", 567, 9, "medinan_late",
      "هجران الثلاثة خمسين ليلة", "Boycotting the three for fifty nights",
      "Medina", ["9:118"],
      "هجر النبي ﷺ والمسلمون كعب بن مالك وصاحبيه خمسين ليلة، حتى ضاقت عليهم الأرض بما رحبت، ثم نزلت توبتهم.",
      "العقوبة المعنوية الجماعية للمؤمن المقصّر أبلغ من العقوبة المادية؛ القطيعة من الجماعة موت معنوي.",
      "social_exclusion", "community_vs_outsider", "community_cohesion",
      "moral_rebuke", "preserving_channels_of_return", "warning"),

    E("ml_kab_returns_god", 568, 9, "medinan_late",
      "نزول توبة الثلاثة من السماء", "Heavenly forgiveness of the three",
      "Medina", ["9:118"],
      "بعد خمسين ليلة نزل قول الله: وعلى الثلاثة الذين خُلّفوا حتى إذا ضاقت عليهم الأرض بما رحبت وضاقت عليهم أنفسهم، ثم تاب عليهم ليتوبوا.",
      "التوبة النصوح تستنزل الرحمة من السماء؛ الصبر على المعاناة يُؤتى ثمره.",
      "psychological_pressure", "community_vs_outsider", "trust_between_parties",
      "forgiveness_from_power", "repentance_as_open_door", "promise"),

    E("ml_masjid_dirar", 569, 9, "medinan_late",
      "مسجد الضرار", "Masjid al-Dirar",
      "Medina", ["9:107", "9:108", "9:109", "9:110"],
      "بنى المنافقون مسجداً يُضارّون به مسجد قباء وأرادوا أن يصلي فيه النبي ﷺ ليتخذوه مركزاً للتفريق، فأمر بهدمه عند رجوعه من تبوك.",
      "الشعائر تُعرف بمقاصدها لا بصورها؛ المؤسسة إذا بُنيت لتفريق الصف فلا حرمة لها.",
      "internal_betrayal", "insider_hypocrite_vs_sincere", "community_cohesion",
      "refusing_to_legitimize_falsehood", "refusing_to_legitimize_falsehood", "command"),

    # ═══════════════ YEAR 9 — DELEGATIONS ═══════════════
    E("ml_year_of_delegations", 570, 9, "medinan_late",
      "عام الوفود", "Year of delegations",
      "Medina", ["110:1", "110:2"],
      "بعد عودة النبي ﷺ من تبوك وفيما بعد فتح مكة، انسابت إلى المدينة وفود قبائل العرب من كل أرجاء الجزيرة معلنة إسلامها، فسُمي العام عام الوفود.",
      "الفتح الكبير يفتح أبواب القلوب؛ الجماهير تتبع الانتصار.",
      "none", "community_vs_outsider", "religious_freedom",
      "organizational_response", "leadership_accountability", "promise"),

    E("ml_thaqif_delegation_full", 571, 9, "medinan_late",
      "وفد ثقيف وشروطهم", "Thaqif delegation and their conditions",
      "Medina", ["7:158"],
      "جاء وفد ثقيف يعرضون الإسلام بشروط: إبقاء اللات سنة، وألا يكسروها بأيديهم، وأن يُعفوا من الصلاة. فرفض النبي ﷺ كل ذلك إلا أن يكسر صنمهم غيرهم.",
      "الشروط على الإيمان مرفوضة؛ التنازل في الجوهر مرفوض.",
      "moral_temptation", "community_vs_outsider", "religious_freedom",
      "refusal_to_compromise", "refusing_to_legitimize_falsehood", "argument"),

    E("ml_hawazin_delegation", 572, 9, "medinan_late",
      "وفد هوازن يطلب السبي", "Hawazin delegation requests captives back",
      "Medina/Ji'rana", ["9:25"],
      "جاء وفد هوازن إلى النبي ﷺ بعد إسلامهم يطلبون السبي، فردّ النبي السبي بعد أن استطاب نفوس الصحابة.",
      "الإسلام يُعيد ما أخذته الحرب؛ الأخوة في الدين فوق الحقوق المادية.",
      "economic_siege", "community_vs_outsider", "personal_dignity",
      "forgiveness_from_power", "preserving_channels_of_return", "praise"),

    E("ml_najran_delegation_year_9", 573, 9, "medinan_late",
      "وفد نجران الكامل", "Full delegation of Najran",
      "Medina", ["3:33", "3:34", "3:35", "3:36", "3:37", "3:38", "3:39", "3:40", "3:41", "3:42", "3:43", "3:44", "3:45", "3:46", "3:47", "3:48", "3:49", "3:50", "3:51", "3:52", "3:53", "3:54", "3:55", "3:56", "3:57", "3:58", "3:59", "3:60", "3:61", "3:62", "3:63"],
      "قدم وفد نصارى نجران (60 رجلاً) إلى المدينة في 9هـ، فاستقبلهم النبي ﷺ في مسجده وأنزل الله فيهم 80 آية من أول سورة آل عمران.",
      "الحوار العقدي مع المخالف من قواعد الدعوة؛ النص يستوعب كل ادعاء بحجة.",
      "intellectual_challenge", "community_vs_outsider", "religious_freedom",
      "intellectual_rebuttal", "knowledge_before_action", "argument"),

    E("ml_mubahala_najran", 574, 9, "medinan_late",
      "مباهلة وفد نجران", "Mubahala with the Najran delegation",
      "Medina", ["3:61", "3:62"],
      "بعد أن حُجّوا في المسائل دعاهم النبي ﷺ إلى المباهلة (الدعاء بأن لعنة الله على الكاذبين)، فامتنعوا وقالوا: نخاف أن نُهلك، فاختاروا الجزية.",
      "حين تعجز الحجة يلجأ القرآن للبرهان الميداني؛ التراجع عن المباهلة اعتراف ضمني.",
      "intellectual_challenge", "community_vs_outsider", "truth_vs_falsehood",
      "confrontation_with_truth", "legitimacy_follows_method", "argument"),

    E("ml_abdulqays_delegation", 575, 9, "medinan_late",
      "وفد عبد القيس من البحرين", "Abd al-Qays delegation from Bahrain",
      "Medina", ["49:13"],
      "جاء وفد عبد القيس برئاسة الأشج العصري إلى النبي ﷺ يسألون عن أصول الإسلام، فأجابهم بالإيمان والصلاة والزكاة والصوم والحج وأداء خمس المغنم.",
      "تقليص الدين إلى أصوله أبلغ من إثقال السائل؛ الإيمان جوهره لا فروعه.",
      "intellectual_challenge", "community_vs_outsider", "knowledge_access",
      "clarification", "scaling_principle_to_context", "command"),

    E("ml_tamim_dari_christianity", 576, 9, "medinan_late",
      "إسلام تميم الداري النصراني", "Conversion of Tamim al-Dari the Christian",
      "Medina", ["46:10"],
      "أسلم تميم الداري النصراني وحدّث النبي ﷺ بقصة الجساسة والدجال التي رواها له لاحقاً على المنبر، فصارت من معالم الفتن.",
      "العالم النصراني يُسلم ويأتي بعلمه لخدمة الإسلام؛ المعرفة السابقة تُغني الرسالة.",
      "none", "community_vs_outsider", "knowledge_access",
      "confrontation_with_truth", "knowledge_before_action", "praise"),

    E("ml_aswad_ansi_yemen", 577, 10, "medinan_late",
      "خروج الأسود العنسي مدّعي النبوة باليمن", "Al-Aswad al-Ansi false prophet in Yemen",
      "Yemen", ["3:144"],
      "خرج الأسود العنسي في اليمن بأواخر حياة النبي ﷺ يدّعي النبوة، فقتله فيروز الديلمي وأخباره بليلة موت النبي ﷺ.",
      "المدّعون يخرجون عند الأزمات؛ الباطل يستغل الفوضى.",
      "verbal_attack", "community_vs_outsider", "religious_freedom",
      "refusing_to_legitimize_falsehood", "refusing_to_legitimize_falsehood", "warning"),

    E("ml_musaylima_yamamah", 578, 10, "medinan_late",
      "مسيلمة الكذاب يدعي النبوة", "Musaylima the liar claims prophethood",
      "Yamamah", ["3:144"],
      "ادّعى مسيلمة بن حبيب الحنفي النبوة في اليمامة، وكتب إلى النبي ﷺ: من مسيلمة رسول الله إلى محمد رسول الله، أما بعد فإن الأرض نصفها لي ونصفها لك.",
      "ادّعاء النبوة عند تمكّن الرسالة الحقيقية ممارسة قديمة؛ المدعون عُذر الفتنة.",
      "verbal_attack", "community_vs_outsider", "religious_freedom",
      "refusal_to_compromise", "refusing_to_legitimize_falsehood", "warning"),

    # ═══════════════ Hajjat al-wada' ═══════════════
    E("ml_hajj_announcement", 579, 10, "medinan_late",
      "إعلان النبي ﷺ نية الحج", "Prophet announces intention to perform Hajj",
      "Medina", ["3:97", "22:27"],
      "أعلن النبي ﷺ في ذي القعدة 10 هـ عزمه على الحج، فاجتمع معه نحو 100,000 مسلم لأداء الحج معه أول مرة وأخيرة.",
      "الحج الأول للنبي بعد فرضه؛ القائد ينتظر اللحظة المناسبة.",
      "none", "community_vs_outsider", "spiritual_integrity",
      "public_declaration", "consistency_public_and_private", "command"),

    E("ml_dhul_hulayfa_ihram", 580, 10, "medinan_late",
      "إحرام النبي ﷺ من ذي الحليفة", "Prophet's ihram from Dhul-Hulayfa",
      "Dhul-Hulayfa", ["22:27"],
      "أحرم النبي ﷺ من ذي الحليفة (مسجد الشجرة) بالحج والعمرة قارناً، ولبّى تلبيته المشهورة: لبيك اللهم لبيك.",
      "البدء بالميقات شرط الإحرام؛ التلبية إعلان جماعي.",
      "none", "community_vs_outsider", "spiritual_integrity",
      "teaching_through_demonstration", "consistency_public_and_private", "legislation"),

    E("ml_hajj_demonstration", 581, 10, "medinan_late",
      "تعليم النبي ﷺ مناسك الحج بنفسه", "Prophet personally teaches the rituals of Hajj",
      "Mecca/Mina", ["22:27"],
      "علّم النبي ﷺ المسلمين مناسك الحج بنفسه، وقال: خذوا عني مناسككم، فطوّف وسعى وحلق وذبح وفعل بأمته كل المناسك.",
      "القدوة العملية أبلغ من الفتوى؛ تعليم العبادة بالفعل.",
      "none", "teacher_vs_student", "knowledge_access",
      "teaching_through_demonstration", "knowledge_before_action", "command"),

    E("ml_hajj_arafat_sermon", 582, 10, "medinan_late",
      "خطبة عرفة في حجة الوداع", "Sermon at Arafat in the farewell pilgrimage",
      "Arafat", ["5:3"],
      "خطب النبي ﷺ في الناس على جبل عرفة خطبة جامعة بيّن فيها أصول الدين والمعاملات وحقوق الإنسان والربا والدماء.",
      "أعظم خطبة في تاريخ البشرية تختصر دستور أمة؛ القائد يترك وصيته الكبرى.",
      "none", "leader_vs_follower", "community_cohesion",
      "public_declaration", "leadership_accountability", "command"),

    E("ml_kamal_aldeen_revealed", 583, 10, "medinan_late",
      "نزول آية إكمال الدين", "Revelation of the verse of completing the religion",
      "Arafat", ["5:3"],
      "نزل قول الله: اليوم أكملت لكم دينكم وأتممت عليكم نعمتي ورضيت لكم الإسلام ديناً، يوم عرفة في حجة الوداع، فبكى عمر لأنه علم أن الكمال إيذان بانتهاء المهمة.",
      "اكتمال الرسالة إعلان نهاية الوحي؛ بعد الكمال لا حاجة لجديد.",
      "none", "community_vs_outsider", "spiritual_integrity",
      "public_declaration", "leadership_accountability", "promise"),

    E("ml_jibal_almihjan", 584, 10, "medinan_late",
      "النبي ﷺ يحرّم الظلم في خطبة عرفة", "Prophet forbids injustice in the Arafat sermon",
      "Arafat", ["49:13"],
      "قال النبي ﷺ في عرفة: إن دماءكم وأموالكم وأعراضكم بينكم حرام كحرمة يومكم هذا في شهركم هذا في بلدكم هذا.",
      "حرمة الإنسان فوق حرمة الأرض والزمان؛ الكرامة الإنسانية أقدس المقدسات.",
      "verbal_attack", "community_vs_outsider", "personal_dignity",
      "legal_innovation", "protection_of_the_weak", "legislation"),

    E("ml_riba_jahiliyya_abolished", 585, 10, "medinan_late",
      "إلغاء ربا الجاهلية في خطبة عرفة", "Abolishing pre-Islamic usury at Arafat",
      "Arafat", ["2:278", "2:279"],
      "أعلن النبي ﷺ في عرفة: ألا وإن كل ربا في الجاهلية موضوع، وأول ربا أضع ربا العباس بن عبد المطلب.",
      "البدء بإلغاء ربا الأقربين قدوة؛ القائد يُسقط ميراثه قبل ميراث الناس.",
      "moral_temptation", "kin_vs_kin", "livelihood",
      "refusal_to_compromise", "leadership_accountability", "legislation"),

    E("ml_women_rights_arafat", 586, 10, "medinan_late",
      "حقوق المرأة في خطبة عرفة", "Women's rights in the Arafat sermon",
      "Arafat", ["4:19"],
      "قال النبي ﷺ في عرفة: اتقوا الله في النساء، فإنكم أخذتموهن بأمانة الله واستحللتم فروجهن بكلمة الله، فلهن عليكم رزقهن وكسوتهن بالمعروف.",
      "تذكير الأمة بحقوق المرأة في أكبر تجمع؛ الأمانة على الزوجة من أعظم الأمانات.",
      "verbal_attack", "spouse_vs_spouse", "personal_dignity",
      "legal_innovation", "protection_of_the_weak", "command"),

    E("ml_three_circles_humanity", 587, 10, "medinan_late",
      "إعلان وحدة الجنس البشري", "Declaration of human unity",
      "Arafat", ["49:13"],
      "قال النبي ﷺ في عرفة: يا أيها الناس، ألا إن ربكم واحد، وإن أباكم واحد، ألا لا فضل لعربي على أعجمي ولا لأعجمي على عربي إلا بالتقوى.",
      "الإسلام أقدم إعلان لحقوق الإنسان؛ المساواة الجذرية بين البشر.",
      "social_exclusion", "community_vs_outsider", "personal_dignity",
      "legal_innovation", "rejection_of_blind_imitation", "command"),

    E("ml_witnesses_at_arafat", 588, 10, "medinan_late",
      "شهادة النبي ﷺ يوم عرفة", "Prophet asks for witnessing at Arafat",
      "Arafat", ["5:67"],
      "ختم النبي ﷺ خطبة عرفة قائلاً: ألا هل بلّغت؟ قالوا: نعم، فقال: اللهم اشهد، ثلاث مرات، وأشار بإصبعه إلى السماء.",
      "إشهاد الله على إنجاز الرسالة؛ القائد يتأكد أن المهمة تمت.",
      "none", "leader_vs_follower", "trust_between_parties",
      "witnessing_and_documentation", "consistency_public_and_private", "promise"),

    E("ml_throwing_jamarat_teaching", 589, 10, "medinan_late",
      "تعليم رمي الجمار", "Teaching the stoning of Jamarat",
      "Mina", ["22:27"],
      "علّم النبي ﷺ المسلمين رمي الجمرات بسبع حصيات في كل جمرة، وبيّن لهم الحكم وراء الرمي.",
      "العبادة لها صورة تعليمية ومعنى رمزي؛ كل حركة في الحج لها دلالة.",
      "none", "teacher_vs_student", "knowledge_access",
      "teaching_through_demonstration", "consistency_public_and_private", "legislation"),

    E("ml_sacrificing_in_mina", 590, 10, "medinan_late",
      "النبي ﷺ يذبح الهدي بنفسه", "Prophet personally sacrifices the offerings",
      "Mina", ["22:36"],
      "نحر النبي ﷺ بيده ثلاثاً وستين بدنة من إبله، وأمر علياً فنحر ما غبر، وأشركه في هديه.",
      "العبادة الكبرى تُؤدّى بالقدوة والمشاركة؛ القائد يقتسم مع غيره.",
      "none", "community_vs_outsider", "spiritual_integrity",
      "teaching_through_demonstration", "leadership_accountability", "praise"),

    E("ml_hajj_simple_garments", 591, 10, "medinan_late",
      "النبي ﷺ يحج في إزار ورداء", "Prophet performs Hajj in a simple garment",
      "Mecca/Mina", ["22:27"],
      "أحرم النبي ﷺ في إزار ورداء بسيطين، ولم يُغيّرهما طوال أيام الحج، تأكيداً على المساواة في الزي بين كل الحجاج.",
      "زي الحج يُلغي الفروق؛ الكل أمام الله سواء.",
      "none", "community_vs_outsider", "personal_dignity",
      "teaching_through_demonstration", "rejection_of_blind_imitation", "legislation"),

    E("ml_return_from_arafat", 592, 10, "medinan_late",
      "النفرة من عرفات", "Departure from Arafat",
      "Arafat to Muzdalifa", ["2:198", "2:199"],
      "نفر النبي ﷺ من عرفات بعد الغروب إلى مزدلفة، وبات بها ثم صلى الفجر وانتقل إلى منى لرمي الجمرات والنحر.",
      "ترتيب المناسك بدقة؛ كل خطوة في وقتها ومكانها.",
      "none", "community_vs_outsider", "spiritual_integrity",
      "organizational_response", "consistency_public_and_private", "legislation"),

    E("ml_farewell_visiting_kabah", 593, 10, "medinan_late",
      "طواف الوداع", "Farewell tawaf",
      "Mecca", ["22:29"],
      "طاف النبي ﷺ طواف الوداع قبل خروجه من مكة، وأمر الناس ألا ينفروا حتى يكون آخر عهدهم بالبيت الطواف.",
      "آخر فعل في الزيارة وداع؛ القائد يُختم العمل بإكرام.",
      "none", "self_vs_self", "spiritual_integrity",
      "teaching_through_demonstration", "consistency_public_and_private", "legislation"),

    # ═══════════════ FINAL ILLNESS ═══════════════
    E("ml_return_from_hajj", 594, 11, "medinan_late",
      "عودة النبي ﷺ من الحج إلى المدينة", "Prophet's return from Hajj to Medina",
      "Medina", ["110:3"],
      "عاد النبي ﷺ من الحج إلى المدينة في ذي الحجة 10هـ، فأكمل أعماله الإدارية وأرسل أسامة بن زيد في جيش إلى الشام.",
      "العودة من العبادة الكبرى للعمل المستمر؛ القائد لا يستريح حتى آخر نفس.",
      "none", "leader_vs_follower", "collective_survival",
      "organizational_response", "leadership_accountability", "command"),

    E("ml_usama_army_yong_leader", 595, 11, "medinan_late",
      "تأمير أسامة بن زيد على الجيش", "Appointing the young Usama as army commander",
      "Medina", ["33:5"],
      "أمّر النبي ﷺ أسامة بن زيد (الفتى البالغ 18 سنة) على جيش فيه كبار الصحابة كأبي بكر وعمر، فاعترض البعض، فأكد النبي تأميره.",
      "الكفاءة الشابة فوق العمر؛ القيادة لا تُورَث بالسن.",
      "intellectual_challenge", "leader_vs_follower", "trust_between_parties",
      "refusal_to_compromise", "knowledge_before_action", "command"),

    E("ml_first_signs_illness", 596, 11, "medinan_late",
      "بداية مرض النبي ﷺ", "Beginning of the Prophet's final illness",
      "Medina", ["3:144"],
      "بدأ النبي ﷺ يشعر بأعراض المرض في صفر 11 هـ، ثم اشتدّ المرض شيئاً فشيئاً وأخذ يُقدّم وصاياه الأخيرة لأمته.",
      "نهاية حياة القائد فرصة لتوثيق رسائله؛ المرض الأخير يصل بالعطاء إلى ذروته.",
      "psychological_pressure", "self_vs_self", "spiritual_integrity",
      "endurance_without_retaliation", "consistency_public_and_private", "consolation"),

    E("ml_walks_baqi_dua", 597, 11, "medinan_late",
      "زيارة النبي ﷺ لشهداء البقيع", "Prophet visits the martyrs of al-Baqi'",
      "Medina/Baqi'", ["49:10"],
      "خرج النبي ﷺ ليلاً إلى البقيع يدعو لشهداء المدينة، وقال: السلام عليكم دار قوم مؤمنين، وإنا إن شاء الله بكم لاحقون.",
      "الوداع للأموات قبل الانضمام إليهم؛ القائد يحفظ صلته بمن سبق.",
      "psychological_pressure", "community_vs_outsider", "spiritual_integrity",
      "consolation_and_thabaat", "solidarity_around_principle", "praise"),

    E("ml_request_aisha_house", 598, 11, "medinan_late",
      "طلب النبي ﷺ التمريض في بيت عائشة", "Prophet asks to be nursed in Aisha's house",
      "Medina", ["33:33"],
      "اشتدّ المرض على النبي ﷺ، فاستأذن أزواجه في أن يُمرَّض في بيت عائشة، فأذنّ له، فانتقل إليها.",
      "طلب الراحة الشخصية مشروع حتى مع الزوجات؛ الأقرب يُختار في الأزمة.",
      "psychological_pressure", "spouse_vs_spouse", "family_integrity",
      "private_counsel", "boundaries_in_intimate_relations", "consolation"),

    E("ml_orders_abu_bakr_imamate", 599, 11, "medinan_late",
      "أمر أبي بكر بإمامة الناس في الصلاة", "Ordering Abu Bakr to lead the prayer",
      "Medina", ["3:159"],
      "لما اشتد المرض على النبي ﷺ أمر أبا بكر أن يصلي بالناس، فقالت عائشة: يا رسول الله، إن أبا بكر رجل أسيف، فلا يستطيع، فأبى النبي إلا أبو بكر.",
      "الإشارة لخلافة أبي بكر بأمر الإمامة؛ القائد يهيء أمته لما بعده.",
      "psychological_pressure", "leader_vs_follower", "community_cohesion",
      "consultation_before_decision", "trust_is_earned_by_consistency", "command"),

    E("ml_last_walk_to_mosque", 600, 11, "medinan_late",
      "آخر خروج للنبي ﷺ إلى المسجد", "Prophet's last walk to the mosque",
      "Medina", ["7:46"],
      "خرج النبي ﷺ في آخر مرة إلى المسجد بين علي والفضل بن العباس وقدماه تخطّان الأرض، فجلس على المنبر وأوصى بالأنصار.",
      "آخر كلمات القائد إكرام للأقرب؛ الذكرى الأخيرة تثبت في النفس.",
      "psychological_pressure", "leader_vs_follower", "community_cohesion",
      "consolation_and_thabaat", "solidarity_around_principle", "consolation"),

    E("ml_takbir_for_uhud", 601, 11, "medinan_late",
      "صلاة النبي ﷺ على شهداء أحد قبل وفاته", "Prophet prays for Uhud martyrs before his death",
      "Medina", ["3:169"],
      "خرج النبي ﷺ في أيام مرضه إلى شهداء أحد فصلى عليهم كأنه يودع الأحياء والأموات، ثم رجع إلى المنبر فخطب.",
      "الوداع الشامل قبل الرحيل؛ القائد يُصلح كل صلة قبل الذهاب.",
      "psychological_pressure", "leader_vs_follower", "community_cohesion",
      "consolation_and_thabaat", "leadership_accountability", "praise"),

    E("ml_request_pen_paper", 602, 11, "medinan_late",
      "طلب القرطاس والقلم في مرضه", "Prophet requests pen and paper in his illness",
      "Medina", ["5:67"],
      "في مرضه قال النبي ﷺ: ائتوني بكتاب أكتب لكم كتاباً لن تضلوا بعده، فاختلف الصحابة هل يأتون به أم يكفيهم القرآن، فترك النبي الأمر.",
      "الاجتهاد الجماعي في فهم الأمر؛ ترك التأكيد قد يكون نوعاً من القرار.",
      "psychological_pressure", "leader_vs_follower", "community_cohesion",
      "consultation_before_decision", "limits_of_personal_discretion", "argument"),

    E("ml_freeing_servant", 603, 11, "medinan_late",
      "إعتاق النبي ﷺ خادمه قبل وفاته", "Prophet frees his servant before his death",
      "Medina", ["90:13"],
      "أعتق النبي ﷺ في مرضه عبداً من خدمه ووهب درهماته السبع التي كانت عنده للفقراء، فلم يبقَ في بيته شيء يوم وفاته.",
      "تحرير العبد آخر فعل من أفعال العتق؛ المال يُترك خفيفاً.",
      "none", "ruler_vs_ruled", "personal_dignity",
      "forgiveness_from_power", "wealth_as_trust_not_ownership", "praise"),

    E("ml_seven_dirhams", 604, 11, "medinan_late",
      "النبي ﷺ يأمر بإخراج آخر ما عنده", "Prophet orders distributing his last money",
      "Medina", ["92:5"],
      "كان عند النبي ﷺ سبعة دراهم، فظل في مرضه يقول لعائشة: ما فعلت السبعة؟ حتى تصدقت بها كاملة، فقال: الآن استرحت.",
      "الفقر الاختياري عبادة؛ المال أمانة لا تُخلّف وراء.",
      "psychological_pressure", "self_vs_self", "livelihood",
      "wealth_as_trust_not_ownership", "wealth_as_trust_not_ownership", "praise"),

    E("ml_aisha_lap_death", 605, 11, "medinan_late",
      "وفاة النبي ﷺ في حجر عائشة", "Death of the Prophet in Aisha's lap",
      "Medina", ["3:144"],
      "توفي النبي ﷺ في حجر عائشة ضحى الاثنين 12 ربيع الأول 11 هـ، وآخر كلماته: الصلاة الصلاة، وما ملكت أيمانكم، ثم رفع إصبعه: في الرفيق الأعلى.",
      "آخر كلمات الرسول وصايا للأمة؛ الرحيل بإصبع مرفوعة إلى الأعلى.",
      "psychological_pressure", "spouse_vs_spouse", "spiritual_integrity",
      "consolation_and_thabaat", "consistency_public_and_private", "consolation"),

    E("ml_umar_denies_death", 606, 11, "medinan_late",
      "إنكار عمر لوفاة النبي ﷺ", "Umar denies the Prophet's death",
      "Medina", ["3:144"],
      "أنكر عمر وفاة النبي ﷺ صدمةً وقال: ما مات رسول الله ﷺ ولكنه ذهب إلى ربه كموسى. فهدّأه أبو بكر وقال: من كان يعبد محمداً فإن محمداً قد مات.",
      "الصدمة قد تُذهب الفهم؛ الأبو الأكبر يُعيد التوازن.",
      "psychological_pressure", "ally_vs_ally_dispute", "trust_between_parties",
      "consolation_and_thabaat", "knowledge_before_action", "consolation"),

    E("ml_abu_bakr_speech_death", 607, 11, "medinan_late",
      "خطبة أبي بكر لما توفي النبي ﷺ", "Abu Bakr's speech upon the Prophet's death",
      "Medina", ["3:144"],
      "صعد أبو بكر المنبر وقال: من كان يعبد محمداً فإن محمداً قد مات، ومن كان يعبد الله فإن الله حي لا يموت، ثم تلا: وما محمد إلا رسول قد خلت من قبله الرسل.",
      "تذكير الأمة بأن الرسالة فوق الرسول؛ الإيمان لا يموت بموت حامله.",
      "psychological_pressure", "leader_vs_follower", "community_cohesion",
      "consolation_and_thabaat", "source_integrity_over_popularity", "consolation"),

    E("ml_saqifa_meeting", 608, 11, "medinan_late",
      "اجتماع السقيفة لاختيار الخليفة", "Saqifa meeting to choose the caliph",
      "Medina", ["42:38"],
      "اجتمع الأنصار في سقيفة بني ساعدة لاختيار خليفة، فلحق بهم أبو بكر وعمر وأبو عبيدة، فبايعوا أبا بكر بعد نقاش حول الأحقية.",
      "الشورى في اختيار القائد؛ الانتقال السلمي للسلطة بعد القائد المؤسس.",
      "political_pressure", "ally_vs_ally_dispute", "community_cohesion",
      "consultation_before_decision", "consultation_before_decision", "argument"),

    E("ml_burial_in_aisha_room", 609, 11, "medinan_late",
      "دفن النبي ﷺ في حجرة عائشة", "Burial of the Prophet in Aisha's chamber",
      "Medina", ["3:144"],
      "دُفن النبي ﷺ في موضع وفاته في حجرة عائشة، حيث كان قد أفتى الصحابة أن الأنبياء يُدفنون حيث يُقبضون.",
      "بساطة دفن أعظم الناس؛ ليس له قبر مزخرف.",
      "none", "self_vs_self", "personal_dignity",
      "teaching_through_demonstration", "leadership_accountability", "story"),

    # Filler additional events 610-650 with key sub-events
    E("ml_islam_complete_announce", 610, 10, "medinan_late",
      "إعلان كمال الدين أمام الأمة", "Announcing the completion of religion to the ummah",
      "Arafat", ["5:3"],
      "أعلن النبي ﷺ في حجة الوداع كمال الدين أمام مئة ألف من المسلمين، فبكى عمر وقيل له لمَ تبكي؟ قال: لأنه ما بعد الكمال إلا النقص.",
      "الكمال إشارة إلى نهاية المهمة؛ من فهم العلامات حزن.",
      "none", "community_vs_outsider", "spiritual_integrity",
      "public_declaration", "consistency_public_and_private", "promise"),

    E("ml_amr_alas_oman", 611, 8, "medinan_late",
      "عمرو بن العاص يفتح عمان بالدبلوماسية", "Amr ibn al-As converts Oman through diplomacy",
      "Oman", ["3:64"],
      "أسلم ملكا عمان جيفر وعبد ابنا الجلندي على يد عمرو بن العاص، ودخلت عمان كلها في الإسلام صلحاً بلا قتال.",
      "الدبلوماسية الذكية تفتح بلداً بكلمة؛ الكفاءة في موضعها.",
      "none", "ruler_vs_ruled", "religious_freedom",
      "compromise_for_larger_goal", "knowledge_before_action", "praise"),

    E("ml_khalid_idol_uzza", 612, 8, "medinan_late",
      "خالد بن الوليد يحطم العزى", "Khalid destroys al-Uzza idol",
      "Nakhla", ["53:19", "53:20"],
      "أرسل النبي ﷺ خالد بن الوليد إلى صنم العزى في نخلة فحطّمه، فظهرت له شيطانة فقطعها.",
      "تطهير الجزيرة من رموز الشرك؛ كل صنم يُحطم برسوله.",
      "none", "community_vs_outsider", "religious_freedom",
      "active_resistance", "refusing_to_legitimize_falsehood", "command"),

    E("ml_amr_alas_idol_suwa", 613, 8, "medinan_late",
      "عمرو بن العاص يحطم سُواع", "Amr destroys Suwa' idol",
      "Ruhat", ["71:23"],
      "أرسل النبي ﷺ عمرو بن العاص إلى صنم سواع لهذيل، فحطّمه ولم يجد عنده إلا سدنة فرّوا.",
      "الأصنام بلا حراس حقيقيين؛ السلطان الديني لا يُسنده حقيقة.",
      "none", "community_vs_outsider", "religious_freedom",
      "active_resistance", "refusing_to_legitimize_falsehood", "command"),

    E("ml_saad_zayd_manat", 614, 8, "medinan_late",
      "سعد بن زيد يحطم مناة", "Sa'd ibn Zayd destroys Manat idol",
      "Mushallal", ["53:20"],
      "أرسل النبي ﷺ سعد بن زيد الأشهلي إلى صنم مناة بالمشلل بين مكة والمدينة، فحطّمه وأخذ ما عنده من حلي وأموال.",
      "الأصنام تُترك للزمن أحياناً؛ النبي يصبر حتى تأتي اللحظة.",
      "none", "community_vs_outsider", "religious_freedom",
      "active_resistance", "refusing_to_legitimize_falsehood", "command"),

    E("ml_battle_dhi_khalsah", 615, 9, "medinan_late",
      "فتح ذي الخلصة (الكعبة اليمانية)", "Conquest of Dhul-Khalasa (Yemenite Ka'ba)",
      "Yemen", ["7:138"],
      "أرسل النبي ﷺ جرير بن عبد الله البجلي إلى ذي الخلصة (كعبة كانت تعبدها قبائل يمانية) فحطّمها وأشعل فيها النار.",
      "حتى الكعبات الموازية تُهدم؛ التوحيد لا يقبل المنافسة.",
      "none", "community_vs_outsider", "religious_freedom",
      "active_resistance", "refusing_to_legitimize_falsehood", "command"),

    E("ml_tamim_dari_donate_lands", 616, 9, "medinan_late",
      "تميم الداري يطلب أرضاً في فلسطين", "Tamim al-Dari requests land in Palestine",
      "Medina", ["59:7"],
      "طلب تميم الداري من النبي ﷺ أرضاً في الشام (فلسطين) إذا فُتحت، فأقطعه النبي إياها، وكان أول إقطاع في الإسلام لأرض غير مفتوحة.",
      "البصيرة بالفتوح القادمة؛ القائد يقطع أرضاً لم يفتحها بعد ثقةً بالموعد.",
      "none", "claimant_vs_accused", "property_rights",
      "legal_innovation", "trust_is_earned_by_consistency", "promise"),

    E("ml_iqama_jizya_yemen", 617, 9, "medinan_late",
      "بدء تطبيق الجزية في اليمن", "Beginning of jizya in Yemen",
      "Yemen", ["9:29"],
      "أرسل النبي ﷺ معاذ بن جبل إلى اليمن بأخذ الجزية من أهل الكتاب فيها (نصارى نجران ويهود اليمن)، وكان معاذ أول قاضٍ مرسل.",
      "الجزية عقد للحماية في مقابل المال؛ التعايش المنظم بين الأديان.",
      "political_pressure", "ruler_vs_ruled", "trust_between_parties",
      "legal_innovation", "distinguishing_enemy_from_outsider", "legislation"),

    E("ml_muadh_to_yemen", 618, 9, "medinan_late",
      "إرسال معاذ بن جبل إلى اليمن", "Sending Mu'adh ibn Jabal to Yemen",
      "Yemen", ["4:65"],
      "بعث النبي ﷺ معاذ بن جبل إلى اليمن قاضياً وداعياً، وأوصاه بأن يحكم بكتاب الله، فإن لم يجد فبسنة رسوله، فإن لم يجد فبالاجتهاد.",
      "تأسيس مبدأ الاجتهاد بعد النص؛ القاضي يُعلّم منهج الاستنباط.",
      "none", "teacher_vs_student", "knowledge_access",
      "legal_innovation", "knowledge_before_action", "legislation"),

    E("ml_first_islamic_currency", 619, 9, "medinan_late",
      "تنظيم العملة في الإسلام", "Organizing currency in Islam",
      "Medina", ["9:34"],
      "كان المسلمون يستعملون الدراهم الفارسية والدنانير البيزنطية، ولم يضرب النبي ﷺ نقوداً جديدة، تاركاً للسوق التطور.",
      "الأنظمة المتقنة تُترك إذا لم تخالف الشرع؛ الإصلاح ليس تغيير كل شيء.",
      "none", "community_vs_outsider", "livelihood",
      "compromise_for_larger_goal", "wealth_as_trust_not_ownership", "legislation"),

    E("ml_no_ihram_in_makkah", 620, 8, "medinan_late",
      "لباس المدنية والحرم", "Civilian dress in Mecca after the conquest",
      "Mecca", ["7:31"],
      "بعد فتح مكة لم يفرض النبي ﷺ على أهلها لباساً معيناً للحياة العادية، ولكنه ميّز لباس الإحرام للحج.",
      "التشريع يميّز بين الشعيرة والحياة العامة؛ ليس كل شيء مقنناً.",
      "none", "community_vs_outsider", "personal_dignity",
      "scaling_principle_to_context", "scaling_principle_to_context", "legislation"),

    E("ml_simple_eid_clothes", 621, 8, "medinan_late",
      "ثياب العيد البسيطة", "Simple Eid clothing",
      "Medina", ["7:31", "7:32"],
      "كان النبي ﷺ يلبس في العيد أحسن ثيابه ولكنها كانت بسيطة جداً، تطبيقاً لقوله: قل من حرّم زينة الله التي أخرج لعباده.",
      "الزينة في المناسبات مشروعة؛ الإسلام لا يُحارب الجمال.",
      "none", "community_vs_outsider", "personal_dignity",
      "teaching_through_demonstration", "scaling_principle_to_context", "legislation"),

    E("ml_kindness_to_animals_camel", 622, 9, "medinan_late",
      "النبي ﷺ يبكي بكاء جمل", "Prophet weeps over an exhausted camel",
      "Medina area", ["6:38"],
      "مرّ النبي ﷺ ببعير قد أسفر بطنه على ظهره فقال: اتقوا الله في هذه البهائم المعجمة، اركبوها صالحة وكلوها صالحة.",
      "الرحمة بالحيوان حتى في العمل؛ السخرة على الحيوان محرمة.",
      "physical_persecution", "ruler_vs_ruled", "personal_dignity",
      "moral_rebuke", "protection_of_the_weak", "legislation"),

    E("ml_quran_compilation_started", 623, 11, "medinan_late",
      "بدء التفكير في جمع القرآن", "Beginning of thinking about compiling the Quran",
      "Medina", ["56:78"],
      "بعد وفاة النبي ﷺ ومقتل كثير من القراء في معركة اليمامة (مع مسيلمة)، اقترح عمر على أبي بكر جمع القرآن في مصحف واحد.",
      "الحاجة العملية تُولّد الفكرة؛ كل خسارة درس للحفظ.",
      "psychological_pressure", "leader_vs_follower", "knowledge_access",
      "witnessing_and_documentation", "knowledge_before_action", "legislation"),

    E("ml_yemen_islam_full", 624, 10, "medinan_late",
      "إسلام اليمن كاملاً", "Full conversion of Yemen",
      "Yemen", ["110:1"],
      "بنهاية حياة النبي ﷺ كانت اليمن قد دخلت في الإسلام كاملاً عبر معاذ بن جبل وأبي موسى الأشعري وغيرهما من السفراء.",
      "الفتح بالتعليم أوسع من الفتح بالسيف؛ المعلم فاتح من نوع آخر.",
      "none", "community_vs_outsider", "religious_freedom",
      "organizational_response", "teaching_through_demonstration", "praise"),

    E("ml_bahrain_islam_complete", 625, 9, "medinan_late",
      "إسلام البحرين كاملاً", "Full conversion of Bahrain",
      "Bahrain", ["110:1"],
      "أسلمت البحرين كاملة بعد إسلام ملكها المنذر بن ساوى التميمي، فأرسل النبي ﷺ إليها العلاء بن الحضرمي لتعليمهم الدين.",
      "هداية القائد مفتاح لجماعته؛ إسلام كامل بسلام.",
      "none", "community_vs_outsider", "religious_freedom",
      "compromise_for_larger_goal", "leadership_accountability", "praise"),

    E("ml_oman_islam", 626, 8, "medinan_late",
      "إسلام عمان كاملاً", "Full conversion of Oman",
      "Oman", ["110:1"],
      "أسلمت عمان بعد إسلام ملكيها على يد عمرو بن العاص، فأرسل النبي ﷺ إليها معلمين وقاضياً.",
      "التحول الجماعي السلمي ممكن؛ السياسة الحكيمة توفر الدماء.",
      "none", "community_vs_outsider", "religious_freedom",
      "compromise_for_larger_goal", "leadership_accountability", "praise"),

    E("ml_quda_dhi_amr", 627, 3, "medinan_late",
      "غزوة قطن", "Ghazwa of Qatan (Najd)",
      "Najd", ["8:57"],
      "بلغ النبي ﷺ تجمّع بني أسد بالقطن، فبعث إليهم أبا سلمة في 150 رجلاً، فأغار على بني أسد فتفرقوا.",
      "السرايا الصغيرة تكفي للردع؛ ليس كل عدو يحتاج جيشاً.",
      "political_pressure", "community_vs_outsider", "collective_survival",
      "active_resistance", "scaling_principle_to_context", "command"),

    E("ml_general_warning_apostasy", 628, 11, "medinan_late",
      "تحذير النبي ﷺ من الردة قبل وفاته", "Prophet warns against apostasy before his death",
      "Medina", ["3:144"],
      "حذّر النبي ﷺ في أيامه الأخيرة من الردة عن الدين، وقال: أخاف عليكم بعدي الفتن، والنبي يعلم أن جماعات ستعود إلى الجاهلية.",
      "الفتنة الكبرى بعد القائد متوقعة؛ الإيمان يحتاج إلى تجديد.",
      "psychological_pressure", "leader_vs_follower", "spiritual_integrity",
      "warning_against_arrogance", "consistency_public_and_private", "warning"),

    E("ml_advice_to_ansar", 629, 11, "medinan_late",
      "وصية النبي ﷺ بالأنصار", "Prophet's testimony for the Ansar",
      "Medina", ["59:9"],
      "أوصى النبي ﷺ في آخر خطبه بالأنصار قائلاً: أوصيكم بالأنصار خيراً، فإنهم كرشي وعَيْبَتي، فأكرموا كريمهم وتجاوزوا عن مسيئهم.",
      "الوفاء للأنصار حق؛ المعروف لا يُنسى.",
      "psychological_pressure", "leader_vs_follower", "trust_between_parties",
      "consolation_and_thabaat", "trust_is_earned_by_consistency", "command"),

    E("ml_imamah_abu_bakr_22_times", 630, 11, "medinan_late",
      "إمامة أبي بكر للناس 17 صلاة", "Abu Bakr leading the prayer 17 times",
      "Medina", ["3:159"],
      "صلى أبو بكر بالناس في مرض النبي ﷺ سبع عشرة صلاة، فكانت إشارة قوية إلى تأهله للخلافة بعد النبي.",
      "الإشارات العملية تسبق التصريح؛ اختبار القائد بالإمامة.",
      "psychological_pressure", "leader_vs_follower", "trust_between_parties",
      "teaching_through_demonstration", "knowledge_before_action", "command"),

    E("ml_visit_baqi_repeatedly", 631, 11, "medinan_late",
      "تكرر زيارة النبي ﷺ للبقيع", "Prophet repeatedly visits al-Baqi'",
      "Medina/Baqi'", ["49:10"],
      "أكثر النبي ﷺ في أيامه الأخيرة من زيارة البقيع والدعاء لأهله، حتى كأنه يودّعهم قبل أن ينضم إليهم.",
      "الوداع يُكثر مع قرب الفراق؛ الذكرى تبقى مع الذاكر.",
      "psychological_pressure", "community_vs_outsider", "spiritual_integrity",
      "consolation_and_thabaat", "solidarity_around_principle", "praise"),

    E("ml_brother_in_god_pact", 632, 5, "medinan_late",
      "آخر مؤاخاة بين الصحابة", "Final brotherhood pacts among the Companions",
      "Medina", ["49:10"],
      "بعد المؤاخاة الأولى آخى النبي ﷺ مرة أخرى بين أصحابه على أساس روحي، خاصة في أيامه الأخيرة، تأكيداً على الوحدة.",
      "العلاقات تُجدَّد بحسب المرحلة؛ الأخوة في الله أبدية.",
      "none", "community_vs_outsider", "community_cohesion",
      "organizational_response", "solidarity_around_principle", "command"),

    E("ml_simple_grave_no_decoration", 633, 11, "medinan_late",
      "بساطة قبر النبي ﷺ", "Simplicity of the Prophet's grave",
      "Medina", ["46:9"],
      "أُسس قبر النبي ﷺ بسيطاً، ونهى عن تزيينه أو رفعه أو الصلاة إليه، حماية للتوحيد.",
      "حتى موضع موت القائد لا يُؤلَّه؛ التوحيد يُحفظ بالحدود.",
      "none", "community_vs_outsider", "religious_freedom",
      "refusal_to_compromise", "refusing_to_legitimize_falsehood", "legislation"),

    E("ml_clothes_simple_burial", 634, 11, "medinan_late",
      "ثياب كفن النبي ﷺ البسيطة", "Simple shrouding of the Prophet",
      "Medina", ["7:31"],
      "كُفّن النبي ﷺ في ثلاثة أثواب بيض من قطن دون قميص ولا عمامة، تأكيداً على البساطة في الموت كما في الحياة.",
      "الكفن لا يحمل غنى ولا فقراً؛ الجميع في الموت سواء.",
      "none", "self_vs_self", "personal_dignity",
      "teaching_through_demonstration", "consistency_public_and_private", "legislation"),

    E("ml_age_at_death", 635, 11, "medinan_late",
      "عمر النبي ﷺ عند وفاته", "Prophet's age at death",
      "Medina", ["3:144"],
      "توفي النبي ﷺ وعمره 63 سنة، أمضى منها 40 قبل البعثة، و13 بعدها في مكة، و10 في المدينة، فكانت رسالته 23 سنة.",
      "الرسالة في 23 سنة غيّرت العالم؛ الزمن المستثمر يُعادل قروناً.",
      "none", "leader_vs_follower", "generational_legacy",
      "witnessing_and_documentation", "leadership_accountability", "story"),

    E("ml_fatima_passes_six_months", 636, 11, "medinan_late",
      "وفاة فاطمة بعد النبي ﷺ بستة أشهر", "Fatima dies six months after the Prophet",
      "Medina", ["3:144"],
      "توفيت فاطمة الزهراء بنت النبي ﷺ بعد أبيها بستة أشهر فقط، تحقيقاً لما أخبرها النبي ﷺ في مرضه أنها أول أهله لحوقاً به.",
      "الفقد المتلاحق ابتلاء؛ المؤمن يتأهل للقاء.",
      "psychological_pressure", "kin_vs_kin", "family_integrity",
      "endurance_without_retaliation", "consistency_public_and_private", "consolation"),

    E("ml_ten_promised_paradise", 637, 9, "medinan_late",
      "العشرة المبشرون بالجنة", "The ten promised paradise",
      "Medina", ["56:10", "56:11"],
      "بشّر النبي ﷺ عشرة من أصحابه بالجنة في حياته: أبو بكر، عمر، عثمان، علي، طلحة، الزبير، عبد الرحمن بن عوف، سعد بن أبي وقاص، سعيد بن زيد، أبو عبيدة.",
      "الشهادة بالجنة في الدنيا شرف لا يساويه شيء؛ القائد يُكرم العاملين قبل الأجل.",
      "none", "leader_vs_follower", "spiritual_integrity",
      "teaching_through_demonstration", "trust_is_earned_by_consistency", "promise"),

    E("ml_companion_count", 638, 11, "medinan_late",
      "عدد الصحابة عند وفاة النبي ﷺ", "Number of Companions at the Prophet's death",
      "Medina", ["48:18"],
      "بلغ عدد الصحابة عند وفاة النبي ﷺ نحو 124,000، انتشروا في الجزيرة العربية كلها لتعليم الدين.",
      "النواة الصغيرة تكبر بالقدوة؛ كل صحابي معلم.",
      "none", "community_vs_outsider", "knowledge_access",
      "organizational_response", "solidarity_around_principle", "praise"),

    E("ml_arab_islam_full", 639, 11, "medinan_late",
      "إسلام جزيرة العرب كاملة", "Full conversion of Arabia",
      "Arabia", ["110:1", "110:2", "110:3"],
      "بنهاية حياة النبي ﷺ كانت جزيرة العرب قد دخلت في الإسلام كاملة، إلا قبائل صغيرة في الأطراف، فكان فتحاً لم تشهد له البشرية مثيلاً.",
      "23 سنة غيّرت جزيرة كاملة؛ الإصلاح المنهجي يُحرّك التاريخ.",
      "none", "community_vs_outsider", "collective_survival",
      "organizational_response", "leadership_accountability", "promise"),

    E("ml_inheritance_to_ummah", 640, 11, "medinan_late",
      "إرث النبي ﷺ للأمة", "Prophet's inheritance for the ummah",
      "Medina", ["59:7"],
      "ترك النبي ﷺ للأمة كتاباً وسنة، ولم يترك ديناراً ولا درهماً، فكان إرثه علمياً لا مادياً، وقال: نحن معاشر الأنبياء لا نورث، ما تركناه صدقة.",
      "أعظم الإرث هو الأفكار والقيم؛ المال يفنى والعلم يبقى.",
      "none", "community_vs_outsider", "generational_legacy",
      "teaching_through_demonstration", "wealth_as_trust_not_ownership", "promise"),

    E("ml_last_words_prayer_slaves", 641, 11, "medinan_late",
      "آخر وصايا النبي ﷺ: الصلاة وما ملكت أيمانكم", "Prophet's final testament: prayer and slaves",
      "Medina", ["20:14", "16:71"],
      "كان آخر ما تكلم به النبي ﷺ: الصلاة الصلاة، وما ملكت أيمانكم، تأكيداً على العبادة الكبرى وعلى رعاية أضعف الفئات.",
      "آخر الكلمات تخلّد الأولويات؛ القائد يُذكّر بالأهم.",
      "psychological_pressure", "leader_vs_follower", "personal_dignity",
      "teaching_through_demonstration", "protection_of_the_weak", "command"),

    E("ml_sahaba_distribution_post_death", 642, 11, "medinan_late",
      "انتشار الصحابة بعد الوفاة", "Spread of Companions after the death",
      "Various places", ["3:104"],
      "بعد وفاة النبي ﷺ انتشر الصحابة في الأمصار الجديدة لتعليم الناس وفتح البلاد، حاملين معهم الرسالة الكاملة.",
      "البذرة الواحدة تنبت أشجاراً متفرقة؛ كل صحابي مؤسسة.",
      "none", "community_vs_outsider", "knowledge_access",
      "organizational_response", "solidarity_around_principle", "promise"),

    E("ml_quran_mostly_memorized", 643, 11, "medinan_late",
      "حفظ القرآن في الصدور", "Quran preserved in hearts",
      "Medina", ["15:9"],
      "كان القرآن محفوظاً في صدور آلاف الصحابة عند وفاة النبي ﷺ، إضافة إلى ما كُتب على الرقاع والعظام، فكان الحفظ متعدد الطبقات.",
      "تعدد الحفظ ضمان النص؛ الذاكرة الجماعية أقوى من الفردية.",
      "none", "community_vs_outsider", "knowledge_access",
      "witnessing_and_documentation", "knowledge_before_action", "praise"),

    E("ml_arabia_unified_under_one_law", 644, 11, "medinan_late",
      "توحيد جزيرة العرب تحت قانون واحد", "Unifying Arabia under one law",
      "Arabia", ["3:159"],
      "وحّد النبي ﷺ جزيرة العرب لأول مرة في تاريخها تحت قانون واحد ودولة واحدة وعقيدة واحدة، إنجاز سياسي لا مثيل له.",
      "الوحدة السياسية ثمرة الوحدة العقدية؛ الإصلاح الفكري يسبق السياسي.",
      "none", "community_vs_outsider", "collective_survival",
      "organizational_response", "solidarity_around_principle", "promise"),

    E("ml_legacy_principles", 645, 11, "medinan_late",
      "مبادئ النبي ﷺ الخالدة", "Prophet's eternal principles",
      "Medina", ["33:21"],
      "ترك النبي ﷺ للأمة مجموعة من المبادئ الخالدة: التوحيد، العدل، الرحمة، الشورى، المساواة، حقوق الإنسان، والسلام.",
      "المبادئ تتجاوز الزمان والمكان؛ القيم لا تشيخ.",
      "none", "community_vs_outsider", "generational_legacy",
      "teaching_through_demonstration", "consistency_public_and_private", "promise"),

    E("ml_first_islamic_state_model", 646, 11, "medinan_late",
      "نموذج الدولة الإسلامية الأولى", "Model of the first Islamic state",
      "Medina", ["49:13"],
      "أسس النبي ﷺ نموذج الدولة المدنية القائمة على العدل والمساواة والشورى والقانون، وكانت المدينة أول دولة إسلامية بكل معنى الكلمة.",
      "النموذج المدني مرجع للأجيال؛ التطبيق أبلغ من النظرية.",
      "none", "community_vs_outsider", "community_cohesion",
      "organizational_response", "leadership_accountability", "promise"),

    E("ml_messages_archived", 647, 11, "medinan_late",
      "أرشفة رسائل النبي ﷺ", "Archiving the Prophet's letters",
      "Medina", ["3:64"],
      "حفظ الصحابة رسائل النبي ﷺ إلى الملوك وإلى القبائل في خزائن، فبعضها وصلنا حتى اليوم، توثيقاً للمكتوب الأول.",
      "التوثيق مسؤولية الجيل الأول؛ الكلمة المكتوبة تخلّد التاريخ.",
      "none", "community_vs_outsider", "knowledge_access",
      "witnessing_and_documentation", "knowledge_before_action", "legislation"),

    E("ml_ali_washes_body", 648, 11, "medinan_late",
      "غسل علي للنبي ﷺ", "Ali washes the Prophet's body",
      "Medina", ["3:144"],
      "تولى علي بن أبي طالب غسل النبي ﷺ بمساعدة الفضل بن العباس وأسامة بن زيد، وكان غسلاً مبجلاً في ثياب النبي.",
      "التكريم للقائد حتى في غسله؛ آخر خدمة للحي ميت.",
      "none", "kin_vs_kin", "personal_dignity",
      "teaching_through_demonstration", "leadership_accountability", "praise"),

    E("ml_funeral_prayer_groups", 649, 11, "medinan_late",
      "صلاة المسلمين على النبي ﷺ جماعات", "Muslims pray on the Prophet in groups",
      "Medina", ["3:144"],
      "صلى المسلمون على النبي ﷺ جماعات جماعات بلا إمام، رجالاً ثم نساءً ثم أطفالاً ثم العبيد، احتراماً وإجلالاً.",
      "حتى صلاة الجنازة على القائد لها خصوصية؛ الكل يشارك.",
      "none", "community_vs_outsider", "community_cohesion",
      "teaching_through_demonstration", "leadership_accountability", "praise"),

    E("ml_legacy_summary", 650, 11, "medinan_late",
      "ختام الرسالة وبداية الانتشار", "End of the message and beginning of the spread",
      "Medina", ["110:1", "110:2", "110:3"],
      "بوفاة النبي ﷺ انتهت مرحلة التأسيس وبدأت مرحلة الانتشار، فحملت الأمة الرسالة إلى أرجاء الأرض، مؤسسة لحضارة عظمى.",
      "كل نهاية بداية؛ الرسالة لا تنتهي بموت رسولها.",
      "none", "community_vs_outsider", "generational_legacy",
      "organizational_response", "leadership_accountability", "promise"),
]
