name: Build Python Package with Conda

on:
  push:
  pull_request:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: al-furqan
        environment-file: environment.yml
        auto-activate-base: false
        miniforge-version: latest
    - name: Lint
      shell: bash -el {0}
      run: ruff check src/ tests/
    - name: Test with pytest
      shell: bash -el {0}
      run: pytest -m "not slow"
    - name: Install conda-build
      shell: bash -el {0}
      run: conda install --yes conda-build
    - name: Build Conda package
      shell: bash -el {0}
      run: conda build conda.recipe --output-folder conda-bld
    - name: Upload Conda package
      uses: actions/upload-artifact@v4
      with:
        name: al-furqan-conda-package
        path: conda-bld/**/*.tar.bz2
